### ISSUE TITLE
[Feature Request] FilterFeatures InputTransform

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#1028]
# 🚀 Feature Request

For multiobjective optimization in which it is known in advance that a feature has no impact on one of the objectives but on the others, it can be useful to build a ModelListGP model in which the specific models have different subsets of input features. This amounts to a kind of feature selection scenario.

## Motivation

Look above.

## Pitch

This is my current solution for this kind of problems. I think it is general applicable and could be useful.

```Python
class FilterFeatures(InputTransform, Module):
    
    def __init__(
        self,
        indices: Tensor,
        transform_on_train: bool = True,
        transform_on_eval: bool = True,
        transform_on_fantasize: bool = True,
        transform_on_preprocess: bool = False,
    ) -> None:
        super().__init__()
        self.transform_on_train = transform_on_train
        self.transform_on_eval = transform_on_eval
        self.transform_on_fantasize: bool = True
        self.transform_on_preprocess = transform_on_preprocess
        self.register_buffer("indices", indices)
        
    def transform(self, X: Tensor) -> Tensor:
        return X[...,self.indices]
    
    def equals(self, other: InputTransform) -> bool:
        r"""Check if another input transform is equivalent.

        Args:
            other: Another input transform

        Returns:
            A boolean indicating if the other transform is equivalent.
        """
        return (
            super().equals(other=other)
            and self.indices == other.indices
        )
````

## Additional context

It would be used in combination with a ModelListGP in which those models in which features should be filtered out are using this kind of FilterFeatures input transform.

**Comment by Balandat** [comment]
That looks useful indeed. Would you be willing to open a PR to add this?

**Comment by jduerholt** [comment]
I try to setup one next week ;)
