### ISSUE TITLE
[question] Can qNEHVI be used with KroneckerMultiTaskGP?

### ISSUE THREAD

**Issue by alinaselega** [pytorch/botorch#1036]
Following [this tutorial](https://botorch.org/tutorials/multi_objective_bo), I was trying to swap the `ModelListGP` model for a `KroneckerMultiTaskGP`, with this modification (leaving everything else the same):

```
def initialize_model(train_x, train_obj):
    model = KroneckerMultiTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    return mll, model
```
With this model, the BO loop fails at `optimize_qnehvi_and_get_observation()` with error:

```
AttributeError: 'TransformedPosterior' object has no attribute 'mvn'
```
Does that mean that `KroneckerMultiTaskGP` cannot be used with qNEHVI as it doesn't have the `MultitaskMultivariateNormal` attribute or am I misinterpreting this? Are any other changes necessary?

Thanks a lot!

**Comment by saitcakmak** [comment]
Can you try passing `cache_root=False` to the `qNoisyExpectedHypervolumeImprovement` constructor? I believe that's where you'd get this error.

cc @wjmaddox for KroneckerMTGP. Is KroneckerMTGP not supposed to have an `mvn` or is this just a by product of #983 that can be fixed by modifying `Standardize` etc? If it's not an easy fix, we can modify `qNEHVI` to bypass `cache_root` if the posterior does not have an `mvn` (currently special-casing only for `DeterministicPosterior`).

**Comment by alinaselega** [comment]
@saitcakmak Thank you for your reply! Just checking that you meant passing `cache_root=False` like this:

```
acq_func = qNoisyExpectedHypervolumeImprovement(
        model=model,
        ref_point=problem.ref_point.tolist(),  # use known reference point 
        X_baseline=normalize(train_x, problem.bounds),
        prune_baseline=True,  # prune baseline points that have estimated zero probability of being Pareto optimal
        sampler=sampler,
        cache_root=False
    )
```

Doing this raises a different error at the same step in the BO loop:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-66-8ce255746951> in <module>()
     70         )
     71         new_x_qnehvi, new_obj_qnehvi, new_obj_true_qnehvi = optimize_qnehvi_and_get_observation(
---> 72             model_qnehvi, train_x_qnehvi, train_obj_qnehvi, qnehvi_sampler
     73         )
     74         new_x_random, new_obj_random, new_obj_true_random = generate_initial_data(n=BATCH_SIZE)
...
/usr/local/lib/python3.7/dist-packages/botorch/acquisition/multi_objective/monte_carlo.py in _set_sampler(self, q, posterior)
    707                 end_idx = current_base_samples.shape[-2]
    708                 self.sampler.base_samples[..., :end_idx, :] = current_base_samples.view(
--> 709                     view_shape
    710                 ).expand(expanded_shape)
    711                 # update cached subset indices

RuntimeError: shape '[128, 128, 28]' is invalid for input of size 3584
```

Thanks!

**Comment by saitcakmak** [comment]
I was afraid that may happen (just because I ran into the two errors together previously in #966). Unfortunately, this one is much more difficult to get around. It has to do with the way `_set_sampler` method of `qNEHVI` is implemented, which does not work with the KroneckerMTGP, or any other GP that uses the Matheron's rule for sampling.  `_set_sampler` makes certain assumptions regarding the `base_sample_shape` of the `posterior`, that do not hold in this case. For now, I'd try to avoid using MTGPs with `qNEHVI` - `qEHVI` should be safe if your observations are noise-free though.

**Comment by alinaselega** [comment]
Got it, thanks very much for your help.

**Comment by saitcakmak** [comment]
I just put up #1037, which should resolve that error. It seems that some tests are failing in Python 3.7 (likely due to changes in the Python's `mock` library - I'll investigate shortly), but it should work fine in Python 3.8 and later. If you'd like to give that a try, you can install the patched version using `pip install --upgrade git+https://github.com/pytorch/botorch.git@refs/pull/1037/merge`. In short, it modifies the `_set_sampler` to properly handle KroneckerMTGP posteriors.

**Comment by eytan** [comment]
@saitcakmak, just to clarify #1037 should resolve @alinaselega's issue?

**Comment by saitcakmak** [comment]
Hi @eytan! Yes, with #1037, qNEHVI works with KroneckerMTGP.
[1036.py.txt](https://github.com/pytorch/botorch/files/7724015/1036.py.txt) Replaces the `ModelListGP` in the tutorial with `KroneckerMultiTaskGP` as @alinaselega described above, and runs without any errors on #1037.

**Comment by eytan** [comment]
Awesome!  OK, in that case I'll re-close this out.  @alinaselega feel free to re-open if you have any more issues.  qNEHVI scales much better to higher levels of parallelism even if your data is noise free, so glad we can make this an option!

As an aside, if you do have correlated noisy outcomes with non-diagonal covariances, we'd be very curious to hear about your results!  This is something we hoped to explore in the qNEHVI paper but just didn't have time for (cc @sdaulton).  There definitely appears to be some benefit to considering inter-task correlations (see Fig3 of [this paper](https://arxiv.org/pdf/2106.12997.pdf) w/ @wjmaddox and @Balandat ), although using the ICM / Kronecker MTGPs can result in negative transfer if tasks have very different behaviors.

**Comment by alinaselega** [comment]
Thanks a lot for resolving this!

**Comment by alinaselega** [comment]
> Hi @eytan! Yes, with #1037, qNEHVI works with KroneckerMTGP. [1036.py.txt](https://github.com/pytorch/botorch/files/7724015/1036.py.txt) Replaces the `ModelListGP` in the tutorial with `KroneckerMultiTaskGP` as @alinaselega described above, and runs without any errors on #1037.

Hi @saitcakmak I tried running this script ([1036.py.txt](https://github.com/pytorch/botorch/files/7724015/1036.py.txt)) on #1037 and I am getting this error:

```
Trial  1 of 2 ...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-fd9b75202e28> in <module>()
    258             new_obj_true_qehvi,
    259         ) = optimize_qehvi_and_get_observation(
--> 260             model_qehvi, train_x_qehvi, train_obj_qehvi, qehvi_sampler
    261         )
    262         (

9 frames
/usr/local/lib/python3.7/dist-packages/botorch/generation/gen.py in f(x)
    161             if initial_conditions.dtype != torch.double:
    162                 msg += " Consider using `dtype=torch.double`."
--> 163             raise RuntimeError(msg)
    164         fval = loss.item()
    165         return fval, gradf

RuntimeError: 4 elements of the 4 element gradient array `gradf` are NaN. This often indicates numerical issues.
```

I tried both with Python 3.7 and 3.8 and get the same problem albeit on different bathches. Do you have any advice? Thanks in advance.

**Comment by Balandat** [comment]
@alinaselega before digging deeper, are you running this in `torch.double` dtype? Using the default float32 dtype often results in numerical issues when working with GPs due to the often poor conditioning of the matrices in the linear solves.

**Comment by saitcakmak** [comment]
> are you running this in torch.double dtype?

That seems to be the case. The error message is not suggesting double :)

So, at least in my debugging run, the error happens in qEHVI (not qNEHVI) when evaluating `[0, 1]`, which has been evaluated 3 times already. The samples from the model posterior simply return `NaN`, which then leads to the `acquisition_function` returning `NaN`. 
Looking into it, it seems that the acqf returns NaN when evaluating `[0, 1]` which has been evaluated 3 times before (at least in my run). And this happens in qEHVI, not qNEHVI which wasn't previously supporting KroneckerMTGP. 

The `posterior` itself does not have `NaN` entries (in mean and covar matrix), but `posterior.sample()`, `posterior._posterior.sample` (it's a `TransformedPosterior`) and `self.sampler(posterior)` all produce `NaN` for samples. So, this looks like a `KroneckerMTGP` error to me, though I am not sure what is exactly causing the issue.

**Comment by Balandat** [comment]
I'd have to take a closer look but it could be that due to the ill-conditioned matrices some of the eigendecompositions used in the Kronecker solves end up producing NaNs. The Kronecker solves are fast and scalable, but unfortunately more prone to numerical issues.

**Comment by alinaselega** [comment]
Thank you for your replies! Yes, it is in `torch.double`. 

As @saitcakmak said, the error is raised when using qEHVI with the `KroneckerMultiTaskGP` model and this doesn't happen on every iteration as some complete successfully. I haven't seen this with non-Kronecker models so your explanation makes sense, thanks @Balandat.

I don't know if this observation helps but qNEHVI computes without errors with `KroneckerMultiTaskGP` (in [1036.py.txt](https://github.com/pytorch/botorch/files/7724015/1036.py.txt)).

**Comment by wjmaddox** [comment]
@saitcakmak Are you saying that EHVI is trying to evaluate posteriors on data points that the model has already seen? If so, then the Kronecker algebra and solves are definitely going to be unstable as the associated matrices are singular.

**Comment by saitcakmak** [comment]
@wjmaddox, yes, that's exactly what is happening. The `model.train_inputs` has 3 occurrences of `[0, 1]` and the `NaN` is produced when trying to get posterior samples at `[0, 1]`.
