### ISSUE TITLE
[Bug] Multitask BO data matrix not positive definite

### ISSUE THREAD

**Issue by dswigh** [pytorch/botorch#1055]
# 🐛 Bug

When running multitask BO using Summit, which is built on botorch, the optimisation fails often (but not always) when running with a large number of pretraining datapoints (e.g. 50), and it fails rarely when running with few datapoints (e.g. 10). Using data from a chemical reaction (C-N cross coupling), task 0 is when Benzamide is the nucleophile, and task 1 is Aniline. Data about Benzamide is used as pretraining data (task 0), and the goal is to more quickly find optimal conditions for yield using Aniline as the nucleophile (task 1).

## To reproduce

Running MTBO requires data, so I am not able to paste the whole workflow here. Please see the notebook in this repository to reproduce the error: https://github.com/dswigh/bayesian_opt_bug 

Below you can see the most important parts of the code
```python
def run_mtbo(exp, pt_data, max_iterations=10, task=1):
    exp.reset()
    strategy = MTBO(exp.domain, 
                    pretraining_data=pt_data,
                    categorical_method="one-hot", 
                    task=task)
    r = summit.Runner(strategy=strategy,
                      experiment=exp, 
                      max_iterations=max_iterations)
    r.run()
    return r

exp = aniline_bm #benchmark for simulating experimental outcome
result = run_mtbo(exp, benzamide_ds[0:50], max_iterations=MAX_ITERATIONS, task=1)

```

** Stack trace/error message **
```
---------------------------------------------------------------------------
NotPSDError                               Traceback (most recent call last)
<ipython-input-39-4fbff4ee1d32> in <module>
      3     print(f"Repeat {i}")
      4     exp = aniline_bm
----> 5     result = run_mtbo(exp, benzamide_ds[0:50], max_iterations=MAX_ITERATIONS, task=1)

(...)

~/Library/Caches/pypoetry/virtualenvs/multitask-P_6kt6PW-py3.7/lib/python3.7/site-packages/gpytorch/utils/cholesky.py in _psd_safe_cholesky(A, out, jitter, max_tries)
     46             if not torch.any(info):
     47                 return L
---> 48         raise NotPSDError(f"Matrix not positive definite after repeatedly adding jitter up to {jitter_new:.1e}.")
     49 
     50 

NotPSDError: Matrix not positive definite after repeatedly adding jitter up to 1.0e-04.
```

## Expected Behavior

I expect the optimisation to run to completion, exactly as when the Single Task/Single Objective BO (SOBO) strategy is used.

## System information

**Please complete the following information:**
- BoTorch Version: 0.5.1
- GPyTorch Version: 1.5.1
- 
- Computer OS: macOS Big Sur 11.5.2

## Additional context

A few points to note:
- Using the Random and SOBO strategy on the dataset works fine
- I was able to run MTBO with 10 pretraining datapoints but not 50
- Running MTBO with 50 datapoints succeeded in the first iteration, but not the second

I think that the matrix not being positive definite means that there are (at least) two rows in the data matrix which are equivalent, however, I'm not sure if this is the case, or indeed why/how this would happen.
The fact that MTBO is able to run through one iteration, but fails the second time implies that there's not a syntactical error, but rather that there's some randomness somewhere that causes it to fail. I have observed that the 'NotPSDError' also occurs even with a small number of pretraining datapoints, however this is quite rare. It seems to me that the more pretraining data I use, the higher the risk of getting 'NotPSDError'.

**Comment by Balandat** [comment]
Hey, thanks for flagging this. Great to see that you're using BoTorch in Summit. 

I took a look at the summit code, and it seems that the default data type used there is float: https://github.com/sustainable-processes/summit/blob/master/summit/strategies/multitask.py#L181-L182

This can often lead to numerical issues due to the ill-conditioned kernel matrices that occur with similar data points. Can you try running the model and optimization in double precision? This should provide a much wider margin to avoid the non-psd errors.

In general I would always recommend doing that, unless you are running this on a GPU and really need that performance boost from fp32 computations. The differences on the CPU are small and not really worth worrying about for the peace of mind you get from running in double precision.

**Comment by dswigh** [comment]
> Hey, thanks for flagging this. Great to see that you're using BoTorch in Summit.
> 
> I took a look at the summit code, and it seems that the default data type used there is float: https://github.com/sustainable-processes/summit/blob/master/summit/strategies/multitask.py#L181-L182
> 
> This can often lead to numerical issues due to the ill-conditioned kernel matrices that occur with similar data points. Can you try running the model and optimization in double precision? This should provide a much wider margin to avoid the non-psd errors.
> 
> In general I would always recommend doing that, unless you are running this on a GPU and really need that performance boost from fp32 computations. The differences on the CPU are small and not really worth worrying about for the peace of mind you get from running in double precision.

The change from single to double precision seems to have solved the issue, thank you so much!

**Comment by Balandat** [comment]
Glad to help.
