### ISSUE TITLE
[question] How to do predictions using the trained GP models?

### ISSUE THREAD

**Issue by gooster1997** [pytorch/botorch#1110]
## Issue description

Hello! I recently start using BoTorch in my work on chemistry but i'm only newbie to bayes optimization and also programming. I was wondering how to use the GPmodels trained on my datasets to make predictions. Having tried my best to read the code but still cannot find a way. Hope to get your instructions and suggestions.

Thank you so much for this great toolbox.

## Code example

I'm just using the same code framework as the 'q-Noisy Constrained EI' in tutorial.

## System Info
Please provide information about your setup, including
- BoTorch Version 0.6.0
- GPyTorch Version 1.6.0
- Ubuntu

**Comment by Balandat** [comment]
So if you have a `Model` (like `model_obj` in the tutorial you referenced), you can do `model_obj.posterior(X_test)`, where `X_test` is a tensor of the same format as your training data to the model (`train_x` in the tutorial). This will yield a `GPyTorchPosterior` object with  `mean` and `variance` properties of the posterior prediction you can also get covariances from the `.mvn` attribute of the posterior.

**Comment by gooster1997** [comment]
> 

Thank you!

**Comment by gooster1997** [comment]
> So if you have a `Model` (like `model_obj` in the tutorial you referenced), you can do `model_obj.posterior(X_test)`, where `X_test` is a tensor of the same format as your training data to the model (`train_x` in the tutorial). This will yield a `GPyTorchPosterior` object with `mean` and `variance` properties of the posterior prediction you can also get covariances from the `.mvn` attribute of the posterior.

Thank you!
