### ISSUE TITLE
Model fitting in pairwise comparison tutorial fails on M1 Mac

### ISSUE THREAD

**Issue by ananyan** [pytorch/botorch#1155]
## Issue description

Having trouble with model fitting in the pairwise comparison preference learning tutorial notebook.

I've followed instructions to run pytorch natively using miniforge on an M1 Macbook. Some of the other tutorials are running fine with this setup (I tried turbo_1), but both of the preference learning ones that use PairwiseGP show the same error. I tried to replicate the environment on a different setup (Windows 10) and the tutorial worked fine, so I'm assuming there is some compatibility issue with M1 unless I'm missing something? Would appreciate any guidance towards what might be going wrong! Thank you!

## Code example
Running the preference_bo tutorial notebook with no changes.

Error messages and stack trace:
<pre>---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [3], in <cell line: 7>()
      5 model = PairwiseGP(train_X, train_comp)
      6 mll = PairwiseLaplaceMarginalLogLikelihood(model)
----> 7 mll = fit_gpytorch_model(mll)

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/botorch/fit.py:127, in fit_gpytorch_model(mll, optimizer, **kwargs)
    125     sample_all_priors(mll.model)
    126 try:
--> 127     mll, _ = optimizer(mll, track_iterations=False, **kwargs)
    128 except NotPSDError:
    129     retry += 1

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/botorch/optim/fit.py:239, in fit_gpytorch_scipy(mll, bounds, method, options, track_iterations, approx_mll, scipy_objective, module_to_array_func, module_from_array_func)
    236 cb = store_iteration if track_iterations else None
    238 with gpt_settings.fast_computations(log_prob=approx_mll):
--> 239     res = minimize(
    240         scipy_objective,
    241         x0,
    242         args=(mll, property_dict),
    243         bounds=bounds,
    244         method=method,
    245         jac=True,
    246         options=options,
    247         callback=cb,
    248     )
    249     iterations = []
    250     if track_iterations:

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/scipy/optimize/_minimize.py:681, in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    678     res = _minimize_newtoncg(fun, x0, args, jac, hess, hessp, callback,
    679                              **options)
    680 elif meth == 'l-bfgs-b':
--> 681     res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
    682                            callback=callback, **options)
    683 elif meth == 'tnc':
    684     res = _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
    685                         **options)

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/scipy/optimize/_lbfgsb_py.py:362, in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, finite_diff_rel_step, **unknown_options)
    356 task_str = task.tobytes()
    357 if task_str.startswith(b'FG'):
    358     # The minimization routine wants f and g at the current x.
    359     # Note that interruptions due to maxfun are postponed
    360     # until the completion of the current minimization iteration.
    361     # Overwrite f and g:
--> 362     f, g = func_and_grad(x)
    363 elif task_str.startswith(b'NEW_X'):
    364     # new iteration
    365     n_iterations += 1

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py:285, in ScalarFunction.fun_and_grad(self, x)
    283 if not np.array_equal(x, self.x):
    284     self._update_x_impl(x)
--> 285 self._update_fun()
    286 self._update_grad()
    287 return self.f, self.g

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py:251, in ScalarFunction._update_fun(self)
    249 def _update_fun(self):
    250     if not self.f_updated:
--> 251         self._update_fun_impl()
    252         self.f_updated = True

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py:155, in ScalarFunction.__init__.<locals>.update_fun()
    154 def update_fun():
--> 155     self.f = fun_wrapped(self.x)

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py:137, in ScalarFunction.__init__.<locals>.fun_wrapped(x)
    133 self.nfev += 1
    134 # Send a copy because the user may overwrite it.
    135 # Overwriting results in undefined behaviour because
    136 # fun(self.x) will change self.x, with the two no longer linked.
--> 137 fx = fun(np.copy(x), *args)
    138 # Make sure the function returns a true scalar
    139 if not np.isscalar(fx):

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/scipy/optimize/_optimize.py:76, in MemoizeJac.__call__(self, x, *args)
     74 def __call__(self, x, *args):
     75     """ returns the the function value """
---> 76     self._compute_if_needed(x, *args)
     77     return self._value

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/scipy/optimize/_optimize.py:70, in MemoizeJac._compute_if_needed(self, x, *args)
     68 if not np.all(x == self.x) or self._value is None or self.jac is None:
     69     self.x = np.asarray(x).copy()
---> 70     fg = self.fun(x, *args)
     71     self.jac = fg[1]
     72     self._value = fg[0]

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/botorch/optim/utils.py:213, in _scipy_objective_and_grad(x, mll, property_dict)
    211 mll.zero_grad()
    212 try:  # catch linear algebra errors in gpytorch
--> 213     output = mll.model(*train_inputs)
    214     args = [output, train_targets] + _get_extra_mll_args(mll)
    215     loss = -mll(*args).sum()

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/gpytorch/module.py:30, in Module.__call__(self, *inputs, **kwargs)
     29 def __call__(self, *inputs, **kwargs):
---> 30     outputs = self.forward(*inputs, **kwargs)
     31     if isinstance(outputs, list):
     32         return [_validate_module_outputs(output) for output in outputs]

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/botorch/models/pairwise_gp.py:820, in PairwiseGP.forward(self, datapoints)
    815 transformed_dp = self.transform_inputs(datapoints)
    817 # We pass in the untransformed datapoints into set_train_data
    818 # as we will be setting self.datapoints as the untransformed datapoints
    819 # self.transform_inputs will be called inside before calling _update()
--> 820 self.set_train_data(datapoints, self.comparisons, update_model=True)
    822 # Take a newton step on the posterior MAP point to fill
    823 # in gradients for pytorch
    824 self.utility = self._util_newton_updates(
    825     transformed_dp, self.utility, max_iter=1
    826 )

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/botorch/models/pairwise_gp.py:780, in PairwiseGP.set_train_data(self, datapoints, comparisons, strict, update_model)
    778 if update_model:
    779     transformed_dp = self.transform_inputs(datapoints)
--> 780     self._update(transformed_dp)
    782 self.to(self.datapoints)

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/botorch/models/pairwise_gp.py:554, in PairwiseGP._update(self, datapoints, **kwargs)
    552     with warnings.catch_warnings():
    553         warnings.filterwarnings("ignore", category=RuntimeWarning)
--> 554         x = optimize.fsolve(
    555             x0=x0,
    556             func=self._grad_posterior_f,
    557             fprime=self._hess_posterior_f,
    558             xtol=xtol,
    559             maxfev=maxfev,
    560             args=fsolve_args,
    561             **kwargs,
    562         )
    564 self._x0 = x.copy()  # save for warm-starting
    565 f = torch.tensor(x, dtype=datapoints.dtype, device=datapoints.device)

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/scipy/optimize/_minpack_py.py:160, in fsolve(func, x0, args, fprime, full_output, col_deriv, xtol, maxfev, band, epsfcn, factor, diag)
     49 """
     50 Find the roots of a function.
     51 
   (...)
    150 
    151 """
    152 options = {'col_deriv': col_deriv,
    153            'xtol': xtol,
    154            'maxfev': maxfev,
   (...)
    157            'factor': factor,
    158            'diag': diag}
--> 160 res = _root_hybr(func, x0, args, jac=fprime, **options)
    161 if full_output:
    162     x = res['x']

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/scipy/optimize/_minpack_py.py:243, in _root_hybr(func, x0, args, jac, col_deriv, xtol, maxfev, band, eps, factor, diag, **unknown_options)
    241     if (maxfev == 0):
    242         maxfev = 100 * (n + 1)
--> 243     retval = _minpack._hybrj(func, Dfun, x0, args, 1,
    244                              col_deriv, xtol, maxfev, factor, diag)
    246 x, status = retval[0], retval[-1]
    248 errors = {0: "Improper input parameters were entered.",
    249           1: "The solution converged.",
    250           2: "The number of calls to function has "
   (...)
    260               "ten iterations.",
    261           'unknown': "An error occurred."}

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/botorch/models/pairwise_gp.py:404, in PairwiseGP._grad_posterior_f(self, utility, datapoints, D, DT, covar_chol, covar_inv, ret_np)
    401     utility = torch.tensor(utility, dtype=self.datapoints.dtype)
    402     prior_mean = prior_mean.cpu()
--> 404 b = self._grad_likelihood_f_sum(utility, D)
    406 # g_ = covar_inv x (utility - pred_prior)
    407 p = (utility - prior_mean).unsqueeze(-1).to(covar_chol)

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/botorch/models/pairwise_gp.py:345, in PairwiseGP._grad_likelihood_f_sum(self, utility, D)
    332 def _grad_likelihood_f_sum(self, utility: Tensor, D: Tensor) -> Tensor:
    333     r"""Compute the sum over of grad. of negative Log-LH wrt utility f.
    334     Original grad should be of dimension m x n, as in (6) from [Chu2005preference]_.
    335     Sum over the first dimension and return a tensor of shape n
   (...)
    343         The sum over the first dimension of grad. of negative Log-LH wrt utility f
    344     """
--> 345     _, _, _, h = self._calc_z(utility, D)
    346     h_factor = (h / math.sqrt(2)).unsqueeze(-2)
    347     grad = (h_factor @ (-D)).squeeze(-2)

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/botorch/models/pairwise_gp.py:326, in PairwiseGP._calc_z(self, utility, D)
    322 # Clamp z for stable log transformation. This also prevent extreme values
    323 # from appearing in the hess matrix, which should help with numerical
    324 # stability and avoid extreme fitted hyperparameters
    325 z = z.clamp(-self._zlim, self._zlim)
--> 326 z_logpdf = std_norm.log_prob(z)
    327 z_cdf = std_norm.cdf(z)
    328 z_logcdf = torch.log(z_cdf)

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/torch/distributions/normal.py:73, in Normal.log_prob(self, value)
     71 def log_prob(self, value):
     72     if self._validate_args:
---> 73         self._validate_sample(value)
     74     # compute the variance
     75     var = (self.scale ** 2)

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/torch/distributions/distribution.py:286, in Distribution._validate_sample(self, value)
    284 valid = support.check(value)
    285 if not valid.all():
--> 286     raise ValueError(
    287         "Expected value argument "
    288         f"({type(value).__name__} of shape {tuple(value.shape)}) "
    289         f"to be within the support ({repr(support)}) "
    290         f"of the distribution {repr(self)}, "
    291         f"but found invalid values:\n{value}"
    292     )

ValueError: Expected value argument (Tensor of shape (100,)) to be within the support (Real()) of the distribution Normal(loc: tensor([0.], dtype=torch.float64), scale: tensor([1.], dtype=torch.float64)), but found invalid values:
tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan], dtype=torch.float64)
</pre>

## System Info
Please provide information about your setup, including
- BoTorch Version: 0.6.3.2.dev6+g4a838f0b
- GPyTorch Version: 1.6.0
- PyTorch Version: 1.11.0
- Computer OS: Mac OS Monterey 12.3

**Comment by ItsMrLin** [comment]
Hi @ananyan, thanks for reaching out! It seems like this is a numerical problem during optimization on M1. I just tested running the tutorial on a linux machine and it executed fine.

Have you tried changing the number of n and m to something smaller like n=5 and m=10 (Or to explicitly set `SMOKE_TEST=True`)?

**Comment by ananyan** [comment]
Yeah I figured it might be related to the M1. I tried changing n and m, but run into the same issue unfortunately

**Comment by eytan** [comment]
Hi,

a few ideas:
1. Does the tutorial work on an intel Mac?
2. Looking at some of the M1 related issues in PyTorch, There are some instances of PyTorch generating nans with Conda / Pip, but other users having success with miniforge3. https://github.com/pytorch/pytorch/issues/66410 … perhaps you could try with that package manager?

**Comment by ananyan** [comment]
Thanks for the ideas! I think the tutorial is works on an intel mac. I tried using miniforge3 instead but still get the same error.

**Comment by ItsMrLin** [comment]
Hi @ananyan! So I finally got my hands on a M1 (pro) macbook and I was able to run the tutorial with no problem.
I wonder if this is related to some underlying M1 chip related pytorch issue but got fixed later.

What version of python, botorch and pytorch are you using? Using Python 3.10.3, torch 1.11.0, and botorch 0.6.4, I am able to run this tutorial a M1 pro chip macbook.

**Comment by ananyan** [comment]
Hi thanks for looking into it! I tried again using Python 3.10.4, torch 1.11.0 and botorch 0.6.4 but still had the same issue. It could be related to how I installed pytorch in that case

**Comment by ItsMrLin** [comment]
Hm, this is a very strange issue. I installed python using pyenv and packages using pip. Do you think you would be able to try  installing the packages using pip and see if that changes anything.

**Comment by ananyan** [comment]
That worked for me!

**Comment by ItsMrLin** [comment]
Great to hear that! :D
