### ISSUE TITLE
[question] Can multi-objective BO in botorch be constrained to finding a single optimal location for all objectives?

### ISSUE THREAD

**Issue by alinaselega** [pytorch/botorch#1157]
Following [this tutorial](https://botorch.org/tutorials/multi_objective_bo), the initial training data is said to be generated from [0,1]^2 so `train_x` values at which the two objectives are probed are different. Similarly, when computing new observations with e.g. qNEHVI,  `candidates` returned by the optimization are also 2-dimensional and thus, `new_x` also has different locations for the two objectives. Is this approach to optimization with outputting `d`-dimensional new location (for `d` objectives) by design? Is there a way to constrain the optimization to return a single (scalar) location `x` at which all objectives will be probed?

Thanks!

**Comment by saitcakmak** [comment]
> so train_x values at which the two objectives are probed are different.

So, this is a misunderstanding. `BraninCurrin` function is a mapping from R^2 to R^2 (2d input, 2d output). Both `Branin` and `Currin` objectives depend on both dimensions of the input, i.e., the `train_x` here (function definition [here](https://github.com/pytorch/botorch/blob/20c84510153477eb4fea6d4254074d8e6c120816/botorch/test_functions/multi_objective.py#L94-L147)). As a result, all objectives are probed at the same `x`, which in this case happens to be 2d.

As an example of a multi-objective test problem where the input dimension is different than the number of objectives, you can check out [Penicillin](https://github.com/pytorch/botorch/blob/20c84510153477eb4fea6d4254074d8e6c120816/botorch/test_functions/multi_objective.py#L671-L801), which has 7d input and 3d output (again all outputs depending on all inputs).

**Comment by alinaselega** [comment]
Thanks so much, I indeed misunderstood the input dimension and number of objectives.
