### ISSUE TITLE
[Feature Request]Can you implement for trace-aware Knowledge Gradient？

### ISSUE THREAD

**Issue by fanqiNO1** [pytorch/botorch#1162]
# 🚀 Feature Request

Can you implement the trace-aware Knowledge Gradient? Namely, taKG. It was proposed in https://arxiv.org/abs/1903.04703

## Motivation

As botorch a famous Bayesian optimization library, I'd like to use taKG in botorch.

Thank you! And thank you for botorch.

**Comment by Balandat** [comment]
Thanks for your interest. taKG is implemented in BoTorch (under the more generic name `qMultiFidelityKnowledgeGradient` that is in line with our other naming conventions). Check out this tutorial: https://botorch.org/tutorials/multi_fidelity_bo. Feel free to re-open the issue if you have questions.
