### ISSUE TITLE
[Question] How to perform multi-fidelity BO with GIBBON?

### ISSUE THREAD

**Issue by npielawski** [pytorch/botorch#1163]
# 🚀 Feature Request

I would like to perform mult-fidelity bayesian optimization with GIBBON or qLowerBoundMaxValueEntropy. The [tutorial](https://botorch.org/tutorials/GIBBON_for_efficient_batch_entropy_search) seems to indicate that it is indeed possible:
`However, in order to support batch and multi-fidelity BO, our implementation of MES employs numerical integrations and fantasy observations (i. e., we generate one point each time and when we try to generate the 𝑖-th point of a batch, we condition the models on the 𝑖−1 points generated prior to this).`

## Motivation

I cannot find a `qMultiFidelityLowerBoundMaxValueEntropy` class to perform MF BO with GIBBON, though there is a `qMultiFidelityMaxValueEntropy(qMaxValueEntropy)` class.

## Pitch

**Describe the solution you'd like**
I'd like to have a way to perform MF BO with GIBBON, I think a tutorial would also be valuable if there are many differences with the MFKG tutorial.

**Comment by npielawski** [comment]
Maybe I should link @henrymoss to the conversation.

**Comment by Balandat** [comment]
Hmm it's been a while since I looked at this code, but the only difference between `qMultiFidelityMaxValueEntropy` and a MF variant of Gibbon (i.e. `qMultiFidelityLowerBoundMaxValueEntropy`) would be how `_compute_information_gain` is implemented. It seems that this is in fact the only function implemented on `qLowerBoundMaxValueEntropy` (that is not inherited from the parent class). So it should be possible to just do the following and then use this like qMultiFidelityMaxValueEntropy (haven't had the time to test this yet though):

```
class qMultiFidelityLowerBoundMaxValueEntropy(qLowerBoundMaxValueEntropy, qMultiFidelityMaxValueEntropy):
   ...
```

**Comment by npielawski** [comment]
Thanks for your reply!
That's what I did for now:
```python
class qMultiFidelityLowerBoundMaxValueEntropy(
    qMultiFidelityMaxValueEntropy, qLowerBoundMaxValueEntropy
):
    r"""... docstring ..."""

    def _compute_information_gain(
        self, X: Tensor, mean_M: Tensor, variance_M: Tensor, covar_mM: Tensor
    ) -> Tensor:
        r"""... docstring ..."""
        return qLowerBoundMaxValueEntropy._compute_information_gain(
            self, X=X, mean_M=mean_M, variance_M=variance_M, covar_mM=covar_mM
        )
```
And it worked, it's encouraging that you came up with the same solution.

Would you accept a PR implementing the `qMultiFidelityLowerBoundMaxValueEntropy` class?

**Comment by Balandat** [comment]
Sure we'd be happy to accept a PR.

**Comment by npielawski** [comment]
Alright!
PR submitted in #1185
