### ISSUE TITLE
Attempting to compute the posterior mean of the GP's gradient

### ISSUE THREAD

**Issue by trbedwards** [pytorch/botorch#1164]
I'm attempting to compute argmax ||mu_delta(x)||, the value of x which maximises the posterior mean of the gradient GP, where the 'gradient GP' is the GP that models delta(f(x)), the gradient of the objective function. This is needed for implementing a local penalisation scheme for batch Bayesian Optimisation (see [J. Gonzalez et al, 2016](https://arxiv.org/abs/1505.08052)). Presumably I would need rely on pytorch generating the gradient graphs and computing them via a call to `.backward`. 

I have attempted to do this by subclassing the `PosteriorMean` class from `botorch.acquisition`, and following the steps I [found here](https://jejjohnson.github.io/research_notebook/content/notes/egps/notebooks/gpytorch_egp_taylor.html#tensors) to compute gradients:

```python
class PosteriorMeanOfGradientGP(PosteriorMean):
    def forward(self, X: Tensor) -> Tensor:
        gp = self.model
        X_var = torch.autograd.Variables(X, requires_grad=True)
        y_pred = gp.likelihood(gp(X_var))
        y_mean_sum = y_pred.mean.sum()
        y_mean_sum.backward()
        dy_dx = X.grad
        return dy_dx
```

However, when I run my Bayesian Optimisation routine, it raises a RuntimeError saying "element 0 of tensors does not require grad and does not have a grad_fn". Upon running the debugger and tracking the `requires_grad` attribute, I found that the output tensor from `gp(X_var)` loses its `requires_grad` status somewhere in the `self.exact_prediction` method of the `DefaultPredictionStrategy` class. 

What can I do to ensure that gradients are propagated when calling the GP model on `X_var`?

## System Info
- BoTorch 0.6.3.1
- GPyTorch 1.6.0
- PyTorch 1.10.2
- Ubuntu 18.04.3 LTS 64-bit

**Comment by wjmaddox** [comment]
I'm not actually sure that this is a bug but rather some autograd subleties where you need to forcibly turn on the gradient during the initialization process inside of botorch. This chunk of code works for me:
```python
import torch
import botorch
from botorch.optim import optimize_acqf

class PosteriorMeanOfGradientGP(botorch.acquisition.PosteriorMean):
    def forward(self, X: torch.Tensor) -> torch.Tensor:
        gp = self.model
        X_var = X.clone().requires_grad_(True)
        with torch.enable_grad():
            y_pred = gp.likelihood(gp(X_var))
            y_mean_sum = y_pred.mean.sum()
            dy_dx = torch.autograd.grad(y_mean_sum, X_var, create_graph = True)[0]
        return dy_dx.mean((-2, -1))

acqf = PosteriorMeanOfGradientGP(model=gp)

optimize_acqf(
    acq_function=acqf, q=2, bounds = torch.tensor([[-3., 3.], [-3., 3.]]).t(), num_restarts=4,
    raw_samples=32,
) # runs properly
```

**Comment by wjmaddox** [comment]
Yeah, so the subleties are a) doing the explicit grad call rather than backwards, b) [this line](https://github.com/pytorch/botorch/blob/1c1bb5ba3a99c7f02e01a5617f5aec31ee9dcd2b/botorch/optim/initializers.py#L176) now that I look at it.

The `torch.no_grad()` there is what was throwing me errors with the original code (no grad --> the loss just doesn't require a gradient).

**Comment by Balandat** [comment]
Makes sense! Nice gotcha... should probably add this somewhere to the acquisition function base class (putting this into every class might be information overkill for 99% of use cases...). Let's keep this issue open for now until we've documented this in the code.

**Comment by trbedwards** [comment]
> I'm not actually sure that this is a bug but rather some autograd subleties where you need to forcibly turn on the gradient during the initialization process inside of botorch. This chunk of code works for me:
> 
> ```python
> import torch
> import botorch
> from botorch.optim import optimize_acqf
> 
> class PosteriorMeanOfGradientGP(botorch.acquisition.PosteriorMean):
>     def forward(self, X: torch.Tensor) -> torch.Tensor:
>         gp = self.model
>         X_var = X.clone().requires_grad_(True)
>         with torch.enable_grad():
>             y_pred = gp.likelihood(gp(X_var))
>             y_mean_sum = y_pred.mean.sum()
>             dy_dx = torch.autograd.grad(y_mean_sum, X_var, create_graph = True)[0]
>         return dy_dx.mean((-2, -1))
> 
> acqf = PosteriorMeanOfGradientGP(model=gp)
> 
> optimize_acqf(
>     acq_function=acqf, q=2, bounds = torch.tensor([[-3., 3.], [-3., 3.]]).t(), num_restarts=4,
>     raw_samples=32,
> ) # runs properly
> ```

Thanks! The `torch.enable_grad` call was key. I actually have implemented it (more) correctly now:

```python
def forward(self, X: Tensor) -> Tensor:
    gp = self.model
    X_var = X.clone().requires_grad_(True)
    
    with torch.enable_grad():
        mu = super().foward(X_var)
        dmu_dx = torch.autograd.grad(mu.sum(), X_var, create_graph=True)[0]

    norm_dmu_dx = dmu_dx.norm(dim=-1).view_as(mu)
    return norm_dmu_dx
```
```

**Comment by Balandat** [comment]
Leaving this open until we add documentation on this gotcha.

**Comment by shikhar-saxena** [comment]
> I'm not actually sure that this is a bug but rather some autograd subleties where you need to forcibly turn on the gradient during the initialization process inside of botorch. This chunk of code works for me:
> 
> ```python
> import torch
> import botorch
> from botorch.optim import optimize_acqf
> 
> class PosteriorMeanOfGradientGP(botorch.acquisition.PosteriorMean):
>     def forward(self, X: torch.Tensor) -> torch.Tensor:
>         gp = self.model
>         X_var = X.clone().requires_grad_(True)
>         with torch.enable_grad():
>             y_pred = gp.likelihood(gp(X_var))
>             y_mean_sum = y_pred.mean.sum()
>             dy_dx = torch.autograd.grad(y_mean_sum, X_var, create_graph = True)[0]
>         return dy_dx.mean((-2, -1))
> 
> acqf = PosteriorMeanOfGradientGP(model=gp)
> 
> optimize_acqf(
>     acq_function=acqf, q=2, bounds = torch.tensor([[-3., 3.], [-3., 3.]]).t(), num_restarts=4,
>     raw_samples=32,
> ) # runs properly
> ```

The code shared here doesn't run anymore. I'm getting the following error:
```
NotImplementedError: the derivative for '_cdist_backward' is not implemented.
```

### Package Versions

- Botorch 0.9.5
- Pytorch 2.2.1
- Gpytorch 1.11
- Python 3.11.4
