### ISSUE TITLE
[Bug] `ABNORMAL_TERMINATION_IN_LNSRCH` in `fit_gpytorch_scipy` is not being caught, leading to poor model fits

### ISSUE THREAD

**Issue by crasanders** [pytorch/botorch#1169]
# 🐛 Bug

I unfortunately don't have a concise example to share, but we make use of `fit_gpytorch_model` in [aepsych](https://github.com/facebookresearch/aepsych). `fit_gpytorch_model` calls `fit_gpytorch_scipy`, which calls `scipy.minimize`, which sometimes fails to converge with `"ABNORMAL_TERMINATION_IN_LNSRCH"`.  For some reason this is not being caught by the `with warnings.catch_warnings(record=True) as ws:` line in `fit_gpytorch_model`, which leads to poor model fits on our end.

## System information

**Please complete the following information:**
-  Botorch: 0.6.2
-  GPyTorch: 1.6.0
-  PyTorch: 1.9.1
-  Mac OS 12.3.1

**Comment by saitcakmak** [comment]
That's an interesting error, one I haven't seen before. A google search brought up this [thread](https://stackoverflow.com/questions/34663539/scipy-optimize-fmin-l-bfgs-b-returns-abnormal-termination-in-lnsrch) which suggests that this may be related to function / gradient mismatch. It may just be a numerical issue in grad computation, but it might be worth looking into whether there's a bigger issue going on with the gradients in this case.

Is the `scipy.minimize` output something like `{'grad': array([ -1.36050603e-05]), 'task': b'ABNORMAL_TERMINATION_IN_LNSRCH', 'funcalls': 51, 'nit': 4, 'warnflag': 2}` (found in google search results) when this happens? If so, it should be easy to look into task and filter it that way.

**Comment by crasanders** [comment]
The `scipy.minimize` output looks like this: 
```
fun: nan
 hess_inv: <3196x3196 LbfgsInvHessProduct with dtype=float64>
      jac: array([ 0.09521612,  0.35479467, -0.02726126, ...,  0.00897098,
       -0.05011029,  0.70100166])
  message: 'ABNORMAL_TERMINATION_IN_LNSRCH'
     nfev: 6
      nit: 3
     njev: 6
   status: 2
  success: False
        x: array([ 0.65288807, -0.28074463,  0.23027564, ...,  8.96318507,
        0.92354893,  0.42418053])
```
I have tentatively fixed it on my end by adding `warnings.simplefilter("always")` underneath `with warnings.catch_warnings(record=True) as ws:`, but I'm not sure if there's a better way to catch it.

**Comment by saitcakmak** [comment]
It's strange that `warnings.catch_warnings()` misses this by default (i.e., without `warnings.simplefilter("always")`). In this output, fit clearly fails with `success: False`, which should raise a warning in these lines: https://github.com/pytorch/botorch/blob/main/botorch/optim/fit.py#L261-L270

Anyways, nice catch! Putting up a PR shortly.
