### ISSUE TITLE
[Feature Request] optimize_acqf_list_mixed

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#1272]
# 🚀 Feature Request

So far `botorch` offers helper functions to optimize a list of acquisition functions and to optimize over a mixed domain. A combination is not yet straight-forward possible and a helper function for this would be helpful. A possible use case would be for example a qnparego optimization over a mixed domain.

## Pitch

From my point of view, the easiest solution would be to extend the `optimize_acqf_list` method with another argument called `fixed_features_list` which is initialized per default to `None`. If a list is provided the method could use `optimize_acqf_mixed` instead of  `optimize_acqf`.

What do you think? If this solution sounds reasonable for you, I am happy to provide a PR.

**Comment by saitcakmak** [comment]
Hi @jduerholt! That sounds like a reasonable solution to me. Happy to review if you want to put up a PR for this.

**Comment by saitcakmak** [comment]
This was implemented in #1342
