### ISSUE TITLE
[Bug] Sphinx pulls documentation from ancestor classes for some Models, making documentation incorrect

### ISSUE THREAD

**Issue by esantorella** [pytorch/botorch#1306]
# 🐛 Bug
The phrase "Initializes internal Module state, shared by both nn.Module and ScriptModule." occurs nonsensically 12 times in BoTorch [Sphinx-rendered documentation]((https://botorch.org/api/models.html)). This phrase does not occur in BoTorch; it comes from the docstrings for the `__init__` for `torch.nn.Module`, which is an ancestor of the affected classes.

There are several other similar issues:
* Documentation under `SingleTaskMultiFidelityGP` lists two separate sets of parameters, return type, and examples. The second set of parameters contains the _union_ of the parameters for this class and for its super class, `SingleTaskGP`. The example is from `SingleTaskGP`. The parameters listed are especially confusing, because there is no method that has that signature.
* `FixedNoiseMultiFidelityGP`, `SACGP`, `LCEAGP`, `LCEMGP`, and `FixedNoiseLCEMGP` all have similar issues to the above.
* [`ModelListGPyTorchModel`](https://botorch.org/api/models.html#botorch.models.gpytorch.ModelListGPyTorchModel) includes a sentence (starting with "A multi-output") and example that are from the `__init__` docstring for `ModelList`, one of `ModelListGPyTorchModel`'s superclasses.

![image](https://user-images.githubusercontent.com/9137425/179120285-3c94d34f-7fae-4a35-9c61-84f46730f62a.png)

## To reproduce

Read the botorch.org and [source code on botorch.org](https://botorch.org/api/_modules/botorch/models/gpytorch.html#ModelListGPyTorchModel).

## Expected Behavior

I would have expected documentation under a class to only contain material from the class and `__init__` docstrings for that class. I think this is what the authors of the docstrings expected.

## System information

**Please complete the following information:**
- BoTorch Version: 0.6.4 (current version on botorch.org -- I'm not running any code; this is all in the browser.)
- Computer OS: MacOS Monterey 12.4
- Browser: Chrome

## Additional context

This is not a surprise, since [Sphinx does render superclass documentation when `autoclass_content='both'`](https://github.com/sphinx-doc/sphinx/issues/7782), which matches BoTorch's [Sphinx config](https://github.com/pytorch/botorch/blob/3318c06333166328c95d24edd1055d4ef4bded70/sphinx/source/conf.py).

I think what's happening is:
- When a class has no `__init__`, such as `ModelListGPytorchModel`, or if its `__init__` has no docstring as in  `SACGP` and `LCEAGP`, then Sphinx takes a docstring from the first super class that does specify an `__init__`, and appends it to the class's class-level docstring.
- When a class has an `__init__` docstring, Sphinx doesn't take anything from super class  `__init__` docstrings.
- I'm not sure about the behavior of class docstrings.

**Comment by Balandat** [comment]
Hmm good catch.

Looks like for the contextual models (e.g. `SACGP`, `LCEAGP`) the issue is that there is no docstring for `__init__`. So moving the Args block from the class docstring into the `__init__` method and making it consistent with the rest of the code base should fix those issues. 

We'll have to think a bit more about what to do if a class doesn't have an `__init__` method but we don't want to include the docstring from the parent class.

**Comment by esantorella** [comment]
It would be ideal if this could be fixed just by changing the Sphinx config.

If that's not possible, then yeah I think it makes sense to require that `__init__` docstrings contain an Args block. For the classes that don't have an `__init__`, most seem to be ABCs or other base classes that probably shouldn't be instantiated or even touched by end users. Do we want these in the Sphinx-rendered documentation at all? We could just not include them by adding `:meta private:` to the docstring.

**Comment by esantorella** [comment]
Closed by #1319
