### ISSUE TITLE
Visiting botorch.org results in a 404

### ISSUE THREAD

**Issue by tyler-romero** [pytorch/botorch#1309]
# Visiting botorch.org results in a 404

## To reproduce

Open https://botorch.org/

## Expected Behavior

Site loads

## Additional context

```
404
There isn't a GitHub Pages site here.
```

**Comment by eytan** [comment]
The site loads for me... try again?

**Comment by saitcakmak** [comment]
Yeah, I just fixed this. It was broken for 10-15 mins.

For context: Our automated release process failed for 0.6.5 release. I manually uploaded 0.6.5 packages and I was updating the website manually as well. That website update part failed, which lead to the 404. For now, I reverted to 0.6.4 website. I'll investigate and update it properly later today.
