### ISSUE TITLE
[Bug] One unit test failing on main, Python 3.9 only

### ISSUE THREAD

**Issue by esantorella** [pytorch/botorch#1331]
# 🐛 Bug

One unit test is failing. This happened for MacOS, Ubuntu, and Windows, but on Python 3.9 only (not 3.7). This happened on [main](https://github.com/pytorch/botorch/runs/7587401356?check_suite_focus=true), as well as in PRs #1327 , #1328 , #1329 , and #1330, none of which could have plausibly broken this test.

## To reproduce

[Actions](https://github.com/pytorch/botorch/runs/7587401356?check_suite_focus=true)

** Stack trace/error message **
```
=================================== FAILURES ===================================
___________________ TestSampleUtils.test_find_interior_point ___________________

self = <test.utils.test_sampling.TestSampleUtils testMethod=test_find_interior_point>

    def test_find_interior_point(self):
        # basic problem: 1 <= x_1 <= 2, 2 <= x_2 <= 3
        A = np.concatenate([np.eye(2), -np.eye(2)], axis=0)
        b = np.array([2.0, 3.0, -1.0, -2.0])
        x = find_interior_point(A=A, b=b)
        self.assertTrue(np.allclose(x, np.array([1.5, 2.5])))
        # problem w/ negatives variables: -2 <= x_1 <= -1, -3 <= x_2 <= -2
        b = np.array([-1.0, -2.0, 2.0, 3.0])
        x = find_interior_point(A=A, b=b)
        self.assertTrue(np.allclose(x, np.array([-1.5, -2.5])))
        # problem with bound on a single variable: x_1 <= 0
        A = np.array([[1.0, 0.0]])
        b = np.zeros(1)
        x = find_interior_point(A=A, b=b)
        self.assertLessEqual(x[0].item(), 0.0)
        # unbounded problem: x >= 3
        A = np.array([[-1.0]])
        b = np.array([-3.0])
        x = find_interior_point(A=A, b=b)
>       self.assertAlmostEqual(x.item(), 6.201544, places=4)
E       AssertionError: 5.0 != 6.201544 within 4 places (1.2015440000000002 difference)

test/utils/test_sampling.py:311: AssertionError
```

## Expected Behavior

`x.item()` should be close to  6.201544 rather than being 5.0.

## System information

GitHub Actions on current commit (147cf755db8f2da5e22788a9155372432f0c1ae6)

## Additional context

The last overnight run passed, so I think #1318 was the only commit recent enough to do this.

**Comment by Balandat** [comment]
Huh, interesting. My initial guess would be that maybe the scipy version on the py3.9 install is a different one than on <3.8 which may have changed the behavior of the linear programming solver? Will have to dig a bit deeper what's going on here.

**Comment by Balandat** [comment]
From the scipy 1.9.0 release notes: 

> The default method of scipy.optimize.linprog is now 'highs', not
'interior-point' (which is now deprecated), so callback functions and
some options are no longer supported with the default method. With the
default method, the x attribute of the returned OptimizeResult is
now None (instead of a non-optimal array) when an optimal solution
cannot be found (e.g. infeasible problem).

Since scipy 1.9.0 requires python 3.8+, we're not seeing the test failure on the 3.7 test (which uses the old scipy version). I think the proper thing to do here is probably to just explicitly use the new `highs` method and update the expected result. Will put up a PR.
