### ISSUE TITLE
NEI not outperforming EI?

### ISSUE THREAD

**Issue by EvanClaes** [pytorch/botorch#1391]
## Issue description

I'm evaluating the performance of NEI vs EI on two in silico bioprocess models. When there is no noise on the observations, EI clearly outperforms a random exploration and a simple GP maximization algorithm (the maximum expected value of the GP is taken as the next query). However, when I add noise (Gaussian with standard deviation of 1% the observed value), the performance of both EI and the GP max algorithm becomes equal to random exploration.

So I tried NEI (with a fixed noise GP), but this did not improve the performance (still equal to random exploration). Is there anything I can check to see what is going wrong?

I also checked the [q-NEI tutorial](https://botorch.org/tutorials/closed_loop_botorch_only) to start from there and then adjust towards my case, but the figure at the end there also seems to show that NEI is not outperforming EI...?

**Comment by eytan** [comment]
Are you using the default model?  How are you normalizing your inputs?  Is
it possible that you are injecting more noise than you think you?

It might be helpful to compare the GP model fits w/ and w/o the noise.  If
the GP ends up just predicting the mean then I would expect most algorithms
to end up doing random exploration.
https://botorch.org/tutorials/batch_mode_cross_validation has some code for
doing cross validation / ocular tests of the GP fit.

e

**Comment by EvanClaes** [comment]
Hello Eytan,

Thanks for your feedback, it helped. The noise specification was indeed the problem. I was giving the model the noise of the observed values, not of the standardized ones.  I properly scaled the noise and now it is working perfectly.

PS: Any idea why the tutorial is not showing the NEI as better than EI?

**Comment by eytan** [comment]
That’s a good question. Perhaps the noise level isn’t very high? The
standard errors are also very wide, so there aren’t many replicates. 10
random restarts can also be a bit low especially in the constrained
setting. So there might be a larger gap if one increases either of those
numbers.

**Comment by Balandat** [comment]
Yeah I think it's just too noisy to say much - and running a proper comparison with a lot of iterations is a bit too costly to run as a tutorial. Maybe we can clarify this in the text of the tutorial and point folks to other evaluations we've done as part of papers?

**Comment by esantorella** [comment]
Closing in favor of #1861 for clarity
