### ISSUE TITLE
gpytorch.utils.broadcasting.{name} deprecated causing import error

### ISSUE THREAD

**Issue by nirtiac** [pytorch/botorch#1404]
If you are submitting a bug report or feature request, please use the respective
issue template.

## Issue description

The [newest release](https://github.com/cornellius-gp/gpytorch/blame/master/gpytorch/utils/broadcasting.py) of gypytorch deprecated gpytorch.utils.broadcasting causing an import error (as pictured). 

![Screen Shot 2022-09-12 at 15 11 52](https://user-images.githubusercontent.com/8173741/190473751-b7feff58-ee8d-40d9-b5ab-a54744997b7e.png)

## Code example

from botorch.models.utils import fantasize as fantasize_flag

## System Info
Please provide information about your setup, including
- BoTorch Version (run `print(botorch.__version__)` : 1.9
- GPyTorch Version (run `print(gpytorch.__version__)`0.7
- PyTorch Version (run `print(torch.__version__)` 1.1.2
- Computer OS Ubuntu and Mac

**Comment by saitcakmak** [comment]
Hi @nirtiac. This issue should be resolved after 0.7.0 release. I tried both with 0.7.0 and 0.7.1 versions and everything seems fine. The imports causing the error was removed in #1363.
