### ISSUE TITLE
[Feature Request] "fixed_samples" during optimization

### ISSUE THREAD

**Issue by x94carbone** [pytorch/botorch#1407]
# 🚀 Feature Request

Currently, BoTorch seems to allow the user to fix certain features during optimization via providing the `fixed_features` argument to `optimize_acqf` and related functions [here](https://botorch.org/api/_modules/botorch/optim/optimize.html). During the process of finding the "next point to sample" under the given policy/acquisition function, these features will remain fixed.

In a way, one can imagine for some value of `q` and a problem with `n` features, the proposed matrix of `q x n` points are the points to sample for the next experiment, where `q > 1` is obviously for joint optimization. Using `fixed_features` allows you to fix certain _columns_ during this procedure.

I would like to fix certain _rows_ during joint (or sequential) optimization.

## Motivation

This feature is not related to any problem with BoTorch and might even be out of scope. The motivation is as follows. I would like to solve the problem of:

Given a model, the data it was conditioned on, and `m` inputs _for which we do not know the output_, what are the next `q` inputs to choose?

There does appear to be an intuitive way to solve this, but it is unclear to me whether or not it is the most efficient or practical way: For the `m` constrained inputs (of shape `m x n`) for which we do not know the ground truth, simply sample from whatever approximator/surrogate is being used (e.g. if it's a GP, just draw a sample from it), and treat that sample as the source of ground truth. Then, recondition/refit the model on those "dummy" ground truth values and do joint/sequential optimization over your `q` points using the tools BoTorch already provides. My concern with this approach is its efficiency, since there is now an "outer loop" over samples from the approximating surrogate.

I tried to dig around to see where `fixed_features` was used during the optimization process, and it appears that it's applied in the `botorch.generation.gen.gen_canddaites_scipy` function. From there it's not as obvious to me how this could be done, but perhaps there's a way to modify some of the arguments passed to the SciPy functions to make this possible? I would understand if it's simply not possible though, or if perhaps the "outer loop" I mention above is actually required and then does not require any new features in BoTorch.

### Describe the solution you'd like
If I am correct that a more sensible solution is possible than what I've provided in the Motivation is true, then it would be great to have an argument `fixed_samples` added to the `botorch.optim.optimize.optimize_acqf` family of functions, allowing the user to specify these fixed samples.

### Describe alternatives you've considered
See Motivation.

### Are you willing to open a pull request?
I would usually be more than happy to, but in these circumstances [I am simply not comfortable with opening a PR](https://github.com/pytorch/botorch/issues/1366#issuecomment-1226563366) given the non-standard "paperwork" required.

**Comment by eytan** [comment]
Hi Matt,

If I understand correctly, this sounds a lot like how we handle batch
optimization with "sequential" greedy optimization.  We have some built-in
functionality for appending fixed pending points using a
decorator, ***@***.***_pending_points`.  For many classes of acquisition
functions, conditioning on the selected data, and integrating over the
posterior when computing AF is a good approximation of the joint problem,
and often works better in practice (since many AFs are submodular, and the
smaller optimization problem is easier).  See Sec 5.2 of
https://arxiv.org/pdf/1910.06403.pdf for more description on how to do this
in BoTorch, and pointers to related work.

**Comment by x94carbone** [comment]
@eytan I think this is _almost_ what I am looking for, but possibly with an important difference, please correct me if I'm wrong.

I want to set those "pending points" manually, not through some sequential process. To do this, would I simply set the `X_pending` attribute manually? The [docs](https://botorch.org/api/utils.html#botorch.utils.transforms.concatenate_pending_points) are not super clear on this matter. If all I need to do is: 

1. Set `X_pending` manually, and
2. Add the `concatenate_pending_points` decorator to the `forward` methods of the acquisition function

then that solves my problem, as I can just write a class factory for this, and unless you want to make a completely new feature for this it's easily solved outside of BoTorch.

Does this make sense? Thank you!

**Comment by eytan** [comment]
Can you give some broader context about why you want to do this? That
strategy sounds reasonable but I’ll let others chime in here. Whether or
not it’s worth upstreaming depends on how generally useful this will be to
users in the future.

**Comment by x94carbone** [comment]
> Can you give some broader context about why you want to do this?

@eytan Sure, time-delayed, sequential experimentation: Given an observation, I have a delay period where other experiments are locked in but not yet observed. So I want to optimize my next input given a model, a set of `{x, y}` pairs (which is more or less embedded in the model, which is a GP via gpytorch for me), _and_ a set of inputs `{x}` which are _going_ to run but have not run yet.

To me, this is in principle as simple as having a batch size `q`, but locking in `m < q` of those batches to fixed points, which do not change during the MC optimization (or whatever search procedure is used). I'm going to guess in practice this is more challenging.

**Comment by Balandat** [comment]
> Given an observation, I have a delay period where other experiments are locked in but not yet observed. So I want to optimize my next input given a model, a set of {x, y} pairs (which is more or less embedded in the model, which is a GP via gpytorch for me), and a set of inputs {x} which are going to run but have not run yet.

This is exactly the setting the pending points are designed to handle. You don't need to use a decorator for this, you can just pass in the pending points as a tensor to the constructor of the acquisition function (this is supported by most if not all MC acquisition functions, e.g. `qEI`: https://github.com/pytorch/botorch/blob/main/botorch/acquisition/monte_carlo.py#L134).

**Comment by x94carbone** [comment]
@Balandat Ah perfect, I think that solves my problem.

That said, unless there's some reason not to you might want to consider updating the `optimize_acqf` API to allow for passing `X_pending` directly. That could then call the `set_X_pending` [method](https://github.com/pytorch/botorch/blob/b0d9f7743884e4b5d74216ef36893c290fcbe381/botorch/acquisition/acquisition.py#L70) in the acquisition function base class.

I'll give this a try in my own code and if there's any problems related to BoTorch I'll update!

**Comment by Balandat** [comment]
> That said, unless there's some reason not to you might want to consider updating the optimize_acqf API to allow for passing X_pending directly. That could then call the set_X_pending in the acquisition function base class.

Hmm so one reason to not do it is to avoid overloading the `optimize_acqf` API (it's got a lot of options already). Is there anything that makes passing `X_pending` into the acquisition function instantiation more cumbersome than passing it to `optimize_acqf`? Or is it a discoverability issue that people may not be aware of this capability?

**Comment by x94carbone** [comment]
Yeah absolutely fair points. I agree the `optimize_acqf` function has quite a lot of inputs already. For me, this is the big thing:

>  Or is it a discoverability issue that people may not be aware of this capability?

I wasn't aware! 😁

The "smaller thing": I personally don't have a strong argument against leaving `X_pending` where it is, but something to consider is the way that `optimize_acqf` is used. To me, `optimize_acqf` is called every time someone wants to get a new point. It might be logical to consider allowing users to pass `X_pending` there for that logical reason. It would also make a nice companion to the argument `fixed_features` (as I implicitly suggested you could even consider renaming the argument as `fixed_inputs` or something). Totally up to you. On the other hand it could complicate the logic somewhat (what if the user already set `X_pending` in their acquisition function?). I can see both sides of this.

**Comment by Balandat** [comment]
> To me, optimize_acqf is called every time someone wants to get a new point.

That is true, but usually a new acquisition function object is instantiated with a new model as soon as new data is available ( I understand this is not actually the case in this particular scenario). My main thought here is that the acquisition function object encapsulates the "state" of the optimization world (i.e. the what data we have, what data is pending, , and options to `optimize_acqf` are for specifying desiderata for new points to be generated. I'd like to keep this kind of logical separation in order to not overcomplicate the API.

**Comment by x94carbone** [comment]
@Balandat that's totally fair. Just curious: on a related note, what's the reason for putting `fixed_features` in `optimize_acqf`? Seems like that also belongs in the acquisition function no?

**Comment by Balandat** [comment]
That argument could be made, I guess. Though you may also do sth like compute the next recommended candidate for different values of `fixed_features` without conditioning on the ones you have already generated. E.g. this can be the case in a human-in-the loop setting where you may want to inspect the model predictions at the generated candidates for sanity checking / evaluating whether they are reasonable (in many such cases it's basically impossible to encode all the domain knowledge and latent preferences into the mathematical problem description, so there is some degree of interactivity - this is pretty common when using this e.g. for field experiments in the large-batch slow-iteration setting).

**Comment by saitcakmak** [comment]
> what's the reason for putting fixed_features in optimize_acqf? Seems like that also belongs in the acquisition function no?

Just to add, `fixed_features` are handled using a `FixedFeatureAcquisitionFunction` under the hood. So, the `optimize_acqf` input is there purely for convenience.

**Comment by x94carbone** [comment]
Got it. Thank you all for your help. I believe that overall my issue is resolved. Ultimately the rest are design decisions which are obviously up to you all 👍

Feel free to close the issue unless you feel it's worth further discussion.

**Comment by Balandat** [comment]
Sounds good, thanks for the great discussion! We've had some internal discussions about potentially overhauling our acquisition function optimization APIs so I'll close this issue for now but earmark it for some of those larger discussions.
