### ISSUE TITLE
  Usage of constraints in botorch

### ISSUE THREAD

**Issue by 1bing2** [pytorch/botorch#1416]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```python
# Your code goes here
# Please make sure it does not require any external dependencies
```

** Stack trace/error message **
```
// Paste the bad output here!
```

## System information

**Please complete the following information:**
- 
- 
- 
-

**Comment by saitcakmak** [comment]
Hi @1bing2. Can you please fill out the details to explain the bug you're seeing? It is very difficult for us to look into a bug report without steps to reproduce.

**Comment by 1bing2** [comment]
Hi, @saitcakmak . My code will  attach as follow.
`import os
from botorch.exceptions.warnings import BotorchWarning, OptimizationWarning
import torch
import logging
import warnings
from copy import deepcopy
import numpy as np
from botorch.optim.fit import fit_gpytorch_scipy
np.random.seed(0)
import random
from botorch.models.utils import fantasize as fantasize_flag, validate_input_scaling
random.seed(0)
torch.manual_seed(0)
from botorch.acquisition.multi_objective.analytic import ExpectedHypervolumeImprovement
from gpytorch.mlls.sum_marginal_log_likelihood import SumMarginalLogLikelihood
import torch.nn as nn
import gpytorch
from botorch.settings import debug
from botorch.models.gp_regression import SingleTaskGP
from botorch.models.transforms.outcome import Standardize
from gpytorch.mlls.exact_marginal_log_likelihood import ExactMarginalLogLikelihood
from botorch.utils.transforms import unnormalize
from botorch.utils.sampling import draw_sobol_samples
from botorch.optim.optimize import optimize_acqf, optimize_acqf_list,optimize_acqf_discrete
from botorch.models.converter import batched_to_model_list, model_list_to_batched
from botorch.utils.multi_objective.box_decompositions.non_dominated import NondominatedPartitioning
from botorch.acquisition.multi_objective.monte_carlo import qExpectedHypervolumeImprovement
from botorch import fit_gpytorch_model
from botorch.exceptions.errors import UnsupportedError
from botorch.sampling.samplers import SobolQMCNormalSampler
from botorch.exceptions import BadInitialCandidatesWarning
from botorch.utils.multi_objective.pareto import is_non_dominated
from botorch.utils.multi_objective.hypervolume import Hypervolume
from botorch.optim.utils import sample_all_priors
import sys
from gpytorch.utils.errors import NotPSDError
from gpytorch.kernels.matern_kernel import MaternKernel
from gpytorch.kernels.scale_kernel import ScaleKernel
from gpytorch.means.constant_mean import ConstantMean
from gpytorch.models.exact_gp import ExactGP
from gpytorch.priors.torch_priors import GammaPrior
from botorch.models.gpytorch import BatchedMultiOutputGPyTorchModel
torch.set_default_tensor_type(torch.DoubleTensor)
from gpytorch.likelihoods.gaussian_likelihood import (
    _GaussianLikelihoodBase,
    FixedNoiseGaussianLikelihood,
    GaussianLikelihood,)
from gpytorch.constraints.constraints import GreaterThan
from gpytorch.distributions.multivariate_normal import MultivariateNormal

a_np=np.array([[0.09,0.11,1000,23,0,120,1],
        [0.1,0.12,1000,140,20,120,1],
        [0.11,0.13,1000,130,10,150,1],
        [0.12,0.14,1000,110,40,120,1],
        [0.08, 0.11, 1000, 120, 30, 140, 0.8],
        [0.012, 0.11, 1000, 100, 50, 120, 0.9]])
a_tensor=torch.from_numpy(a_np)
class DNN_Feature_Extractor(nn.Module):
     def __init__(self,train_x):
            super(DNN_Feature_Extractor, self).__init__()
            self.linear1=torch.nn.Linear(7, 500)  #train_x.size(-1)
            self.relu1=torch.nn.ReLU()
            self.linear2=torch.nn.Linear(500, 100)
            self.relu2= torch.nn.ReLU()
            self.linear3=torch.nn.Linear(100, 50)
            self.relu3=torch.nn.ReLU()
            self.linear4=torch.nn.Linear(50, 7)
     def forward(self,train_x):
         # x=train_x.view(-1,3)
         x=self.linear1(train_x)
         x=self.relu1(x)
         x = self.linear2(x)
         x = self.relu2(x)
         x = self.linear3(x)
         x = self.relu3(x)
         x = self.linear4(x)
         return x
MIN_INFERRED_NOISE_LEVEL = 1e-4
class GPRegressionModel2(BatchedMultiOutputGPyTorchModel, gpytorch.models.ExactGP):
    def __init__(self,train_X,train_Y,likelihood =None,covar_module= None,mean_module = None,
            outcome_transform = None,input_transform = None,) :
        with torch.no_grad():
            transformed_X = self.transform_inputs(
                X=train_X, input_transform=input_transform
            )
        if outcome_transform is not None:
            train_Y, _ = outcome_transform(train_Y)
        self._validate_tensor_args(X=transformed_X, Y=train_Y)
        ignore_X_dims = getattr(self, "_ignore_X_dims_scaling_check", None)
        validate_input_scaling(
            train_X=transformed_X, train_Y=train_Y, ignore_X_dims=ignore_X_dims
        )
        self._set_dimensions(train_X=train_X, train_Y=train_Y)
        train_X, train_Y, _ = self._transform_tensor_args(X=train_X, Y=train_Y)
        if likelihood is None:
            noise_prior = GammaPrior(1.1, 0.05)
            noise_prior_mode = (noise_prior.concentration - 1) / noise_prior.rate
            likelihood = GaussianLikelihood(
                noise_prior=noise_prior,
                batch_shape=self._aug_batch_shape,
                noise_constraint=GreaterThan(
                    MIN_INFERRED_NOISE_LEVEL,
                    transform=None,
                    initial_value=noise_prior_mode,
                ),
            )
        else:
            self._is_custom_likelihood = True
        ExactGP.__init__(self, train_X, train_Y, likelihood)
        if mean_module is None:
            mean_module = ConstantMean(batch_shape=self._aug_batch_shape)
        self.mean_module = mean_module
        if covar_module is None:
            covar_module = ScaleKernel(
                MaternKernel(
                    nu=2.5,
                    ard_num_dims=transformed_X.shape[-1],
                    batch_shape=self._aug_batch_shape,
                    lengthscale_prior=GammaPrior(3.0, 6.0),
                ),
                batch_shape=self._aug_batch_shape,
                outputscale_prior=GammaPrior(2.0, 0.15),
            )
            self._subset_batch_dict = {
                "likelihood.noise_covar.raw_noise": -2,
                "mean_module.constant": -2,
                "covar_module.raw_outputscale": -1,
                "covar_module.base_kernel.raw_lengthscale": -3,
            }
        self.covar_module = covar_module
        if outcome_transform is not None:
            self.outcome_transform = outcome_transform
        if input_transform is not None:
            self.input_transform = input_transform
        self.to(train_X)
        feature_extractor = DNN_Feature_Extractor(train_X)
        self.feature_extractor = feature_extractor


    def forward(self, x):
        if self.training:
            x = self.transform_inputs(x)
        projected_x = self.feature_extractor(x)
        # projected_x = self.scale_to_bounds(projected_x)
        a = projected_x
        mean_x = self.mean_module(a)
        covar_x = self.covar_module(a)
        return MultivariateNormal(mean_x, covar_x)
class MOBO:
    # This builds the MO
    # The user can input the problem bounds in numpy format.
    # BATCH_SIZE is integer (q) for the batch of the qEHVI
    # N_iteration is the number of iteration that are alg perform
    # If the optimization is a minimization let minimize = True
    def __init__(self, BATCH_SIZE=3,N_iteration=25, minimize=False):
        self.N_BATCH = N_iteration

        self.tkwargs = {
            "dtype": torch.double,
            # "device": torch.device("cuda" if torch.cuda.is_available() else "cpu"),
            "device": torch.device("cpu"),
        }
        self.SMOKE_TEST = os.environ.get("SMOKE_TEST")
        input_data=np.array([[0.08,0.1,0,23,0,120,0.5],[0.12,0.14,4000,150,50,155,1]])
        self.BATCH_SIZE = BATCH_SIZE
        self.NUM_RESTARTS = 30
        self.RAW_SAMPLES = 1024
        self.standard_bounds =torch.from_numpy(input_data)
        # self.standard_bounds[0]= 0
        # self.standard_bounds[1] = 1




    def generate_initial_data(self):
        # generate training data
        #problem = self.problem
        #train_x = draw_sobol_samples(bounds=self.standard_bounds, n=1, q=n, seed=torch.randint(1000, (1,)).item()).squeeze( 0)
        #train_obj = problem.evaluate(train_x)
        # negative values imply feasibility in botorch
        train_x_input=np.array([[0.09,0.11,1000,23,0,120,1],
                       [0.09,0.11,2000,23,0,120,1],
                       [0.09,0.11,3000,23,0,120,1],
                       [0.09,0.11,4000,23,0,120,1],
                       [0.09,0.11,1000,120,30,120,1],
                       [0.09,0.11,1000,150,30,120,1],
                       [0.1,0.11,1000,23,0,120,1],
                       [0.1,0.11,1000,120,30,150,1],
                       [0.1,0.11,1000,120,50,150,1],
                       [0.1,0.11,1000,130,30,150,1],
                       [0.1, 0.11, 1000, 130, 50, 150, 1],
                       [0.1,0.11,1000,140,50,150,1],
                       [0.1,0.11,1000,150,50,150,1],
                                [0.1,0.12,1000,120,30,120,1],
                                [0.1,0.12,1000,120,30,130,1],
                                [0.1,0.12,1000,120,30,140,1],
                                [0.1,0.12,1000,120,30,150,1],
                      [0.09, 0.125, 1000, 23, 0, 120, 1],
                    [0.09, 0.125, 2000, 23, 0, 120, 1],
                    [0.09, 0.125, 3000, 23, 0, 120, 1],
                    [0.09, 0.125, 4000, 23, 0, 120, 1],
                                [0.09, 0.125, 1000, 120, 30, 120, 1],
                                [0.09, 0.125, 1000, 150, 30, 120, 1],
                                [0.1, 0.125, 1000, 120, 30, 120, 1],
                                [0.1, 0.125, 1000, 120, 30, 130, 1],
                                [0.1, 0.125, 1000, 120, 30, 140, 1],
                                [0.1, 0.125, 1000, 120, 30, 150, 1],
                                [0.1, 0.125, 1000, 23, 0, 120, 1],
                                [0.1, 0.125, 1000, 120, 50, 120, 1],
                                [0.1, 0.125, 1000, 120, 50 ,130, 1],
                                [0.1, 0.125, 1000, 120, 50, 140, 1],
                                [0.1, 0.125, 1000, 120, 50, 150, 1],
                                [0.1, 0.125, 1000, 120, 10, 150, 0.9],
                                [0.1, 0.125, 1000, 120, 10, 150, 0.8]])
        train_x=torch.from_numpy(train_x_input)
        train_obj_input=np.array([[0.6,0.6,0.7],
                                  [0.55,0.6,0.7],
                                  [0.5,0.5,0.7],
                                  [0.5,0.45,0.7],
                                  [0.7,0.7,0.7],
                                  [0.65,0.65,0.7],
                                  [0.8,0.65,0.7],
                                  [0.85,0.7,0.7],
                                 [0.75,0.7,0.7],
                                  [0.8,0.7,0.7],
                                  [0.7,0.65,0.7],
                                  [0.7,0.6,0.7],
                                  [0.65,0.6,0.7],
                                  [0.75,0.6,0.5],
                                  [0.75,0.65,0.5],
                                  [0.85,0.7,0.5],
                                  [0.75,0.7,0.5],
                                  [0.65,0.65,0.65],
                                  [0.55,0.55,0.65],
                                  [0.55,0.55,0.65],
                                  [0.55,0.55,0.65],
                                  [0.75,0.75,0.8],
                                  [0.6,0.6,0.65],
                                  [0.85,0.75,0.5],
                                  [0.85,0.8,0.5],
                                  [0.9,0.85,0.5],
                                  [0.85,0.9,0.5],
                                  [0.7,0.6,0.5],
                                  [0.9,0.75,0.55],
                                  [0.9,0.75,0.55],
                                  [0.9,0.8,0.55],
                                  [0.8,0.8,0.5],
                                  [0.7,0.65,0.6],
                                  [0.7,0.65,0.55]])
        train_obj=torch.from_numpy(train_obj_input)
        self.ref_point = train_obj.min(0).values#problem.ref_point#problem.ref_point#feas_train_obj.max(0).values#

        return train_x, train_obj
    def initialize_model(self,train_x, train_obj):
        # define models for objective and constraint
        # train_x=DNN_Feature_Extractor(train_x)
        model = GPRegressionModel2(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
        # train_x1= torch.Tensor(train_x)
        # model = SingleTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
        # train_obj1 = torch.Tensor(train_obj)
        # likelihood=gpytorch.likelihoods.GaussianLikelihood()
        # model=GPRegressionModel(train_x1,train_obj,likelihood)
        mll = ExactMarginalLogLikelihood(model.likelihood, model)
        # if torch.cuda.is_available():
        #     model = model.cuda()
        #     mll = mll.cuda()
        return mll, model
    def optimize_qehvi_and_get_observation(self,model, train_obj, sampler):
        """Optimizes the qEHVI acquisition function, and returns a new candidate and observation."""
        # partition non-dominated space into disjoint rectangles
        partitioning = NondominatedPartitioning(ref_point=self.ref_point, Y=train_obj)
        acq_func = qExpectedHypervolumeImprovement(
            model=model,
            ref_point=self.ref_point.tolist(),  # use known reference point
            partitioning=partitioning,
            sampler=sampler,
        )
  candidates, _ = optimize_acqf_discrete(
            acq_function=acq_func,
            q=self.BATCH_SIZE,
             # q=1,
            choices=a_tensor,
            max_batch_size=2048,
            unique=True,
        )
  new_x = unnormalize(candidates.detach(), bounds=self.standard_bounds)
        # new_obj = problem.evaluate(new_x)
        return new_x
)
    def perform_MOBO(self):
        import time
        import warnings

        warnings.filterwarnings('ignore', category=BadInitialCandidatesWarning)
        warnings.filterwarnings('ignore', category=RuntimeWarning)

        self.N_TRIALS = 1 if not self.SMOKE_TEST else 2

        self.MC_SAMPLES = 128 if not self.SMOKE_TEST else 16

        verbose = False

        hvs_qehvi_all = []


        # average over multiple trials
        for trial in range(1, self.N_TRIALS + 1):
            torch.manual_seed(trial)

            hvs_qehvi = []

            # call helper functions to generate initial training data and initialize model
            # train_x_qehvi, train_obj_qehvi = self.generate_initial_data(n=3 * (self.problem.dim + 1))
            train_x_qehvi, train_obj_qehvi = self.generate_initial_data()
            hv = Hypervolume(ref_point=self.ref_point)

            # compute hypervolume
            # train_x_qehvi.cuda()
            # train_obj_qehvi.cuda()
            mll_qehvi, model_qehvi = self.initialize_model(train_x_qehvi, train_obj_qehvi)

            # compute pareto front
            # is_feas = (train_con_qehvi <= 0).all(dim=-1)
            # feas_train_obj = train_obj_qehvi[is_feas]
            # if feas_train_obj.shape[0] > 0:
            pareto_mask = is_non_dominated(train_obj_qehvi)
            pareto_y = train_obj_qehvi[pareto_mask]
            # compute hypervolume
            volume = hv.compute(pareto_y)
            # else:
            #     volume = 0.0

            hvs_qehvi.append(volume)

            # run N_BATCH rounds of BayesOpt after the initial random batch

            for iteration in range(1, self.N_BATCH + 1):

                t0 = time.time()

                # fit the models

                # fit_gpytorch_model(mll_qehvi) weight_decay=1e-5
                optimizer = torch.optim.Adam([
                    {'params': model_qehvi.feature_extractor.parameters()},
                    {'params': model_qehvi.covar_module.parameters()},
                    {'params':model_qehvi.mean_module.parameters()},
                    {'params': model_qehvi.likelihood.parameters()},
                ], lr=0.0001,weight_decay=1e-5)
                mll_qehvi.eval()
                model_qehvi.eval()
                qehvi_sampler = SobolQMCNormalSampler(num_samples=self.MC_SAMPLES)

                new_x_qehvi= self.optimize_qehvi_and_get_observation(
                    model_qehvi, train_obj_qehvi, qehvi_sampler
                )
                print(new_x_qehvi)
 print(model_qehvi(new_x_qehvi))
                a=[]
                n = int(input())
                input_obj = []
                for _ in range(n):
                    input_obj.append(list(map(float, input().rstrip().split())))

                # new_obj_qehvia=float(input("请输入vlsi_flow得到的目标值："))
                print(input_obj)
                input_numpy = np.array(input_obj)
                new_obj_qehvi=torch.from_numpy(input_numpy)
                for i in range(1):
                    # Zero backprop gradients
                    optimizer.zero_grad()
                    # Get output from model
                    # fit_gpytorch_model(mll_qehvi)
                    output = model_qehvi(new_x_qehvi)
                    # output.view(3,2)
                    # Calc loss and backprop derivatives
                    # output
                    output1=output[0]
                    output2=output[1]
                    output3 = output[2]
                    # output1 = output[0]
                    # output2 = output[1]
                    new_obj_qehvi1=new_obj_qehvi[0]
                    new_obj_qehvi2=new_obj_qehvi[1]
                    new_obj_qehvi3 = new_obj_qehvi[2]
                    loss1 = - mll_qehvi(output1, new_obj_qehvi1)
                    loss2 = - mll_qehvi(output2, new_obj_qehvi2)
                    loss3 = - mll_qehvi(output3, new_obj_qehvi3)
                    loss=loss1+loss2+loss3
                    # loss=-mll_qehvi(output,new_obj_qehvi)
                    loss_mean=loss.mean([0])
                    a.append(loss_mean.detach().numpy())

                    loss_mean.backward()
                    # iterator.set_postfix(loss=loss.item())
                    optimizer.step()

                    torch.save(model_qehvi.state_dict(), 'my_gp_with_nn_model.pth')
                # mll_qehvi.eval()
                # model_qehvi.eval()
                # model_qehvi.train()
                # mll_qehvi.train()

                # define the qEI and qNEI acquisition modules using a QMC sampler

                # qehvi_sampler = SobolQMCNormalSampler(num_samples=self.MC_SAMPLES)
                #
                # # optimize acquisition functions and get new observations
                #
                # new_x_qehvi, new_obj_qehvi = self.optimize_qehvi_and_get_observation(
                #     model_qehvi, train_obj_qehvi, qehvi_sampler
                # )

                # update training points

                train_x_qehvi = torch.cat([train_x_qehvi, new_x_qehvi])
                train_obj_qehvi = torch.cat([train_obj_qehvi, new_obj_qehvi])
                # train_con_qehvi = torch.cat([train_con_qehvi, new_con_qehvi])
                self.train_x_qehvi, self.train_obj_qehvi = train_x_qehvi, train_obj_qehvi
                # update progress
                for hvs_list, train_obj, train_x in zip(
                        (hvs_qehvi,),
                        (train_obj_qehvi,),
                        (train_x_qehvi,)
                ):
                    # compute pareto front

                # if feas_train_obj.shape[0] > 0:
                    pareto_mask = is_non_dominated(train_obj)
                    pareto_y = train_obj[pareto_mask]
                    pareto_x = train_x[pareto_mask]

                    # compute feasible hypervolume
                    volume = hv.compute(pareto_y)
                    # else:
                    #     volume = 0.0
                    hvs_list.append(volume)

                # reinitialize the models so they are ready for fitting on next iteration
                # Note: we find improved performance from not warm starting the model hyperparameters
                # using the hyperparameters from the previous iteration
                mll_qehvi, model_qehvi = self.initialize_model(train_x_qehvi, train_obj_qehvi)

                t1 = time.time()

                # if verbose:
                #     print(
                #         f"\nBatch {iteration:>2}: Hypervolume (random, qParEGO, qEHVI) = "
                #         f"({hvs_random[-1]:>4.2f}), "
                #         f"time = {t1-t0:>4.2f}.", end=""
                #     )
                # else:
                #     print(".", end="")
                # the exact output you're looking for:
                sys.stdout.write('\r')
                sys.stdout.write("trial: " + str(trial) + "/" + str(self.N_TRIALS) +
                                 ": [{:{}}] {:.1f}%".format("=" * iteration, self.N_BATCH, (100 / (self.N_BATCH) * iteration)))
                # sys.stdout.write("trial: " + str(trial) + "/" + str(self.N_TRIALS) + ": [%-",(self.N_BATCH),"s] %d%%" % (
                # '=' * iteration, iteration / self.N_BATCH * 100))
                sys.stdout.flush()
                b=a
            self.pareto_y = pareto_y
            self.pareto_x = pareto_x
            c=b
            hvs_qehvi_all.append(hvs_qehvi)
        return hvs_qehvi_all,pareto_x,pareto_y,c
`

MY trial code
`import torch
import time
import numpy as np
from botorch.test_functions.multi_objective import BraninCurrin
np.random.seed(0)
import random

random.seed(0)
torch.manual_seed(0)

from src.MOBO_reg import MOBO



#np.array([[-np.pi, -5.,-5.],[np.pi,5.,5.]])
# problem1=BraninCurrin(negate=True)
start=time.process_time()
MOBO_TRY = MOBO(minimize=True, N_iteration=10)
end=time.process_time()
hvs_qehvi_all,pareto_x,pareto_y,c=MOBO_TRY.perform_MOBO()

print(c)
print(hvs_qehvi_all)
print(pareto_x)
print(pareto_y)
print(end-start)`








As youcan see,my entire code  upload. My input is the real experiment results, i use the _optimize_acqf_discrete_ function to find the new_candidate in my design space(  Design space in code is   a_tensor） However ,in the trial the new_candidates is not in my design space .  Thank you!

The trial result is tensor([[8.0480e-02, 1.0440e-01, 4.0000e+06, 1.2723e+04, 2.5000e+03, 4.3200e+03,
         9.5000e-01],
        [8.4800e-02, 1.0560e-01, 4.0000e+06, 1.3993e+04, 2.0000e+03, 4.3200e+03,
         1.0000e+00],
        [8.4000e-02, 1.0480e-01, 4.0000e+06, 1.7803e+04, 1.0000e+03, 4.3200e+03,
         1.0000e+00]])
my design space is:
a_np=np.array([[0.09,0.11,1000,23,0,120,1],
        [0.1,0.12,1000,140,20,120,1],
        [0.11,0.13,1000,130,10,150,1],
        [0.12,0.14,1000,110,40,120,1],
        [0.08, 0.11, 1000, 120, 30, 140, 0.8],
        [0.012, 0.11, 1000, 100, 50, 120, 0.9]])

**Comment by saitcakmak** [comment]
Closing this in favor of #1430
