### ISSUE TITLE
Problems with noisy expected improvement and heteroskedastic noise GP

### ISSUE THREAD

**Issue by EvanClaes** [pytorch/botorch#1436]
## Issue description

I'm trying to use q-noisy expected improvement together with a heteroskedastic noise GP, but am getting 
`NanError: cholesky_cpu: 9 of 9 elements of the torch.Size([3, 3]) tensor are NaN.`
when setting up the acquisition function.

Notably, this does not happen every time. The code is somewhat stochastic though, as I add some gaussian noise in line 163.

## Code example

```
import os
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from botorch.utils.sampling import draw_sobol_samples
from scipy.integrate import ode
from botorch.models.gp_regression import SingleTaskGP, FixedNoiseGP, HeteroskedasticSingleTaskGP
from gpytorch.mlls.sum_marginal_log_likelihood import ExactMarginalLogLikelihood
from botorch.fit import fit_gpytorch_model
from botorch.utils.transforms import unnormalize, normalize
from mpl_toolkits.mplot3d import axes3d
from botorch.acquisition.analytic import ExpectedImprovement, NoisyExpectedImprovement
from botorch.acquisition.monte_carlo import qExpectedImprovement, qNoisyExpectedImprovement
from botorch.optim import optimize_acqf
from scipy.optimize import minimize
from botorch.sampling.samplers import SobolQMCNormalSampler




def calc_growth_rate(t):
    g = np.array([49427.9581111241, 0.0112812472592155])
    c = 1e6 + g[0]/g[1]*(1 - np.exp(-g[1]*t))
    mu  = g[0]*np.exp(-g[1]*t)/c
    return mu,c

def fun_rAAV(t,y,pars):
    #PARAMETERS
    kuptake = pars[0] #DNA uptake from medium into cell cytosol (1/h)
    # kuptake = 1.19*10**-3 #DNA uptake from medium into cell cytosol (1/h)
    kescape = pars[1] #endosomal escape (1/h)
    knuclear_entry = pars[2] #nuclear entry (1/h)
    kplasmid_degrade = pars[3] #plasmid degradation (1/h)
    kCap_syn = pars[4] #capsid protein synthesis (molecule/cell/h)
    kRep_syn = pars[5] #Rep protein synthesis (molecule/cell/h)
    kVP_degrade = pars[6] #VP degradation (1/h)
    kRep_protein_degrade = pars[7] #Rep protein degradation (1/h)
    kDNA_rep = pars[8] #transgene rescue and replication (cell²/molecule²/h)
    kassembly = pars[9] #capsid assembly (1/h)
    ksecrete = pars[10] #capsid secretion from the nucleus to the cytosol (1/h)
    kDNA_pack = pars[11] #viral DNA encapsidation (molecule/cell/h)
    kRep_bind_plasmid = pars[12] #binding of Rep protein on packaging plasmid (molecule/cell/h)
    kRep_bind_capsid = pars[13] #binding of Rep protein on empty capsid (molecule/cell/h)
    
#     µ = pars[14] #cell growth rate
    # µ = 1/18 #cell growth rate
    # µ = 1/30 #cell growth rate
    µ,c = calc_growth_rate(t)
    
    
    #STATES & INTERMEDIATE PARAMETERS
    #gene delivery
    ExComplex_H = y[0] #extracellular helper plasmid complexes
    EndosComplex_H = y[1] #endosomal helper plasmid complexes
    CytoComplex_H = y[2] #cytosomal helper plasmid complexes
    NuclearPlasmid_H = y[3] #naked helper plasmid in nucleus
    ExComplex_P = y[4] #extracellular packaging plasmid complexes
    EndosComplex_P = y[5] #endosomal packaging plasmid complexes
    CytoComplex_P = y[6] #cytosomal packaging plasmid complexes
    NuclearPlasmid_P = y[7] #naked packaging plasmid in nucleus
    ExComplex_V = y[8] #extracellular vector plasmid complexes
    EndosComplex_V = y[9] #endosomal vector plasmid complexes
    CytoComplex_V = y[10] #cytosomal vector plasmid complexes
    NuclearPlasmid_V = y[11] #naked vector plasmid in nucleus

    #viral vector synthesis
    RepProtein = y[12] #rep protein
    VP = y[13] #viral protein
    vDNA = y[14] #viral DNA
    EmptyCapNuc = y[15] #empty capsids in nucleus
    FullCapNuc = y[16] #full capsids in nucleus
    EmptyCapCyto = y[17] #empty capsids in cytoplasm
    FullCapCyto = y[18] #full capsids in cytoplasm
    RepRCcomplex = y[19] #plasmids bound with rep protein
    CapRepComplex = y[20] #empty capsids bound with rep protein
    
    
    #DIFF EQ
    #gene delivery
    dExComplex_Hdt = -kuptake*ExComplex_H
    dEndosComplex_Hdt = kuptake*ExComplex_H-(kescape+kplasmid_degrade+µ)*EndosComplex_H
    dCytoComplex_Hdt = kescape*EndosComplex_H-(knuclear_entry+kplasmid_degrade+µ)*CytoComplex_H
    dNuclearPlasmid_Hdt = knuclear_entry*CytoComplex_H-(kplasmid_degrade+µ)*NuclearPlasmid_H
    dExComplex_Pdt = -kuptake*ExComplex_P
    dEndosComplex_Pdt = kuptake*ExComplex_P-(kescape+kplasmid_degrade+µ)*EndosComplex_P
    dCytoComplex_Pdt = kescape*EndosComplex_P-(knuclear_entry+kplasmid_degrade+µ)*CytoComplex_P
#     dNuclearPlasmid_Pdt = knuclear_entry*CytoComplex_P-(kplasmid_degrade+µ)*NuclearPlasmid_P
    dNuclearPlasmid_Pdt = knuclear_entry*CytoComplex_P-(kplasmid_degrade+µ)*NuclearPlasmid_P-kRep_bind_plasmid*NuclearPlasmid_P*RepProtein
    dExComplex_Vdt = -kuptake*ExComplex_V
    dEndosComplex_Vdt = kuptake*ExComplex_V-(kescape+kplasmid_degrade+µ)*EndosComplex_V
    dCytoComplex_Vdt = kescape*EndosComplex_V-(knuclear_entry+kplasmid_degrade+µ)*CytoComplex_V
    dNuclearPlasmid_Vdt = knuclear_entry*CytoComplex_V-(kplasmid_degrade+µ)*NuclearPlasmid_V
    
    #viral vector synthesis
    dRepProteindt = kRep_syn*NuclearPlasmid_P*NuclearPlasmid_H-kRep_bind_plasmid*RepProtein*NuclearPlasmid_P-kRep_bind_capsid*RepProtein*EmptyCapNuc+kDNA_pack*CapRepComplex*vDNA-(kRep_protein_degrade+µ)*RepProtein
    dVPdt = kCap_syn*NuclearPlasmid_P*NuclearPlasmid_H-(kVP_degrade+µ)*VP-60*kassembly*VP
    dvDNAdt = kDNA_rep*RepProtein*NuclearPlasmid_H*NuclearPlasmid_V-kDNA_pack*CapRepComplex*vDNA-µ*vDNA
    dEmptyCapNucdt = kassembly*VP-kRep_bind_capsid*RepProtein*EmptyCapNuc-(ksecrete+µ)*EmptyCapNuc
    dFullCapNucdt = kRep_bind_capsid*RepProtein*EmptyCapNuc-(ksecrete+µ)*FullCapNuc
    dEmptyCapCytodt = ksecrete*EmptyCapNuc-µ*EmptyCapCyto
    dFullCapCytodt = ksecrete*FullCapNuc-µ*FullCapCyto
    dRepRCcomplexdt = kRep_bind_plasmid*RepProtein*NuclearPlasmid_P
    dCapRepComplexdt = kRep_bind_capsid*RepProtein*EmptyCapNuc-kDNA_pack*CapRepComplex*vDNA
    
    diffeq = [dExComplex_Hdt,dEndosComplex_Hdt,dCytoComplex_Hdt,dNuclearPlasmid_Hdt,
             dExComplex_Pdt,dEndosComplex_Pdt,dCytoComplex_Pdt,dNuclearPlasmid_Pdt,
             dExComplex_Vdt,dEndosComplex_Vdt,dCytoComplex_Vdt,dNuclearPlasmid_Vdt,
             dRepProteindt,dVPdt,dvDNAdt,dEmptyCapNucdt,dFullCapNucdt,
             dEmptyCapCytodt,dFullCapCytodt,dRepRCcomplexdt,dCapRepComplexdt]
    
    return diffeq

def simulate_rAAV(ps):
    tend = 48
    p1 = ps[0]
    p2 = ps[1]
    p3 = ps[2]
    r = ode(fun_rAAV).set_integrator('lsoda',nsteps = 10000)
    r.set_initial_value([p1,0,0,0,p2,0,0,0,p3,0,0,0,0,0,0,0,0,0,0,0,0]).set_f_params([1.19*10**-3,6.00*10**-1,4.30*10**-3,1.95*10**-2,6.50*10**4,6.50*10**4,2.77*10**-1,2.45*10**-2,3.10*10**-7,1.00*10**5,1.00*10**5,8.18*10**-2,3.38*10**-5,5.70*10**-3])
    dt = 0.001
    
    t = []
    y = []
    while r.t+dt < tend:
        t.append(r.t+dt)
        y.append(r.integrate(r.t+dt))

    y = np.array(y)
    allfullcap = y[-1,16]+y[-1,18]
    allemptycap = y[-1,15]+y[-1,17]
    ratiocap = 100*allfullcap/(allfullcap+allemptycap)
        
    return ratiocap

def generateSobolSamples(N,Q,bounds): #function to generate SOBOL samples
    train_x = draw_sobol_samples(torch.from_numpy(bounds).type(torch.FloatTensor),n=N, q=Q, seed=42).squeeze(1)
    return train_x

def standardizeY(Y):
    meanpar = np.mean(Y.numpy())
    varpar = np.std(Y.numpy())
    return [torch.from_numpy((Y.numpy()-meanpar)/varpar),meanpar,varpar]

nRep = 25
sobolSize = 3
boundsrAAV = np.array([[1,1,1],[2.7*10**5,2.7*10**5,2.7*10**5]]) #amount of plasmid
XsrAAV = generateSobolSamples(sobolSize,25,boundsrAAV)


noiseLevel = 1 #percent

for j in range(nRep):
    print(j)
    XrAAV = XsrAAV[:,j,:]
    YrAAV = np.zeros((XrAAV.shape[0],1))
    YrAAV_noisy = np.zeros((XrAAV.shape[0],1))

    resrAAVList = []
    for i in range(XrAAV.shape[0]):
        resrAAV = simulate_rAAV(XrAAV[i,:].numpy())
        YrAAV[i,0] = resrAAV
        YrAAV_noisy[i,0] = np.random.normal(resrAAV,(noiseLevel/100)*resrAAV)
        resrAAVList.append(resrAAV)
    YrAAV = torch.from_numpy(YrAAV)
    YrAAV_noisy = torch.from_numpy(YrAAV_noisy)

    X_normrAAV = normalize(XrAAV,boundsrAAV)
    Y_standrAAV,meanparrAAV,varparrAAV = standardizeY(YrAAV_noisy)

    #fit model
    modelrAAV = HeteroskedasticSingleTaskGP(X_normrAAV, Y_standrAAV, (torch.tensor((np.array(resrAAVList)*(noiseLevel/100))**1)[:,None]/varparrAAV)**2) #fit model
    mllrAAV = ExactMarginalLogLikelihood(modelrAAV.likelihood, modelrAAV)
    fit_gpytorch_model(mllrAAV)
    qNEIrAAV = qNoisyExpectedImprovement(model=modelrAAV, X_baseline=X_normrAAV, sampler=SobolQMCNormalSampler(1024))   

    candidaterAAV, _ = optimize_acqf(
        acq_function=qNEIrAAV,
        bounds=torch.tensor([[0.0] * 3, [1.0] * 3]),
        q=1,
        num_restarts=2,
        raw_samples=32,  # used for intialization heuristic
    #     options={"batch_limit": 5, "maxiter": 200},
    )
```

## System Info
Please provide information about your setup, including
- BoTorch Version 0.6.2
- GPyTorch Version 1.6.0
- PyTorch Version 1.11.0
- Computer OS windows

**Comment by Balandat** [comment]
If I read this correctly this code uses float precision:

```
torch.from_numpy(bounds).type(torch.FloatTensor)
```

This is likely a numerical issue similar to https://github.com/pytorch/botorch/issues/1437. Quoting from there:

> Likely your training data is such that the involved covariance are quite ill-conditioned so that you're running into numerical accuracy issues with float that produce NaNs. This is pretty common when using GPs and unless you have a good reason (e.g. you want to save GPU memory or you really need the faster float processing on some models) I would recommend always using double.

**Comment by Balandat** [comment]
Given that it occurs only occasionally I'm pretty sure this is the reason. I'll close this for now, but feel free to reopen if this doesn't fix the issue.

**Comment by EvanClaes** [comment]
Hello Max,

Thanks for the swift response. I cannot reopen the issue I think.

I checked the tensor types in my code, and all the tensors the model is seeing (X_normrAAV, X_normrAAV and the noise variance tensor) are all double type... I added the code that prints these types.

`import os
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from botorch.utils.sampling import draw_sobol_samples
from scipy.integrate import ode
from botorch.models.gp_regression import SingleTaskGP, FixedNoiseGP, HeteroskedasticSingleTaskGP
from gpytorch.mlls.sum_marginal_log_likelihood import ExactMarginalLogLikelihood
from botorch.fit import fit_gpytorch_model
from botorch.utils.transforms import unnormalize, normalize
from mpl_toolkits.mplot3d import axes3d
from botorch.acquisition.analytic import ExpectedImprovement, NoisyExpectedImprovement
from botorch.acquisition.monte_carlo import qExpectedImprovement, qNoisyExpectedImprovement
from botorch.optim import optimize_acqf
from scipy.optimize import minimize
from botorch.sampling.samplers import SobolQMCNormalSampler




def calc_growth_rate(t):
    g = np.array([49427.9581111241, 0.0112812472592155])
    c = 1e6 + g[0]/g[1]*(1 - np.exp(-g[1]*t))
    mu  = g[0]*np.exp(-g[1]*t)/c
    return mu,c

def fun_rAAV(t,y,pars):
    #PARAMETERS
    kuptake = pars[0] #DNA uptake from medium into cell cytosol (1/h)
    # kuptake = 1.19*10**-3 #DNA uptake from medium into cell cytosol (1/h)
    kescape = pars[1] #endosomal escape (1/h)
    knuclear_entry = pars[2] #nuclear entry (1/h)
    kplasmid_degrade = pars[3] #plasmid degradation (1/h)
    kCap_syn = pars[4] #capsid protein synthesis (molecule/cell/h)
    kRep_syn = pars[5] #Rep protein synthesis (molecule/cell/h)
    kVP_degrade = pars[6] #VP degradation (1/h)
    kRep_protein_degrade = pars[7] #Rep protein degradation (1/h)
    kDNA_rep = pars[8] #transgene rescue and replication (cell²/molecule²/h)
    kassembly = pars[9] #capsid assembly (1/h)
    ksecrete = pars[10] #capsid secretion from the nucleus to the cytosol (1/h)
    kDNA_pack = pars[11] #viral DNA encapsidation (molecule/cell/h)
    kRep_bind_plasmid = pars[12] #binding of Rep protein on packaging plasmid (molecule/cell/h)
    kRep_bind_capsid = pars[13] #binding of Rep protein on empty capsid (molecule/cell/h)
    
#     µ = pars[14] #cell growth rate
    # µ = 1/18 #cell growth rate
    # µ = 1/30 #cell growth rate
    µ,c = calc_growth_rate(t)
    
    
    #STATES & INTERMEDIATE PARAMETERS
    #gene delivery
    ExComplex_H = y[0] #extracellular helper plasmid complexes
    EndosComplex_H = y[1] #endosomal helper plasmid complexes
    CytoComplex_H = y[2] #cytosomal helper plasmid complexes
    NuclearPlasmid_H = y[3] #naked helper plasmid in nucleus
    ExComplex_P = y[4] #extracellular packaging plasmid complexes
    EndosComplex_P = y[5] #endosomal packaging plasmid complexes
    CytoComplex_P = y[6] #cytosomal packaging plasmid complexes
    NuclearPlasmid_P = y[7] #naked packaging plasmid in nucleus
    ExComplex_V = y[8] #extracellular vector plasmid complexes
    EndosComplex_V = y[9] #endosomal vector plasmid complexes
    CytoComplex_V = y[10] #cytosomal vector plasmid complexes
    NuclearPlasmid_V = y[11] #naked vector plasmid in nucleus

    #viral vector synthesis
    RepProtein = y[12] #rep protein
    VP = y[13] #viral protein
    vDNA = y[14] #viral DNA
    EmptyCapNuc = y[15] #empty capsids in nucleus
    FullCapNuc = y[16] #full capsids in nucleus
    EmptyCapCyto = y[17] #empty capsids in cytoplasm
    FullCapCyto = y[18] #full capsids in cytoplasm
    RepRCcomplex = y[19] #plasmids bound with rep protein
    CapRepComplex = y[20] #empty capsids bound with rep protein
    
    
    #DIFF EQ
    #gene delivery
    dExComplex_Hdt = -kuptake*ExComplex_H
    dEndosComplex_Hdt = kuptake*ExComplex_H-(kescape+kplasmid_degrade+µ)*EndosComplex_H
    dCytoComplex_Hdt = kescape*EndosComplex_H-(knuclear_entry+kplasmid_degrade+µ)*CytoComplex_H
    dNuclearPlasmid_Hdt = knuclear_entry*CytoComplex_H-(kplasmid_degrade+µ)*NuclearPlasmid_H
    dExComplex_Pdt = -kuptake*ExComplex_P
    dEndosComplex_Pdt = kuptake*ExComplex_P-(kescape+kplasmid_degrade+µ)*EndosComplex_P
    dCytoComplex_Pdt = kescape*EndosComplex_P-(knuclear_entry+kplasmid_degrade+µ)*CytoComplex_P
#     dNuclearPlasmid_Pdt = knuclear_entry*CytoComplex_P-(kplasmid_degrade+µ)*NuclearPlasmid_P
    dNuclearPlasmid_Pdt = knuclear_entry*CytoComplex_P-(kplasmid_degrade+µ)*NuclearPlasmid_P-kRep_bind_plasmid*NuclearPlasmid_P*RepProtein
    dExComplex_Vdt = -kuptake*ExComplex_V
    dEndosComplex_Vdt = kuptake*ExComplex_V-(kescape+kplasmid_degrade+µ)*EndosComplex_V
    dCytoComplex_Vdt = kescape*EndosComplex_V-(knuclear_entry+kplasmid_degrade+µ)*CytoComplex_V
    dNuclearPlasmid_Vdt = knuclear_entry*CytoComplex_V-(kplasmid_degrade+µ)*NuclearPlasmid_V
    
    #viral vector synthesis
    dRepProteindt = kRep_syn*NuclearPlasmid_P*NuclearPlasmid_H-kRep_bind_plasmid*RepProtein*NuclearPlasmid_P-kRep_bind_capsid*RepProtein*EmptyCapNuc+kDNA_pack*CapRepComplex*vDNA-(kRep_protein_degrade+µ)*RepProtein
    dVPdt = kCap_syn*NuclearPlasmid_P*NuclearPlasmid_H-(kVP_degrade+µ)*VP-60*kassembly*VP
    dvDNAdt = kDNA_rep*RepProtein*NuclearPlasmid_H*NuclearPlasmid_V-kDNA_pack*CapRepComplex*vDNA-µ*vDNA
    dEmptyCapNucdt = kassembly*VP-kRep_bind_capsid*RepProtein*EmptyCapNuc-(ksecrete+µ)*EmptyCapNuc
    dFullCapNucdt = kRep_bind_capsid*RepProtein*EmptyCapNuc-(ksecrete+µ)*FullCapNuc
    dEmptyCapCytodt = ksecrete*EmptyCapNuc-µ*EmptyCapCyto
    dFullCapCytodt = ksecrete*FullCapNuc-µ*FullCapCyto
    dRepRCcomplexdt = kRep_bind_plasmid*RepProtein*NuclearPlasmid_P
    dCapRepComplexdt = kRep_bind_capsid*RepProtein*EmptyCapNuc-kDNA_pack*CapRepComplex*vDNA
    
    diffeq = [dExComplex_Hdt,dEndosComplex_Hdt,dCytoComplex_Hdt,dNuclearPlasmid_Hdt,
             dExComplex_Pdt,dEndosComplex_Pdt,dCytoComplex_Pdt,dNuclearPlasmid_Pdt,
             dExComplex_Vdt,dEndosComplex_Vdt,dCytoComplex_Vdt,dNuclearPlasmid_Vdt,
             dRepProteindt,dVPdt,dvDNAdt,dEmptyCapNucdt,dFullCapNucdt,
             dEmptyCapCytodt,dFullCapCytodt,dRepRCcomplexdt,dCapRepComplexdt]
    
    return diffeq

def simulate_rAAV(ps):
    tend = 48
    p1 = ps[0]
    p2 = ps[1]
    p3 = ps[2]
    r = ode(fun_rAAV).set_integrator('lsoda',nsteps = 10000)
    r.set_initial_value([p1,0,0,0,p2,0,0,0,p3,0,0,0,0,0,0,0,0,0,0,0,0]).set_f_params([1.19*10**-3,6.00*10**-1,4.30*10**-3,1.95*10**-2,6.50*10**4,6.50*10**4,2.77*10**-1,2.45*10**-2,3.10*10**-7,1.00*10**5,1.00*10**5,8.18*10**-2,3.38*10**-5,5.70*10**-3])
    dt = 0.001
    
    t = []
    y = []
    while r.t+dt < tend:
        t.append(r.t+dt)
        y.append(r.integrate(r.t+dt))

    y = np.array(y)
    allfullcap = y[-1,16]+y[-1,18]
    allemptycap = y[-1,15]+y[-1,17]
    ratiocap = 100*allfullcap/(allfullcap+allemptycap)
        
    return ratiocap

def generateSobolSamples(N,Q,bounds): #function to generate SOBOL samples
    train_x = draw_sobol_samples(torch.from_numpy(bounds).type(torch.FloatTensor),n=N, q=Q, seed=42).squeeze(1)
    return train_x

def standardizeY(Y):
    meanpar = np.mean(Y.numpy())
    varpar = np.std(Y.numpy())
    return [torch.from_numpy((Y.numpy()-meanpar)/varpar),meanpar,varpar]

nRep = 25
sobolSize = 3
boundsrAAV = np.array([[1,1,1],[2.7*10**5,2.7*10**5,2.7*10**5]]) #amount of plasmid
XsrAAV = generateSobolSamples(sobolSize,25,boundsrAAV)


noiseLevel = 1 #percent

for j in range(nRep):
    print(j)
    XrAAV = XsrAAV[:,j,:]
    YrAAV = np.zeros((XrAAV.shape[0],1))
    YrAAV_noisy = np.zeros((XrAAV.shape[0],1))

    resrAAVList = []
    for i in range(XrAAV.shape[0]):
        resrAAV = simulate_rAAV(XrAAV[i,:].numpy())
        YrAAV[i,0] = resrAAV
        YrAAV_noisy[i,0] = np.random.normal(resrAAV,(noiseLevel/100)*resrAAV)
        resrAAVList.append(resrAAV)
    YrAAV = torch.from_numpy(YrAAV)
    YrAAV_noisy = torch.from_numpy(YrAAV_noisy)

    X_normrAAV = normalize(XrAAV,boundsrAAV)
    Y_standrAAV,meanparrAAV,varparrAAV = standardizeY(YrAAV_noisy)

    #print tensor types
    print(X_normrAAV.type())
    print(X_normrAAV.type())
    print(((torch.tensor((np.array(resrAAVList)*(noiseLevel/100))**1)[:,None]/varparrAAV)**2).type())
    
    #fit model
    modelrAAV = HeteroskedasticSingleTaskGP(X_normrAAV, Y_standrAAV, (torch.tensor((np.array(resrAAVList)*(noiseLevel/100))**1)[:,None]/varparrAAV)**2) #fit model
    mllrAAV = ExactMarginalLogLikelihood(modelrAAV.likelihood, modelrAAV)
    fit_gpytorch_model(mllrAAV)
    qNEIrAAV = qNoisyExpectedImprovement(model=modelrAAV, X_baseline=X_normrAAV, sampler=SobolQMCNormalSampler(1024))   

    candidaterAAV, _ = optimize_acqf(
        acq_function=qNEIrAAV,
        bounds=torch.tensor([[0.0] * 3, [1.0] * 3]),
        q=1,
        num_restarts=2,
        raw_samples=32,  # used for intialization heuristic
    #     options={"batch_limit": 5, "maxiter": 200},
    )

`

**Comment by Balandat** [comment]
What are the ranges of the noise variance that are passed into the model. Note that under the hood `HeteroskedasticSingleTaskGP` log-transforms this, so if values are zero or close to it this could result in NaNs.

Taking a step back, what is the reason you are using a `HeteroskedasticSingleTaskGP` here? Are you interested in modeling the noise level out-of-sample? Note that even a `FixedNoiseGP` will deal with heteroskeastic noise (I know the name is a bit confusing - fixed here is about the noise level being provided rather than inferred by the model). It's just that it can't predict noise levels out-of-sample, but you don't need that if you are using `qNEI` (this is only needed for lookahead acquisition functions such as KG). If that is enough, switching over to a `FixedNoiseGP` will likely help with the numerical issues.

**Comment by EvanClaes** [comment]
Hello Max,

In the case above the noise (standard deviation of the gaussian) was 1% of the observed 'true value'. I just ran the script a couple of times again with 10% noise and encountered no issues.

I'm was using the HeteroskedasticSingleTaskGP because technically, if my noise is a fixed percentage of the expected mean then it is heteroskedastic, no? 

I'm a little bit confused on why we don't need out-of-sample noise predictions for qNEI, but that's probably because I lack the theoretical understanding (need to work on that). Doesn't qNEI use noise estimations at the locations of the potential queries to calculate the EI?

Anyways you can consider this issue as closed. Thanks for your help!

**Comment by Balandat** [comment]
> Doesn't qNEI use noise estimations at the locations of the potential queries to calculate the EI?

So it does use posterior variance inferred by the model, but this is the variance of the latent function `f`, rather than of the observations `y = f + obs_noise`. 

> I'm was using the HeteroskedasticSingleTaskGP because technically, if my noise is a fixed percentage of the expected mean then it is heteroskedastic, no?

Yup it is. But `FixedNoiseGP` is sufficient to account for heteroskedastic `obs_noise` so long as you don't need to predict that out-of-sample.
