### ISSUE TITLE
[Question] Seed value setting and Reproducibility in optimize_acqf_discrete_local_search

### ISSUE THREAD

**Issue by Display-NK** [pytorch/botorch#1485]
Hello.
When I used `optimize_acqf_discrete_local_search` to search sample, I noticed that the results were different each time and this function does not have parameters to set seed value in the argument.
Could you tell me if there is a reason why seed is not in the argument?
Or, if I am missing something, could you tell me how to set seed value?

**Comment by saitcakmak** [comment]
Hi @Display-NK. You're correct that by default the optimizers will not set a seed. If you'd like to set a seed, you can either call `torch.manual_seed(<seed>)` before calling the optimizer, or pass in the seed as `options = {"seed": <seed>}`.

**Comment by Display-NK** [comment]
@saitcakmak
Thanks to your advice I have solved the problem.

But, why do I sometimes get duplicate output despite the parameter `unique=True`?

**Comment by saitcakmak** [comment]
If I understand correctly, you're passing `q > 1` and `unique=True`, but the output you get has the same candidate repeated. This is odd, as the candidates should be getting filtered out while generating the next ones. Would you be able to share a reproducible example for us to investigate? cc @dme65
