### ISSUE TITLE
[Bug] TestNoisyExpectedImprovement.test_noisy_expected_improvement is flaky in single precision

### ISSUE THREAD

**Issue by esantorella** [pytorch/botorch#1592]
# 🐛 Bug

TestNoisyExpectedImprovement.test_noisy_expected_improvement fails in single precision for certain numerical inputs

## To reproduce

Ref: https://github.com/pytorch/botorch/blob/cbd5002fdca43411211f98392043bc3c46872153/test/acquisition/test_analytic.py#L551
The test can be made to fail by setting `torch.manual_seed(541)`.

** Stack trace/error message **
GitHub Actions: https://github.com/pytorch/botorch/actions/runs/3773311159/jobs/6414696343

Actions shows
```
>           self.assertTrue(
                torch.allclose(X_test.grad[0], X_test_log.grad[0], atol=atol)
            )
E           AssertionError: False is not true
```

## System information

GitHub Actions. Also repro'd on my Mac:

-  BoTorch Version: '0.8.1.dev24+g5066540c.d20221221'
- GPyTorch Version:  '1.9.0'
- PyTorch Version : '1.13.1'
-  OS X

cc @SebastianAment

**Comment by SebastianAment** [comment]
@esantorella Thank you for reporting this! I haven't been able to reproduce this yet on my Mac, nor the internal machines. I put the `manual_seed` here:
```python 
   def test_noisy_expected_improvement(self):
        for dtype in (torch.float, torch.double):
            torch.manual_seed(541)
            model = self._get_model(dtype=dtype)
```
Is this where you put it too?

**Comment by esantorella** [comment]
@SebastianAment Yeah, that makes it fail for me, including on the current main branch. Maybe it's machine-dependent... A couple other things to try to get it to fail:

* set `torch.manual_seed(i)` where it's currently set to 541 and loop over a lot of values of `i` (this identified a seed that makes it fail in a couple minutes for me)
* Pass a seed of 374918 to `SobolQMCNormalSampler` here: https://github.com/pytorch/botorch/blob/b88560983719817da39d9461f2ae4dbcacfedd70/botorch/acquisition/analytic.py#L644

**Comment by SebastianAment** [comment]
I was able to repro this in double precision, where an error of `1.1e-14` occurred while the tolerance was `1e-14`. #1600 should fix this. Thanks again for reporting!
