### ISSUE TITLE
[question] question abount "constraint" parameter in qnehvi

### ISSUE THREAD

**Issue by open2333** [pytorch/botorch#1593]
## Issue description
Dear contributors, I am using qnehvi acquisition function, and I don't know how to define the parameter "constraints" of qNoisyExpectedHypervolumeImprovement
in the example "constraints=[lambda Z: (Z[..., -1])]" means constraint is on the last outcome, what should I use if my problem has n constraints, I tried the last n outcome, but the shape of tensor is not right. Could you please give me another example if the problem has 3 constraints, how to define this parameter? Thanks a lot.

## Code example
    acq_func = qNoisyExpectedHypervolumeImprovement(
        model=model,
        ref_point=ref_point,  # use known reference point
        X_baseline=train_x,
        sampler=sampler,
        prune_baseline=True,
        # define an objective that specifies which outcomes are the objectives
        objective=IdentityMCMultiOutputObjective(outcomes=[i for i in range(len(ref_point))]),
        # specify that the constraint is on the last outcome
        constraints=[lambda Z: (Z[..., -1])],
    )

**Comment by Balandat** [comment]
See my response here: https://github.com/pytorch/botorch/issues/1326#issuecomment-1365445417

**Comment by open2333** [comment]
many thanks!
