### ISSUE TITLE
ModelListGP-dimension issues

### ISSUE THREAD

**Issue by Echojie** [pytorch/botorch#1603]
If you are submitting a bug report or feature request, please use the respective
issue template.

## Issue description

Hi all,
For multiple output GP settings, I would like to consider independent outputs with different training data. Which means, different outputs may use different training data set x. 
I tried to use ModellistGP; however, I have a running time error, as shown below. Is it because the training x for separate GP should be in the same dimension? If, for different outputs, the number of features for training is different, what type of model should I use?

## Code example

obj1_model = SingleTaskGP(x_train_p1, y_train_p1)
obj1_mll = ExactMarginalLogLikelihood(obj1_model.likelihood, obj1_model)
fit_gpytorch_model(obj1_mll)
obj2_model = SingleTaskGP(x_train_p2, y_train_p2)
obj2_mll = ExactMarginalLogLikelihood(obj2_model.likelihood, obj2_model)
fit_gpytorch_model(obj2_mll)
model = ModelListGP(obj1_model, obj2_model)
acquisition = qExpectedImprovement(model, best_f = best_f, objective= objective)
candidate, acq_value= optimize_acqf(acquisition, bounds=bounds, q=1, num_restarts=5, raw_samples=256 )

The errors are:
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 2 for tensor number 1 in the list.

Please try to provide a minimal example to repro the issue.
Error messages and stack traces are also helpful.

## System Info
Please provide information about your setup, including
- BoTorch Version 0.8.0
- GPyTorch Version 1.11
- PyTorch Version 1.9.0
- ComputerOS: Windows

**Comment by saitcakmak** [comment]
Hi @Echojie What are the shapes of your training tensors? Also, what part of code do you get the error? A full stack trace would be helpful.

**Comment by Balandat** [comment]
>  If, for different outputs, the number of features for training is different, what type of model should I use?

It sounds like in this case you'd just use two different models altogether rather than combining them? 

At a higher level, what are you trying to do when you're optimizing the acquisition function? If the models have different training features you will most likely also have different features for prediction - so what does optimizing the acquisition function mean here? Is your goal to do sth like consider both domains and optimize over two different input spaces jointly?

**Comment by Echojie** [comment]
> 

Hi Max,
Thank you so much for your reply. I may not explain my issues clearly. Yes, my goal is to optimize over two different input spaces jointly.

For the multiple-outputs model, for example, d=4, m=12, sometimes not all 12 outputs depend on the 4 input features. Some output may be determined by a subset of the input features. So instead of formulating a SingleTaskGP, I would like to build a Gaussian process (GP) surrogate model for a specific m over the reduced search space. 

My worked example is, a composite function, g(h(x)), h(x): R^2 -> R^2 is defined as:
def h(x):
    h_x = np.zeros((2, 1))

    h_x[0] = 10 * (x[1] - x[0]**2)
    h_x[1] = 1 - x[0]

g() is a sum of the squared function. 
In this worked example,    h_x[0] depends on x1 and x0, while  h_x[1] only depends on x0. I am considering of model them separately.

**Comment by Echojie** [comment]
> Hi @Echojie What are the shapes of your training tensors? Also, what part of code do you get the error? A full stack trace would be helpful.

Hi @saitcakmak , Thank you for your reply! 
x_train = # shape: (n_train, d), in the example d=2
x_train_p1 = ...  # shape: (n_train, d1), here d1 \subset d, in the example d1=2
x_train_p2 = ...  # shape: (n_train, d2), here d2 \subset d, in the example d2=1
y_train_p1 = ...  # shape: (n_train, 1)
y_train_p2 = ...  # shape: (n_train, 1)
y_train = # shape: (n_train, m), in the example m=2.
My problem is g(h(x)), a composite function where h(x): R^2->R^2, g: R^2->R. The goal is to maximize g, while I would like to take advantage that one h function only depends on a subset of input features. 


Below is my full stack trace:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [84], in <cell line: 7>()
     16 model = ModelListGP(obj1_model, obj2_model)
     17 acquisition = qExpectedImprovement(model, best_f = best_f, objective= objective)
---> 18 x_trial, acq_value= optimize_acqf(acquisition, bounds=bounds, q=1, num_restarts=5, raw_samples=256 )
     19 print('x trial', x_trial)
     20 x_train_p1 = torch.cat([x_train_p1, x_trial])

File D:\Python\lib\site-packages\botorch\optim\optimize.py:238, in optimize_acqf(acq_function, bounds, q, num_restarts, raw_samples, options, inequality_constraints, equality_constraints, nonlinear_inequality_constraints, fixed_features, post_processing_func, batch_initial_conditions, return_best_only, sequential, **kwargs)
    234     return X, acq_value
    236 if not initial_conditions_provided:
--> 238     batch_initial_conditions = ic_gen(
    239         acq_function=acq_function,
    240         bounds=bounds,
    241         q=q,
    242         num_restarts=num_restarts,
    243         raw_samples=raw_samples,
    244         fixed_features=fixed_features,
    245         options=options,
    246         inequality_constraints=inequality_constraints,
    247         equality_constraints=equality_constraints,
    248         **kwargs,
    249     )
    251 batch_limit: int = options.get(
    252     "batch_limit", num_restarts if not nonlinear_inequality_constraints else 1
    253 )
    255 def _optimize_batch_candidates() -> Tuple[Tensor, Tensor, List[Warning]]:

File D:\Python\lib\site-packages\botorch\optim\initializers.py:193, in gen_batch_initial_conditions(acq_function, bounds, q, num_restarts, raw_samples, fixed_features, options, inequality_constraints, equality_constraints)
    191 while start_idx < X_rnd.shape[0]:
    192     end_idx = min(start_idx + batch_limit, X_rnd.shape[0])
--> 193     Y_rnd_curr = acq_function(
    194         X_rnd[start_idx:end_idx].to(device=device)
    195     ).cpu()
    196     Y_rnd_list.append(Y_rnd_curr)
    197     start_idx += batch_limit

File D:\Python\lib\site-packages\torch\nn\modules\module.py:1110, in Module._call_impl(self, *input, **kwargs)
   1106 # If we don't have any hooks, we want to skip the rest of the logic in
   1107 # this function, and just call forward.
   1108 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110     return forward_call(*input, **kwargs)
   1111 # Do not call functions when jit is used
   1112 full_backward_hooks, non_full_backward_hooks = [], []

File D:\Python\lib\site-packages\botorch\utils\transforms.py:319, in concatenate_pending_points.<locals>.decorated(cls, X, **kwargs)
    317 if cls.X_pending is not None:
    318     X = torch.cat([X, match_batch_shape(cls.X_pending, X)], dim=-2)
--> 319 return method(cls, X, **kwargs)

File D:\Python\lib\site-packages\botorch\utils\transforms.py:276, in t_batch_mode_transform.<locals>.decorator.<locals>.decorated(acqf, X, *args, **kwargs)
    274 # add t-batch dim
    275 X = X if X.dim() > 2 else X.unsqueeze(0)
--> 276 output = method(acqf, X, *args, **kwargs)
    277 if hasattr(acqf, "model") and is_fully_bayesian(acqf.model):
    278     output = output.mean(dim=-1)

File D:\Python\lib\site-packages\botorch\acquisition\monte_carlo.py:178, in qExpectedImprovement.forward(self, X)
    164 @concatenate_pending_points
    165 @t_batch_mode_transform()
    166 def forward(self, X: Tensor) -> Tensor:
    167     r"""Evaluate qExpectedImprovement on the candidate set `X`.
    168 
    169     Args:
   (...)
    176         model and input `X`.
    177     """
--> 178     posterior = self.model.posterior(
    179         X=X, posterior_transform=self.posterior_transform
    180     )
    181     samples = self.get_posterior_samples(posterior)
    182     obj = self.objective(samples, X=X)

File D:\Python\lib\site-packages\botorch\models\gpytorch.py:604, in ModelListGPyTorchModel.posterior(self, X, output_indices, observation_noise, posterior_transform, **kwargs)
    602     mvn_gen = zip(output_indices, mvns)
    603 else:
--> 604     mvns = self(*transformed_X)
    605     if observation_noise is not False:
    606         mvnX = [(mvn, transformed_X[i]) for i, mvn in enumerate(mvns)]

File D:\Python\lib\site-packages\gpytorch\models\model_list.py:82, in IndependentModelList.__call__(self, *args, **kwargs)
     81 def __call__(self, *args, **kwargs):
---> 82     return [model.__call__(*args_, **kwargs) for model, args_ in zip(self.models, _get_tensor_args(*args))]

File D:\Python\lib\site-packages\gpytorch\models\model_list.py:82, in <listcomp>(.0)
     81 def __call__(self, *args, **kwargs):
---> 82     return [model.__call__(*args_, **kwargs) for model, args_ in zip(self.models, _get_tensor_args(*args))]

File D:\Python\lib\site-packages\gpytorch\models\exact_gp.py:303, in ExactGP.__call__(self, *args, **kwargs)
    301         train_input = train_input.expand(*batch_shape, *train_input.shape[-2:])
    302         input = input.expand(*batch_shape, *input.shape[-2:])
--> 303     full_inputs.append(torch.cat([train_input, input], dim=-2))
    305 # Get the joint distribution for training/test data
    306 full_output = super(ExactGP, self).__call__(*full_inputs, **kwargs)

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 2 for tensor number 1 in the list.

**Comment by Balandat** [comment]
@Echojie I understand the modeling aspect and why you'd want to do this, but how are you planning to utilize these models? What optimization problem are you trying to solve?

**Comment by saitcakmak** [comment]
We have a `FilterFeatures` input transform that'd allow you to filter out the features you do not want from each individual model. You can train each model on only the subset of the features that are relevant to them, and include a `FilterFeatures` input transform while constructing the model. With this setup, the `ModelListGP` would be evaluated on the full features, but under the hood each individual model would be evaluated on the features specified by the transform.

https://github.com/pytorch/botorch/blob/main/botorch/models/transforms/input.py#L1163

**Comment by Echojie** [comment]
> @Echojie I understand the modeling aspect and why you'd want to do this, but how are you planning to utilize these models? What optimization problem are you trying to solve? 

I am trying to optimize the acquisition function. Once I formulate separate models (each model with specific mean and std dev) by using different features, the next step is to deduce a GP surrogate model (say M) over the full search space. The acquisition function I am tying to optimize is defined by the M. The output of the optimized acquisition function is the learned full features.

**Comment by Balandat** [comment]
> I am trying to optimize the acquisition function. Once I formulate separate models (each model with specific mean and std dev) by using different features, the next step is to deduce a GP surrogate model (say M) over the full search space. The acquisition function I am tying to optimize is defined by the M. The output of the optimized acquisition function is the learned full features.

A few more questions:
- What acquisition function are you trying to optimize - are you performing multi-objective optimization or are you optimizing a composite objective defined over the outputs of your two models? 
- Do the separate models share any of the features, or are the feature sets completely disjoint?

Depending on the above things may look slightly different, but @saitcakmak explained above how you can use existing components for this. The alternative would be to write your own model container that takes in the full features `X`, splits them up and passes a subset to different models. But it looks like this wouldn't really have any benefits over the `FilterFeatures` solution, so I would recommend to start with that. Let us know how it goes!

**Comment by Echojie** [comment]
> 

Hi @Balandat , thank you for your reply.

For the questions:
1. I am trying to optimize a composite objective defined over the outputs of the two models.
2. The separate models share the features. They are not completely disjoint.**

I tried the FilterFeatures solution.  The code shows below. This component works!



def h(x):
    x= x.reshape(-1,1)
    h_x = np.zeros((2, 1))

    h_x[0] = 10 * (x[1] - x[0]**2)
    h_x[1] = 1 - x[0]

    return torch.from_numpy(h_x).reshape(1,-1)

def c_batched(X, k=None):
    return torch.stack([h(x) for x in X])
def g_function(x):
    z_norm = x.norm(dim=-1, p=2)
    z = z_norm.pow(2)
    return z.mul(-1.0)

objective = GenericMCObjective(g_function)

N=2
x_train = torch.rand(2, 2)
bounds = torch.tensor([[0.0]*2, [1.0]*2])
feature_kept_2 = torch.tensor([0])

for i in range(N):
    print("this is iteration", i)

    y_train = c_batched(x_train)
    best_f = objective(y_train).max()
    gp_1 = SingleTaskGP(x_train, y_train.squeeze(1)[:,0].reshape(-1,1)) # the first model uses features x0 and x1
    gp_2 = SingleTaskGP(x_train, y_train.squeeze(1)[:,1].reshape(-1,1), input_transform=FilterFeatures(feature_indices=feature_kept_2))  #the second model uses one feature: x0
    model = ModelListGP(gp_1, gp_2)
    smll = SumMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_mll(smll)
    qei = qExpectedImprovement(model, best_f = best_f, objective=objective)
    x_trail, acq_value = optimize_acqf(qei, bounds=bounds, q=1, num_restarts=10, raw_samples=100)
    x_train = torch.cat([x_train, x_trail])
