### ISSUE TITLE
ModelList in combination with qNoisyExpectedImprovement fails

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#1604]
## Issue description

When I tried to use a ModelList in combination with `qNoisyExpectedImprovement`, I got an error regarding the missing attribute `distribution` of the object `PosteriorList`. Is this error intended? Because that means that it is currently not possible to use `qNoisyExpectedImprovement`  on problems where for example the output constraint is defined by a deterministic model and the actual objective by a `SingleTaskGP`.

## Code example

This is the MWE:

```python
import torch
from botorch.models import SingleTaskGP, ModelList, ModelListGP
from botorch.fit import fit_gpytorch_mll
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood
from botorch.acquisition import qNoisyExpectedImprovement


train_X = torch.rand(10, 2)
Y = 1 - torch.norm(train_X - 0.5, dim=-1, keepdim=True)
Y = Y + 0.1 * torch.randn_like(Y)  # add some noise
train_Y = standardize(Y)

gp = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
fit_gpytorch_mll(mll)

ml = ModelList(gp)


qNoisyExpectedImprovement(model=ml, X_baseline=train_X)
```

And this is the error trace:

```
Cell In [22], line 21
     16 fit_gpytorch_mll(mll)
     18 ml = ModelList(gp)
---> 21 qNoisyExpectedImprovement(model=ml, X_baseline=train_X)

File ~/sandbox/botorch/botorch/acquisition/monte_carlo.py:294, in qNoisyExpectedImprovement.__init__(self, model, X_baseline, sampler, objective, posterior_transform, X_pending, prune_baseline, cache_root, **kwargs)
    290 self.register_buffer("baseline_samples", baseline_samples)
    291 self.register_buffer(
    292     "baseline_obj_max_values", baseline_obj.max(dim=-1).values
    293 )
--> 294 self._baseline_L = self._compute_root_decomposition(posterior=posterior)

File ~/sandbox/botorch/botorch/acquisition/cached_cholesky.py:92, in CachedCholeskyMCAcquisitionFunction._compute_root_decomposition(self, posterior)
     71 def _compute_root_decomposition(
     72     self,
     73     posterior: Posterior,
     74 ) -> Tensor:
     75     r"""Cache Cholesky of the posterior covariance over f(X_baseline).
     76 
     77     Because `LinearOperator.root_decomposition` is decorated with LinearOperator's
   (...)
     90         posterior: The posterior over f(X_baseline).
     91     """
...
    181         f"`PosteriorList` does not define the attribute {name}. "
    182         "Consider accessing the attributes of the individual posteriors instead."
    183     )

AttributeError: `PosteriorList` does not define the attribute distribution. Consider accessing the attributes of the individual posteriors instead.
```

**Comment by saitcakmak** [comment]
Hi @jduerholt, thanks for flagging! The `cache_root` functionality of qNEI & qNEHVI requires a the model to produce a `GPyTorchPosterior`. The `ModelList` produces a `PosteriorList`, which is not a `GPyTorchPosterior`. In this case, we should not be using the `cache_root` functionality. There's some functionality that turns off `cache_root` for certain unsupported models, but looks like it needs better coverage. As a workaround, you can use `qNoisyExpectedImprovement(model=ml, X_baseline=train_X, cache_root=False)` instead.

**Comment by jduerholt** [comment]
Thanks for the quick response. In our internal application/wrapper, I am making heavy use of `get_acquisition_function`. fpr qNEHVI the `cache_root` functionality is already exposed there. I think it makes then also sense to do the same for qNEI, or?

**Comment by esantorella** [comment]
Thanks for spotting and fixing this!

**Comment by saitcakmak** [comment]
Let's keep this open for tracking. We should update `CachedCholeskyAcqusitionFunction._setup` to detect all unsupported models and overwrite `cache_root=False` for a complete fix.
