### ISSUE TITLE
[Bug] posterior sampling produces NaN

### ISSUE THREAD

**Issue by shalijiang** [pytorch/botorch#161]
# 🐛 Bug

posterior sampling produced NaN
## To reproduce
unzip the attached data, then run the pasted code below

```python
with open('posterior_sample_get_nan_bug', 'rb') as f:
    post = pickle.load(f)
posterior = post['posterior']
samples = posterior.rsample(sample_shape=post['sample_shape'], 
                            base_samples=post['base_samples'])
print(torch.isnan(samples).sum())
print(samples[torch.isnan(samples)])
print(torch.nonzero(samples == float("inf")).shape)
print(samples[6216,   49,    0,    0])
```
Output:
```
tensor(2)
tensor([nan, nan])
torch.Size([72, 4])
tensor(inf)
```
The `Inf` samples lead to `Inf` `qEI` values, which makes the `while` loop in `initializers.py` never exit when using `joint_optimize` to optimize `qEI` function
(https://github.com/pytorch/botorch/blob/8b17815b736cf0b95cc6a8c0ad9d8867a2d541bc/botorch/optim/initializers.py#L130)
```
while alpha_pos.sum() < n:
    alpha = 0.1 * alpha
    alpha_pos = Y >= alpha * max_val
```
[posterior_sample_get_nan_bug.zip](https://github.com/pytorch/botorch/files/3200050/posterior_sample_get_nan_bug.zip)

**Comment by eytan** [comment]
Shali,

Do you have similar issues with pickling and unpickling gpytorch models? I wonder if this is an issue with the botorch wrapper or the underlying model.

**Comment by shalijiang** [comment]
I didn't have problems with pickling or unpickling. 
I tested this code snippet on a notebook. 
I use python3.7 on ubuntu 18.04.

**Comment by eytan** [comment]
I see, so you are just pickling the model for reproducibility, but the failure occurs even if you don’t pickle and unpickle.

**Comment by shalijiang** [comment]
yes. 
I was running some BO experiments, and I find some of the jobs just hang in there forever. 
After some debugging, I find it was because the `qEI` values are `Inf`, so the loop in the `initializers.py` never ends, which was caused by the `samples` of the `posterior` having `Inf` entries (also `nan` entries). So I pickled the program state needed to show you this problem.

**Comment by shalijiang** [comment]
note this problem only happens occasionly. Most of my jobs can finish normally.

**Comment by sdaulton** [comment]
@shalijiang when I loaded unpickled the file, I noticed that `post["base_samples"]` contains `inf`s:
```
post['base_samples'].max()
```
Output:
```
tensor(inf)
```
This will lead to more `inf`s when you use these base samples to sample from the posterior. One recommended option is to sample from a posterior in botorch using one of the provided `MCSampler`s (https://github.com/pytorch/botorch/blob/master/botorch/acquisition/sampler.py), but you many also use your own base samples (or no base samples).

**Comment by shalijiang** [comment]
actually I didn't use any other sampler outside botorch. 
This is how I used `qEI`: 
```
qmc_sampler = SobolQMCNormalSampler(num_samples=10000)
qEI = qExpectedImprovement(
            model=model,
            best_f=current_best,
            sampler=qmc_sampler,
        )
```

**Comment by sdaulton** [comment]
Hmm, when I draw samples using `SobolQMCNormalSampler` on the posterior in the zip file, there are no  `inf`s or `nan`s. Can you provide a larger code example for reproducing this? Thanks

**Comment by shalijiang** [comment]
OK, I have located the exact location where Inf samples are generated: 

```
from botorch.qmc.normal import NormalQMCEngine
normal_qmc_engine = NormalQMCEngine(d=2, seed=343, inv_transform=True)
samples = normal_qmc_engine.draw(10000, dtype=torch.float)
print(samples.max())
```
Output
```
tensor(inf)
```

**Comment by eytan** [comment]
Hi @shalijiang, thanks for the reproducible example.  I would recommend using the Box-Muller transform instead, by setting `inv_transform` to False when computing the Sobol sequences.  The issue is that the base sample from the Sobol sequences includes a value that is exactly 1.0, which messes up the computation when inv_transform is True.  Right now we are lopping off some small number from this base sample, butt it is not enough.  I'll put in a PR to fix this problem

**Comment by shalijiang** [comment]
sounds good, thanks!
