### ISSUE TITLE
Get the covariance matrix of posterior when using gp.posterior() method

### ISSUE THREAD

**Issue by takafusui** [pytorch/botorch#1621]
I want to retrieve the covariance matrix of the posterior.
First, I standardized `train_X` and `train_y` datasets using `botorch`'s `Standardize` and `InputStandardize` methods.
Then train the GP model using the standard `botorch`'s routine:

```python
# Train the GP model with the standardized inputs
gp = SingleTaskGP(
    train_X, train_y,
    input_transform=InputStandardize(d=train_X_dim),
    outcome_transform=Standardize(m=train_y_dim)
)
mll = gpytorch.mlls.ExactMarginalLogLikelihood(gp.likelihood, gp)
fit_gpytorch_model(mll)  # Using BoTorch's routine

with torch.no_grad(), gpytorch.settings.fast_pred_var():
    # As we standardized inputs, we must use gp.posterior to get
    # rescaled outputs.
    pred_test_X = gp.posterior(test_X)
    pred_test_X_mean = pred_test_X.mean
    pred_test_X_var = pred_test_X.variance
```
After having the posterior, how can I compute the covariance matrix, especially on `test_X`?

I am sorry in advance that I am missing something here. Thank you very much in advance.

**Comment by saitcakmak** [comment]
Hi @takafusui. The covariance matrix should be available as `pred_test_X.distribution.covariance_matrix`.

**Comment by saitcakmak** [comment]
Note that for multi output models, GPyTorch might store the model as a batch of single output models. For SingleTaskGP, the covariance matrix will likely have a shape `batch_X x num_outcomes x len_X x len_X`, where each `num_output` batch corresponds to the covariance matrix for one of the outcomes.

**Comment by takafusui** [comment]
Hi @saitcakmak , thank you very much for your comment. `pred_test_X.distribution.covariance_matrix` is the method that I am looking for. I would like to close this issue.
