### ISSUE TITLE
[Bug] Evaluating ModelListGP returns the wrong number of outputs

### ISSUE THREAD

**Issue by roussel-ryan** [pytorch/botorch#1622]
# 🐛 Bug

Evaluating a ModelListGP model should produce the same number of outputs as is given by model.num_outputs. It currently does not unless you call model.posterior(). Is this the intended behavior?

## To reproduce

** Code snippet to reproduce **
```python
import botorch
import gpytorch
import torch

train_X = torch.tensor([[0., 0.],
                        [0.1, 0.1],
                        [0.5, 0.5]])
train_Y = torch.tensor([[0.1],
                        [0.5],
                        [1.0]])
test_X = torch.tensor([[0.3, 0.3]])

# Train and fit a single model.
model = botorch.models.SingleTaskGP(
    train_X, train_Y,
    # Use any transform that returns a TransformedPosterior
)

botorch.fit_gpytorch_mll(
    gpytorch.mlls.ExactMarginalLogLikelihood(model.likelihood, model)
)

# Access that model via a ModelListGP.
model_list = botorch.models.ModelListGP(model, model)

with torch.no_grad():
    result = model(test_X)
    list_result = model_list(test_X)

print(f"Model posterior: {result.mean, result.variance}")
print(f"Number of model output results: {len(list_result)}")
print(f"Number of model_list outputs: {model_list.num_outputs}")
```

** Stack trace/error message **
```
Model posterior: (tensor([0.8695]), tensor([0.2155]))
Number of model output results: 1
Number of model_list outputs: 2
```

## Expected Behavior

Expecting 2 outputs for a ModelListGP that has 2 models in it

## System information

**Please complete the following information:**
- botorch 0.8.1
- gpytorch 1.9.1
- pytorch 1.12.1
- Windows

**Comment by roussel-ryan** [comment]
Thanks for the quick response, you are right, I mixed up which calls do the un-transformation of outcomes when doing visualization

**Comment by saitcakmak** [comment]
This got fixed by https://github.com/cornellius-gp/gpytorch/pull/2249. Thanks again for reporting!
