### ISSUE TITLE
Implmentation of Multiobjectif Bayesian Optimisation 

### ISSUE THREAD

**Issue by SamirLamin** [pytorch/botorch#1638]
I tried to implement the Multiobjectif Bayesian Optimisation  but not working
can you help me to solve this problem

**Comment by eytan** [comment]
Hi,

This tutorial might be a good place for you to start.

https://botorch.org/tutorials/multi_objective_bo

Hope this helps.

**Comment by SamirLamin** [comment]
Hello Sir 
Thank you for your response. I tried to implement the code that existed in the tutorial but it did not work 
![Screenshot 2023-01-22 001101](https://user-images.githubusercontent.com/55294434/213892901-03cd03e9-ac81-426a-b896-b0b982e4a6dc.png)

Firstly I'm trying to implement this code that existed in the tutorial and I will adapt my research optimization problem to find the Pareto front using Bayesian Optimisation with Botorch 

I will be thankful if you help me at this point

**Comment by Balandat** [comment]
It appears you're using the new sampler APIs but have an old botorch version installed. The `sample_shape` argument was added to the samplers in https://github.com/pytorch/botorch/pull/1486, and made it into botorch in [version 0.8.0](https://github.com/pytorch/botorch/releases/tag/v0.8.0). I recommend updating your botorch installation to the newest version.

**Comment by SamirLamin** [comment]
Hello
Thank you so much sir, it works
