### ISSUE TITLE
`SingleTaskVariationalGP` output shapes do not match `SingleTaskGP`?

### ISSUE THREAD

**Issue by Hersh500** [pytorch/botorch#1654]
When I train a SingleTaskVariationalGP on training inputs of shape $(n, n_x)$ and training targets of shape $(n, n_y)$, and then evaluate it on test inputs of shape $(m, n_x)$, the output mean is of shape $(m, n_y)$, and, the output covariance matrix is of shape $(m \times n_y, m \times n_y)$, instead of $(n_y, m, m)$ like SingleTaskGP. Am I misunderstanding how the inputs/outputs should be shaped for SingleTaskVariationalGP? This is causing issues in my code where I would like to use SingleTask(Variational)GP interchangeably.Thank you! 

## To reproduce

```python
from botorch.models import SingleTaskGP, SingleTaskVariationalGP
from gpytorch.mlls import ExactMarginalLogLikelihood, VariationalELBO
from botorch.fit import fit_gpytorch_mll
from botorch.optim.fit import fit_gpytorch_torch
import torch

train_inputs = torch.rand(100, 5)
train_targets = torch.rand(100, 2)
test_inputs = torch.rand(10, 5)

# Single Task GP
gp_1 = SingleTaskGP(train_inputs, train_targets)
mll_1 = ExactMarginalLogLikelihood(gp_1.likelihood, gp_1)
fit_gpytorch_mll(mll_1)
gp_1.eval()
mll_1.eval()
test_output_1 = gp_1(test_inputs)
print(test_output_1.mean.shape)  # (2, 10)
print(test_output_1.covariance_matrix.shape)  # (2, 10, 10)

# Variational GP
gp_2 = SingleTaskVariationalGP(train_inputs, train_targets)
mll_2 = VariationalELBO(gp_2.likelihood, gp_2.model, num_data=100)
fit_gpytorch_torch(mll_2)
test_output_2 = gp_2(test_inputs)
print(test_output_2.mean.shape)  # (10, 2)
print(test_output_2.covariance_matrix.shape) # (20, 20)
```

## System information

**Please complete the following information:**
- BoTorch Version 0.7.2
- GPyTorch Version 1.9.0

**Comment by Balandat** [comment]
So `SingleTaskGP` and `SingleTaskVariationalGP`. use somewhat different implementations under the hood. However, if you call the `posterior()` method, the results you get will be consistent (this is the usual way we use the models in botorch).  
<img width="870" alt="Screenshot 2023-02-03 at 9 35 53 PM" src="https://user-images.githubusercontent.com/1605878/216750771-65330c61-7f18-4e7c-a56b-d1817c08ab1b.png">

**Comment by Hersh500** [comment]
Thank you!
