### ISSUE TITLE
[Bug] filter_kwargs warning leads to unintended thrown exception, when using `partial`

### ISSUE THREAD

**Issue by mrcslws** [pytorch/botorch#1667]
# 🐛 Bug

Currently if I run `batch_cross_validation` using `partial(MyModel, ...)` as my `model_cls`, botorch accidentally throws an exception. The exception happens during param checking, when it tries to print the `__name__` of the `partial`. This code worked without throwing an exception until the recent changes to [`_filter_kwargs`](https://github.com/pytorch/botorch/blob/89f923d9f677cb7664909b2ff0bcc30b4d37007a/botorch/optim/utils/common.py#L20).

This `warn` happens by default with `batch_cross_validation` because this function passes in `train_Yvar=None` into the class, which many classes don't use (e.g. `SingleTaskGP`). You might consider this a second bug; [`batch_cross_validation`](https://github.com/pytorch/botorch/blob/89f923d9f677cb7664909b2ff0bcc30b4d37007a/botorch/cross_validation.py#L151) should only pass in `train_Yvar` if it is not None.

## To reproduce

Here's an isolated repro that doesn't require calling `batch_cross_validation`.

```python
import functools

import botorch

class MyModel:
    def __init__(self, my_param1, my_param2):
        self.my_param1 = my_param1
        self.my_param2 = my_param2

# This works.
cls = MyModel
botorch.optim.utils._filter_kwargs(MyModel,
                                   my_param1=42,
                                   my_param2=43,
                                   my_param3=44)

# This used to work, but started failing recently.
cls = functools.partial(MyModel,
                        my_param1=42)
botorch.optim.utils._filter_kwargs(cls,
                                   my_param2=43,
                                   my_param3=44)
```

** Stack trace/error message **
```
Traceback (most recent call last):
    botorch.optim.utils._filter_kwargs(cls,
  File "/Users/mrcslws/dev/src/botorch/botorch/optim/utils/common.py", line 28, in _filter_kwargs
    f" not allowed parameters for function {function.__name__}. Allowed "
AttributeError: 'functools.partial' object has no attribute '__name__'
```

## Expected Behavior

It should just print a warning, as the code intended. Instead, the printing code itself is hitting an error.

## System information

botorch: 0.7.3.dev22+g208470e7.d20221102
gpytorch: 1.9.1.dev32+g23b068b5
torch: 1.13.1
MacOS M1

**Comment by Balandat** [comment]
Thanks for the report. This is interesting, I've never seen `partial` being used with classes - seems a bit weird to me, borderline abusive (but then again a lot of python is borderline abusive by default). 

To support this specific use case we could just check whether this is a `partial` and then check for its args on the `func` attribute that contains the class. This seems like a bit of a hack to accommodate this; but then again I see the value of using `partial` here. 

An alternative would be to just subclass the model and write an `__init__` method that fixes those inputs, but presumably that's way too clunky/verbose? 

cc @esantorella as this seems to be a consequence of your recent changes.

**Comment by Balandat** [comment]
> You might consider this a second bug; [batch_cross_validation](https://github.com/pytorch/botorch/blob/89f923d9f677cb7664909b2ff0bcc30b4d37007a/botorch/cross_validation.py#L151) should only pass in train_Yvar if it is not None. 

Good point, will make a new issue for tracking this.

**Comment by esantorella** [comment]
This is a great point, thanks for the bug report! This would also fail if `functools.partial` is applied to a function, e.g. 

```python
from scipy.optimize import minimize
from functools import partial

# raises AttributeError
partial(minimize, method="L-BFGS-B").__name__
```

I'll put in a fix!
