### ISSUE TITLE
[Bug] Cannot scale qNoisyExpectedHypervolumeImprovement qbatch sizes shown to be possible in the paper

### ISSUE THREAD

**Issue by hkenlay** [pytorch/botorch#1694]
# 🐛 Bug

I'm trying to use qNoisyExpectedHypervolumeImprovement with large qbatch sizes. In Figure 2 of the [Parallel Bayesian Optimization of Multiple Noisy Objectives with Expected Hypervolume Improvement](https://arxiv.org/abs/2105.08195) manuscript the authors manage to optimise the acquisition function up to `q=100`. However, using the same problem setup and an NVIDIA A10G (24GB memory) I run out of memory at `q=21` when trying to compute the acquisition function. 

## To reproduce

Using `python nehvi.py --qbatch_size 21` where the below is `nehvi.py`

```python
import argparse

import torch
from botorch import fit_gpytorch_mll
from botorch.acquisition.multi_objective.monte_carlo import (
    qNoisyExpectedHypervolumeImprovement,
)
from botorch.models.gp_regression import FixedNoiseGP
from botorch.models.model_list_gp_regression import ModelListGP
from botorch.models.transforms.outcome import Standardize
from botorch.sampling.normal import SobolQMCNormalSampler
from botorch.test_functions.multi_objective import DTLZ2
from botorch.utils.sampling import draw_sobol_samples
from botorch.utils.transforms import normalize
from gpytorch.mlls.sum_marginal_log_likelihood import SumMarginalLogLikelihood

parser = argparse.ArgumentParser()
parser.add_argument(
    "--qbatch_size",
    type=int,
    default=1,
)
args = parser.parse_args()

tkwargs = {"dtype": torch.double, "device": torch.device("cuda")}
problem = DTLZ2(dim=6, num_objectives=2, noise_std=0.1).to(**tkwargs)

train_x = draw_sobol_samples(bounds=problem.bounds, n=20, q=1).squeeze(1)
train_y = problem(train_x)

train_x = normalize(train_x, problem.bounds)
models = []
for i in range(problem.num_objectives):
    train_y_single_objective = train_y[:, i].unsqueeze(1)
    train_yvar = torch.full_like(train_y_single_objective, problem.noise_std**2)
    models.append(
        FixedNoiseGP(
            train_x,
            train_y_single_objective,
            train_yvar,
            outcome_transform=Standardize(m=1),
        )
    )
model = ModelListGP(*models).to(**tkwargs)
mll = SumMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_mll(mll)

sampler = SobolQMCNormalSampler(sample_shape=torch.Size([128]))
acq_func = qNoisyExpectedHypervolumeImprovement(
    model=model,
    ref_point=problem.ref_point.tolist(),  # use known reference point
    X_baseline=normalize(train_x, problem.bounds),
    prune_baseline=True,
    # prune baseline points that have estimated zero probability of being Pareto optimal
    sampler=sampler,
).to(**tkwargs)

batch = torch.rand(1, args.qbatch_size, problem.dim).to(**tkwargs)
torch.cuda.empty_cache()
print(acq_func(batch))
```
the output is
```
 File "~/.venv/lib/python3.9/site-packages/botorch/acquisition/multi_objective/monte_carlo.py", line 321, in _compute_qehvi
    obj_subsets = obj.index_select(dim=-2, index=q_choose_i.view(-1))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.73 GiB (GPU 0; 22.20 GiB total capacity; 19.51 GiB already allocated; 936.12 MiB free; 20.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
For smaller values of `qbatch_size` the above outputs a tensor of size `(1,)`

## Expected Behavior

To be able to compute the acquisition function up to `qbatch_size=100` on a large memory GPU.

## System information

**Please complete the following information:**
- BoTorch Version `0.8.1`
- GPyTorch Version `1.9.1` 
- PyTorch Version `1.13.1` 
- OS Amazon Linux 2

**Comment by hkenlay** [comment]
I will close this issue as I realised Figure 2 are wall times for sequential optimisation rather than batch, so the above does not contradict those results.

**Comment by saitcakmak** [comment]
If the joint evaluation is important for you, you might be able to scale it further by compiling parts of the code with the new `torch.compile` functionality (See https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html). Unfortunately, I do not have any up-to-date code pointers for this. @sdaulton observed significant speed ups and reduction in memory usage with a compiled version of qNEHVI in the past.

Based on my limited experience with `torch.compile`, GPyTorch does not play well with it. If you were to try this, I'd use the existing code for getting the posterior samples and only try compile `_compute_qehvi` part (which may also require some changes).

**Comment by hkenlay** [comment]
Thanks for the advice @saitcakmak.
