### ISSUE TITLE
[Bug] Pickling of botorch models

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#1697]
# 🐛 Bug

When I try to pickle a botorch model with `torch.save`, it works when I do it directly after the fit, but when I do an inference step before the `torch.save`, I get an error.

Do you know the reason for it and is this intended behavior?

## To reproduce

```python
import torch
from botorch.fit import fit_gpytorch_mll
from botorch.models import SingleTaskGP
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood

train_X = torch.rand(10, 2)
Y = 1 - torch.norm(train_X - 0.5, dim=-1, keepdim=True)
Y = Y + 0.1 * torch.randn_like(Y)  # add some noise
train_Y = standardize(Y)

gp = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
fit_gpytorch_mll(mll)

# this works
torch.save(gp, "gp.pth")

# do inference
gp.posterior(train_X).mean

# this fails
torch.save(gp, "gp2.pth")
```

** Stack trace/error message **
```
_pickle.PicklingError: Can't pickle <function TriangularLinearOperator.to_dense at 0x10f00ac10>: it's not the same object as linear_operator.operators.triangular_linear_operator.TriangularLinearOperator.to_dense
```

## Expected Behavior

I would expect that pickling is also possible after inference.

## System information

**Please complete the following information:**
- botorch version: 0.6.1.dev307+ge8d12b57
- gpytorch version: 1.9.1.dev35+gc35d094a
- torch version: 1.12.0
- macos

**Comment by Balandat** [comment]
This is an issue with `LinearOperator`, which surface after the prediction step b/c of the caching of the covariance decomposition that is done on the gpytorch end. Related issue: https://github.com/cornellius-gp/gpytorch/issues/2264#issue-1567345205. 

I just put up https://github.com/cornellius-gp/linear_operator/pull/51 and verified that with this change your example above works.

**Comment by jduerholt** [comment]
Great, thank you very much! Will pull from there, and hope that this gets merged so that pickling is again possible ;)

**Comment by jduerholt** [comment]
Hi @Balandat, 

coming back to this issue, back then you fixed the problem directly in `linear_operator` and it was merged in https://github.com/cornellius-gp/linear_operator/pull/51. 

Unfortunately, there had not been a `linear_operator` release since then, and one only get the fix by installing all from sources. Is there some kind of maintenance release planned for getting this easily available?

Best,

Johannes

**Comment by Balandat** [comment]
`linear_operator` release with the fix is out: https://github.com/cornellius-gp/linear_operator/releases/tag/v0.4.0

We'll put out a botorch version with that new dep soon.
