### ISSUE TITLE
[Feature Request] Recompute the acquisition values after post processing in `optimize_acqf`

### ISSUE THREAD

**Issue by saitcakmak** [pytorch/botorch#1736]
# 🚀 Feature Request 

## Motivation

We currently [post process the candidates](https://github.com/pytorch/botorch/blob/main/botorch/optim/optimize.py#L380-L381) but continue to use the acquisition values computed with the raw candidates to [select the best candidate to return](https://github.com/pytorch/botorch/blob/main/botorch/optim/optimize.py#L383-L386). This is sub-optimal as it can lead to an inferior candidate being returned, e.g., when we use continuous relaxation + rounding to optimize the acquisition functions in Ax.

## Pitch

Recompute the acquisition values with the post processed candidates, and use these values to pick the best candidate.

**Comment by Balandat** [comment]
That makes a lot of sense to me. Is this something you're planning to put a PR up for?

**Comment by saitcakmak** [comment]
If someone else wants to take it, be my guest. Otherwise, I'll put up a PR for it eventually.
