### ISSUE TITLE
[Bug] No module named 'botorch.sampling'

### ISSUE THREAD

**Issue by peterroelants** [pytorch/botorch#174]
# 🐛 Bug

When following the tutorial from https://botorch.org/tutorials/closed_loop_botorch_only I get a `ModuleNotFoundError: No module named 'botorch.sampling'`

## To reproduce

Run notebook from https://botorch.org/files/closed_loop_botorch_only.ipynb in environment with:

```
botorch                   0.1.0                    pypi_0    pypi
gpytorch                  0.3.2                    pypi_0    pypi
python                    3.7.3                h0371630_0 
pytorch-cpu               1.1.0               py3.7_cpu_0    pytorch
```
I installed botorch via `pip` because the conda version relies on a conda version of `gpytorch` which requires `pytorch` with CUDA and not `pytorch-cpu`. I'm unable to install botorch with `conda install botorch -c pytorch` because of this.

** Stack trace/error message **
```
----> 4 from botorch.sampling.samplers import SobolQMCNormalSampler

ModuleNotFoundError: No module named 'botorch.sampling'
```

## Expected Behavior

`botorch.sampling` can be imported.

## System information

**Please complete the following information:**
- BoTorch Version (0.1.0)
- GPyTorch Version (0.3.2)
- PyTorch Version (1.1.0)
- Ubuntu 18.04

**Comment by peterroelants** [comment]
It seems to work when I install the latest master as illustrated in https://github.com/pytorch/botorch#installing-from-latest-master

However, in that case, there is a small fix that needs to be done when creating the `ModelListGP`

**Comment by Balandat** [comment]
Thanks for raising this.

You are right, this won't work with the 0.1.0 release. Apologies for the friction, this is still beta code and we're trying to get the interface right so there may be some breaking changes of this sort. 

We are about to roll out a versioned website though that will ensure that the tutorials and code examples are properly tied to the different releases (or the latest master). 

I'll put up a fix for creating the `ModelListGP` momentarily.

**Comment by peterroelants** [comment]
I understand that it is beta code. I'm just getting to learn the framework at the moment and it seems interesting, thanks for the great work!

**Comment by Balandat** [comment]
I landed a fix for the `ModelListGP` construction in the tutorial.

Since we're actively working on versioned tutorials / docs, I'm going to close this issue.

Thanks again for flagging.

**Comment by motingzhi** [comment]
Hello @Balandat, I am exploring Botorch as well, but I have this same issue now- ModuleNotFoundError: No module named 'botorch.sampling', do you know how to fix it?
My installed version is:
botorch                       0.9.5.dev36+g03e0d7af
gpytorch                      1.12.dev24+g14705b9d
torch                            1.11.0
Python 3.10.13
Maxos.
Thank you!

**Comment by saitcakmak** [comment]
Hi @motingzhi. `botorch.sampling` is a valid module (https://github.com/pytorch/botorch/tree/main/botorch/sampling), so I am not sure why you're getting this error. Can you open a separate issue with a full stack trace, since this one is quite old? 

We're also releasing a new BoTorch version today. If there are any discrepancies between the main branch and the tutorials on the website, those should be resolved. In general, the tutorials from the main branch in github should always be compatible with the code in the main branch.
