### ISSUE TITLE
A little problem in the tutorial for information-theoretic acquisition functions.

### ISSUE THREAD

**Issue by WrynnChou** [pytorch/botorch#1741]
In the Section 2 of the tutorial for information-theoretic acquisition functions, the dimension of the input is d = 3, and there are totally 16 points. Why the output, train_y, has the shape of [4,2]? Why not [16,2]? That makes me confused. Could any one tell me why? Thanks.

**Comment by Balandat** [comment]
I am not sure I understand - the shape of `train_Y` is in fact `[16, 2]` (I just checked).

**Comment by WrynnChou** [comment]
Sry，I just find I made a stupid mistake. Thanks a lot for your help!
