### ISSUE TITLE
[Bug] Multiple inequality constraints in Botorch

### ISSUE THREAD

**Issue by minsu77** [pytorch/botorch#1751]
# 🐛 Bug

Hi, I'm trying to apply multiple inequality parameter constraints in botorch.
"Bayesian Optimization with Inequality Constraints"
In the above paper, it is described that it can be extended with multiple inequality constraints, but it is difficult to implement.

Do you have any ideas?

The code below applies x1+x2 <= 0.17, and this code works.

## To reproduce

```python
#     candidates, acq_value = optimize_acqf(
        acq_function=acq_func,
        bounds=standard_bounds,
        q=BATCH_SIZE,
        num_restarts=NUM_RESTARTS,
        raw_samples=RAW_SAMPLES,  
        options={"batch_limit": 5, "maxiter": 200},
        inequality_constraints=ineq_constraints, 
        sequential=True,
    )

ineq_constraints = [
            (torch.tensor([0, 1]), torch.tensor([-1., -1.]), torch.tensor([-0.17]))
        ]

```

**Comment by Balandat** [comment]
Not sure I fully understand what makes it "difficult to implement" - from the docstring: 

>         inequality_constraints: A list of tuples (indices, coefficients, rhs),
>            with each tuple encoding an inequality constraint of the form
>            `\sum_i (X[indices[i]] * coefficients[i]) >= rhs`

So if you wanted to add the additional constraint of, say, `x1 + 0.5*x2 >= -1.0`, you'd pass in both constraints as a list of tuples as follows:

```
ineq_constraints = [
    (torch.tensor([0, 1]), torch.tensor([-1., -1.]), torch.tensor([-0.17])),
    (torch.tensor([0, 1]), torch.tensor([1., 0.5]), torch.tensor([-1.0])),
]
```

Hope this helps.

**Comment by minsu77** [comment]
> 

Thank you so much. it is really helpful!!
