### ISSUE TITLE
[Feature Request] Make `gen_batch_initial_conditions` more flexible

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#1776]
# 🚀 Feature Request

## Motivation

When optimizing an acqf it could be possible that the default starting point sampler is not sufficient (for example when dealing with non-linear constraints or NChooseK constraints). In these case one can provide a initializer method via the `ic_generator` argument or samples directly  via the `batch_initial_conditions` keyword. When looking at the default generator `gen_batch_initial_conditions` one sees that there is lot of logic besides simple sampling included, namely boltzmann weighting of the samples, catching of zero acqf values etc. 

I propose to make this logic more broadly available to have a easy way to use it in situations where the default intialization does not work and custom samplers has to be used.

## Pitch

For this purpose, I propose to add a new optional argument to `gen_batch_initial_conditions` which accepts a callable of type `Callable[[int, int], Tensor]` that just returns samples that are then further processed (boltzmann weighted based on the acqf values etc.) The two arguments of the function would be `n` and `q` and the returned Tensor would be of shape `n x q x d`. 

What do you think?

**Are you willing to open a pull request?** Yes.

**Comment by Balandat** [comment]
Sounds like a great improvement to me! Happy to review a PR for this.
