### ISSUE TITLE
Question : Optimization with noise minimisation (or robustness) as an objective

### ISSUE THREAD

**Issue by Kh-im** [pytorch/botorch#1806]
Hello,

I'm trying to do a multiobjective (2 objectives) optimization but my second objective is somewhat the observed noise on my first objective. I'm doing that because I want to somewhat tell the optimizer that an optimal solution with little noise is better than something more optimal but with a lot of noise.  It seems that MOO is not the best way to do that. Do you have a better choice for this kind of problem ?
Thanks for your help

**Comment by sdaulton** [comment]
Hi @Kh-im, interesting problem. This paper considers the same problem and https://proceedings.neurips.cc/paper/2021/file/8f97d1d7e02158a83ceb2c14ff5372cd-Paper.pdf addresses it using a mean-variance objective: it assumes you know can know that your objective is a linear combination of the mean and the heteroskedadtic noise variance as the objective with known weights. If you don’t know how the weights for your optimal mean-heteroskedastic noise variance trade off, then multi-objective or constrained optimization seem like the right thing to do.

**Comment by Kh-im** [comment]
Thanks, it's exactly what I was looking for !
