### ISSUE TITLE
Is there a way to condition a model on a certain input variable before generating candidates with qNEI?

### ISSUE THREAD

**Issue by EvanClaes** [pytorch/botorch#1810]
Hi,

I'm using a model (SingleTaskGP) with three inputs to generate a batch of experimental candidates with qNoisyExpectedImprovement, which is working fine. I would now like to condition the model for a certain value of the third input, and would then like to generate experimental candidates with that model.

Is there a way to do this? condition_on_observations from the docs does not seem to be what I need...

**Comment by sdaulton** [comment]
Hi @EvanClaes,

To clarify, you have a model, and want to generate a batch of designs, where the third input dimension of those designs is fixed to a specific value? This can be done by passing `fixed_features` to `optimize_acqf`: https://github.com/pytorch/botorch/blob/1264316a5d590bdba4ec6b06567b257c1be7a657/botorch/optim/optimize.py#L465-L466

**Comment by EvanClaes** [comment]
OK, thanks. Just tried it and it works perfectly. You can consider this issue closed.

Enjoy your weekend!
