### ISSUE TITLE
[Feature Request] Fixed features and nonlinear constraints

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#1904]
# 🚀 Feature Request

I would like to use fixed features in combination with non-linear inequality constraints.

## Motivation

I have an optimization problem with 4 continuous variables and an NChooseK constraint on top of them modelled via continuous relaxation as a non-linear inequality constraint and a categorical variable. Running `optimize_acqf_mixed` on this problem leads to this `NotImplementedError`: https://github.com/pytorch/botorch/blob/main/botorch/generation/gen.py#L120. It is already stated in a comment that this should be in principle possible, especially in the case from above where the fixed feature is independent from the nonlinear constraint.

## Pitch

My idea would to just remove the if statement and the `NotImplementedError` and rely on the user that the callables for the nonlinear constraints are also valid for the reduced problem, but perhaps anybody has a better/safer solution. Any suggestions?

**Are you willing to open a pull request?**  Yes.

```[tasklist]
### Tasks
```

**Comment by Balandat** [comment]
How about something like this?
```
if fixed_features:
    if nonlinear_inequality_constraints:
        new_callables = []
        for nic in nonlinear_inequality_constraints:

            def _wrap_nic(X: Tensor) -> Tensor:
                return nic(fix_features(X, fixed_features))

        new_callables.append(_wrap_nic)
    nonlinear_inequality_constraints = new_callables
```

**Comment by jduerholt** [comment]
Looks perfect. Thanks. I will create a PR in the course of the next week.
