### ISSUE TITLE
[Feature Request] Add (discrete) Thompson Sampling acquisition function

### ISSUE THREAD

**Issue by Balandat** [pytorch/botorch#199]
# 🚀 Feature Request

Various folks have been interested in this, see e.g. https://github.com/cornellius-gp/gpytorch/issues/757

Let's clean up our ad-hoc code for this and add it as an acquisition function.

**Comment by Tenoke** [comment]
Just curious if this is still on the cards?

**Comment by Balandat** [comment]
yeah let me put up a PR for this

**Comment by Balandat** [comment]
Here is a RFC:  #218

**Comment by eytan** [comment]
@Tenoke curious to know what your use-case is for TS.  AFAIK we do have a version of it in Ax, but it is oriented around A/B test-related applications.

**Comment by jmren168** [comment]
> yeah let me put up a PR for this

Curious about what "PR" means here? And thanks.

**Comment by Balandat** [comment]
> Curious about what "PR" means here?

Pull Request :)

**Comment by Balandat** [comment]
Added as `MaxPosteriorSampling` in #218
