### ISSUE TITLE
Usage of deprecated torch.norm

### ISSUE THREAD

**Issue by kit1980** [pytorch/botorch#2001]
`torch.norm` is deprecated and may be removed in a future PyTorch release. Its documentation and behavior may be incorrect, and it is no longer actively maintained.

Please follow https://pytorch.org/docs/stable/generated/torch.norm.html to update.

Issues found with https://github.com/pytorch/test-infra/tree/main/tools/torchfix:

./botorch/acquisition/penalized.py:47:14: TOR101 Use of deprecated function torch.norm
./botorch/acquisition/penalized.py:75:14: TOR101 Use of deprecated function torch.norm
./botorch/acquisition/penalized.py:104:20: TOR101 Use of deprecated function torch.norm
./botorch/acquisition/penalized.py:260:35: TOR101 Use of deprecated function torch.norm
./botorch/acquisition/penalized.py:292:17: TOR101 Use of deprecated function torch.norm
./botorch/models/pairwise_gp.py:674:21: TOR101 Use of deprecated function torch.norm
./botorch/test_functions/synthetic.py:142:60: TOR101 Use of deprecated function torch.norm
./botorch/test_functions/synthetic.py:234:17: TOR101 Use of deprecated function torch.norm
./botorch/test_functions/synthetic.py:458:31: TOR101 Use of deprecated function torch.norm
./botorch/utils/sampling.py:169:22: TOR101 Use of deprecated function torch.norm
./test/acquisition/test_penalized.py:44:18: TOR101 Use of deprecated function torch.norm
./test/acquisition/test_penalized.py:62:29: TOR101 Use of deprecated function torch.norm
./test/acquisition/test_penalized.py:80:18: TOR101 Use of deprecated function torch.norm
./test/acquisition/test_penalized.py:269:28: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_categorical.py:30:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_categorical.py:37:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_contextual.py:36:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_contextual.py:64:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_downsampling.py:51:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_downsampling.py:67:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_downsampling.py:99:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_downsampling.py:122:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_downsampling.py:128:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_downsampling.py:135:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_downsampling.py:141:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_downsampling.py:148:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_downsampling.py:179:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_downsampling.py:195:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_exponential_decay.py:35:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_exponential_decay.py:52:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_exponential_decay.py:74:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_exponential_decay.py:96:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_exponential_decay.py:102:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_exponential_decay.py:109:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_exponential_decay.py:115:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_exponential_decay.py:122:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_exponential_decay.py:128:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_exponential_decay.py:135:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_linear_truncated_fidelity.py:59:30: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_linear_truncated_fidelity.py:62:30: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_linear_truncated_fidelity.py:108:30: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_linear_truncated_fidelity.py:112:18: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_linear_truncated_fidelity.py:153:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_linear_truncated_fidelity.py:162:26: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_linear_truncated_fidelity.py:183:14: TOR101 Use of deprecated function torch.norm
./test/models/kernels/test_linear_truncated_fidelity.py:196:14: TOR101 Use of deprecated function torch.norm
./test/optim/test_optimize.py:69:17: TOR101 Use of deprecated function torch.norm

**Comment by saitcakmak** [comment]
Thanks for flagging! I had updated Ax but looks like BoTorch is the bigger offender here

**Comment by Balandat** [comment]
I can get a PR out for this
