### ISSUE TITLE
[Bug] Lapack Error when evaluating new experiment trial

### ISSUE THREAD

**Issue by icanwalkinyourmind** [pytorch/botorch#202]
# 🐛 Bug

Try to implement example form here https://botorch.org/tutorials/custom_botorch_model_in_ax

But replace branin function with LGBM model fit
Search space: 
```python
from ax import ParameterType, RangeParameter, SearchSpace, ChoiceParameter
search_space = SearchSpace(
    parameters=[
        RangeParameter(
            name="bagging_freq", parameter_type=ParameterType.INT, lower=1, upper=10, 
        ),
        RangeParameter(
            name="learning_rate", parameter_type=ParameterType.FLOAT, lower=10e-5, upper=10e-1
        ),
        RangeParameter(
            name="min_data_in_leaf", parameter_type=ParameterType.INT, lower=10, upper=1000
        ),
        RangeParameter(
            name="min_sum_hessian_in_leaf", parameter_type=ParameterType.INT, lower=10, upper=1000
        ),
        RangeParameter(
            name="num_leaves", parameter_type=ParameterType.INT, lower=2, upper=128
        ), 
        RangeParameter(
            name="max_depth", parameter_type=ParameterType.INT, lower=1, upper=20
        ),
        RangeParameter(
            name="num_treas", parameter_type=ParameterType.INT, lower=100, upper=1000
        ),
        ChoiceParameter(
            name='boost', parameter_type=ParameterType.STRING, values = ['gbdt', 'gbrt', 'goss']
        )
    ]
)
```

After some number of evaluating exp.new_trial got this ERROR:
```
Lapack Error syev : 2 off-diagonal elements didn't converge to zero at /pytorch/aten/src/TH/generic/THTensorLapack.cpp:296
```
It is a bug or I'm doing something wrong?

## System information

**Please complete the following information:**
-  BoTorch Version: 0.1.1
- GPyTorch Version: 0.3.3
- PyTorch Version: 1.1.1
- Computer OS : Ubuntu 19.04

**Comment by Balandat** [comment]
This error seems to be a numerical issue with the GP model. Are you actually using a custom GP model? Or are you just using `SimpleCustomGP` from the tutorial and the only difference in your case the underlying function you're trying to optimize? 

This tutorial is meant as a simple illustration for hooking a custom GP model into Ax; we don't actually advise to use this model in practical problems (I'll update the tutorial text to make that more clear). 

Instead, you should just use one of Ax's [APIs](https://ax.dev/docs/api.html) directly. This will make things easier and also use a more robust GP model with reasonably priors on the hyperparameters and additional safeguards against degenerate parameter values, which could be the cause for the error you're seeing.

**Comment by icanwalkinyourmind** [comment]
Thank you for answer. I'll try to learn more about GP models and correct my own.

**Comment by Balandat** [comment]
> Each optimization batch we call get_botorch function and create new GP model. Why should not we train one GP model during all optimization cycle?

I am not sure I fully understand this question. Clearly, we need to include the new observations we make into our model, that's the whole idea of Bayesian Optimization. Are you saying we could speed things up by re-using our previous model? That is a possibility, we can warm-start our hyperparameters from the previous values to save some fitting time. If we have a lot of data and don't expect the optimal hyperparameters to change much with new data we can also do a cheap update without refitting the hyperparameters. But typically the majority of time in Bayesian Optimization is spent on optimizing the acquisition function, so we wouldn't gain all that much from going that route. 


> Are you able to give me some references on useful examples?

A good introduction to GPs is [this book](http://www.gaussianprocess.org/gpml/). However, if you want to use Bayesian Optimization as a technology without digging deep into the details, I suggest you just use Ax. BoTorch is more geared towards research-level work, and we expect some familiarity with GPs and Bayesian Optimization.
