### ISSUE TITLE
Implementation of Constrained Multi-Objective Optimization for material discovery using qNEHVI

### ISSUE THREAD

**Issue by Paeyus** [pytorch/botorch#2035]
# 🐛 Bug
 I am working on a material discovery problem where I am using qNEHVI for constrained multiobjective optimization (two objectives and one constrained). I am a beginner with both PyTorch and Botorch, so I hope I can get help in solving my issue.

Cell In[11], line 27
     24     with warnings.catch_warnings():
     25         warnings.simplefilter("ignore")
---> 27         policy = qNoisyExpectedHypervolumeImprovement(
     28             model=ModelListGP(model1, model2, constraint_model), 
     29             ref_point=ref_point,
     30             X_baseline=train_x,
     31             prune_baseline=False,
     32             partitioning=FastNondominatedPartitioning(ref_point, train_y),
     33             constraints={2: [[None, 6.0]]}
     34         )
     36 with warnings.catch_warnings():
     37     warnings.filterwarnings('ignore', category=RuntimeWarning)

## To reproduce

Here is my full code

train_x = torch.tensor([[3., 0., 0.], [0., 0., 0.], [1., 0., 0.]]).type(torch.float64)
train_y1 = torch.tensor([17189., 10068., 11139.]).to(train_x.dtype)
train_y2 = torch.tensor([77., 4., 17.]).to(train_x.dtype)

# combining objectives 1 & 2
train_Y = torch.vstack([train_y1.flatten(), train_y2.flatten()]).transpose(-1, -2)

constraint_Y = torch.tensor([2.5, 0., 0.]).to(train_x.dtype).unsqueeze(-1)

# Normalize train_Y and Constraint
train_y = (train_Y - train_Y.mean()) / train_Y.std()
constraint = (constraint_Y - constraint_Y.mean()) / constraint_Y.std()

class GPModel(gpytorch.models.ExactGP, botorch.models.gpytorch.GPyTorchModel):
    _num_outputs = 1

    def __init__(self, train_x, train_y, likelihood):
        super().__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.MaternKernel(nu=2.5, ard_num_dims=train_x.shape[1])
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

def fit_gp_model(train_x, train_y, num_train_iters=500):
    # declare the GP
    noise = 1e-4
    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    model = GPModel(train_x, train_y, likelihood)
    model.likelihood.noise = noise

    # train the hyperparameter (the constant)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

    model.train()
    likelihood.train()
    for i in range(num_train_iters):
        optimizer.zero_grad()
        output = model(train_x)
        loss = -mll(output, train_y)
        loss.backward()
        optimizer.step()
    model.eval()
    likelihood.eval()
    return model, likelihood

ref_point = torch.tensor([train_y[:, 0].min(), train_y[:, 1].min()])
bounds = torch.tensor([[-10., -10., -10.], [10., 10., 10.]])
num_queries = 50
num_repeats = 10
batch_size = 3

strategy = "qNEHVI"

hypervolumes = torch.zeros(num_repeats, num_repeats)

for trial in range(num_repeats):
    print("trial", trial)

    torch.manual_seed(trial)

    for i in tqdm(range(num_queries)):
        dominated_part = DominatedPartitioning(ref_point, train_y)
        hypervolumes[trial, i] = dominated_part.compute_hypervolume().item()

        model1, likelihood1 = fit_gp_model(train_x, train_y[:, 0].squeeze(-1))
        model2, likelihood2 = fit_gp_model(train_x, train_y[:, 1].squeeze(-1))
      # add constraint
        constraint_model, constraint_likelihood = fit_gp_model(train_x, constraint_Y.squeeze(-1))

        if strategy == "qNEHVI":
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")

                policy = qNoisyExpectedHypervolumeImprovement(
                    model=ModelListGP(model1, model2, constraint_model), 
                    ref_point=ref_point,
                    X_baseline=train_x,
                    prune_baseline=False,
                    partitioning=FastNondominatedPartitioning(ref_point, train_y),
                    constraints={2: [None, 6.0]}
                )

        with warnings.catch_warnings():
            warnings.filterwarnings('ignore', category=RuntimeWarning)
            next_x, acq_val =  optimize_acqf(
                acq_function=policy,
                bounds=bounds,
                q=batch_size,
                num_restarts=100,
                raw_samples=500, 
                options={"batch_limit":5, "max_iter":200},
            )

        next_y = train_Y(next_x)
        next_constraint = constraint_Y(next_x)

        train_x = torch.cat([train_x, next_x])
        train_Y= torch.cat([train_y, next_y])
        constraint = torch.cat([constraint_Y, next_constraint])

# Your code goes here
# Please make sure it does not require any external dependencies
```

** Stack trace/error message **
```
// Paste the bad output here!
```TypeError                                 Traceback (most recent call last)
Cell In[11], line 27
     24     with warnings.catch_warnings():
     25         warnings.simplefilter("ignore")
---> 27         policy = qNoisyExpectedHypervolumeImprovement(
     28             model=ModelListGP(model1, model2, constraint_model), 
     29             ref_point=ref_point,
     30             X_baseline=train_x,
     31             prune_baseline=False,
     32             partitioning=FastNondominatedPartitioning(ref_point, train_y),
     33             constraints={2: [[None, 6.0]]}
     34         )
     36 with warnings.catch_warnings():
     37     warnings.filterwarnings('ignore', category=RuntimeWarning)

File ~\Anaconda3\envs\Project_Battery\lib\site-packages\botorch\acquisition\multi_objective\monte_carlo.py:515, in qNoisyExpectedHypervolumeImprovement.__init__(self, model, ref_point, X_baseline, sampler, objective, constraints, X_pending, eta, prune_baseline, alpha, cache_pending, max_iep, incremental_nehvi, cache_root, **kwargs)
    510 # In the case that X_pending is not None, but there are fewer than
    511 # max_iep pending points, the box decompositions are not performed in
    512 # set_X_pending. Therefore, we need to perform a box decomposition over
    513 # f(X_baseline) here.
    514 if X_pending is None or X_pending.shape[-2] <= self._max_iep:
--> 515     self._set_cell_bounds(num_new_points=X_baseline.shape[0])
    516 # Set q_in=-1 to so that self.sampler is updated at the next forward call.
    517 self.q_in = -1

File ~\Anaconda3\envs\Project_Battery\lib\site-packages\botorch\acquisition\multi_objective\monte_carlo.py:583, in qNoisyExpectedHypervolumeImprovement._set_cell_bounds(self, num_new_points)
    580     obj = self.objective(samples, X=self.X_baseline)
    581     if self.constraints is not None:
    582         feas = torch.stack(
--> 583             [c(samples) <= 0 for c in self.constraints], dim=0
    584         ).all(dim=0)
    585 else:
    586     sample_shape = (
    587         self.sampler.sample_shape
    588         if self.sampler is not None
    589         else self._default_sample_shape
    590     )

File ~\Anaconda3\envs\Project_Battery\lib\site-packages\botorch\acquisition\multi_objective\monte_carlo.py:583, in <listcomp>(.0)
    580     obj = self.objective(samples, X=self.X_baseline)
    581     if self.constraints is not None:
    582         feas = torch.stack(
--> 583             [c(samples) <= 0 for c in self.constraints], dim=0
    584         ).all(dim=0)
    585 else:
    586     sample_shape = (
    587         self.sampler.sample_shape
    588         if self.sampler is not None
    589         else self._default_sample_shape
    590     )

TypeError: 'int' object is not callable

## Expected Behavior

<!-- A clear and concise description of what you expected to happen. -->

## System information

**Please complete the following information:**
- <!-- BoTorch Version (run `print(botorch.__version__)` -->0.8.5
- <!-- GPyTorch Version (run `print(gpytorch.__version__)` -->1.10
- <!-- PyTorch Version (run `print(torch.__version__)` --> 1.13.1
- <!-- Computer OS --> Windows 10


## Additional context

Add any other context about the problem here.

**Comment by eytan** [comment]
Hi @Paeyus , is your intent just to use qNEHVI for your research or to develop novel Bayesian optimization algorithms?  If it is the former, then we offer an easier to use interface to BoTorch called Ax.  Here is an example of what the API looks like: https://ax.dev/tutorials/multiobjective_optimization.html

Let us know if this is what you are looking for.  Happy to help with debugging the BoTorch code if Ax does not seem like the right solution for you.

**Comment by Paeyus** [comment]
> Hi @Paeyus , is your intent just to use qNEHVI for your research or to develop novel Bayesian optimization algorithms? If it is the former, then we offer an easier to use interface to BoTorch called Ax. Ax handles normalization and includes heuristics that might improve qNEHVI performance over the baseline AF implementation (e.g., good default hyperparameters for optimizing the AF, adaptively selecting reference points in case they are infeasible). Here is an example of what the API looks like: https://ax.dev/tutorials/multiobjective_optimization.html
> 
> Let us know if this is what you are looking for. Happy to help with debugging the BoTorch code if Ax does not seem like the right solution for you.


Thank you for the response. I am working on a constrained MOO, and since qNEHVI outperforms qEHVI and EI, I want to use it in my work. I have also checked out Ax, however, I want help in debugging this code, so then I can familiarize myself with it. Thank you

**Comment by Paeyus** [comment]
> From the stack trace, the issue seems to be that you're providing the constraints in the wrong format.
> 
> * You pass in `constraints={2: [[None, 6.0]]}`.
> * Code executes `[c(samples) <= 0 for c in self.constraints], dim=0`
> * Since you provided a dict, `c in self.constraints` returns the key `2`, which is an int and not a callable, resulting in `TypeError: 'int' object is not callable`.
> 
> qNEHVI expects constraints as a list of callables. More information on this can be found in the docstring: https://github.com/pytorch/botorch/blob/main/botorch/acquisition/multi_objective/monte_carlo.py#L403-L407


@saitcakmak, thank you for your suggestion, I implemented your suggestion as follows:

                policy = qNoisyExpectedHypervolumeImprovement(
                    model=ModelListGP(model1, model2, constraint_model), 
                    ref_point=ref_point,
                    X_baseline=train_x,
                    prune_baseline=False,
                    partitioning=FastNondominatedPartitioning(ref_point, train_y),
                    constraints=[lambda samples: samples[2] <= 6.0]

but I got a different error message. 

File ~\Anaconda3\envs\Project_Battery\lib\site-packages\botorch\acquisition\multi_objective\monte_carlo.py:515, in qNoisyExpectedHypervolumeImprovement.__init__(self, model, ref_point, X_baseline, sampler, objective, constraints, X_pending, eta, prune_baseline, alpha, cache_pending, max_iep, incremental_nehvi, cache_root, **kwargs)
    510 # In the case that X_pending is not None, but there are fewer than
    511 # max_iep pending points, the box decompositions are not performed in
    512 # set_X_pending. Therefore, we need to perform a box decomposition over
    513 # f(X_baseline) here.
    514 if X_pending is None or X_pending.shape[-2] <= self._max_iep:
--> 515     self._set_cell_bounds(num_new_points=X_baseline.shape[0])
    516 # Set q_in=-1 to so that self.sampler is updated at the next forward call.
    517 self.q_in = -1

File ~\Anaconda3\envs\Project_Battery\lib\site-packages\botorch\acquisition\multi_objective\monte_carlo.py:604, in qNoisyExpectedHypervolumeImprovement._set_cell_bounds(self, num_new_points)
    602 obj = obj.view(new_batch_shape, *obj.shape[-2:])
    603 if self.constraints is not None and feas is not None:
--> 604     feas = feas.view(new_batch_shape, *feas.shape[-1:])
    606 if self.partitioning is None and not self.incremental_nehvi:
    607     self._compute_initial_hvs(obj=obj, feas=feas)

RuntimeError: shape '[128, 3]' is invalid for input of size 9

**Comment by saitcakmak** [comment]
Hi @Paeyus. The constraints should be mapping a `sample_shape x batch-shape x q x m`-dim input to a `sample_shape x batch-shape x q`-dim feasibility value. In your case, replacing `constraints=[lambda samples: samples[2] <= 6.0]` with `constraints=[lambda samples: samples[..., 2] <= 6.0]` would produce the correct shape.

In addition, for the gradient based acquisition function optimization to work well, the constraints should be differentiable. Otherwise, optimizing the acquisition function using `optimize_acqf` will not work. To get around this, we typically use a sigmoid approximation of the constraints rather than using a boolean feasible / infeasible output. A helper like this one can be used to  smoothly approximate a constraint: https://github.com/pytorch/botorch/blob/main/botorch/utils/objective.py#L122

As Eytan suggested, if you choose to use Ax for your optimization, this and many other best practices would be handled automatically for you. I'd recommend checking out https://ax.dev/tutorials/gpei_hartmann_service.html

**Comment by esantorella** [comment]
I'm closing this as it is hopefully solved, but feel free to reopen if not.

**Comment by SebastianAment** [comment]
Hi @Paeyus,

Regarding,

> using qNEHVI for constrained multiobjective optimization

The latest BoTorch release offers an improved version of `qNEHVI`, which you can use by simply replacing `qNoisyExpectedHypervolumeImprovement` with `qLogNoisyExpectedHypervolumeImprovement`, see our upcoming [NeurIPS spotlight paper](https://arxiv.org/abs/2310.20708). We recommend that you switch to the new version for your experiments, since it can significantly improve the optimization performance. Let me know if you have any questions about this!

**Comment by Paeyus** [comment]
Dear @SebastianAment, 
I tried optimizing with qLogNoisyExpectedHypervolumeImprovement as you recommended; I was able to run the code using a 1-dimensional function and achieved good results; however, I still face a bug when I run my code. I honestly could not comprehend what @saitcakmak suggested, so I would appreciate it if you could assist me with the script that will help the code run successfully. 


RuntimeError                              Traceback (most recent call last)
Cell In[11], line 24
     21 with warnings.catch_warnings():
     22     warnings.simplefilter("ignore")
---> 24     policy = qLogNoisyExpectedHypervolumeImprovement(
     25         model=ModelListGP(model1, model2, constraint_model),
     26         ref_point=ref_point,
     27         X_baseline = train_x,
     28         #partitioning=NondominatedPartitioning(ref_point, train_y, ),
     29         constraints=[lambda samples: samples[..., 2] <= 6.0])
     31 with warnings.catch_warnings():
     32     warnings.filterwarnings("ignore", category=RuntimeWarning)

File ~\Anaconda3\envs\Project_Battery\lib\site-packages\botorch\acquisition\multi_objective\logei.py:420, in qLogNoisyExpectedHypervolumeImprovement.__init__(self, model, ref_point, X_baseline, sampler, objective, constraints, X_pending, eta, prune_baseline, alpha, cache_pending, max_iep, incremental_nehvi, cache_root, tau_relu, tau_max, fat, marginalize_dim)
    411 MultiObjectiveMCAcquisitionFunction.__init__(
    412     self,
    413     model=model,
   (...)
    417     eta=eta,
    418 )
    419 SubsetIndexCachingMixin.__init__(self)
--> 420 NoisyExpectedHypervolumeMixin.__init__(
    421     self,
    422     model=model,
    423     ref_point=ref_point,
    424     X_baseline=X_baseline,
    425     sampler=sampler,
    426     objective=objective,
    427     constraints=constraints,
    428     X_pending=X_pending,
    429     prune_baseline=prune_baseline,
    430     alpha=alpha,
    431     cache_pending=cache_pending,
    432     max_iep=max_iep,
    433     incremental_nehvi=incremental_nehvi,
    434     cache_root=cache_root,
    435     marginalize_dim=marginalize_dim,
    436 )
    437 # parameters that are used by qLogEHVI
    438 self.tau_relu = tau_relu

File ~\Anaconda3\envs\Project_Battery\lib\site-packages\botorch\utils\multi_objective\hypervolume.py:644, in NoisyExpectedHypervolumeMixin.__init__(self, model, ref_point, X_baseline, sampler, objective, constraints, X_pending, prune_baseline, alpha, cache_pending, max_iep, incremental_nehvi, cache_root, marginalize_dim)
    639 # In the case that X_pending is not None, but there are fewer than
    640 # max_iep pending points, the box decompositions are not performed in
    641 # set_X_pending. Therefore, we need to perform a box decomposition over
    642 # f(X_baseline) here.
    643 if X_pending is None or X_pending.shape[-2] <= self._max_iep:
--> 644     self._set_cell_bounds(num_new_points=X_baseline.shape[0])
    646 # Set q_in=-1 to so that self.sampler is updated at the next forward call.
    647 self.q_in = -1

File ~\Anaconda3\envs\Project_Battery\lib\site-packages\botorch\utils\multi_objective\hypervolume.py:761, in NoisyExpectedHypervolumeMixin._set_cell_bounds(self, num_new_points)
    758     self.partitioning = BoxDecompositionList(*partitionings)
    759 else:
    760     # use batched partitioning
--> 761     obj = _pad_batch_pareto_frontier(
    762         Y=obj,
    763         ref_point=self.ref_point.unsqueeze(0).expand(
    764             obj.shape[0], self.ref_point.shape[-1]
    765         ),
    766         feasibility_mask=feas,
    767     )
    768     self.partitioning = self.p_class(
    769         ref_point=self.ref_point, Y=obj, **self.p_kwargs
    770     )
    771 cell_bounds = self.partitioning.get_hypercell_bounds().to(self.ref_point)

File ~\Anaconda3\envs\Project_Battery\lib\site-packages\botorch\utils\multi_objective\box_decompositions\utils.py:73, in _pad_batch_pareto_frontier(Y, ref_point, is_pareto, feasibility_mask)
     66     raise UnsupportedError(
     67         "_pad_batch_pareto_frontier only supports a single "
     68         f"batch dimension, but got {len(batch_shape)} "
     69         "batch dimensions."
     70     )
     71 if feasibility_mask is not None:
     72     # set infeasible points to be the reference point (corresponding to the batch)
---> 73     Y = torch.where(feasibility_mask.unsqueeze(-1), Y, ref_point)
     74 if not is_pareto:
     75     pareto_mask = is_non_dominated(Y)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

**Comment by saitcakmak** [comment]
@SebastianAment's comment addresses the constraint setup & differentiability issue that I mentioned in my previous comment. 

> RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

I believe this happens because you're missing an objective while constructing `qNoisyExpectedHypervolumeImprovement`. The goal of the objective here is to remove the outcomes corresponding to the constraints (so, the hypervolume can be computed over the objectives only and constraint gets applied after). Since the first two outcomes of the `ModelListGP` corresponds to the objectives, you can use `objective=IdentityMCMultiOutputObjective(outcomes=[0, 1])`. An example of this is also found in this tutorial: https://botorch.org/tutorials/constrained_multi_objective_bo

**Comment by SebastianAment** [comment]
Hi @Paeyus, were you able to resolve the issue?

**Comment by Paeyus** [comment]
Hi @SebastianAment,
Yes, I made the modifications based on your recommendation and that of @saitcakmak, but after running for first query,
I had an error as follows:

> TypeError                                 Traceback (most recent call last)

Cell In[18], line 42
     33         warnings.filterwarnings("ignore", category=RuntimeWarning)
     35         next_x, acq_val = optimize_acqf(
     36             acq_function=policy,
     37             bounds = bounds, 
     38             q=batch_size,
     39             num_restarts=100,
     40             raw_samples=500)
---> 42 next_y = train_Y(next_x)
     43 next_constraint = constraint_Y(next_x)
     45 train_x = torch.cat([train_x, next_x])

TypeError: 'Tensor' object is not callable

**Comment by SebastianAment** [comment]
Hi @Paeyus, 

This error message comes from a line of your code, `next_y = train_Y(next_x)`, and means that `train_Y` is a `Tensor`, which can't be used as a function. The code assigns `train_Y= torch.cat([train_y, next_y])`, note the mismatch between `train_y` and `train_Y` two lines below, so this is bound to happen. What you intend to do is evaluate the the objective function, whose name I can't identify in the code you shared. 

Once you get the loop to work, we strongly recommend that you switch to [`qLogNoisyExpectedHypervolumeImprovement` (`qLogNEHVI`)](https://github.com/pytorch/botorch/blob/b5b4fb7c316983f0cfb2f3257247e52c71a23b7d/botorch/acquisition/multi_objective/logei.py#L320), which has been shown to lead to substantial optimization improvements for challenging constrained problems ([NeurIPS paper](https://arxiv.org/abs/2310.20708)).

**Comment by Paeyus** [comment]
Hello @SebastianAment, 

I modified the code based on your previous comments by creating the functions as recommended. The training loop did run, but the candidates for the **next_y** and **next_constraint** are the same ones I provided.  

1. Kindly have a look at it and let me know where the mistake is. 
2. Secondly, from the look of my data, the values **train_y'**s are high, so should I scale those as opposed to the **train_x's** and at what point in the code should I do that? 

Here is the full code :
`
train_x = torch.tensor([[3., 0., 0.], [0., 0., 0.], [1., 0., 0.]]).type(torch.float64)
train_y1 = torch.tensor([17189., 10068., 11139.]).to(train_x.dtype)
train_y2 = torch.tensor([77., 4., 17.]).to(train_x.dtype)
train_cost = torch.tensor([2.5, 0., 0.]).to(train_x.dtype).unsqueeze(-1) #constraint



def objective1(x):
    train_y1 = torch.tensor([17189., 10068., 11139.]).to(train_x.dtype)
    
    return train_y1


def objective2(x):
    train_y2 = torch.tensor([77., 4., 17.]).to(train_x.dtype)
    
    return train_y2

def joint_objective(x):
    train_y = torch.vstack([y1.flatten(), y2.flatten()]).transpose(-1, -2)
    return train_y 


y1 = torch.tensor([17189., 10068., 11139.]).to(train_x.dtype)
y2 = torch.tensor([77., 4., 17.]).to(train_x.dtype)

train_y= torch.vstack([y1.flatten(), y2.flatten()]).transpose(-1, -2).cuda()


class GPModel(gpytorch.models.ExactGP, botorch.models.gpytorch.GPyTorchModel):
    _num_outputs = 1

    def __init__(self, train_x, train_y, likelihood):
        super().__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.MaternKernel(nu=2.5, ard_num_dims=train_x.shape[1])
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


def fit_gp_model(train_x, train_y, num_train_iters=500):
    # declare the GP
    noise = 1e-4

    likelihood = gpytorch.likelihoods.GaussianLikelihood().cuda()
    model = GPModel(train_x, train_y, likelihood).cuda()
    model.likelihood.noise = noise

    # train the hyperparameter (the constant)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

    model.train()
    likelihood.train()

    for i in range(num_train_iters):
        optimizer.zero_grad()

        output = model(train_x)
        loss = -mll(output, train_y)

        loss.backward()
        optimizer.step()

    model.eval()
    likelihood.eval()

    return model, likelihood


ref_point = torch.tensor([train_y[:, 0].min(), train_y[:, 1].min()]).cuda()
bounds = torch.tensor([[-10., -10., -10.], [10., 10., 10.]]).cuda()

num_queries = 50
num_repeats = 10
batch_size = 3

hypervolumes =torch.zeros((num_repeats, num_queries))

for trial in range(num_repeats):
    print("trial", trial)
    
    torch.manual_seed(trial)
    
    for i in tqdm(range(num_queries)):
        dominated_part = DominatedPartitioning(ref_point, train_y).cuda()
        hypervolumes[trial, i] = dominated_part.compute_hypervolume().item()
        
        model1, likelihood1 = fit_gp_model(train_x, train_y[:, 0].squeeze(-1))
        model2, likelihood2 = fit_gp_model(train_x, train_y[:, 1].squeeze(-1))
        
        # add the constraint
        constraint_model, constraint_likelihood = fit_gp_model(train_x, train_cost.squeeze(-1)) # change to constraint
        
        
        #if strategy == qNEHVI:
            
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")

            policy = qLogNoisyExpectedHypervolumeImprovement(
                model=ModelListGP(model1, model2, constraint_model),
                ref_point=ref_point,
                #partitioning=FastNondominatedPartitioning(ref_point, train_y),
                X_baseline = train_x,
                objective=IdentityMCMultiOutputObjective(outcomes=[0, 1]),
                constraints=[lambda samples: samples[..., 2] - 6.0])

        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", category=RuntimeWarning)

            next_x, acq_val = optimize_acqf(
                acq_function=policy,
                bounds = bounds, 
                q=batch_size,
                num_restarts=100,
                raw_samples=500)


    next_y = joint_objective(next_x)
    next_constraint = constraint_func(next_x)
    
    next_x = next_x.cuda()
    next_y = next_y.cuda()
    next_constraint =next_constraint.cuda()

    
    train_x = torch.cat([train_x, next_x])
    train_y = torch.cat([train_y, next_y])
    train_cost = torch.cat([train_cost, next_constraint])
`

**Comment by Balandat** [comment]
Hi @Paeyus, looks like you still have some misunderstandings about how to generate the new training tensors from previous and newly generated observations. This is hard to figure out without a full repro; please take a look how this is done in https://github.com/pytorch/botorch/blob/main/tutorials/closed_loop_botorch_only.ipynb (esp. the `# update training points` section)

**Comment by esantorella** [comment]
Closing as inactive, but feel free to reopen with any new questions.

**Comment by Paeyus** [comment]
Hello @Balandat,

I checked out link you sent, however, my problem is, most of the examples used pre-defined functions (i.e., Hartmann, Branin, etc.), and was used to generate random points for the training process, and also used to evaluate the new candidate points.  

But my data is experimental points which are being optimized, so how do I use the data to create the function, or which function should I used to evaluate my candidate points for the loop to run. Thank you

**Comment by Balandat** [comment]
> But my data is experimental points which are being optimized, so how do I use the data to create the function, or which function should I used to evaluate my candidate points for the loop to run. Thank you

Well in this case the "function" you have is your experimental process. So after generating a set of candidate points, you'll have to evaluate those using your experimental procedures. After you've done that you'll get the results back as the `Y`s. You don't need to write this as a python function, you can just run your experiments and then stick the data in a tensor in any way you want. 

As mentioned above, a lot of this is made easier when using Ax's Service API, see https://ax.dev/tutorials/multiobjective_optimization.html#Using-the-Service-API
