### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by DavidSiretMarques** [pytorch/botorch#2038]
# 🚀 Feature Request: Add use examples in synthetic functions

Example uses for functions in  `botorch.test_functions.synthetic`
## Motivation

**Is your feature request related to a problem? Please describe.**

I'm trying to do some benchmark testing for a project I'm working on, and I decided to understand first how the synthetic function module works and what and how it returns things. But I'm not able to do an Ackley 2-dimensional function plot. I've tried everything I can think about, giving it single values, trying with different sized tensors,... But I don't get how to use this function (or any other function in the module). 

## Pitch

**Describe the solution you'd like**

I think it would be useful for the docs to have a couple of examples for the functions in this module, with how they work and with that it would be easier to understand how to use them.

**Describe alternatives you've considered**

Alternatively, there could be a jupyter notebook where some of these functions are used, to show how they work

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))
Sure, If I can understand how the function works...

**Comment by Balandat** [comment]
I'm assuming this is resolved then?
