### ISSUE TITLE
[Bug] Optional constraints in `gen_batch_initial_conditions`

### ISSUE THREAD

**Issue by AdrianSosic** [pytorch/botorch#2042]
# 🐛 Bug

This is not a real bug but I suspect it's not desired behavior either. The function `gen_batch_initial_conditions` takes constraints in the following way:
```python
...
inequality_constraints: Optional[List[Tuple[Tensor, Tensor, float]]] = None,
equality_constraints: Optional[List[Tuple[Tensor, Tensor, float]]] = None,
...
```
and I guess most people would expect that the function should behave in the same way when passing empty constraints lists or when omitting the arguments / providing `None`s. 

However, further below in the function, there are explicit None-comparisons, i.e.
```python
...
elif inequality_constraints is None and equality_constraints is None:
...
```
which trigger different behavior when empty constraint lists or `None` are given as arguments. In particular, in the first case, `sample_q_batches_from_polytope` gets called while, in the second case, `draw_sobol_samples` is executed.

## To Reproduce

For example, use the following setup:
```python
train_X = torch.tensor([[0.0]])
train_Y = torch.tensor([[0.0]])
model = SingleTaskGP(train_X, train_Y)
qEI = qExpectedImprovement(model, best_f=0.0)
bounds = torch.tensor([[0.0], [1.0]])
```

The following calls then execute different code internally:
```python
Xinit = gen_batch_initial_conditions(
    qEI, bounds, q=3, num_restarts=25, raw_samples=500
)
Xinit = gen_batch_initial_conditions(
    qEI, bounds, q=3, num_restarts=25, raw_samples=500, equality_constraints=[]
)
```

## Expected Behavior

Both above calls of `gen_batch_initial_conditions` should trigger the same logic, namely `draw_sobol_samples` should be called, but they don't due to the above described issue.

## Potential Fix 
I guess the proper fix would be to explicitly convert the optional `None`s to empty lists at the function start and then test instead for:
```
elif not (inequality_constraints or equality_constraints):
```

**Comment by AdrianSosic** [comment]
Of course, if this is the right way to go, I'm happy to open a PR =)

**Comment by saitcakmak** [comment]
Hi @AdrianSosic. Thanks for flagging this. 
`elif not (inequality_constraints or equality_constraints):`
should work for both `None` and `[]`, so we can update the check without having to set a default value at the function start.

I'd be happy to accept a PR for this. Let's also add a comment that this block is used when there are no constraints, since the new check is somewhat more opaque than explicitly checking for None.

**Comment by AdrianSosic** [comment]
Ok, great 👍. Yes, I guess you are right, changing the if condition should suffice and no changes are needed for the variables themselves. However, I'm not entirely sure if `gen_batch_initial_conditions` is the best or rather the only place where a change like this is required. I actually stumbled upon this while working with the optimization functions (e.g. `optimize_acqf`), which have the same signature for the constraints arguments. That means, if someone would add an explicit `is None`-check to those functions in the future, you'd run into the same problem again.

One exception I saw is `optimize_acqf_discrete_local_search`, which converts the variable in the way I've suggested earlier:
```
inequality_constraints = inequality_constraints or []
```
But I don't have a perfect overview of how all these different functions and their helper play together, so I don't know which other code lines require modifications / I can't tell what is the ideal place where a conversion could be done such that it correctly propagates to all subroutines. It seems `OptimizeAcqfInputs` is one such central place!?

I will open a PR with the change you suggested and we can continue the discussion from there!

**Comment by saitcakmak** [comment]
@Balandat, @esantorella Thoughts on how to handle this more broadly? As @AdrianSosic mentions, there are other places (e.g., `OptimizeAcqfInputs.__post_init__`) where we rely on `is not None` checks when these can also be empty lists. Should we move away from using `is / is not None` & utilize the boolean value of the argument more broadly there?

**Comment by esantorella** [comment]
Interesting question. I find `not (inequality_constraints or equality_constraints)` to be pretty opaque; it won't be clear to a reader that this intentionally covers the empty-list case. But it's clearly correct so I'm happy to accept the PR. Regardless of how we specify the check, I'm glad @AdrianSosic has highlighted that this is a bad design pattern and that BoTorch is inconsistent here; even once this is fixed, a new contribution could easily make the `not None` mistake again.

Maybe we could require constraints to be lists anywhere that they're passed internally within BoTorch, while allowing `None` in user-facing functions for convenience. Then the checks should just be on `len(constraints)`.

For a bigger change, we could have a `Constraint` class with an `is_non_empty` attribute. Users could pass in either `None` or a `Constraint` instance, and BoTorch internally could require everything to be a (possibly empty) `Constraint` instance. Constraints are pretty annoying to type correctly and find documentation on , so a `Constraint` class make things clearer. It could also support common functions like checking if a point obeys the constraint. Introducing a Constraint class would be more work, but IMO it would make things clearer and harder to mess up for both users and developers.

**Comment by Balandat** [comment]
I think both of these suggestions make sense!
