### ISSUE TITLE
[Bug] Can't get a new trial following tutorial with my data.

### ISSUE THREAD

**Issue by Jgmedina95** [pytorch/botorch#2063]
# 🐛 Bug
Hello!, I wasnt intending to create an issue, but after many attempts trying to get a new trial with BoTorch and Ax, I decided to stop and ask. 

I've simplified my problem the most I can. This is the part I'm stucked right now.
Im making a "custom BOTorch model" like in the tutorials. (ignore the input_transform for now)
```
class ExactGPModel(gpytorch.models.ExactGP, GPyTorchModel):
    
    _num_outputs = 1 

    def __init__(self, train_X, train_Y,**kwargs):
        input_transform = kwargs.pop('input_transform', None)
        self._training_data = SupervisedDataset(train_X, train_Y)
        super().__init__(train_x, train_y, GaussianLikelihood(), **kwargs)
 
        self.mean_module = gpytorch.means.ConstantMean()
       # self.input_transform = input_transform

        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())
        self.to(train_x)
        
    def forward(self, x):
        #if self.input_transform is not None:
        #    x = self.input_transform(x)
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
    @classmethod
    def construct_inputs(cls, training_data: TrainingData, **kwargs):
        r"""Construct kwargs for the `SimpleCustomGP` from `TrainingData` and other options.

        Args:
            training_data: `TrainingData` container with data for single outcome
                or for multiple outcomes for batched multi-output case.
            **kwargs: None expected for this class.
        """
        return {"train_X": training_data.X, "train_Y": training_data.Y}
```

Then, I made a generation strategy with the surrogate model and acquisition function.

```
model = ExactGPModel(train_X=torch.tensor(train_features),train_Y= torch.tensor(train_final_label).reshape(-1,1))
surrogate = Surrogate.from_botorch(model=model)

gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.BOTORCH_MODULAR,
            num_trials=-1,  # No limitation on how many trials should be produced from this step
            # For `BOTORCH_MODULAR`, we pass in kwargs to specify what surrogate or acquisition function to use.
            model_kwargs={
                "surrogate":surrogate,
              
                "botorch_acqf_class": qExpectedImprovement,
                },
        ),
    ]
)
```

made my client and added some points with .add_trials. with a dataset i have:
```ax_client = AxClient(generation_strategy = gs)
ax_client.create_experiment(parameters = ax_parameters, objectives= {"f":ObjectiveProperties(minimize=False)})
#add data to ax_client
for i in range(len(modified_features)):
    ax_client.attach_trial(parameters = {ax_parameters[j]['name']: modified_features[i][j] for j in range(9)})
    ax_client.complete_trial(trial_index = i, raw_data = {"f": train_final_label[i]})
```

But whenever i try to get a new point:
```parameters, trial_index = ax_client.get_next_trial()```
I get the following error:
```
ile [~/miniforge3/envs/DOEv2/lib/python3.10/site-packages/ax/models/torch/botorch_modular/surrogate.py:158](https://file+.vscode-resource.vscode-cdn.net/Users/jorgemedina/Desktop/PhD/DOE%20/DOE/AgML/~/miniforge3/envs/DOEv2/lib/python3.10/site-packages/ax/models/torch/botorch_modular/surrogate.py:158), in Surrogate.training_data(self)
    155 @property
    156 def training_data(self) -> List[SupervisedDataset]:
    157     if self._training_data is None:
--> 158         raise ValueError(NOT_YET_FIT_MSG)
    159     return self._training_data

ValueError: Underlying BoTorch `Model` has not yet received its training_data. Please fit the model first.
```

Trying to follow the error message i did the following (based on chat gpt advice haha):

```model = ExactGPModel(train_X=torch.tensor(train_features),train_Y= torch.tensor(train_final_label).reshape(-1,1))
mll = ExactMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_model(mll)
```
But same luck. Tried to dive into the surrogate documentation and code and tried to instantiate ```surrogate._training_data ```
manually, but then i got:

```TrainingData = [SupervisedDataset(torch.tensor(modified_features)[i], torch.tensor(train_final_label).reshape(-1,1)[i]) for i in range(len(train_final_label))]  
surrogate._training_data = TrainingData
```
But then at the end i got the following error:
```
-> 479 X_obs_set = {tuple(float(x_i) for x_i in x) for x in Xs[outcome_list[0]]}
    480 for _, idx in enumerate(outcome_list, start=1):
    481     X_obs_set = X_obs_set.intersection(
    482         {tuple(float(x_i) for x_i in x) for x in Xs[idx]}
    483     )

File [~/miniforge3/envs/DOEv2/lib/python3.10/site-packages/torch/_tensor.py:990](https://file+.vscode-resource.vscode-cdn.net/Users/jorgemedina/Desktop/PhD/DOE%20/DOE/AgML/~/miniforge3/envs/DOEv2/lib/python3.10/site-packages/torch/_tensor.py:990), in Tensor.__iter__(self)
    980 def __iter__(self):
    981     # NB: we use 'imap' and not 'map' here, so that in Python 2 we get a
    982     # generator and don't eagerly perform all the indexes.  This could
   (...)
    987     # NB: We have intentionally skipped __torch_function__ dispatch here.
    988     # See gh-54457
    989     if self.dim() == 0:
--> 990         raise TypeError("iteration over a 0-d tensor")
    991     if torch._C._get_tracing_state():
    992         warnings.warn(
    993             "Iterating over a tensor might cause the trace to be incorrect. "
    994             "Passing a tensor of different shape won't change the number of "
   (...)
    998             stacklevel=2,
    999         )

TypeError: iteration over a 0-d tensor
```
And i ran out of ideas haha. I did try several approaches from the tutorials but with similar luck. This is the approach that got me closer i think. In any case, any help or advice would be enormously useful :). And sorry for the long post.

## Expected Behavior

I just want to get a new trial with a custom GP and expected improvement acquisition function. Should be straightforward as I'm just trying to stay as close to the tutorials as possible. 

## System information

**Please complete the following information:**
- 
- 
-

**Comment by saitcakmak** [comment]
Hi @Jgmedina95. The issue here is `surrogate = Surrogate.from_botorch(model=model)` part. This is a very poorly supported setup that is not really suitable for use in a BO loop. If you want to keep using `from_botorch`, you should also call `surrogate._training_data = SupervisedDataset(X=..., Y=...)` to inform the surrogate of the training data being used (this is also a bug on our end as this should be required by the API). 

In general, I'd recommend not using `from_botorch` and instead constructing your surrogate as `surrogate=Surrogate(botorch_model_class=ExactGPModel)`. This way, it'll get updated with the current data at each iteration rather than the model retaining the same data throughout, which is not something you'd want in a BO loop.

**Comment by Jgmedina95** [comment]
Hi! thank you very much for taking a look into this :). Originally I was indeed trying just with Surrogate and wasn't working. Eventually the from_botorch method got me a step further. Here is an example of what happens when I use ```surrogate=Surrogate(botorch_model_class=ExactGPModel)```. 
Is my first time trying  to 
use this framework, so I wouldn't discard that I'm making a mistake either defining the model class either. 
Im attaching a notebook with a dataset to reproduce the error :). 
[modified_features.csv](https://github.com/pytorch/botorch/files/13116607/modified_features.csv)
[reproduction_error_botorch.ipynb.json](https://github.com/pytorch/botorch/files/13116612/reproduction_error_botorch.ipynb.json)

**Comment by Jgmedina95** [comment]
Hi! already solved the problem :)  The solution is [here ](https://github.com/facebook/Ax/issues/1923)
