### ISSUE TITLE
Implementation of HeteroskedasticMixedSingleTaskGP that supports categorical variable search 

### ISSUE THREAD

**Issue by chemyibinjiang** [pytorch/botorch#2075]
# 🚀 Feature Request

Implementation of HeteroskedasticMixedSingleTaskGP that supports categorical variable search 

## Motivation

Many black-box problems are related in the search of both categorical space and continous space MixedSingleTaskGP. In the meantime, if the noise of the observations can be evaluated, this can be handled by HeteroskedasticSingleTaskGP. However, having both feature in one model seems to be missing. 

## Pitch

**Describe the solution you'd like**
Define a new class of GP models called HeteroskedasticMixedSingleTaskGP, which is an extension of HeteroskedasticSingleTaskGP to categorical space.

**Comment by saitcakmak** [comment]
Hi @chemyibinjiang. Sorry for the late response here. If you'd like to implement such a model, we'd welcome a PR under botorch_community. There are endless combinations of possible models, and implementing each one would turn BoTorch into a maintenance nightmare. For that reason, we try to avoid adding more models into core BoTorch unless we intend to use them regularly (typically through Ax).
