### ISSUE TITLE
[Bug] Multi-objective Optimization with qUCB

### ISSUE THREAD

**Issue by flysavage** [pytorch/botorch#212]
I tried to use Botorch on multi(two)-objective optimization. I used the custom acquisition function from [here](https://botorch.org/tutorials/custom_acquisition). It's working well with `joint_optimize` but not with`sequential_optimize`. You can find both [here](https://github.com/pytorch/botorch/blob/master/botorch/optim/optimize.py). And this is the error I got. I'm sorry I couldn't share my code here.

** Stack trace/error message **
```
~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/botorch/optim/optimize.py in sequential_optimize(acq_function, bounds, q, num_restarts, raw_samples, options, inequality_constraints, equality_constraints, fixed_features, post_processing_func)
     79             inequality_constraints=inequality_constraints,
     80             equality_constraints=equality_constraints,
---> 81             fixed_features=fixed_features,
     82         )
     83         if post_processing_func is not None:

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/botorch/optim/optimize.py in joint_optimize(acq_function, bounds, q, num_restarts, raw_samples, options, inequality_constraints, equality_constraints, fixed_features, post_processing_func)
    150         num_restarts=num_restarts,
    151         raw_samples=raw_samples,
--> 152         options=options,
    153     )
    154     batch_limit = options.get("batch_limit", num_restarts)

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/botorch/optim/optimize.py in gen_batch_initial_conditions(acq_function, bounds, q, num_restarts, raw_samples, options)
    247                 while start_idx < X_rnd.shape[0]:
    248                     end_idx = min(start_idx + batch_limit, X_rnd.shape[0])
--> 249                     Y_rnd_curr = acq_function(X_rnd[start_idx:end_idx])
    250                     Y_rnd_list.append(Y_rnd_curr)
    251                     start_idx += batch_limit

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/botorch/utils/transforms.py in decorated(cls, X)
    126                 )
    127             X = X if X.dim() > 2 else X.unsqueeze(0)
--> 128             return method(cls, X)
    129 
    130         return decorated

~/Desktop/code/bo-benchmarks/mc_acqf.py in forward(self, X)
     46         # o: output dimensions
     47         posterior = self.model.posterior(X)
---> 48         samples = self.sampler(posterior)  # n x b x q x o
     49         scalarized_samples = samples.matmul(self.weights)  # n x b x q
     50         mean = posterior.mean  # b x q x o

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/botorch/sampling/samplers.py in forward(self, posterior)
     53         self._construct_base_samples(posterior=posterior, shape=base_sample_shape)
     54         samples = posterior.rsample(
---> 55             sample_shape=self.sample_shape, base_samples=self.base_samples
     56         )
     57         return samples

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/botorch/posteriors/gpytorch.py in rsample(self, sample_shape, base_samples)
     78         with gpytorch.settings.fast_computations(covar_root_decomposition=False):
     79             samples = self.mvn.rsample(
---> 80                 sample_shape=sample_shape, base_samples=base_samples
     81             )
     82         # make sure there always is an output dimension

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/gpytorch/distributions/multitask_multivariate_normal.py in rsample(self, sample_shape, base_samples)
    113             base_samples = base_samples.view(*sample_shape, *self.loc.shape)
    114 
--> 115         samples = super().rsample(sample_shape=sample_shape, base_samples=base_samples)
    116         if not self._interleaved:
    117             # flip shape of last two dimensions

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/gpytorch/distributions/multivariate_normal.py in rsample(self, sample_shape, base_samples)
    158 
    159             # Now reparameterize those base samples
--> 160             covar_root = covar.root_decomposition().root
    161             # If necessary, adjust base_samples for rank of root decomposition
    162             if covar_root.shape[-1] < base_samples.shape[-2]:

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/gpytorch/utils/memoize.py in g(self, *args, **kwargs)
     32         cache_name = name if name is not None else method
     33         if not is_in_cache(self, cache_name):
---> 34             add_to_cache(self, cache_name, method(self, *args, **kwargs))
     35         return get_from_cache(self, cache_name)
     36 

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/gpytorch/lazy/lazy_tensor.py in root_decomposition(self)
   1320                 )
   1321 
-> 1322         res = self._root_decomposition()
   1323         return RootLazyTensor(res)
   1324 

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/gpytorch/lazy/block_diag_lazy_tensor.py in _root_decomposition(self)
     65 
     66     def _root_decomposition(self):
---> 67         return self.__class__(self.base_lazy_tensor._root_decomposition())
     68 
     69     def _root_inv_decomposition(self, initial_vectors=None):

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/gpytorch/lazy/lazy_tensor.py in _root_decomposition(self)
    577             batch_shape=self.batch_shape,
    578             matrix_shape=self.matrix_shape,
--> 579         )(*self.representation())
    580         return res
    581 

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/gpytorch/functions/_root_decomposition.py in forward(self, *matrix_args)
     51             matrix_shape=self.matrix_shape,
     52             batch_shape=self.batch_shape,
---> 53             init_vecs=self.initial_vectors,
     54         )
     55 

~/.local/share/virtualenvs/bo-benchmarks-uT2BAiPg/lib/python3.6/site-packages/gpytorch/utils/lanczos.py in lanczos_tridiag(matmul_closure, max_iter, dtype, device, matrix_shape, batch_shape, init_vecs, num_init_vecs, tol)
     80     # Copy over alpha_0 and beta_0 to t_mat
     81     t_mat[0, 0].copy_(alpha_0)
---> 82     t_mat[0, 1].copy_(beta_0)
     83     t_mat[1, 0].copy_(beta_0)
     84 

IndexError: index 1 is out of bounds for dimension 1 with size 1
```

## System information

**Please complete the following information:**
- botorch==0.1.2
- gpytorch==0.3.4
- torch==1.1.0
- MacOS 10.14.5

**Comment by Balandat** [comment]
Thanks for reporting this, I'll take a look at what's going on here. 

FWIW, if you're interested in this particular acquisition function, #210 will add some general utilities to make it much simpler to use.

**Comment by Balandat** [comment]
As an aside, the need for two different functions `joint_optimize` and `sequential_optimize` isn't super clear to me. I'm thinking of soft-deprecating these and add a single `optimize` function that takes a `sequential` kwarg to select the behavior.

**Comment by flysavage** [comment]
@Balandat I'm sorry I didn't make it clear. So I used `joint_optimize` when I generated new candidates at first and it worked well. And then I saw facebook-ax used `sequential_optimize` to generate new candidates so I just wanted to give it a try but I got this error.

**Comment by Balandat** [comment]
I see - so this is only an issue with the analytic version `ScalarizedUpperConfidenceBound`, the Monte-Carlo based `qScalarizedUpperConfidenceBound` should work fine with `sequential_optimize`.

The issue with `joint_optimize` is that for all but the first step it requires conditioning on the candidates generated in the optimization step. This is relatively straightforward to support for the MC-based acquisition functions, but less straightforward to do for the analytic ones (it will require "fantasizing"). If you're curious, you can take a look at how `NoisyExpectedImprovement` does this [here](https://github.com/pytorch/botorch/blob/a8d90cce54b44760fd06515c6b1fdb99cf0c0588/botorch/acquisition/analytic.py#L426). 

I'm curious about the error you're getting though, if I use `joint_optimize` I get the following (which is what should happen):
```
AttributeError: 'ScalarizedUpperConfidenceBound' object has no attribute 'X_pending'
```

Adding generic support for analytic acquisition functions in `joint_optimize` is a little challenging, so we haven't added it so far. But it's something we may consider doing in the future. 

Typically, we've found the joint optimization to perform equally as well as the sequential one in terms of closed-loop performance, at least for smaller problems. If you have high-dimensional features and a large batch size `q`, then the resulting optimization problem can become pretty large and yield suboptimal solutions, in which case one may prefer `sequential_optimize`.

If you're dealing with larger-scale problems, be sure also to use a recent version that includes #207 (see related discussion [here](https://github.com/pytorch/botorch/issues/209#issuecomment-511479389))

**Comment by Balandat** [comment]
FWIW, if the issue is that running this through Ax as suggested at the end of the tutorial fails, I can discuss that in the code. You can use the default Ax generation by forcing it to use `joint_optimize`. You can do that by adding it as an `optimizer_kwarg` to `model_gen_options`, i.e. 

```
model_gen_options = {"optimizer_kwargs" {"joint_optimization": True, ...}, ...}
```

and then use this in the Ax `.gen()` call.

**Comment by flysavage** [comment]
@Balandat Thanks for the informative reply! The acquisition function I used in Botorch is `qScalarizedUpperConfidenceBound` but I got this error when I used `sequential_optimize`. I haven't tried Ax because botroch has more flexibility. I just took a look at the code of Ax and I saw it used `sequential_optimize ` so I would like to give it a try. I didn't change anything else when I replaced `joint_optimize` to `sequential_optimize`, even the parameters of `sequential_optimize` I used are as same as `joint_optimize`. I also dig into it a little bit more and I found that it didn't use `lanczos_tridiag` at all when I used `joint_optimize`. If I used `sequential_optimize`, it used `lanczos_tridiag` after 20 steps and I saw this error once it started to use `lanczos_tridiag`.

**Comment by Balandat** [comment]
> I also dig into it a little bit more and I found that it didn't use lanczos_tridiag at all when I used joint_optimize. If I used sequential_optimize, it used lanczos_tridiag after 20 steps and I saw this error once it started to use lanczos_tridiag.

Interesting. This must be related to the automatic switching from Cholesky to Lanczos approximate root decomposition as the problem grows with the number of pending candidates. This is performed during posterior sampling. The relevant code should be here: https://github.com/cornellius-gp/gpytorch/blob/338d93fdc829ff27f03bbfa3c83f7066f16b95a7/gpytorch/lazy/lazy_tensor.py#L1309-L1323

You can override using Lanczos by running things in the contextmanager `with gpytorch.settings.fast_computations(covar_root_decomposition=False)`.

The better thing to do would be to understand why this is failing on the gpytorch side - this is pretty deep in the stack, maybe @jacobrgardner or @gpleiss have a better idea.

**Comment by Balandat** [comment]
@flysavage, there have been some recent fixes on both the botorch and gpytorch side. Does this issue persists if you run the most recent master of both? Note that `joint_optimize` and `sequential_optimize` have recently been consolidated into one in #235

**Comment by flysavage** [comment]
@Balandat it works! Thanks so much for your prompt response! Really appreciate it!

**Comment by Tenoke** [comment]
I'm also getting (as of right now)
` index 1 is out of bounds for dimension 1 with size 1` with the latest masters when attempting to use `qUCB` with `q=1` in `joint_optimize`.

```
 acq_function = qUpperConfidenceBound(model, beta=0.1)
 n_candidates=1
 candidates = joint_optimize(
        acq_function, bounds=bounds, q=n_candidates, num_restarts=15, raw_samples=40,
  )
```
and I get

```
/usr/local/lib/python3.6/dist-packages/gpytorch/utils/lanczos.py in lanczos_tridiag(matmul_closure, max_iter, dtype, device, matrix_shape, batch_shape, init_vecs, num_init_vecs, tol)
     80     # Copy over alpha_0 and beta_0 to t_mat
     81     t_mat[0, 0].copy_(alpha_0)
---> 82     t_mat[0, 1].copy_(beta_0)
     83     t_mat[1, 0].copy_(beta_0)
     84 

IndexError: index 1 is out of bounds for dimension 1 with size 1
```

**Comment by Balandat** [comment]
@Tenoke, can you see if using https://github.com/cornellius-gp/gpytorch/pull/845 fixes this issue?

My suspicion is that this is caused by the Cholesky decomposition in gpytorch not properly dealing with numerical inaccuracies for scalar "matrices".  For `q>1` (and reasonably small) gpytorch performs the root decomposition of the posterior covariance, adding jitter if this is almost singular. For `q=1` the posterior is just a univariate Gaussian (so assuming you don't use an objective or pending points you probably want to use the analytic version `UpperConfidenceBound`, but that's an aside). In certain cases the code path evaluates the sqrt of a `DiagLazyTensor`, which can produce nans if the the posterior variance is zero, but its numerical value is slightly negative.

The PR above fixes that behavior, so there is hope it will fix your issue...
