### ISSUE TITLE
Acquisition function for a multitask multioutput GP 

### ISSUE THREAD

**Issue by hajar-el** [pytorch/botorch#2138]
Hello everyone, 

I am new to botorch, and I am running a multitask multioutput GP (number of tasks is 5). For this purpose, I first build a multitask multioutput GP using MultitaskGPModel as below,

```

class MultitaskGPModel(gpytorch.models.ExactGP):
    num_outputs=5
    def __init__(self, train_x, train_y, likelihood):
        super(MultitaskGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.MultitaskMean(
            gpytorch.means.ConstantMean(), num_tasks=5
        )
        self.covar_module = gpytorch.kernels.MultitaskKernel(
            gpytorch.kernels.RBFKernel(), num_tasks=5, rank=1
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultitaskMultivariateNormal(mean_x, covar_x)
likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(num_tasks=5)
model = MultitaskGPModel(train_x, train_y, likelihood)

```

 Then, I want to build an acquisition function over the GP model. For this purpose,  I do some scalarization of the outcome by passing an Objective into the acquisition function constructor as suggested in this post [https://github.com/pytorch/botorch/issues/325]

```
from botorch.acquisition.objective import LinearMCObjective
 from botorch.acquisition import qNoisyExpectedImprovement

 mt_obj = LinearMCObjective(weights=torch.tensor([1, 1,1,1,1]))
 qNEI = qNoisyExpectedImprovement(model=model, X_baseline=train_x, objective=mt_obj)

```
However, I get the following error

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1693             if name in modules:
   1694                 return modules[name]
-> 1695         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
   1696 
   1697     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'MultitaskGPModel' object has no attribute 'posterior'

I am wondering how can I construct an acquisition function correctly, in this case? 

Thank you very much for your help

**Comment by eytan** [comment]
This is because you need to use a BoTorch model that implements posterior,
rather than use the GPyTorch model directly. In BoTorch I believe you want
to use
botorch.models.multitask.MultiTaskGP

See
https://botorch.org/docs/models#multi-task-gps for a more complete list of
multi task models. Note that if the assumption that lengthscales are the
same across tasks (the ICM kernel) is incorrect you could get negative
transfer. So if you want to use a more vanilla multi output GP ModelListGP
is your best bet.

E

**Comment by hajar-el** [comment]
Dear Eytan, 
Thank you very much for your prompt reply. I followed your suggestion and I am now using MultiTaskGP from botorch.models.multitask which solved my problem. Thank you again.
