### ISSUE TITLE
Batch with 'q' not declared as 'int' fails sometimes

### ISSUE THREAD

**Issue by jakobzeitler** [pytorch/botorch#2139]
Hi guys,

Put together a simple batch BO closed pipeline, when I at times would get an error:

> batch_size=3.0
  Traceback (most recent call last):
    File "/Users/jakobzeitler/MatterhornStudioLocalDev/MatterhornStudioFlow-BoTorch/modules/fetch_dataset/resources/usr/bin/fetch-dataset.py", line 119, in <module>
      candidates, acq_value = optimize_acqf(
    File "/opt/conda/lib/python3.10/site-packages/botorch/optim/optimize.py", line 563, in optimize_acqf
      return _optimize_acqf(opt_acqf_inputs)
    File "/opt/conda/lib/python3.10/site-packages/botorch/optim/optimize.py", line 584, in _optimize_acqf
      return _optimize_acqf_batch(opt_inputs=opt_inputs)
    File "/opt/conda/lib/python3.10/site-packages/botorch/optim/optimize.py", line 274, in _optimize_acqf_batch
      batch_initial_conditions = opt_inputs.get_ic_generator()(
    File "/opt/conda/lib/python3.10/site-packages/botorch/optim/initializers.py", line 356, in gen_batch_initial_conditions
      X_rnd = draw_sobol_samples(bounds=bounds_cpu, n=n, q=q, seed=seed)
    File "/opt/conda/lib/python3.10/site-packages/botorch/utils/sampling.py", line 96, in draw_sobol_samples
      sobol_engine = SobolEngine(q * d, scramble=True, seed=seed)
    File "/opt/conda/lib/python3.10/site-packages/torch/quasirandom.py", line 59, in __init__
      self.sobolstate = torch.zeros(dimension, self.MAXBIT, device=cpu, dtype=torch.long)
  TypeError: zeros() received an invalid combination of arguments - got (float, int, dtype=torch.dtype, device=torch.device), but expected one of:
   * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
   * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

Since, I have identified that I was passing 'q' as a float, assuming it'd be converted to int at some point.

Turns out it's not and so at times breaks the following line:

https://github.com/pytorch/botorch/blob/449b91180f8b0bd97775fa1f8a1df00e77dfe403/botorch/utils/sampling.p
y#L96

Apologies for brevity, it's quite possible I am overlooking something here as well.

I am also aware that documentation clearly specifies 'q' as 'int' in 'optimize_acqf', but less careful users might input a float and get confused by the randomly occurring error message. (I have no clue why it would only break sometimes).

Thanks!

**Comment by Balandat** [comment]
Thanks for flagging. I'm not sure why this would only sometimes occur - this seems like it should always cause issues?

That said, the error that is raised does point out that this is this being an issue with a `float` being passed instead of an `int` and so provides reasonably useful debug info. This is also the first time I've seen this issue come up so at least for now I'm inclined to not add a bunch of runtime type checking at higher levels to handle this (doing this manually for all kinds of similar things could easily get out of hand)

**Comment by jakobzeitler** [comment]
Yup, that makes sense. I am essentially just recording it for others making the same mistake in the future. :)

In regards to why this happens only some of the time, I have absolutely no clue. I looked through the trace for possible stochastic lines, but as you said, either it should break all the time or never. 

A debug for another time. :)
