### ISSUE TITLE
Transfer of Bayesian Optimization

### ISSUE THREAD

**Issue by hajar-el** [pytorch/botorch#2147]
Hello everyone, 

I would like to use Bayesian Optimization to improve the optimization of a newly observed target task by reusing knowledge from other tasks. In fact, I would like to solve $max_x f_target(x)$ by leveraging information from two other tasks $f_1(x)$ and $f_2(x)$.

I have dataset for each of these two tasks, that consists of the input features  (of dimension 10*2 for task1 and 20*2 for task2) and their corresponding noisy observations of  $f_1(x)$ and $f_2(x)$.

I also have a dataset of the target task that consists of the input features (of dimension 5*2) and their corresponding noisy observations of  $f_target(x)$.

I use Botch to infer the optimum of f_target however I am not sure I do it in the right way. Could you please check my code below and confirm whether I do it correctly? 

General idea of the code: 

1- First, I create the datasets of the three tasks and concatenate them
2- I create the multitask GP using model = MultiTaskGP(train_X, train_Y, task_feature=-2) . A question here, what is “task_feature” used for? 
3- I train the multitask GP over the 3 tasks
4- I use an acquisition function for select the next evaluation point
5- I augment my dataset and reiterate from 2. 

Code: 
```

from botorch.acquisition.objective import LinearMCObjective
from botorch.acquisition import qNoisyExpectedImprovement
from botorch.models.multitask import MultiTaskGP
from botorch.optim import optimize_acqf
import torch
import gpytorch
import numpy as np


# function f1
def f_1(X):
  return torch.cos(X[:,0])+torch.sin(X[:,1])+0.1*torch.randn(X.shape[0])

# function f2
def f_2(X):
  return 2*torch.sin(X[:,0])+torch.sin(X[:,1])+0.1*torch.randn(X.shape[0])

# function ftarget
def f_target(X):
  return torch.cos(X[:,0])+2*torch.cos(X[:,1])+0.1*torch.randn(X.shape[0])

#training dataset
X1, X2 = torch.rand(10, 2), torch.rand(20, 2) # trainingX for task1
Xtarget= torch.rand(5, 2) # trainingX for taskTarget

i1, i2, i3 = torch.zeros(X1.shape[0], 1), torch.ones(X2.shape[0], 1), 3*torch.ones(Xtarget.shape[0], 1)# column tasks indices including the target

train_X = torch.cat([torch.cat([X1, i1], -1), torch.cat([X2, i2], -1),torch.cat([Xtarget, i3], -1)]) 
train_Y = torch.cat([f_1(X1), f_2(X2),f_target(Xtarget)]).unsqueeze(-1)


#Create the multitask GP model

model = MultiTaskGP(train_X, train_Y, task_feature=-2)
likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(num_tasks=3)

#Train the model
model.train()
likelihood.train()
mll = gpytorch.mlls.ExactMarginalLogLikelihood(model.likelihood, model)
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)  # Includes GaussianLikelihood parameters

training_iterations=10
for i in range(training_iterations):
    optimizer.zero_grad()
    output = model(train_X)
    loss = -mll(output, train_Y[:,0])
    loss.backward()
    print('Iter %d/%d - Loss: %.3f' % (i + 1, training_iterations, loss.item()))
    optimizer.step()

bounds = torch.stack([torch.zeros(3), torch.ones(3)])#This will be used for the acquisition function

BestSoFar=[]
Bayesian_iterations=10
for t in range(Bayesian_iterations):
 # Use acquisition function to find the optimum
   mt_obj = LinearMCObjective(weights=torch.tensor([1]))
   qNEI = qNoisyExpectedImprovement(model=model, X_baseline=train_X, objective=mt_obj)
   candidate, acq_value = optimize_acqf(
    qNEI, bounds=bounds, q=5, num_restarts=5, raw_samples=2000,
  )

   new_y=f_target(candidate[0:2])

   ind=np.argmax(new_y)
   BestCandidate=candidate[ind]
   BestNew_y=new_y[ind]

   train_X = torch.cat([train_X,BestCandidate.reshape([1,train_X.shape[1]]),])
   train_Y = torch.cat([train_Y, BestNew_y.reshape([1,train_Y.shape[1]]),])

   model = MultiTaskGP(train_X, train_Y, task_feature=-2)
   model.train()
   likelihood.train()
   mll = gpytorch.mlls.ExactMarginalLogLikelihood(model.likelihood, model)
   optimizer = torch.optim.Adam(model.parameters(), lr=0.1)  # Includes GaussianLikelihood parameters

   for i in range(training_iterations):
     optimizer.zero_grad()
     output = model(train_X)
     loss = -mll(output, train_Y[:,0])
     loss.backward()
     print('Iter %d/%d - Loss: %.3f' % (i + 1, training_iterations, loss.item()))
     optimizer.step()
   BestSoFar.append(train_Y.max())

```

**Comment by Balandat** [comment]
Hi @hajar-el, at a high level this seems correct. The only issue I see is how you set up the `MultiTaskGP` model. First, your `task_feature` should be `-1` and not `-1` - to answer your question, this is the column index corresponding to the task identifier (0,1, 3 <- not sure why 3 and not 2 btw). The other thing you'll want to do is to set `output_tasks=[2]` - assuming 2 is the index corresponding to your target task - doing so makes the model only return a single output and so you can use the standard acquisition functions without having to define an objective. 

Finally, is there a reason you're using Adam to optimize the model parameters? Unless it's a very complex model (e.g. with NN components or the like) using `fit_gpytorch_mll` should yield better / more robust results.

**Comment by hajar-el** [comment]
Hi @Balandat , thank you very much for your reply, I truly appreciate it. I have a question though, why the task_feature should be -1? If it corresponds to the column of the target task then it should be 2, right ?(and yes, I agree, I should change the target task identifier to 2 instead of 3, thank you). 
Thank you also for suggesting to use fit_gptorch_mll, indeed I am planning to change the model and use a kernel with NN. 

Many thanks again!

**Comment by hajar-el** [comment]
@eytan , Thank you very much Eytan, I will check it out! Very kind of you!

**Comment by Balandat** [comment]
> I have a question though, why the task_feature should be -1? If it corresponds to the column of the target task then it should be 2, right 

2 is correct, yes. But you can also use negative indexing to select the last column (which is equivalent to using 2).

**Comment by hajar-el** [comment]
That makes sense :), thank you!
