### ISSUE TITLE
Input transforms in posterior call of `MultiTaskGPytorchModel`

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#2232]
In the posterior call of the `MultiTaskGPytorchModel`, the task feature is identified on the untransformed input and then the input is transformed based on the registered input transforms. https://github.com/pytorch/botorch/blob/bdd370817165a4716a6b3df1a312859823a9e8ab/botorch/models/gpytorch.py#L805

Would it be possible to apply the transforms before actually identifying the task feature? 

The usecase is the following: we had the idea encode the task feature as kind of a categorical feature which is one-hot encoded and then apply a OneHotToNumeric transform to map it back to an integer. What do you think?

**Comment by saitcakmak** [comment]
Hi @jduerholt. I think the main reason it is done this way is that the transforms are typically configured to work with `X_full` that includes the task feature. This makes the transform applicable to both `train_X` in `__init__` and `X_full` in `posterior`, both of which include the task feature.

We could change this to support your use case but it'd require some care to make sure we don't break anything unintentionally. We might need to require the transforms like `Normalize` to specify `indices` to have them applicable to both `X` with & without task features.

**Comment by jduerholt** [comment]
Hi @saitcakmak,

thanks for your quick response and sorry for my late one ;) I think it will create to much overhead to change this in existing workflows due to the need to reconfigure other transforms, so we will fix it on our side and use directly an ordinal encoding of the task parameter. It will not be too much effort.

Best,

Johannes
