### ISSUE TITLE
How to optimize a custom function for BoTorch

### ISSUE THREAD

**Issue by trudramukerji14** [pytorch/botorch#2239]
If you are submitting a bug report or feature request, please use the respective
issue template.

## Issue description

Hello all, 

I've been following the tutorial [Using a custom BoTorch model with Ax](https://botorch.org/tutorials/custom_botorch_model_in_ax)

This tutorial uses a import of the Branin function available [here](https://github.com/pytorch/botorch/blob/main/botorch/test_functions/base.py)

I want to instead define the Branin function or any function manually, for example, one could set 

`
def branin(parameterization, *args): 
    x1, x2 = parameterization["x1"], parameterization["x2"]
    y = (x2 - 5.1 / (4 * np.pi ** 2) * x1 ** 2 + 5 * x1 / np.pi - 6) ** 2
    y += 10 * (1 - 1 / (8 * np.pi)) * np.cos(x1) + 10
    # let's add some synthetic observation noise
    y += random.normalvariate(0, 0.1)
    return {"branin": (y, 0.0)}
`

but I'm unsure of how to create an experiment from here. Feel free to direct me to any reference.

**Comment by Balandat** [comment]
All you need to do is to implement the `evaluate()` function (Ax doesn't care what happens there - it is indeed black box optimization). In your case this could be as simple as
```
def evaluate(parameters):
    x1, x2 = parameterization["x1"], parameterization["x2"]
    y = (x2 - 5.1 / (4 * np.pi ** 2) * x1 ** 2 + 5 * x1 / np.pi - 6) ** 2 y += 10 * (1 - 1 / (8 * np.pi)) * np.cos(x1) + 10
    # let's add some synthetic observation noise
    noise_std = 0.1
    y += random.normalvariate(0, noise_std)
    return {"branin": (y, noise_std)}
```

Here I am returning a known `noise_std` - but you can also return `NaN` or `None` in which case the model would infer the noise level. Other than that the setup for the experiment would be exactly the same. 

Hope that helps!

**Comment by trudramukerji14** [comment]
This worked thank you!
