### ISSUE TITLE
[Bug] versions are not numerical order in docs

### ISSUE THREAD

**Issue by nzw0301** [pytorch/botorch#2256]
# 🐛 Bug

https://botorch.org/versions says the latest stable version is 0.9.5, but I think the actual latest stable version is 0.10.0, which is above 0.1.4 on the list. I think the current versions are ordered by string representations. 

## Expected Behavior

0.10.0 should be the latest stable instead of 0.9.5.

## System information

**Please complete the following information:**
-  0.10.0
-  NA
-  NA
-  latest stable MacOS and Google Chrome

**Comment by nzw0301** [comment]
I'm not familiar with javascript at all, but https://github.com/pytorch/botorch/blob/1a8b4ea1b0a613d3e9e1d8ee9f531da54c56727f/scripts/versions.js#L19 looks related logic to this issue.

**Comment by Balandat** [comment]
Ugh good catch, thanks for flagging this.

**Comment by Balandat** [comment]
Landed the forward looking fix in #2257

Performed a manual update of the `gh-pages` branch to fix the sorting: https://github.com/pytorch/botorch/commit/026f246dec57c5acc0366c74927fb01f0d8af83c
