### ISSUE TITLE
ubuntu conda 

### ISSUE THREAD

**Issue by yiyinying** [pytorch/botorch#226]
ubuntu 19.04,python 3.7.3 ,is use conda.
pytorch 1.2.0,botorch is not install.

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package ncurses conflicts for:
botorch -> ncurses[version='>=6.1,<7.0a0']
python=3.7 -> ncurses[version='>=6.1,<6.2.0a0|>=6.1,<7.0a0']
Package openssl conflicts for:
botorch -> openssl[version='>=1.1.1b,<1.1.2a']
python=3.7 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a']
Package bzip2 conflicts for:
python=3.7 -> bzip2[version='>=1.0.6,<2.0a0']
Package pip conflicts for:
python=3.7 -> pip
Package tk conflicts for:
python=3.7 -> tk[version='>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
botorch -> tk[version='>=8.6.8,<8.7.0a0']
Package pytorch conflicts for:
botorch -> pytorch[version='>=1.1']
Package libffi conflicts for:
botorch -> libffi[version='>=3.2.1,<4.0a0']
python=3.7 -> libffi[version='>=3.2.1,<3.3.0a0|>=3.2.1,<4.0a0']
Package sqlite conflicts for:
python=3.7 -> sqlite[version='>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0']
botorch -> sqlite[version='>=3.28.0,<4.0a0']
Package xz conflicts for:
python=3.7 -> xz[version='>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0']
botorch -> xz[version='>=5.2.4,<6.0a0']
Package libedit conflicts for:
botorch -> libedit[version='>=3.1.20181209,<3.2.0a0']
Package readline conflicts for:
python=3.7 -> readline[version='>=7.0,<8.0a0|>=8.0,<9.0a0']
botorch -> readline[version='>=7.0,<8.0a0']
Package scipy conflicts for:
botorch -> scipy
Package libstdcxx-ng conflicts for:
python=3.7 -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
Package zlib conflicts for:
botorch -> zlib[version='>=1.2.11,<1.3.0a0']
python=3.7 -> zlib[version='>=1.2.11,<1.3.0a0']
Package libgcc-ng conflicts for:
python=3.7 -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
Package gpytorch conflicts for:
botorch -> gpytorch[version='>=0.3.2|>=0.3.3|>=0.3.4']

**Comment by Balandat** [comment]
Not quite sure what that means exactly (can't actually spot any conflicts skimming over the above). Likely related to https://github.com/pytorch/botorch/pull/225#issuecomment-519931090 though, should be fixed by a new release.

**Comment by yiyinying** [comment]
thanks

**Comment by yiyinying** [comment]
I use python 3.6, pytorch 1.1 is the same

**Comment by Balandat** [comment]
@yiyinying, I ran into the same problem on Ubuntu. It seems that installing gpytorch explicitly first solves the issue: 

```
conda create --name botorch_virign
conda install -c gpytorch gpytorch
conda install -c pytorch botorch
```

Not quite sure what's going on there, the botorch install works fine on OSX. We'll make sure to fix this in the upcoming compatibility release, for now the above workaround should unblock you.

**Comment by Balandat** [comment]
Also, installing via `conda install -c pytorch -c gpytorch botorch` works for me. Seems like some kind of channel issue with conda, will look into it.

**Comment by yiyinying** [comment]
It seems like this, the installation is successful.

**Comment by mfeurer** [comment]
I also ran into an issue regarding the installation of botorch on conda which appears to be related. I tried to run the command on botorch.org and ran into the following issue:
```
feurerm@mllap04:~/sync_dir/projects/smac3/dist$ conda install botorch -c pytorch
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - botorch
  - gpytorch[version='>=0.3.3']

Current channels:

  - https://conda.anaconda.org/pytorch/linux-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
and I also had to install gpytorch manually before I could install botorch via the given command.

It turns out that gpytorch is not available in the pytorch channel. 

It would be great if you could fix this by either adding gpytorch to the pytorch channel or by updating the installation instructions on botorch.org.

**Comment by Balandat** [comment]
Thanks for pointing this out. I'll update the install instructions.

**Comment by Balandat** [comment]
Instructions are now updated. The bot will push a new version of the website over night - you'll need to select "latest" version rather than "stable" to see the changes.

**Comment by Aya-S** [comment]
can someone help me decipher this as well, please?
```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package sqlite conflicts for:
python=2.7 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0']
Package tensorflow-base conflicts for:
tensorflow=1.7.0 -> tensorflow-base==1.7.0
Package tensorboard conflicts for:
tensorflow=1.7.0 -> tensorboard[version='>=1.7.0,<1.8.0']
Package pip conflicts for:
python=2.7 -> pip
Package libstdcxx-ng conflicts for:
python=2.7 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
Package six conflicts for:
keras=2.1.5 -> six[version='>=1.9.0']
Package ncurses conflicts for:
python=2.7 -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0']
Package tk conflicts for:
python=2.7 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package tensorflow conflicts for:
keras=2.1.5 -> tensorflow
Package numpy conflicts for:
keras=2.1.5 -> numpy[version='>=1.9.1']
Package wheel conflicts for:
pip -> wheel
Package python conflicts for:
pip -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
keras=2.1.5 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
Package ca-certificates conflicts for:
python=2.7 -> ca-certificates
Package scipy conflicts for:
keras=2.1.5 -> scipy[version='>=0.14']
Package libffi conflicts for:
python=2.7 -> libffi[version='3.2.*|>=3.2.1,<4.0a0']
Package readline conflicts for:
python=2.7 -> readline[version='7.*|>=7.0,<8.0a0']
Package pyyaml conflicts for:
keras=2.1.5 -> pyyaml
Package zlib conflicts for:
python=2.7 -> zlib[version='>=1.2.11,<1.3.0a0']
Package openssl conflicts for:
python=2.7 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
Package libgcc-ng conflicts for:
python=2.7 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
Package setuptools conflicts for:
pip -> setuptools
Package h5py conflicts for:
keras=2.1.5 -> h5py

```

I'm trying to create a new environment using this file :
```
name: wikimedia-env
channels:
- defaults
dependencies:
- python=2.7
- keras=2.1.5
- tensorflow=1.7.0
- pip:
  - scikit-learn==0.18.1
```
