### ISSUE TITLE
[Feature Request] [Question] Bayesian optimization for sparse structured data with prior information on features

### ISSUE THREAD

**Issue by Kh-im** [pytorch/botorch#2284]
# 🚀 [Help]

Hello everyone, when using bayesian optimization for high dimensional structured sparse data, it seems difficult to obtain good proposition from EI. Here is an example of the sparse structured data (YX is the objective value, FX is a feature (an input) .

```
          F0   F1  F2  F3  ..  FX   
Y0      0    0.2   0.2 0      0
Y1      0.1 0      0    0.5   0
Y2      0    0      0    0      0.1  
Y3      0    0      0    0.2   0
```

The first idea is : There are a lot of 0. 
The second idea is : you have prior information on the similarity between features. Example, F0 is defined by for example 4 values (B0_0, B0_1, B0_2, B0_3) and if BX values are similar between F0 and F1, the impact of F0 and F1 on the  objective will be similar Y0(F0=0.1)~Y1(F1=0.1). 

I was thinking of Latent space bayesian optimization. What are your thoughts on this ?

Thanks a lot to BoTorch team. 
Regards,

**Comment by SebastianAment** [comment]
Hi @Kh-im,

> it seems difficult to obtain good proposition from EI

Could you elaborate on what problem you are running into specifically? Are you trying to attain a proposal that is sparse itself? 

> The second idea is 

If all your features `F` are actually functions of `B`, why not just parameterize the entire optimization problem with `B` to begin with? I.e. run the optimization on `reparameterized_objective(B1, B2, B3, B4) = objective(F1(B1, ..., B4), F2(B1, ..., B4), ..., FD(B1, ..., B4))`?

**Comment by esantorella** [comment]
Closing as inactive, but feel free to reopen if needed.
