### ISSUE TITLE
Problems regarding the progress of multi-output optimization using qNEHVI, qEHVI.

### ISSUE THREAD

**Issue by allChaeYoung** [pytorch/botorch#2288]
# 🚀 Feature Request

  Hi! I'm currently conducting Bayesian optimization using Multi-Task Gaussian Processes (GP) and qNEHVI, qEHVI. However, I have a question regarding this. Suppose you have two outputs (tasks), where one output aims to maximize its value, while the other output aims to minimize its **absolute magnitude**. In this case, how should qNEHVI and qEHVI be designed?

  In the case of qNEHVI and qEHVI, it seems that they can handle scenarios where both outputs aim to maximize or minimize, or one output aims to maximize while the other aims to minimize (by negating it to achieve a maximization goal). However, **I'm curious about strategies to reduce the absolute value.**

  Taking the absolute value directly on the training set would lead to scaling issues, so this approach cannot be pursued.

   I would appreciate it if you could reply. Thank You!

**Comment by sdaulton** [comment]
Hi @allChaeYoung,

I'd recommend using qNEHVI where the first objective is the first output (maximize) and the second objective is the negative squared distance of the second output from 0 (or just the negative squared second output)--which will also be maximized. For the second output, you can use a composite objective. 

To do this in botorch, use the following objective:

```
def custom_objective(Y, X): 
    return Y[..., 0], -(Y[..., 1].pow(2))

objective = GenericMCMultiOutputObjective(objective=custom_objective)
```
