### ISSUE TITLE
Using a fitted GP's mean and covariance functions as mean and covariance function in a new GP

### ISSUE THREAD

**Issue by neildhir** [pytorch/botorch#2299]
# 🐛 Bug

It is not clear that this is a bug but I am not getting the expected behaviour, consequently, it has been filed under 'bug' but maybe something else.

There are three GPs involved in this example

- gp1 is conditioned on a small dataset
- gp2 is conditioned on a larger dataset, but from the same domain as gp1
- gp3 is meant to use the fitted mean function gp2.mean_module and covariance function gp2.covar_module, while being conditioned on the same dataset as gp1 (a form of transfer learning)

## To reproduce

```python
import torch
import matplotlib.pyplot as plt

# True reference function
bounds = torch.tensor([0., 1.5])
x = torch.linspace(bounds[0],bounds[1],1000).unsqueeze(-1)

# Define the function as a lambda
sd = 0.1

def f(x, sd):
    f = lambda x: -(1.4 - 3.0 * x) * torch.sin(18.0 * x) #torch.sin(10 * x * torch.pi) / (2*x) + (x-1)**4
    if sd:
        noise = sd*torch.randn(x.size())
        return f(x) + noise
    else:
        return f(x)

y = f(x, None)


# Plot the function
plt.figure(figsize=(9, 3))
plt.plot(x, y)
plt.xlabel('x')
plt.ylabel('f(x)')
plt.title('1D Function with lots of local Minima')
plt.show()
```
![d13e14ae-3744-4648-b793-9ca02297150a](https://github.com/pytorch/botorch/assets/5817673/a9d6de39-6950-4175-8edb-1290a5fd0ce8)

```python
# Simulate data for gp1 (red dots) and gp2 (green crosses)
N = 10
xx = torch.linspace(bounds[0]+0.5, bounds[1]-0.5, 1000)
# Random samples from xx
xx = xx[torch.randperm(xx.size(0))[:N]]
yy = f(xx, 0.5)
samples = {"X":xx.reshape(-1,1).to(torch.float64), "Y": yy.reshape(-1,1).to(torch.float64)}
s_x = torch.tensor([0.25, 1.,1.25]).reshape(-1,1).to(torch.float64)
y_s_x = f(s_x, 0.25)

plt.figure(figsize=(8, 3))
# True function
plt.plot(x, y, 'k', alpha=0.6, label='True function')
plt.scatter(samples['X'], samples['Y'], color='green', marker='x')
plt.scatter(s_x, y_s_x, color='red', marker='o')
plt.show()
```
<img width="604" alt="Screenshot 2024-04-16 at 18 55 18" src="https://github.com/pytorch/botorch/assets/5817673/711ba3f0-64c8-4a05-a180-f14a72051eb5">

```python

def train_gp(
    train_X: tensor, train_Y: tensor, mean_module: Mean = None, covar_module: Kernel = None, bounds: tensor = None
) -> SingleTaskGP:
    if bounds.ndim == 1:
        bounds = bounds.reshape(-1, 1)

    d = train_X.shape[1]
    input_transform = Normalize(d=d, bounds=bounds) if bounds is not None else Normalize(d=d)

    if train_Y.shape[1] == 1:
        gp = SingleTaskGP(
            train_X=train_X,
            train_Y=train_Y,
            mean_module=mean_module,
            covar_module=covar_module,
            outcome_transform=Standardize(m=1),
            input_transform=input_transform,
        )
        mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
    else:
        raise NotImplementedError("Multi-task GP not implemented yet")
    fit_gpytorch_mll(mll)

    return gp

# Fit first gpa (blue)
train_X1, train_Y1 = s_x, y_s_x 
gp1 = train_gp(train_X1, train_Y1, bounds=bounds.unsqueeze(-1))

# Fit second gp (orange)
train_X2, train_Y2 = samples['X'], samples['Y']
gp2 = train_gp(train_X2, train_Y2, bounds=bounds)

# Visualise
def plot_gp(gp, x_plot, color, label):
    with torch.no_grad():
        p = gp.posterior(x_plot)
        m = p.mean.squeeze().detach()
        s = p.variance.sqrt().squeeze().detach()

    plt.plot(x_plot, m, color, label=label)
    plt.fill_between(x_plot.squeeze(), m + s, m - s, color=color, alpha=0.3)

plt.figure(figsize=(8, 3))
plt.plot(x.detach(), y.detach(), 'k', label='True function')
plt.plot(train_X1.detach(), train_Y1.detach(), "ro")
plt.plot(train_X2.detach(), train_Y2.detach(), "gx")
plot_gp(gp1, x, "C0")
plot_gp(gp2, x, "orange")
plt.show()
```
<img width="593" alt="Screenshot 2024-04-16 at 19 01 07" src="https://github.com/pytorch/botorch/assets/5817673/5fe67431-428b-4021-bde6-3ef90540da74">

The intent now is to use fitted mean and covariance functions of gp2 in a new model (gp3), wanting to make use of its reduced uncertain in region where it has data, in gp1, and used gp2's inflated uncertainty in some regions to inflate the same regions in gp1.

```python
# Write custom mean and kernels

from gpytorch.means import Mean
from torch import no_grad
from gpytorch.kernels import Kernel, MaternKernel, ScaleKernel


class ConditionalMean(Mean):
    def __init__(self, gp):
        super().__init__()
        self.gp = gp  # Assumed to be in eval() mode

    def forward(self, x):
        with no_grad():
            m = self.gp.posterior(x).mean.squeeze(-1)
        return m

class ConditionalScaledMaternKernel(Kernel):
    has_lengthscale = True
    # is_stationary = True

    def __init__(self, gp):
        super().__init__()
        self.gp = gp  # Assumed to be in eval() mode
        self.scaled_matern_kernel = ScaleKernel(MaternKernel())

    def forward(self, x1, x2, **params):
        with no_grad():
            sigma = self.gp.posterior(x1).variance.sqrt()
            sigma_ = self.gp.posterior(x2).variance.sqrt()
            B = sigma @ sigma_.T
        A = self.scaled_matern_kernel(x1, x2)
        K = A + B
        return K

from botorch.models.transforms import Normalize, Standardize
from botorch.fit import fit_gpytorch_mll
from botorch.models import SingleTaskGP
from gpytorch.mlls import ExactMarginalLogLikelihood

if bounds.ndim == 1:
    bounds = bounds.reshape(-1, 1)

d = train_X1.shape[1]
input_transform = Normalize(d=d, bounds=bounds) if bounds is not None else Normalize(d=d)

gp3 = SingleTaskGP(
    train_X=train_X1,
    train_Y=train_Y1,
    mean_module=ConditionalMean(gp2),
    covar_module=ConditionalScaledMaternKernel(gp2),
    outcome_transform=Standardize(m=1),
    input_transform=input_transform,
)
mll = ExactMarginalLogLikelihood(gp3.likelihood, gp3)

# Wanting to keep fixed the already learned parameters, we turn off the gradients of these parameters to ensure they are not optimised by torch/scipy
for param_name, param in mll.named_parameters():
    if 'gp' in param_name:
        # Turn off gradients for the GP trained on (train_X2, train_Y2) data
        param.requires_grad = False
        print(param_name, param.requires_grad)
fit_gpytorch_mll(mll)

plt.figure(figsize=(8, 3))
plt.plot(x.detach(), y.detach(), 'k', label='True function')
plt.plot(train_X1.detach(), train_Y1.detach(), "ro")
plt.plot(train_X2.detach(), train_Y2.detach(), "gx")
plot_gp(gp1, x, "C0")
plot_gp(gp2, x, "orange")
plot_gp(gp3, x, "red")
plt.show()
```
<img width="593" alt="Screenshot 2024-04-16 at 19 07 51" src="https://github.com/pytorch/botorch/assets/5817673/fbab05de-c682-4a48-bdd6-79a72f19d526">

## Expected Behavior

The red curve (gp3) should inherit inflated uncertainty regions of the orange curve, gp2, when being trained on the small dataset (red dots). But it seems to be doing the opposite instead. I expected that adding the learned variance through a new kernel and using the mean function in gp2, would do the trick but this doesn't seem to have worked. It may be the case that turning off the gradients for the gp2 parameters, before passing it to the optimizer, is not the right way to go. Further, using the orange mean function, around x=0.8, I would have expected the (red) mean prediction there to be similar to that of gp2 but the mean has instead gone the opposite direction. 

Alternatively, this other issue may be that way to go: https://github.com/cornellius-gp/gpytorch/issues/743 but it is unclear if one would have to brute-force the model in the same way as the OP does in that issue, to maintain fixed the learned parameters.

## System information

- BoTorch Version: 0.9.5
- GPyTorch Version: 1.11
- PyTorch Version: 2.2.0.post100
- Computer OS: Mac OS Sonoma 14.4

## Additional context

Still new to BoTorch/GPyTorch so may have completely misunderstood something. Also, this is meant to feature as part of a BO loop but haven't managed to get the surrogates (this question) to work properly yet.

**Comment by esantorella** [comment]
> The intent now is to use fitted mean and covariance functions of gp2 in a new model (gp3), wanting to make use of its reduced uncertain in region where it has data, in gp1, and used gp2's inflated uncertainty in some regions to inflate the same regions in gp1.

Why do you want to do this?

I'm wondering if a multi-fidelity model like `SingleTaskMultiFidelityGP` would help. [Here](https://botorch.org/tutorials/discrete_multi_fidelity_bo) is a tutorial. In this case, it sounds like the small dataset might be "full fidelity", providing more reliable data but at a higher cost (since it's noiseless and you can't collect many such points) and the larger data set might be lower fidelity, cheap but noisy? Then you could pass all the data to the same model, using a column of the `x` data to mark which observations are low-fidelity.

**Comment by neildhir** [comment]
Certainly, there are different ways to combine datasets, and this is just a method that I have been working on. 

In the example above, both datasets have some noise but it is certainly true that the smaller one represents a setting where data is a lot more scarce. Whereas the larger dataset contains more samples but are ultimately just random samples from the same domain.

My next intent was actually to explore multi-task multi-fidelity modelling, but I want to get this working first. The idea above is easy enough to understand (I hope) and I thought it would have been easy to implement but something is not going quite right in the fitting of the model, hence hoping more knowledgeable people could help out.

**Comment by saitcakmak** [comment]
Hi @neildhir. Looks like you're training gp3 with only the data for that model, which will adapt the hyper parameters of `ConditionalScaledMaternKernel` to minimize the MLL with that data only. The data from `gp2` is not involved in this MLL computation in any way, so transferring the information over in this way seems hard to achieve. Skipping the model training for `gp3` (and the added scale-matern kernel altogether) might be worth a try, since it will limit the correction applied by the fitting procedure to adopt the model to the training data of gp3.

**Comment by neildhir** [comment]
Hi @saitcakmak 

Hmm, let me see now so `gp2` is trained on the 'big' dataset which means that its parameters are fitted once its mean and covariance function are passed to `gp3`, so the data from `gp2` is transferred in that sense (perhaps more correct to say the information). I then want `gp3` to be trained on the 'small' dataset (the same as `gp1`, red dots) but doing so whilst taking into account the information gained from the big dataset, through the fitted mean and covariance function from `gp2`. The MLL computation should only be fitting the parameters of the `ScaledMaternKernel` quite right, but leaving alone the parameters of the learned covariance function of `gp2`. The contribution from `gp2` comes in the forward pass, through:

```python
        with no_grad():
            sigma = self.gp.posterior(x1).variance.sqrt() # from gp2
            sigma_ = self.gp.posterior(x2).variance.sqrt() # from gp2
            B = sigma @ sigma_.T
```

Then, only the free parameters of the `ScaledMatern` kernel is adjusted to the 'small' dataset. This way the kernel ought to be leveraging the uncertainty from the big dataset in its uncertainty estimation for the small dataset. That at least was my intent.

**Comment by saitcakmak** [comment]
I haven't checked the terminology in the paper closely, so I can't say whether what you implemented is the same as the proposed approach, but it seems to fit the framework.

> Then, only the free parameters of the ScaledMatern kernel is adjusted to the 'small' dataset:

That's correct. The `no_grad` context should prevent gp2 hyper-params from getting updated during training.

One potential issue I noticed while looking at this is the use of input/outcome transforms & the `posterior` call within the kernel. In a BoTorch model with input / outcome transforms, the underlying GPyTorch components operate in the transformed space. When you're evaluating `self.gp.posterior` in `ConditionalScaledMaternKernel`, the Xs you use for evaluation will be already transformed. The `self.gp.posterior` call will transform these again (since `self.gp` also has input transforms attached), which will lead to `self.gp` being evaluated with different inputs than its parent model. Similarly, the `Posterior` returned by `self.gp.posterior` will be untransformed using the outcome transforms, and will get untransformed again as part of the parent model's posterior call. 

To avoid these transform related issues within `ConditionalScaledMaternKernel`, you need to skip input & outcome transforms while evaluating `self.gp`. Replacing
```
        with no_grad():
            sigma = self.gp.posterior(x1).variance.sqrt() # from gp2
            sigma_ = self.gp.posterior(x2).variance.sqrt() # from gp2
```
with 
```
        with no_grad():
            self.gp.eval()
            sigma = self.gp(x1).covariance_matrix.diagonal(dim1=-2, dim2=-1).sqrt() # from gp2
            sigma_ = self.gp(x2).covariance_matrix.diagonal(dim1=-2, dim2=-1).sqrt() # from gp2
```
should work for single output `SingleTaskGP`.

**Comment by neildhir** [comment]
This is great, thanks, a few questions then.

Given these issues, first, is it worth just not using any in and output transforms and just operating on the raw data (or having it scaled outside BoTorch)? It seems that it gets very messy with the transformations in my setting.

So I thought that `no_grad()` would prevent the hyperparams from getting updated, but that does not seem to be the case. So I did this above:

```python
for param_name, param in mll.named_parameters():
    if 'gp' in param_name:
        # Turn off gradients for the GP trained on (train_X2, train_Y2) data
        param.requires_grad = False
        print(param_name, param.requires_grad)
fit_gpytorch_mll(mll)
```
to ensure that no parameters related to `gp2` are updated during training. I assume that is still valid? This then brings us to the next point, according to the documentation `fit_gpytorch_mll(mll)` returns a gp in `eval()` which is why I did not believe I needed to impose those inside the Kernel function. But it looks like you're saying that is indeed the case but rather to circumvent the issues with the transforms.

Do I need to do the same thing in the Mean function too? Apologies, lots of questions.

Finally, using your suggested change (though no change to the mean function if I understand this correctly):
```python
        with no_grad():
            self.gp.eval()
            sigma = self.gp(x1).covariance_matrix.diagonal(dim1=-2, dim2=-1).sqrt() # from gp2
            sigma_ = self.gp(x2).covariance_matrix.diagonal(dim1=-2, dim2=-1).sqrt() # from gp2
```
I get 
<img width="1244" alt="Screenshot 2024-04-17 at 15 31 57" src="https://github.com/pytorch/botorch/assets/5817673/6b235279-e768-4f02-bd8b-6b145c0fe42e">

where `x = torch.linspace(bounds[0],bounds[1],1000).unsqueeze(-1)` and gets raised when it tris to plot the final (combined) GP: `plot_gp(gp3, x, "red")`.

**Comment by neildhir** [comment]
Okay I did some more experimentation and managed to get some things to work. I'll try to organise this a bit more.

## Working mean and kernel functions

```python
class ConditionalScaledMaternKernel(Kernel):
    has_lengthscale = True
    def __init__(self, gp):
        super().__init__()
        self.gp = gp  # Assumed to be in eval() mode
        self.scaled_matern_kernel = ScaleKernel(MaternKernel())

    def forward(self, x1, x2, **params):
        with no_grad():
            self.gp.eval()
            sigma = self.gp(x1).covariance_matrix.diagonal(dim1=-2, dim2=-1).sqrt().unsqueeze(-1)
            sigma_ = self.gp(x2).covariance_matrix.diagonal(dim1=-2, dim2=-1).sqrt().unsqueeze(-1)
            B = sigma @ sigma_.T
        A = self.scaled_matern_kernel(x1, x2)
        K = A + B
        return K

class ConditionalMean(Mean):
    def __init__(self, gp):
        super().__init__()
        self.gp = gp  # Assumed to be in eval() mode

    def forward(self, x):
        with no_grad():
            # self.gp.eval()
            m = self.gp.posterior(x).mean.squeeze(-1)
            # m = self.gp(x).mean.squeeze(-1)
        return m
```

## Gradients

It seems that we explicitly have to turn off the gradients before running `fit_gpytorch_mll(mll)`. If we don't then we get the following behaviour.

<img width="585" alt="Screenshot 2024-04-18 at 14 49 40" src="https://github.com/pytorch/botorch/assets/5817673/8c68d040-6d8f-4a79-a252-25dd2c2664cd">

Here we use `m = self.gp.posterior(x).mean.squeeze(-1)` with `gp.eval()` commented out and gradients updates are not set to `True` for the gp2's parameters.

If on the other hand we do turn them off i.e.

```python
for param_name, param in mll.named_parameters():
    if 'gp' in param_name:
        # Turn off gradients for the GP trained on (train_X2, train_Y2) data
        param.requires_grad = False
fit_gpytorch_mll(mll)
```

Then we get 

<img width="585" alt="Screenshot 2024-04-18 at 14 51 51" src="https://github.com/pytorch/botorch/assets/5817673/a6df3d66-f9e4-48d4-99ef-13055b7a312f">

Where again we use `m = self.gp.posterior(x).mean.squeeze(-1)` with `gp.eval()` commented out. In fact `gp.eval()` seems to have not effect at all in the mean function which is what I would expect since `fit_gpytorch_mll(mll)` puts the gp into eval() mode anyway at the end of that function.

## Which mean calculation to use?

As you can see in the mean function definition above there are two ways to calculate the mean, with `m = self.gp(x).mean.squeeze(-1)` inspired by @saitcakmak 's use of the same type of construct in the kernel definition. Now if we use this way of calculating the mean we get the following posterior behaviour.

<img width="585" alt="Screenshot 2024-04-18 at 14 55 14" src="https://github.com/pytorch/botorch/assets/5817673/3c3f443a-f6e5-4ca8-9d5b-52043daf38f4">

In both of the above two plots we have turned off the gradients before running `fit_gpytorch_mll(mll)` which is why gp3 (in red) is shown.

Now I wonder, what is the difference is between the two? The intent is to use the mean function calculated in gp2, as a prior for the mean in gp3. But `m = self.gp.posterior(x).mean.squeeze(-1)` and `m = self.gp(x).mean.squeeze(-1)` produce very different behaviours.

**Comment by saitcakmak** [comment]
Re gradients: It is interesting that you have to turn them off manually, despite using `no_grad`. I guess the gradients must still be accumulating on those parameters due to subsequent operations, even though the operations within the context do not populate the grad graph.

Re eval: Both `eval()` and `train()` calls apply to sub-modules recursively. In `fit_gpytorch_mll`, we would first put the model in `train()`, fit the model in this mode, then call `eval()` on the model before returning it. In GPyTorch, `ExactGP.__call__` checks for `self.training` and calculates the prior / posterior accordingly. Having an `eval()` call there would make sure that the model would always get evaluated in posterior mode. Without it, I'd expect the model to get evaluated in prior mode when the larger model is being trained but it would not make a difference in evaluations when the larger model itself is in eval / posterior mode.

> Which mean calculation to use

I think `m = self.gp(x).mean.squeeze(-1)` would be the correct computation here since it eliminates any interference from the input & outcome transforms. Both options should be equivalent if you don't use any input / outcome transforms. You could compare the difference between the two by adding some print statements into your code. I'd also recommend testing on a few different examples, which would help ensure that the behavior you're seeing is a general pattern and not due to the particular data in the example.
