### ISSUE TITLE
[Feature Request] Minimization with Monte Carlo acquisition functions

### ISSUE THREAD

**Issue by slishak-PX** [pytorch/botorch#2316]
# 🚀 Feature Request

Analytic acquisition functions all have a `maximize` keyword argument to determine the direction of the optimisation problem. None of the Monte Carlo acquisition functions currently support this, so only support function maximisation.

## Motivation

**Is your feature request related to a problem? Please describe.**
Not a problem as such, and not hard to work around, but would make a good first contribution.

## Pitch

**Describe the solution you'd like**
Add a `maximize=True` keyword argument to all Monte Carlo acquisition functions.

**Describe alternatives you've considered**
One can simply change the sign of the function to be optimised.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))
Yes, but it is not high priority so it might take some time. Logging the issue here in case another community member wishes to contribute it.

**Comment by saitcakmak** [comment]
Hi @slishak-PX. Thanks for bringing this up. Some of the analytic acquisition functions had a `maximize` argument from the start (as they have slightly different definitions in the literature for minimization), so we continued supporting this for the analytic acquisition functions for consistency. 

Overall, I don't believe that the value add of a `maximize` kwarg justifies the added complexity. We have multiple options that can be used to maximize a function:
- as suggested in your post, the function can be negated
- for Gaussian posteriors, you can define a `PosteriorTransform` that negates the posterior mean
- you can use a `LinearMCObjective` with negative weights, which would simply negate the posterior samples
