### ISSUE TITLE
[Bug] get_polytope_samples provides non-random samples when there is a fixed value constraint (x = 1)

### ISSUE THREAD

**Issue by Waschenbacher** [pytorch/botorch#2351]
# 🐛 Bug

`get_polytope_samples` provides non-random samples when there is a "fixed value" constraint, e.g., x = 1. By fixed parameter I mean a linear equality constraint with only one parameter involved. As a workaround, we can set the bounds of x to [1, 1] and we get the expected samples, as shown in the "Expected Behavior". Nevertheless, we would like to raise the awareness in case `get_polytope_samples` is called with a "fixed parameter" constraint. Please evaluate whether there is a need to fix it in `get_polytope_samples` and/or adding a warning when it is called with a "fixed parameter" constraint.

## To reproduce

** Code snippet to reproduce **
```python
import torch
from botorch.utils.sampling import get_polytope_samples

N_SAMPLES = 10
N_PARAMS = 3

torch_dtype = torch.float64

# parameters x1, x2, x3
bounds = torch.cat(
    (
        -torch.ones(1, N_PARAMS, dtype=torch_dtype),
        torch.ones(1, N_PARAMS, dtype=torch_dtype),
    ),
    dim=0,
)

# constraints
# `x0 = 1´
# `xi 0 x2 >=0´
con_lin_eq = (torch.tensor([0]), torch.tensor([1.0], dtype=torch_dtype), 1.0)
con_lin_ineq = (torch.tensor([1, 2]), torch.tensor([1.0, 1.0], dtype=torch_dtype), 0.0)

# generate samples
points = get_polytope_samples(
    n=N_SAMPLES,
    bounds=bounds,
    equality_constraints=[con_lin_eq],
    inequality_constraints=[con_lin_ineq],
)

print(points)
```

** Stack trace/error message **
```
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
```

## Expected Behavior
x1 and x2 should have random samples (an example is given below), instead of fixed ones.
```
tensor([[ 1.0000,  0.3422,  0.2928],
        [ 1.0000, -0.0520,  0.4683],
        [ 1.0000, -0.4603,  0.5908],
        [ 1.0000,  0.2395,  0.2232],
        [ 1.0000, -0.1642,  0.4870],
        [ 1.0000,  0.3090,  0.7517],
        [ 1.0000,  0.4425,  0.0754],
        [ 1.0000, -0.6307,  0.8496],
        [ 1.0000, -0.1179,  0.5641],
        [ 1.0000, -0.0433,  0.4929]], dtype=torch.float64)
```
## System information

**Please complete the following information:**
BoTorch Version: 0.8.5
GPyTorch Version: 1.11
PyTorch Version: 1.12.1
Computer OS: macOS

**Comment by saitcakmak** [comment]
Hi @Waschenbacher. Thanks for reporting. This seems to be a bug in `sample_polytope`. I'll put up a fix for it.

**Comment by Waschenbacher** [comment]
@saitcakmak Great! It's working wonderfully now. A big thank you for the quick fix.

**Comment by Waschenbacher** [comment]
@saitcakmak We really need this bug fix in our production. Could you please estimate when is the next release? Is it possible to have a minor release in the near future?

**Comment by saitcakmak** [comment]
Hi @Waschenbacher. I'll try to put up a release next week. I hope that works for you!

**Comment by saitcakmak** [comment]
Hi @Waschenbacher. I just initiated the release. It should be available on pip / conda in the next hour, assuming it all goes smoothly :)
