### ISSUE TITLE
[Bug] Unexpected `BotorchTensorDimensionWarning`

### ISSUE THREAD

**Issue by AdrianSosic** [pytorch/botorch#2376]
# 🐛 Bug

I noticed that the behavior of `optimize_acqf` and `optimize_acqf_discrete` is inconsistent in that the latter throws a `BotorchTensorDimensionWarning` for `qNegIntegratedPosteriorVariance`. After a first glance, it appears to me that the warning is silenced in the first cast but not in the second (if I'm not mistaken, the line raising the warning is executed in both cases). Thought it's faster to raise an issue instead of diggin' through botorch low-level internals 🙃 

## To reproduce

**Code snippet to reproduce**

```python
import torch
from botorch.acquisition import qNegIntegratedPosteriorVariance
from botorch.fit import fit_gpytorch_mll
from botorch.models import SingleTaskGP
from botorch.optim import optimize_acqf, optimize_acqf_discrete
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood

torch.set_default_dtype(torch.float64)

# >>>>> Copied from botorch.org landing page
train_X = torch.rand(10, 2)
Y = 1 - torch.linalg.norm(train_X - 0.5, dim=-1, keepdim=True)
Y = Y + 0.1 * torch.randn_like(Y)  # add some noise
train_Y = standardize(Y)

gp = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
fit_gpytorch_mll(mll)

bounds = torch.stack([torch.zeros(2), torch.ones(2)])
# <<<<<

acqf = qNegIntegratedPosteriorVariance(gp, mc_points=train_X)

# Throws no warning
optimize_acqf(
    acqf,
    bounds=bounds,
    q=1,
    num_restarts=5,
    raw_samples=20,
)

# Throws BotorchTensorDimensionWarning
optimize_acqf_discrete(acqf, q=1, choices=train_X)

```

**Stack trace/error message**
```
BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 3 and Y with dimension 4).
  self._validate_tensor_args(X=X, Y=Y, Yvar=Yvar, strict=False)
```

## Expected Behavior

No warning should be thrown in both cases.

## System information

BoTorch Version: 0.11.0
GPyTorch Version: 1.11
PyTorch Version: 2.3.0
OS: macOS

**Comment by saitcakmak** [comment]
Hi @AdrianSosic. Thanks for the nice repro! When I run the code, both optimizers do throw the warning. The warning comes from the `fantasize` call. It seems like the regular usage of `fantasize`, so we should indeed silence it there. This call reproduces it without going into the acquisition function.
```
gp.fantasize(X=torch.rand(20, 1, 2), sampler=SobolQMCNormalSampler(torch.Size([1])))
```

**Comment by AdrianSosic** [comment]
Hi @saitcakmak, thanks for the confirmation, glad that I got the mechanism right. I wonder, though, why you also see the warning for `optimize_acqf` 🤔 I've double-checked and I really don't get any warning there. A friend of mine tested it, too, and independently reported the same: no warning. Could you perhaps have another look?

**Comment by saitcakmak** [comment]
It could be that it is triggered but caught somewhere. The way I checked for it was to turn the warning into an exception using `warnings.filterwarnings("error", category=BotorchTensorDimensionWarning)`. Thinking of it, I believe we have some warning filtering in `optimize_acqf`.

**Comment by AdrianSosic** [comment]
OK, that would explain it, thx! So as far as I'm concerned, you can consider the issue solved 👍🏼
