### ISSUE TITLE
[Bug]  Feasible method of PolytopeSampler class returns False in spite of the sample being feasible

### ISSUE THREAD

**Issue by dsanyal** [pytorch/botorch#2383]
# 🐛 Bug

Because of incorrect tensor broadcasting, the check whether a sample satisfies the inequality constraints of a polytope, fails.

## To reproduce

```python
import torch
from botorch.utils.sampling import HitAndRunPolytopeSampler

inequality_constraints = (torch.tensor([[0.,0., 1.]], dtype=torch.float64),
                              torch.tensor([[0.5]], dtype=torch.float64))

A, b  = inequality_constraints

polytope_sampler = HitAndRunPolytopeSampler(  
    bounds = torch.tensor([[0.,0.0,0.],[1.0,1.0,1.0]], dtype=torch.float64),
    inequality_constraints=inequality_constraints,
    n_burnin=10000,
)
samples = polytope_sampler.draw(n=10)
print(polytope_sampler.feasible(samples[0]).item()) 
# False
print(((A @ samples.t() - b) > 0).sum().item() == 0)
# True
```
In `feasible()`, the check for whether the inequality constraints are satisfied, is given by `ineq = (self.A @ x - self.b <= 0).all()`. 

In the example above, ` self.A` has shape _(7, 3)_, `self.b` has shape _(7, 1)_, but, because of tensor broadcasting, `(self.A @ x - self.b)` has a shape _(7,7)_ instead of _(7,)_ in this case. Therefore, the variable `ineq` is erroneously set to `False`. 
_Side note_: The the shape of `self.A` is _(7, 3)_ because the bounds (3 upper and 3 lower) are converted to inequality constraints.

## Expected Behavior

The `feasible()` method should return `True` because the sample lies within the constrained polytope.

## System information

**Please complete the following information:**
-  BoTorch Version `0.9.4`
- GPyTorch Version `1.11` 
- PyTorch Version `2.0.1`
- MacOS Sonoma 14.5

## Additional context

I'd be happy to open a PR if you wish.

**Comment by Balandat** [comment]
This is not a bug. You're passing in a one-dimensional tensor with `d` elements, but tthe API expects a `d x 1`-dimensional tensor: https://github.com/pytorch/botorch/blob/79bff188ab17562bbca4204e160856a854af01f0/botorch/utils/sampling.py#L533-L538

Calling `polytope_sampler.feasible(samples[0].unsqueeze(-1))` will return `tensor(True)` as expected.

Now, if you feel like the API could be more permissive, I'd be happy to accept a PR that would automatically unsqueeze one-dimensional tensors under the hood in `feasible`.

**Comment by dsanyal** [comment]
Thanks for the quick response :)
