### ISSUE TITLE
[Question] Anyway to ensure non-duplicated inclusion of pending configs when wrapping acquisitions?

### ISSUE THREAD

**Issue by eddiebergman** [pytorch/botorch#2493]
**Question:** If wrapping an acquisition function with another one, should I ensure that the wrapped acquisition does not receive `X_pending` in its `__init__`? I'm not sure if this was known, a bug, or intentional, and in general, I did not find any documentation around weighting of acquisition other than a [closed PR](https://github.com/pytorch/botorch/pull/585) and a [closed issue](https://github.com/pytorch/botorch/issues/579).

---

While looking into wrapping acquisition functions, the approach I took was to follow PiBO: https://github.com/pytorch/botorch/blob/d52205a031ecd83b9ef73ba05ca990a284179edb/botorch/acquisition/prior_guided.py#L30-L46

Notably it takes in a `X_pending` argument which is used by the decorator [`
@concatenate_pending_points`](https://github.com/pytorch/botorch/blob/d52205a031ecd83b9ef73ba05ca990a284179edb/botorch/utils/transforms.py#L312-L336) which will take `self.X_pending` and concatenate it before calling the `forward()` method: https://github.com/pytorch/botorch/blob/d52205a031ecd83b9ef73ba05ca990a284179edb/botorch/acquisition/prior_guided.py#L74-L90
 
However, if you scroll down the above code block, PiBO acquisition weighting will call the acquisition it's wrapping, which could also include this `@concatenate_pending_points`. [Here is a search for its usage through BoTorch](https://github.com/search?q=repo%3Apytorch%2Fbotorch%20%40concatenate_pending_points&type=code)

For example, this problem could occur if you were to wrap any [`MultiObjectiveMCAcquisitionFunction`](https://github.com/pytorch/botorch/blob/d52205a031ecd83b9ef73ba05ca990a284179edb/botorch/acquisition/multi_objective/base.py#L70) with pibo. 

```python
# Summary
@concatenate_pending_points
def forward(x: Tensor) -> Tensor:
    ... If not SampleReducingMCAcquisitionFunction

    # Calls the forward of the base acq here, again calling the `concatenate_pending_points`
    # of self.acq_func
    af_val = self.acq_func(X).unsqueeze(-1)
```

More generally, this will happen for any class that does not inherit form `SampleReducingMCAcquisitionFunction`

**Comment by sdaulton** [comment]
Hi @eddiebergman,

The pending points are should only be set on the `PriorGuidedAcquisitionFunction`---not on the `acq_function` argument that is passed to `PriorGuidedAcquisitionFunction`. Pending points are then only concatenated in `PriorGuidedAcquisitionFunction.forward`. I think we aught to raise an warning if X_pending is set on the `acq_function` and describe this more clearly in the documentation.
