### ISSUE TITLE
Consistent use of torch device in ‎HitAndRunPolytopeSampler

### ISSUE THREAD

**Issue by mhrmsn** [pytorch/botorch#2500]
## Issue description

In `botorch.utils.sampling.‎HitAndRunPolytopeSampler.draw` ([see here](
https://github.com/pytorch/botorch/blob/1f6bf87d656d74c5b24c30d88a374290f33e50e0/botorch/utils/sampling.py#L682-L691)), when calling `sample_polytope`, the tensors `A` and `b` are explictly moved to the CPU, but not `x0`. 

Is this intended, and if so why? If not, should this be changed to moving `x0` also explicitly to the CPU or by taking the source devices of all tensors? 

`x0` seems to ultimately come from the equality constraints (`x0 -> self.nullC -> Vh -> self.C -> equality_constraints`). Depending on where the equality constraints come from (external library that calls botorch) this might be an issue, and given that those tensors must anyway be on the same device for multiplication in `sample_polytope`, it might make sense to change this.

## System Info
Please provide information about your setup, including
- BoTorch Version (0.11.3)
- GPyTorch Version (1.12)
- PyTorch Version (2.3.0)
- macOS Sonoma, 14.6.1

**Comment by Balandat** [comment]
> Is this intended, and if so why?

No, I don't think so. `x0` is constructed as a new tensor there, so it will be constructed on the default torch device. If that is not the cpu then this could cause errors. It would make sense to explicitly construct this tensor on the GPU, let me put up a quick PR.

**Comment by mhrmsn** [comment]
> > Is this intended, and if so why?
> 
> No, I don't think so. `x0` is constructed as a new tensor there, so it will be constructed on the default torch device. If that is not the cpu then this could cause errors. It would make sense to explicitly construct this tensor on the GPU, let me put up a quick PR.

Perfect, thanks!
