### ISSUE TITLE
[Bug] BotorchTensorDimensionError (Example of Get Started)

### ISSUE THREAD

**Issue by jmren168** [pytorch/botorch#251]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```python
# Your code goes here
# Please make sure it does not require any external dependencies
```
import torch
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_model
from gpytorch.mlls import ExactMarginalLogLikelihood

train_X = torch.rand(10, 2)
Y = 1 - torch.norm(train_X - 0.5, dim=-1) + 0.1 * torch.rand(10)
train_Y = (Y - Y.mean()) / Y.std()

gp = SingleTaskGP(train_X, train_Y)

** Stack trace/error message **
```
// Paste the bad output here!
```
---------------------------------------------------------------------------
BotorchTensorDimensionError               Traceback (most recent call last)
<ipython-input-2-5edc68f1d179> in <module>
     11 train_Y = (Y - Y.mean()) / Y.std()
     12 
---> 13 gp = SingleTaskGP(train_X, train_Y)
     14 mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
     15 fit_gpytorch_model(mll)

C:\Anaconda3\envs\BoTorch\lib\site-packages\botorch\models\gp_regression.py in __init__(self, train_X, train_Y, likelihood, covar_module)
     76             >>> model = SingleTaskGP(train_X, train_Y)
     77         """
---> 78         self._validate_tensor_args(X=train_X, Y=train_Y)
     79         self._set_dimensions(train_X=train_X, train_Y=train_Y)
     80         train_X, train_Y, _ = self._transform_tensor_args(X=train_X, Y=train_Y)

C:\Anaconda3\envs\BoTorch\lib\site-packages\botorch\models\gpytorch.py in _validate_tensor_args(X, Y, Yvar, strict)
     73                         f" {Y.dim()}."
     74                     )
---> 75                 raise BotorchTensorDimensionError(message)
     76         else:
     77             warnings.warn(

BotorchTensorDimensionError: An explicit output dimension is required for targets. Expected Y with dimension: 1 (got 2).

## Expected Behavior
Hope this test case run correctly.

## System information

**Please complete the following information:**
-  BoTorch 0.1.3
-  GPyTroch 0.3.5
-  PyTorch 1.2.0
-  Computer OS: Windows 7 SP1

**Comment by Balandat** [comment]
oops, looks like we forgot to update the getting started example. Since #238 we require explicit output dimensions in the training targets. Will put up a PR to fix this

**Comment by Balandat** [comment]
Thanks for reporting.
