### ISSUE TITLE
[Bug] Links in main website footer broken

### ISSUE THREAD

**Issue by CamDavidsonPilon** [pytorch/botorch#255]
# 🐛 Bug

On my computer, https://pytorch.org/botorch/tutorials/ shows without css

**Comment by Balandat** [comment]
So the correct url is https://botorch.org/tutorials/, where things seem to work.

There is some redirection weirdness about the site being hosted in github pages of pytorch. We should see if we can better hide  https://pytorch.org/botorch/tutorials/

**Comment by CamDavidsonPilon** [comment]
Oh I wish I record how I got to that page. It was some link on the main docs site.

**Comment by Balandat** [comment]
Aha, found it. It's the links in the footer bar. Likely related to the site versioning. Thanks for pointing this out.

cc @kkashin
