### ISSUE TITLE
How to get mean and covariance matrix from GP model?

### ISSUE THREAD

**Issue by ricvolpi** [pytorch/botorch#2559]
## Issue description

I need to retrieve the covariance matrix and the mean vector that define the posterior distibution of the GP model. Is there any function for this? This is the object I'm dealing with

```unix
(Pdb) gp_model
SingleTaskGP(
  (likelihood): GaussianLikelihood(
    (noise_covar): HomoskedasticNoise(
      (noise_prior): LogNormalPrior()
      (raw_noise_constraint): GreaterThan(1.000E-04)
    )
  )
  (mean_module): ConstantMean()
  (covar_module): RBFKernel(
    (lengthscale_prior): LogNormalPrior()
    (raw_lengthscale_constraint): GreaterThan(2.500E-02)
  )
)
```

## System info

- BoTorch version: 0.12.0
- GPyTorch version: 1.13
- Torch version: 2.4.1
- Mac M1 Sonoma 14.2.1

**Comment by saitcakmak** [comment]
Hi @ricvolpi. First, you need to get the posterior for the GP model. You can do this for any given set of points `X` using `posterior = gp_model.posterior(X=X)`. From there, you can access `posterior.mean` and `posterior.covariance_matrix`.

**Comment by ricvolpi** [comment]
Hi @saitcakmak, thanks for the super quick answer. I was expecting the posterior to be already computed for my object, since it's the final model after a round of experiments via [Ax](https://ax.dev).

```python
model = ax_client.generation_strategy.model.model

if isinstance(model.surrogate, Surrogate):
    gp_model = model.surrogate.model
```

`gp_model` is the object I was referring to, and indeed I can imlpement your solution -- but I would like to inspect the covariance matrix as it is at the end of Ax routing, without re-computing it (context: I want to understand how it handles points with the same `x` value). 

In light of you answer, I think I should ask my question on the Ax repo, since BoTorch-wise everything is clear.

**Comment by saitcakmak** [comment]
The posterior is computed within the acquisition function, it gets used and discarded. Since it is dependent on the particular `X`, it will not be retained.

**Comment by ricvolpi** [comment]
If we make repeated inference using the same training set, some parts of the covariance matrix do not change, right? Wouldn't it be more efficient to store those?

<img width="550" alt="image" src="https://github.com/user-attachments/assets/d075f79f-36db-4411-bfdc-355f5e1b675b">

(image from [here](https://distill.pub/2019/visual-exploration-gaussian-processes/))

But we can close, many thanks for the support.

**Comment by saitcakmak** [comment]
You're right and various parts of the equation (those that only depend on train_X) are cached internally in GPyTorch. But the `posterior(test_X)` depends on `test_X` and it cannot be cached independently of `test_X`. Since `test_X` constantly changes in practical usage, we treat the posterior as an ephemeral object.
