### ISSUE TITLE
[Feature Request] allow both get_ic_generator and batch_initial_conditions to be used in the same call.

### ISSUE THREAD

**Issue by CompRhys** [pytorch/botorch#2609]
# 🚀 Feature Request

When targeting a campaign I might want to include some points explicitly and then fill up the rest of the initial candidates using the strategies in botorch. This behaviour would be triggered by having `n_repeats > len(batch_initial_conditions)` 

## Motivation

Makes it much easier to do https://github.com/facebook/Ax/pull/2938 as then all I have to worry about to get the desired behaviour for that to get merged is dropping the points from the given X_pareto front that do not satisfy the constraints

## Pitch

this should be fairly minimal change in the logic to check that `raw_samples is not None` and then just using `raw_samples-len(batch_initial_conditions)` as the number of requested samples to the ic generator.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

yes

## Additional context

**Comment by saitcakmak** [comment]
Hi @CompRhys! That sounds reasonable to me. Happy to review a PR for this.
