### ISSUE TITLE
ImportError: cannot import name 'optimize_acqf'

### ISSUE THREAD

**Issue by reachnatp** [pytorch/botorch#262]
# 🐛 Bug

Tried adapting https://github.com/pytorch/botorch/blob/master/tutorials/closed_loop_botorch_only.ipynb and got this error
from botorch.optim import optimize_acqf

BATCH_SIZE = 3
bounds = torch.tensor([[0.0] * 6, [1.0] * 6], device=device, dtype=dtype)

## To reproduce
from botorch.optim import optimize_acqf fails but from botorch.optim import joint_optimize works 
** Code snippet to reproduce **
```python
# Your code goes here
# Please make sure it does not require any external dependencies
```

** Stack trace/error message **
```
// Paste the bad output here!
```

## System information

**Please complete the following information:**
- 
- 
- 
-

**Comment by Balandat** [comment]
Looks like you're using the latest stable release (which doesn't have `optimize_acqf` yet) on a tutorial updated for master. You have two options:

1. install botorch from the latest master
2. use the old `joint_optimize` function. You can find the tutorials that will work with the latest stable release on the website: https://botorch.org/tutorials/closed_loop_botorch_only (note the version selection at the top right of the page)

Feel free to re-open if that doesn't work for you.

**Comment by reachnatp** [comment]
Installing from source fixes it and I have it running, but wanted to point out the inconsistency when installing via pip and using the tutorials online

**Comment by Balandat** [comment]
Thanks - I guess our assumption is that if people are looking at the tutorials on the repo they are using the most recent master (since the tutorials themselves are living on the master branch), and that if they look on the website they are using the latest stable release. We can make this more clear, but I don't think there is a good way to avoid these kinds of inconsistencies.
