### ISSUE TITLE
[Feature Request]: ConstrainedMaxPosteriorSampling for a problem with a high number of constraints

### ISSUE THREAD

**Issue by paoloascia** [pytorch/botorch#2620]
# 🚀 Feature Request

Switch between in-parallel and in-series evaluations of the constraint models in ConstrainedMaxPosteriorSampling to avoid running into memory problems.

## Motivation

The function ConstrainedMaxPosteriorSampling evaluates the constraint models in parallel. Therefore, it is not possible to evaluate problems with a high number of constraints because memory quickly runs out. This problem occurred with structural optimization problems I set up myself and the benchmark MOPTA08. Both are problems with a high number of constraints.

## Pitch

Locally, I tested this rudimental solution with the MOPTA08 benchmark. The function handled 69 constraints. However, it does not maximize memory usage (i.e., a set of constraints could be evaluated in parallel depending on how much memory is available in the system). Therefore, this solution is not efficient.

```
class ConstrainedMaxPosteriorSampling(MaxPosteriorSampling):
[...]
    def forward(
        self, X: Tensor, num_samples: int = 1, observation_noise: bool = False
    ) -> Tensor:
        r"""Sample from the model posterior.

        Args:
            X: A `batch_shape x N x d`-dim Tensor from which to sample (in the `N`
                dimension) according to the maximum posterior value under the objective.
            num_samples: The number of samples to draw.
            observation_noise: If True, sample with observation noise.

        Returns:
            A `batch_shape x num_samples x d`-dim Tensor of samples from `X`, where
                `X[..., i, :]` is the `i`-th sample.
        """
        posterior = self.model.posterior(
            X=X,
            observation_noise=observation_noise,
            # Note: `posterior_transform` is only used for the objective
            posterior_transform=self.posterior_transform,
        )
        Y_samples = posterior.rsample(sample_shape=torch.Size([num_samples]))
        C_tmp = []
        for c in self.constraint_model.models:
            c_posterior = c.posterior(
                X=X, observation_noise=observation_noise
                )
            C_tmp.append(c_posterior.rsample(sample_shape=torch.Size([num_samples])))
        
        C_samples = torch.cat(C_tmp, dim=2)
        
        # c_posterior = self.constraint_model.posterior(
        #     X=X, observation_noise=observation_noise
        # )
        # C_samples = c_posterior.rsample(sample_shape=torch.Size([num_samples]))

        # Convert the objective and constraint samples into a scalar-valued "score"
        scores = self._convert_samples_to_scores(
            Y_samples=Y_samples, C_samples=C_samples
        )
        return self.maximize_samples(X=X, samples=scores, num_samples=num_samples)
```

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))
Yes, but I have limited coding knowledge.

## Additional context

---

**Comment by saitcakmak** [comment]
Hi @paoloascia. Thanks for flagging the issue. This many constraints seems like quite an edge case that we wouldn't encounter often. Your suggested fix would work great for `ModelListGP` but it wouldn't work if the `constraint_model` is a `SingleTaskGP` or `MultiTaskGP`. I guess we could support both if we had an if/else block there. I can implement that change.
