### ISSUE TITLE
[Bug] Unable to install botorch via conda

### ISSUE THREAD

**Issue by chrisyeh96** [pytorch/botorch#2642]
# 🐛 Bug

When I install botorch via conda and then run python, I am unable to import botorch. Instead, I get the following error message:

```
>>> import botorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'botorch'
```

## To reproduce

On a clean Ubuntu machine with conda installed, run the following command, which follows what the [Getting Started](https://botorch.org/docs/getting_started) page in BoTorch Docs recommends:

```bash
conda create -n env python=3.10 botorch -c pytorch -c gpytorch -c conda-forge
conda activate env
python
```

(I have also tried `python=3.12`, which still results in the same bug.)

Then, in the Python REPL, run:

```python
import botorch
```

For full reproduction steps:

1. Create a blank GitHub codespace. (Go to https://github.com/github/codespaces-blank, and create a codespace from the main branch)
2. At the terminal inside the codespace, run `conda init`. Then open a new terminal window.
3. In the new terminal window, run `conda deactivate`, to deactivate the base environment.
4. Run `conda create -n env python=3.10 botorch -c pytorch -c gpytorch -c conda-forge` to create a new environment with BoTorch installed.
5. Activate the new environment: `conda activate env`
6. Run python: `python`
7. Try importing BoTorch: `import botorch`

Blank GitHub codespaces currently run Ubuntu 20.04.6 LTS.

## Expected Behavior

I expect running `import botorch` to work.

## System information

**Please complete the following information:**
- Computer OS: I have tried this on both Ubuntu 20.04.6 LTS and Ubuntu 22.04.4 LTS.
- Python: I have tried this on both Python 3.10 and Python 3.12

**Comment by saitcakmak** [comment]
Hi @chrisyeh96. We recently stopped supporting conda distributions for BoTorch (see https://github.com/pytorch/botorch/discussions/2613). We recommend installing using pip instead.

I am not familiar with github codespaces but I've tried to reproduce locally on MacOS
```
conda create -n env python=3.10 botorch -c pytorch -c gpytorch -c conda-forge
conda activate env
python
>>> import botorch
```
works without issues. This might be an issue with the codespaces & conda.
