### ISSUE TITLE
Training heteroscedastic GP (possible bug or inconsistency)

### ISSUE THREAD

**Issue by mgarort** [pytorch/botorch#266]
Hi,

I am trying to train a heteroscedastic GP on high-dimensional inputs. Because  `scipy.optimize.minimize` cannot really optimize GPs in more than a few dimensions, I'm trying to use minibatch optimizers from `torch.optim` such as `Adam`. Following the examples on the tutorials, I've created a very simple function to train a GP with `torch.optim`.  The optimization works perfectly for the homoscedastic `SingleTaskGP`, but not so for the heteroscedastic `HeteroskedasticSingleTaskGP`, where I obtain the following error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-4a5cc8aa17fb> in <module>()
      1 hetero_GP = HeteroskedasticSingleTaskGP(x,y,s)
----> 2 hetero_GP = train_a_GP(hetero_GP, x, y, 10)

9 frames
/usr/local/lib/python3.6/dist-packages/gpytorch/module.py in __call__(self, *inputs, **kwargs)
     20 
     21     def __call__(self, *inputs, **kwargs):
---> 22         outputs = self.forward(*inputs, **kwargs)
     23         if isinstance(outputs, list):
     24             return [_validate_module_outputs(output) for output in outputs]

TypeError: forward() missing 1 required positional argument: 'x'
```

I have put together a simple example on this Colab notebook:
https://colab.research.google.com/drive/106oIYcd4fnidAGr2q8-R64jWy0ufu1Y8

Am I doing something wrong? Any help would be greatly appreciated.

Thanks and best wishes,

Miguel

**Comment by sdaulton** [comment]
Hi @mgarort,

When using the heteroskedastic GP, you need pass train_x as an argument to the `mll()` call so that the noise model also receives the training inputs: i.e. replace `-mll(output, train_y)` with `-mll(output, train_y, train_x)` in your fitting loop. Botorch also provides a convenience method `botorch.optim.fit.fit_gpytorch_torch` for using torch optimizers for model fitting and takes care of providing the right required arguments to the `mll`.

**Comment by Balandat** [comment]
One thing to note about `HeteroskedasticSingleTaskGP` is that it currently doesn't properly account for the full MLL - https://github.com/cornellius-gp/gpytorch/pull/870 is meant to fix this and ideally will go in timely.
