### ISSUE TITLE
Are the citations for `MultiTaskGP` correct?

### ISSUE THREAD

**Issue by nabenabe0928** [pytorch/botorch#2661]
The details are already described in the link below:
- https://github.com/cornellius-gp/gpytorch/discussions/2616

In a nutshell, I am wondering if the kernel used in `MultiTaskGP` of BoTorch does the same as the Multi-Task Gaussian Process paper where we approximate the task correlation by optimizing the Cholesky decomposed matrix $L$.

Plus, I would like to know the details of what it means by "Combine the two in an ICM fashion".
If there are any papers you refer to for intrinsic co-regionalization model, I highly appreciate the guidance :pray:

**Comment by Balandat** [comment]
Responded here: https://github.com/cornellius-gp/gpytorch/discussions/2616#discussioncomment-11686132

Closing this out for now, feel free to re-open if any questions remain.
