### ISSUE TITLE
Running Botorch v0.12 on Python3.8

### ISSUE THREAD

**Issue by lucasvandijck** [pytorch/botorch#2662]
We are using Jetson boards running JetPack 5.1.2 which is fixed to Python3.8 (Torch v2 is possible). When looking at the dependencies in the README file, it seems like none of them strictly require Python3.10.

We have tried just using botorch v0.8.5, but this gives entirely different results for the same input values. Additionally, we get a lot of NaNs in our outputs:
![image](https://github.com/user-attachments/assets/4bc966b1-8d0a-479f-9766-92153fa521c4)

Is there a way in which I can try to build the latest BoTorch version on Python3.8? Is there a specific reason why the Python dependency was increased to 3.10 (I assume probably because of security reasons)?

Any help is welcome to get me going in the right direction!

**Comment by saitcakmak** [comment]
Hi @lucasvandijck. Unfortunately, it is not possible to run latest version of BoTorch in Python3.8 without making changes to the code. There are subtle things, type hints come to mind as an example, we utilize from later versions of Python that are not available in 3.8. We generally try to follow [NumPy's schedule](https://scientific-python.org/specs/spec-0000/) for determining when to drop support for Python versions, which recommends dropping support for Python3.10 at this time as well (we'll do so after 3.12 becomes the default internally).

To resolve your issue, would it be possible to install conda on these Jetson boards? If so, you could specify an arbitrary Python version for any given environment, which would let you use later versions of Python than what the boards come pre-installed with.

**Comment by lucasvandijck** [comment]
Thanks for the quick response @saitcakmak! The NumPy schedule makes sense indeed. I'll try to build the package from source when I'm back in the lab to see how big the issues are.

We haven't tried Conda yet, but we have tried manually installing python3.10 in our L4T Docker containers. Sadly, when updating the Python version, CUDA support drops since the Torch modules are build specifically for this version of the platform.

**Comment by Balandat** [comment]
Also, to add here: python 3.8 is past end-of-life and not officially supported anymore: https://devguide.python.org/versions/
