### ISSUE TITLE
Validate shape for best_f in qExpectedImprovement

### ISSUE THREAD

**Issue by wangyifan411** [pytorch/botorch#297]
# 🐛 Bug

Hi,
I am using Botorch to do multi-objective optimization where the number of model outputs is m (m>1). I found optimization of qEI acquisition function is not working as expected for m greater than 1 case. 

I think it is trying to call the function initialize_q_batch_nonneg (which is required by qEI for initialization) and selecting the right indices by passing the flags in alpha_pos. Alpha_pos is 2D tensor but torch.arange(len(Y)) gives a 1D tensor.  Or did I miss something here?

I used some randomly generated X and Y tensors in the example below. I hope it is clear. 

## To reproduce

** Code snippet to reproduce **

```

import numpy as np
import torch
from botorch.models import SingleTaskGP, FixedNoiseGP, HeteroskedasticSingleTaskGP
from botorch.models.gpytorch import GPyTorchModel
from botorch.acquisition.monte_carlo import qExpectedImprovement, qNoisyExpectedImprovement
from botorch.optim import optimize_acqf
from gpytorch.mlls import ExactMarginalLogLikelihood
from botorch.optim.fit import fit_gpytorch_torch
from botorch.sampling.samplers import SobolQMCNormalSampler


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.float


def _get_and_fit_simple_gp(Xs, Ys, **kwargs):

    model = SingleTaskGP(train_X=Xs, train_Y=Ys)
    model.train();
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    mll.train();
    fit_gpytorch_torch(mll);
    mll.eval();
    model.eval();
    return model    


nsamples = 10
nx = 3
my = 2

train_X = torch.rand(nsamples,nx)
train_Y =  torch.rand(nsamples,my)

model = _get_and_fit_simple_gp(train_X, train_Y)

bounds = torch.stack([torch.zeros(nx), torch.ones(nx)])
best_value = torch.ones(my) 

acq_func = qExpectedImprovement(model, best_f= best_value )

new_X, acq_value = optimize_acqf(acq_func, bounds=bounds, q= 1, num_restarts=20, raw_samples=100)

```
** Stack trace/error message **
```
Traceback (most recent call last):
  File "c:\Users\yifan\Documents\GitHub\Learn-BO\testing_files\debug_temp_file.py", line 52, in <module>
    new_X, acq_value = optimize_acqf(acq_func, bounds=bounds, q= 1, num_restarts=20, raw_samples=100)
  File "C:\Users\yifan\Anaconda3\envs\torch\lib\site-packages\botorch\optim\optimize.py", line 148, in optimize_acqf
    options=options,
  File "C:\Users\yifan\Anaconda3\envs\torch\lib\site-packages\botorch\optim\initializers.py", line 103, in gen_batch_initial_conditions
    X=X_rnd, Y=Y_rnd, n=num_restarts, **init_kwargs
  File "C:\Users\yifan\Anaconda3\envs\torch\lib\site-packages\botorch\optim\initializers.py", line 347, in initialize_q_batch_nonneg
    alpha_pos_idcs = torch.arange(len(Y), device=Y.device)[alpha_pos]
IndexError: too many indices for tensor of dimension 1

```

## Expected Behavior

qEI acquisition function can be correctly optimized and return the right next sampling points. 

## System information

**Please complete the following information:**
- 0.1.4
- 0.3.5
- 1.2.0
-  Windows-10-10.0.17763-SP0

**Comment by Balandat** [comment]
Hi @wangyifan411, thanks for the clear repro.

Internally, `qExpectedImprovement` is always evaluated on samples of a scalar outcome. So you can't directly do MOO the way you are trying to do it. In particular, `best_f` must be a scalar.

Instead, you could perform MOO indirectly by optimizing a number of different scalarizations of the outcome. The `objective` abstraction makes that straightforward.

```
from botorch.acquisition.objective import LinearMCObjective

weights = torch.tensor([0.5, 1.5])  # the weight defines a particular scalarization / direction 
best_f_scalar = torch.dot(weights, best_f)
objective = LinearMCObjective(weights=weights) 
acq_func = qExpectedImprovement(model, best_f=best_f_scalar, objective=objective)
```

There are other ways of performing MOO more directly, e.g. by trying to increase the volume of the Pareto set. So far we have not implemented such algorithms in BoTorch, but we're interested in adding them (PRs are welcome :)).

Anyway, we should probably raise an error when the `best_f` has unexpected shape to make this clear. I'll leave the issue open for this.

**Comment by wangyifan411** [comment]
Hi Balandat,

Thank you for your prompt reply and the code example is very helpful! 
Just a quick follow-up question, is[ this example from Ax tutorial ](https://ax.dev/tutorials/visualizations.html) used the same approach for optimizing two outputs? Is this the default option for MOO in Ax and how we can pass the weights into an Ax `SimpleExperiment` object?

**Comment by Balandat** [comment]
The example you mention uses an outcome constraint - basically instead trying to find Pareto improvements this example optimized one modeled output subject to a constraint on another (black box) output. In BoTorch you can achieve this using a [`ConstrainedMCObjective`](https://github.com/pytorch/botorch/blob/master/botorch/acquisition/objective.py#L188).

The alternative for optimizing scalarizations of multiple objectives in Ax you can use the Ax [`ScalarizedObjective`](https://github.com/facebook/Ax/blob/master/ax/core/objective.py#L48).
