### ISSUE TITLE
The links on the Byte-Sized tutorials all return 404.

### ISSUE THREAD

**Issue by CBrauer** [pytorch/botorch#300]
Please fix the links on the "Byte-Sized Tutorials".  All I get is 404!

**Comment by Balandat** [comment]
@CBrauer I just checked, the links work fine for me on both the "latest" and "stable" version of botorch.org. 

How / where exactly are you trying to access these? Does [https://botorch.org/v/latest/tutorials/fit_model_with_torch_optimizer](https://botorch.org/v/latest/tutorials/fit_model_with_torch_optimizer) work?

If not, what browser are you using?

**Comment by CBrauer** [comment]
I was on the GitHub site, not your web site.

**Comment by Balandat** [comment]
Which github site? I still don't understand where/how you're trying to access the tutorials. Can you provide a link?

**Comment by CBrauer** [comment]
Go to https://pytorch.org/botorch/tutorials/.  Click on the “Fitting a model using torch.optum” link.

**Comment by Balandat** [comment]
Ahh ok, I see - the https://pytorch.org/botorch/ site is not meant to be accessed directly, please use the public site https://botorch.org.

Some background: Unfortunately there are some relative link issues that Docusaurus (the tool we use for building the website) is not able to handle well in conjunction with redirects. Quoting @Jakepodell here:
> A lot of how docusaurus links assets is heavily reliant on that baseUrl field, which cannot be relative to to the current directory but rather has to be relative to the top-level hostname.
See https://github.com/facebook/Docusaurus/issues/448, where they admit I think at this point our architecture relies a lot on baseUrl and supporting this will be quite a huge refactor. I personally feel the effort is better spent elsewhere.
The baseUrl also cannot be a fully absolute path, like 'https://botorch.org". The result of all these findings is basically that docusarus is not set up to support the same site existing at two different paths relative to their top-level hostnames.

Unfortunately it doesn't seem that docusaurus is planning to fix this anytime soon, so for now we'll just have to try to keep people away from the https://pytorch.org/botorch/  and possibly  move away from docusaurus down the road (this doesn't seem to be addressed in docusaurus 2.0 either). 

cc @JoelMarcey

**Comment by JoelMarcey** [comment]
This is actually not fully a Docusaurus issue, tbh, if at all really. It is how we have some of our domains setup internally and via the CDN we use.

For example, if you go to https://facebook.github.io/docusaurus, you will see it automatically redirects to https://docusaurus.io. And, of course, the Docusaurus site uses Docusaurus. Hydra is another example --- https://facebookresearch.github.io/hydra ==> https://cli.dev. It also uses Docusaurus. The way we have those domains setup are a little different, allowing for redirecting to work correctly.

This is more of fixing some of the underlying infrastructure of the configuration of some of our domains, imho.

**Comment by endiliey** [comment]
I think its because this repo didnt set a CNAME on siteConfig. Thats why it happens. Maybe its worth a try to set CNAME on siteConfig.js so that the built static files will have CNAME like https://github.com/facebookresearch/hydra/blob/gh-pages/CNAME

**Comment by JoelMarcey** [comment]
@endiliey that would be the normal course of action, yes. Like we do for Docusaurus and Hydra in my examples above. But in this case, the way we have our domains set up, it will cause a permanent redirect. (You could test it I suppose, but I am 99% sure I am right here)

That said, remembering a conversation with @zpao, we may just need to point out internal domain directly to GitHub instead of our CDN and figure another way to get a cert going.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Balandat** [comment]
> But in this case, the way we have our domains set up, it will cause a permanent redirect. (You could test it I suppose, but I am 99% sure I am right here)

Yes, I did test this, browser quits b/c of too many redirects.

**Comment by Balandat** [comment]
Reopening until it is verified that this works on the "latest" version of the site (will be auto-deployed over night).

**Comment by Balandat** [comment]
This in fact does not work properly with the versioned site. If you go to https://pytorch.org/botorch/v/latest/index.html then the site realizes that you are in the wrong place, but the redirect takes you to https://botorch.org/v/latest/v/latest/index.html (instead of https://botorch.org/v/latest/index.html), yielding a 404.

**Comment by zpao** [comment]
Hmm, your versioned docs are … special I suppose. `baseURL` in your siteConfig is just `/` which would work. But seems like these docs are spacial and you'll want to do more in here: https://github.com/pytorch/botorch/blob/master/website/core/Footer.js#L100

**Comment by Balandat** [comment]
Indeed. I guess we should handle both the case of `/botorch/` and `/botorch/v/**/`.

**Comment by Balandat** [comment]
deployed new website for the stable version, this issue is mitigated now
