### ISSUE TITLE
Question about fully bayesian treatment for GP hyperparameters

### ISSUE THREAD

**Issue by yjhong89** [pytorch/botorch#334]
Hi. 

While I am studing about botorch's docs and tutorials, I have a question about inferring GP's kernel hyperparamters.

It seems like Botorch infers GP kernel hyperparameters via optimizing GP's likelihood and 
I cannot find a way of fully bayesian treatment of GP's hyperparameters through MCMC (slice sampling or NUTS). Is it implemented in Botorch?

Thanks you.

**Comment by Balandat** [comment]
Thanks for your interest.

Take a look at the [Fully Bayesian](https://github.com/cornellius-gp/gpytorch/blob/master/examples/01_Simple_GP_Regression/Simple_GP_Regression_Fully_Bayesian.ipynb) example in GPyTorch that does just that. Basically, after running NUTS what you end up with is a batched model where each batch dimension corresponds to one hyperparameter sample from the MCMC run. 

We haven't fully hooked this up to be compatible with BoTorch yet, but this should not be too hard to do - essentially we just need to compute the acquisition function for the batched model (resulting in a batch of values), and add an additional marginalization step (across the MCMC samples) at the end. 

cc @qingfeng10

**Comment by Balandat** [comment]
Fully Bayesian inference has been implemented in Ax, see this tutorial for a particular model: https://github.com/facebook/Ax/blob/main/tutorials/saasbo.ipynb
