### ISSUE TITLE
qKnowledgeGradient doesn't support FixedNoiseGaussianLikelihood

### ISSUE THREAD

**Issue by shalijiang** [pytorch/botorch#348]
If we use a model with FixedNoiseGaussianLikelihood, then it will raise the exception:
`raise RuntimeError("FixedNoiseGaussianLikelihood.fantasize requires a 'noise' kwarg")`,

This is because `noise` is not passed in in the qKG implementation? (https://github.com/pytorch/botorch/blob/124223491c2ca22b916588b737894eb576c51870/botorch/acquisition/knowledge_gradient.py#L152)
`fantasy_model = self.model.fantasize(
            X=X_actual, sampler=self.sampler, observation_noise=True
)`

is there an easy way to get around this?

**Comment by shalijiang** [comment]
sorry I misused the model, never mind

**Comment by Balandat** [comment]
Yeah KG with a model with `FixedNoiseGaussianLikelihood` is kind of hairy, b/c we need to fantasize from the posterior including the observation noise - that means we need to do out-of-sample noise predictions, which if we have a `FixedNoiseGaussianLikelihood` does not work - currently the default that happens here is to use the mean noise level from the training data for all test points.

The proper way to do this if the noise level is unknown would be to use a heteroskedastic GP model that can provide OOS evaluations of the posterior including observation noise, but I don't recall if we have fully tested that yet.

If the observation noise level is known (e.g. in some functional parameterization), it can be passed with the `observation_noise ` kwarg to the `posterior` call. The recommended way to use this would be to define a new likelihood that returns the respective noise levels given an `X`, that way the existing functionality can be used so long as `likelihood(mvn, X)` does the right thing (i.e. add the observation noise) for this new likelihood.
