### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'botorch.test_functions.hartmann6'

### ISSUE THREAD

**Issue by aleczhanshi** [pytorch/botorch#359]
# 🐛 Bug

In the closed_loop_botorch_only example, running the downloaded code generate the error "ModuleNotFoundError: No module named 'botorch.test_functions.hartmann6"

**Comment by Balandat** [comment]
Thanks for raising this, this was overlooked in a test function refactor. I'll put up a fix soon.

You can fix this in the notebook by replacing the line `from botorch.test_functions.hartmann6 import neg_hartmann6` with the following: 

```
from botorch.test_functions import Hartmann

neg_hartmann6 = Hartmann(negate=True)
