### ISSUE TITLE
How do compute EI for test data

### ISSUE THREAD

**Issue by hmedal** [pytorch/botorch#375]
If you are submitting a bug report or feature request, please use the respective
issue template.

## Issue description

A pretty simple question but could you help me figure out how to compute the EI value for a set of training points. I am getting an error about a shape mismatch. I confess that I am new to tensors.

## Code example

from botorch.acquisition import ExpectedImprovement

best_value = train_Y.max()
EI = ExpectedImprovement(model=model, best_f=best_value)
x = torch.linspace(0, 1, k)
xx, yy = np.meshgrid(x, x)
xy = torch.cat([Tensor(xx).unsqueeze(-1), Tensor(yy).unsqueeze(-1)], -1)
ei = EI(xy)

I get this error:

AssertionError: Expected X to be `batch_shape x q=1 x d`, but got X with shape torch.Size([100, 100, 2]).

**Comment by Balandat** [comment]
`ExpectedImprovement` is an analytic acquisition function and only operates on single (`q=1`) points. The way you are passing in the data is `q=100`, hence the error. You'll want to reshape this, e.g. as follows: 

```
x = torch.linspace(0, 1, k)
xx, yy = torch.meshgrid(x, x)  # 10 x 10 each
test_X = torch.stack([xx.unsqueeze(-1), yy.unsqueeze(-1)], dim=-1)  # 10 x 10 x 1 x 2
ei = EI(test_X)
```

This evaluates EI in batch mode using a batch shape of `10 x 10` (according to your meshgrid layout). You can also evaluate with a single batch dimension (that's what one would usually do) using 

```
test_X = torch.stack([xx.reshape(-1, 1), yy.reshape(-1, 1)], dim=-1). # 100 x 1 x 2
```

**Comment by hmedal** [comment]
Thanks a lot Max.
