### ISSUE TITLE
[Feature Request] Obtain parameter and objective values in Ax example

### ISSUE THREAD

**Issue by aleczhanshi** [pytorch/botorch#382]
# 🚀 Variables in Ax
In Ax, how should we go about getting the actual values of the optimized parameters and the objective values? For example, in the tutorial below, it does not print anything at the end and does not python variables (float, int) that can be read and printed.

https://github.com/pytorch/botorch/blob/master/tutorials/custom_botorch_model_in_ax.ipynb

**Comment by Balandat** [comment]
This is more of an Ax question than a BoTorch question. 

The trials that are generated as well as the observations made get attached to the Ax `Experiment` object.

You can use `exp.eval().df` to show a pandas Dataframe of the observations made so far.

You can use the following snippet to generate a Dataframe with the parameters of the generated candidates (called "arms" in Ax): 
```
pd.DataFrame.from_dict(
    {name: arm.parameters for name,arm in exp.arms_by_name.items()},
    orient="index",
)
```

We may want to document this in Ax, provide some simple utilities for this (and joining the two dfs), either on the experiment object or as helpers. @ldworkin 

I can also add this to the tutorial to have everything in one place.

**Comment by ldworkin** [comment]
@aleczhanshi , @Balandat -- the Ax tutorial here has a little more detail on this: https://ax.dev/tutorials/gpei_hartmann_developer.html#5.-Inspect-trials'-data. But I agree that we could do better, and I'm making a todo for us to improve the documentation around this.

@aleczhanshi , let us know if using `eval()` suffices for your use case, or if you'd like further instructions. Thanks!

**Comment by Balandat** [comment]
Assuming this is resolved, please re-open if not.
