### ISSUE TITLE
[Feature Request] Example notebook explaining how to use REMBO model

### ISSUE THREAD

**Issue by roshni-kamath** [pytorch/botorch#385]
# 🚀 Feature Request

I am not sure how REMBO or REMBOStrategy is used with any acquisition function. Can an example be given so that its understood ?

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

**Comment by Balandat** [comment]
Do you mind opening this issue over at https://github.com/facebook/Ax? That's the right place for it. Thanks.
