### ISSUE TITLE
Can I specify the candidates generated by optimize_acqf to be int?

### ISSUE THREAD

**Issue by WeijingDai** [pytorch/botorch#390]
Does the options kwarg in optimize_acqf work for my question?
Thanks

**Comment by Balandat** [comment]
No. `optimize_acqf` will perform optimization over a continuous domain. There are different ways of dealing with this. If the size of your discrete space is small enough, the easiest would just be to enumerate it, batch-evaluate the acquisition function, and pick the max.

If it's too large for that you can do a continuous relaxation of your parameters and use standard GP models, the optimize the continuous relaxation and round to the nearest int. This will often work reasonably well in practice.

**Comment by WeijingDai** [comment]
Well noted, so quick!

**Comment by Balandat** [comment]
Going to close this for now, feel free to re-open if you have additional questions.
