### ISSUE TITLE
[Bug] compare_mc_analytic_acquisition.ipynb

### ISSUE THREAD

**Issue by hmedal** [pytorch/botorch#391]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
Run line [1] of this tutorial:
https://github.com/pytorch/botorch/blob/master/tutorials/compare_mc_analytic_acquisition.ipynb

** Stack trace/error message **
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-994648610aac> in <module>
      3 from botorch.fit import fit_gpytorch_model
      4 from botorch.models import SingleTaskGP
----> 5 from botorch.test_functions import neg_hartmann6
      6 from gpytorch.mlls import ExactMarginalLogLikelihood

ImportError: cannot import name 'neg_hartmann6' from 'botorch.test_functions' (/anaconda2/envs/botorch-pyro/lib/python3.8/site-packages/botorch/test_functions/__init__.py)
```

## System information

- BoTorch Version:  0.2.1
- GPyTorch Version:  1.0.1
- PyTorch Version:  1.4.0
- Computer OS:  macOS-10.14.6-x86_64-i386-64bit

## Additional context

This may already be fixed but I wanted to mention it anyway. I used the same fix as you mentioned in #359 and it is working now.

**Comment by Balandat** [comment]
Thanks for raising this, we must have missed that. We need to do a better job at running the tutorials against all code changes. 

Actually, while looking into this I discovered some other issues with `gen_candidates_torch`, let me fix these and put up a PR to fix things jointly.
