### ISSUE TITLE
[Feature Request] Optimize parameters with fixed choices and discrete values

### ISSUE THREAD

**Issue by aleczhanshi** [pytorch/botorch#400]
Hi there,

I'm trying to follow this tutorial (https://botorch.org/tutorials/closed_loop_botorch_only) to implement my optimization problem in BoTorch. In my problem, the type of parameters are mainly `integers with fixed choices (e.g. 2, 4, 8, 10, 16)` and `discrete values ("A", "B", "C")`. Could you please show me a way to implement them in the tutorial?

THANKS!

**Comment by Balandat** [comment]
So on a high-level there are two things do do:
1. Deal with the categorical variable somehow. You can do a one-hot encoding a simple approach (but that would't really allow you to borrow strength across observations from related parameters), or do something fancier like train an embedding. Probably easiest to start with the one-hot encoding.
2. Optimize over the mixed continuous-discrete space. If the cardinality of the space discrete space is low, then you can enumerate the values, and then optimize the continuous parameters for each. To do this, you can define your preferred acquisition function on your model, loop through the parameter configurations, for each configuration wrap the acquisition function in a `FixedFeatureAcquisitionFunction` with the respective parameters, and then optimize it using `optimize_acqf`.

**Comment by aleczhanshi** [comment]
@Balandat Thanks for the quick reply. Actually I'm wondering how to actually implement integers with fixed choices and discrete parameters in the code, not really the high-level strategy. In particular, the function `optimize_acqf` only takes the lower and upper bounds, instead of the possible choices. How could I specify the potential values (e.g. interger from 2, 4, 8, and a categorical parameter) of these parameters in the optimization of the acquisition function, to make sure the generated parameters are valid? 

Could you give me a pointer to any reference that implements something like this?

**Comment by Balandat** [comment]
`optimize_acqf` only deals with continuous parameters. You can do a continuous relaxation (e.g. optimize over `[2, 16]` and round to the nearest integer. For the categorical parameter you could similarly do a one hot encoding go `{0, 1, 2}, optimize over `[0, 2]` and round to the nearest int. But if you don't have a lot of values the better strategy is the one I outlined above, where you manually optimize by enumerating the discrete combination.

**Comment by aleczhanshi** [comment]
Thanks the relaxation-and-round solution helps!

**Comment by Balandat** [comment]
Hi @talesa, sorry for the delayed response. Yes, this looks good to me!
