### ISSUE TITLE
[Question] Support for minimization

### ISSUE THREAD

**Issue by DavidWalz** [pytorch/botorch#402]
For minimizing my black-box function `y` I can always maximize `-y`.
However, since the analytic acquisition functions (noisy/constrained)EI, PI and UCB support minization via `maximize=False` while the others don't, I was wondering if you plan to implement the `maximize` argument for each acquisition.
Would a negating `OutcomeTransform` or `AcquisitionObjective` be an alternative?

**Comment by Balandat** [comment]
We could support that, but it seems kind of a lot of machinery for flipping a sign. 

> Would a negating OutcomeTransform or AcquisitionObjective be an alternative? 

Sure. we could give `AcquisitionObjective` a `negate` kwarg to carry through. I think that would make more sense than doing this in the outcome transforms.

**Comment by DavidWalz** [comment]
> We could support that, but it seems kind of a lot of machinery for flipping a sign.
Definitively. My thinking was that if there is way to support minimization independent of the acquisition, then not having the `maximize` kwarg in the analytic acquistions woud make it feel more consistent. I know where to look now, thanks!
