### ISSUE TITLE
Questions about acquisition function on discrete domain

### ISSUE THREAD

**Issue by WeijingDai** [pytorch/botorch#420]
Hi, I encountered some situation that there are multiple equal maximum appearing in the acquisition function when I used discrete domains. Any suggestion on how to select the proper candidate in this scenario for next iteration? 
Thank you very much for any comments
Weijing

**Comment by Balandat** [comment]
What acquisition function are you using? 

There isn't a great general answer to this. I assume you're in a sequential setting, i.e. where you get evaluation results of a candidate back before choosing the one? In that case the most obvious thing to do would be to pick one of the maximizers at random.

**Comment by WeijingDai** [comment]
Thanks for the quick reply. I am using ucb as the acquisition function and in a sequential setting. 
The loop started with 10 initial points and in discrete domain. At each iteration, the value of the acquistion function for every possible point were calcualted, and I just used torch.argmax() to extract the candidate for next iteration. However, when I further checked the value of acquisition function, I found multiple maximizers. How the torch.argmax() determine which maximizer to return also puzzles me.

**Comment by Balandat** [comment]
That seems reasonable.

> How the torch.argmax() determine which maximizer to return also puzzles me.

I don't think we can count on any consistency there in terms of tie-breaking if there are multiple maximizers, see [this discussion](https://discuss.pytorch.org/t/function-torch-max-return-indices-inconsistency-between-cup-and-gpu/1890). But in this case it seems that the particular tie breaking shouldn't really matter.

**Comment by Balandat** [comment]
Feel free to reopen if this doesn't clarify things.

**Comment by WeijingDai** [comment]
Thanks for the explanation. Since torch.argmax() only return one value, is it reasonable to extract some more equal maximizers and randomly select one from it? Or will a batch run be more efficient?

**Comment by Balandat** [comment]
> Since torch.argmax() only return one value, is it reasonable to extract some more equal maximizers and randomly select one from it? 

That would be a reasonable thing to do, but how often do you expect there to be multiple maximizers? Seems unlikely in non-degenerate settings. 

> Or will a batch run be more efficient?

What do you mean by that? Evaluating all the maximizers of your acquisition function? Or using a batch acquisition function? If you want to run a batch anyway, you should do the latter.

**Comment by WeijingDai** [comment]
Thank you very much. I get the answer. Such a nice team here
