### ISSUE TITLE
supporting "qUCB" and "UCB" acquisition functions for Multi-step look-ahead acquisition

### ISSUE THREAD

**Issue by zhangyanhui86** [pytorch/botorch#431]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

**Comment by zhangyanhui86** [comment]
Recently I tried to use Botorch on multi-objective optimization. I find Multi-step look-ahead strategy to improve the convergence performance. And I also find the "qUCB" and "UCB" acquisition functions are better than other acquisition functions.
So could the Multi-step look-ahead method support the "qUCB" and "UCB" acquisition functions?

**Comment by Balandat** [comment]
> I also find the "qUCB" and "UCB" acquisition functions are better than other acquisition functions.

I guess that will depend on the particular circumstances, but sure there will be cases where UCB-type acquisition functions will perform well. 

You're working off #410, I take it? Just a warning that this is still in development and the interface may change going forward. You should be able to use UCB acquisition by passing in the class via `valfunc_cls` and setting up the appropriate `valfunc_argfacs` for generating the `beta` parameter.

**Comment by zhangyanhui86** [comment]
Thank you very much for your quick reply.
I also run the example provied in #410. The code is as fllowing:
"
import itertools

import torch

from botorch.acquisition.multi_step_lookahead import qMultiStepLookahead
from botorch.models import SingleTaskGP
from botorch.optim import optimize_acqf
from botorch.acquisition import ExpectedImprovement, qExpectedImprovement

# Toy model
train_X = torch.rand(5, 1)
train_Y = torch.cos(train_X)

bounds = torch.stack([torch.zeros(1), torch.ones(1)])

model = SingleTaskGP(train_X, train_Y)

from botorch.acquisition import UpperConfidenceBound


q = 1
beta = 10.0

qMS = qMultiStepLookahead(
    model=model,
    batch_sizes=[1, 1],
    num_fantasies=[1, 1], # [4, 3],
    valfunc_cls=[UpperConfidenceBound, UpperConfidenceBound, UpperConfidenceBound],
    valfunc_argfacs=[beta, beta, beta],
)

q_prime = qMS.get_augmented_q_batch_size(q)
eval_X = torch.rand(q_prime, 1)


val = qMS(eval_X)

cands, vals = optimize_acqf(
    acq_function=qMS,
    bounds=bounds,
    q=q_prime,
    num_restarts=4,
    raw_samples=16,
)
print('cands:', cands)

"
But return the error as fllowing:
"
TypeError: 'float' object is not callable
"
Please forgive me for being a new person in Botorch. But Botorch is a very good project. 
Thank you very much for your help.

**Comment by Balandat** [comment]
the argfacs need to be factory functions, see the docstring:
> Allows to specify the stage value functions by passing the respective class objects via the `valfunc_cls` list. Optionally, `valfunc_argfacs` takes a list of callables that generate additional kwargs for these constructors.

**Comment by zhangyanhui86** [comment]
Dear Mr Balandat, could you give me a clearer examples for this factory functions about "beta" used in "qUCB" and "UCB"? I have try several factory functions, but unfortunately, they all failed.
Thank you very much for your help.

**Comment by Balandat** [comment]
You'll probably just want sth trivial like

```
def make_beta(model: Model, X: Tensor) -> Dict[str, Any]:
    return {"beta": 0.1}
```

**Comment by zhangyanhui86** [comment]
The problem has been solved. Thank you very much for your help, Dear Mr Balandat.
