### ISSUE TITLE
[Feature Request] Train objective GP and constraint GP with different data

### ISSUE THREAD

**Issue by aleczhanshi** [pytorch/botorch#433]
Hi there,

I'm working on this tutorial but customizing for my own use case (https://botorch.org/tutorials/closed_loop_botorch_only). In particular, I have an objective GP and a constraint GP, as in the tutorial. The difference is that the constraint is a hard constraint, which means if not met, I should not and cannot generate any output to train the objective GP.

Therefore, the objective GP and constraint GP need to train on different data. But together they need to be fed into the `qNoisyExpectedImprovement` function through the parameter `model`. 

Below is the code in the tutorial. 

```python
model_obj = FixedNoiseGP(train_x, train_obj, train_yvar.expand_as(train_obj)).to(train_x)
model_con = FixedNoiseGP(train_x, train_con, train_yvar.expand_as(train_con)).to(train_x)
# combine into a multi-output GP model
model = ModelListGP(model_obj, model_con)

......   

qNEI = qNoisyExpectedImprovement(
    model=model_nei, 
    X_baseline=train_x_nei,
    sampler=qmc_sampler, 
    objective=constrained_obj,
)
```

My question is, is it possible to train `model_obj` and `model_con` separately, and then combine them with `ModelListGP` and feed them to `qNoisyExpectedImprovement`?

**Comment by Balandat** [comment]
That should be possible, provided the domain of the models is the same (which it seems from your example it is).

The acquisition functions have very few assumptions on what the `model` is, so long as it implements the barebones `Model` interface. So if you first fit the models individually, and then stick them together into a `ModelListGP` that  should work (note that `ModelListGP` currently only works with single-outcome models):
```
model_obj = FixedNoiseGP(train_x, train_obj, train_yvar.expand_as(train_obj)).to(train_x)
mll_obj = ExactMarginalLogLikelihood(model_obj.likelihood, model_obj)
fit_gpytorch_model(mll_obj)

model_con = FixedNoiseGP(train_x, train_con, train_yvar.expand_as(train_con)).to(train_x)
mll_con = ExactMarginalLogLikelihood(model_con.likelihood, model_con)
fit_gpytorch_model(mll_con)

model = ModelListGP(model_obj, model_con)
```

**Comment by aleczhanshi** [comment]
Thanks it works!
