### ISSUE TITLE
Question about obj.clamp_min(0)

### ISSUE THREAD

**Issue by aleczhanshi** [pytorch/botorch#438]
Hi there,

I'm building on top of the constrained BO tutorial (https://botorch.org/tutorials/closed_loop_botorch_only). When I'm drilling down into the constrained objective (ConstrainedObjective) used in the code, before the constraints are applied on the objective, the objective is clamped to 0. https://github.com/pytorch/botorch/blob/4302a0c6f70f028c65289f6bf5519ad8562b5663/botorch/utils/objective.py#L85

What is the purpose of the clamp? Does that prevent negative objective values? If my objective value can be negative, should I remove this line?

**Comment by Balandat** [comment]
This is b/c we're multiplying the objective vale with a probability, which only makes sense if the that value is positive, If your objective is negative you can specify an `infeasible cost` [here](https://github.com/pytorch/botorch/blob/4302a0c6f70f028c65289f6bf5519ad8562b5663/botorch/utils/objective.py#L140) or further up in the stack [here](https://github.com/pytorch/botorch/blob/4302a0c6f70f028c65289f6bf5519ad8562b5663/botorch/acquisition/objective.py#L219) to appropriately shift the values.
