### ISSUE TITLE
[Bug] PyPI broken

### ISSUE THREAD

**Issue by to-mi** [pytorch/botorch#444]
# 🐛 Bug

PyPI wheel seems still broken in version `0.2.4` (#442).

## To reproduce

Install fresh `botorch` using `pip`. For example,

```
conda create -n botorch_tmp python pip
conda activate botorch_tmp
pip install botorch
```

Try importing `botorch` in Python:

```python
import botorch
```

** Stack trace/error message **
```
ImportError: cannot import name 'batched_multinomial' from 'botorch.utils.sampling' (/home/USER/anaconda3/envs/botorch_tmp/lib/python3.8/site-packages/botorch/utils/sampling.py)
```

## Expected Behavior

Able to import botorch.

## Additional context

One can also just download the wheel from PyPI, unzip, and check the `botorch/utils/sampling.py` file. It seems to be a wrong version, missing functions.

**Comment by Balandat** [comment]
Thanks for flagging, apologies for the inconvenience. 

This is really weird, I am at a loss as to what's going on. As will all other previous releases, I built the wheel and source dist together from the release commit using `python setup.py sdist bdist_wheel`, so they were generated the same way. The `.tar.gz` source dist is fine and doesn't have this issue. The conda package that works fine was created from the same commit. So this must be something related to the packaging of the wheel. 

The only thing that I can think of here is that I realized after the fact that a recent MacOS upgrade had somehow broken my conda installation, which had caused really weird build issues with the conda package. I wonder if the underlying reason for that is what caused the issues with the wheel. 

Either way, after purging conda from my machine and re-installing, at this point I can verify that the wheel I generate from `python setup.py sdist bdist_wheel` locally does indeed have the full source code. Let me do some more due diligence and then release a new version.

**Comment by Balandat** [comment]
Hmm so for some weird caching reason the `python setup.py sdist bdist_wheel` build must have used some old cached files for the wheel. Looking at the diff of the wheel content against the 0.2.4 release commit, there is a lot of old code in there. It's still a mystery as to why.

**Comment by Balandat** [comment]
I put up a new release 0.2.5, uploaded pypi and conda packages, and deleted the broken wheels from 0.2.3 and 0.2.4. Let me know if you're still running into issues on the new version (in which case I will probably just go insane). 

I still haven't figured out what caused these broken wheels, my best guess is some caching issue putting old code into the wheels b/c of the MacOS upgrade breaking my conda installation.

**Comment by to-mi** [comment]
Thank you for the fast response and fixing the issue! Importing works after upgrading to 0.2.5 through pip.
