### ISSUE TITLE
Bug in MultiTaskGP Example

### ISSUE THREAD

**Issue by hmedal** [pytorch/botorch#446]
## Issue description
The example given for MultiTaskGP throws an error when I run it.

## Code example

When I run the example given for MultiTaskGP (https://botorch.org/api/models.html#botorch.models.multitask.MultiTaskGP), it throws this error:

RuntimeError                              Traceback (most recent call last)
<ipython-input-26-12e9f514abe5> in <module>
      7 print(torch.cat([X1, i1], -1))
      8 print(torch.cat([X2, i2], -1))
----> 9 train_X = torch.stack([torch.cat([X1, i1], -1), torch.cat([X2, i2], -1)])
     10 train_Y = torch.cat(f1(X1), f2(X2))
     11 print(train_Y)

RuntimeError: stack expects each tensor to be equal size, but got [10, 3] at entry 0 and [20, 3] at entry 1

Also, line 10 (train_Y = torch.cat(f1(X1), f2(X2))) gives the following error:

TypeError: cat() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (tuple of Tensors tensors, name dim, *, Tensor out)
 * (tuple of Tensors tensors, int dim, *, Tensor out)

## System Info
Please provide information about your setup, including
- BoTorch Version: 0.2.4
- GPyTorch Version: 1.1.1
- PyTorch Version: 1.5.0
- Computer OS: Mac OSX Catalina

**Comment by Balandat** [comment]
Thanks for flagging, that should just be a `.cat`, not a stack. Fixed in #447

**Comment by hmedal** [comment]
Thanks. If you don't mind, would you mind answering a few questions I have?

- Can you tell me why we are doing `.cat` with X1 and i1 (as well as X2 and i2)?
- Can you explain what the task_feature parameter is and why we set it to -1?
- if I only have one input vector but have two outputs (i.e, `train_Y = torch.cat([f1(X), f2(X)])`) how would I change the code?

**Comment by hmedal** [comment]
Also, I am getting an error when I run this example file:

https://github.com/pytorch/botorch/files/3894750/botorch_MTGP_objective.ipynb.txt

Would you mind telling me how to fit it?

```
---------------------------------------------------------------------------
BotorchTensorDimensionError               Traceback (most recent call last)
<ipython-input-2-95504ab225f8> in <module>
     13 
     14 # not specify output_tasks will give an output for each task
---> 15 model = MultiTaskGP(train_X, train_Y, task_feature=1)
     16 mll = ExactMarginalLogLikelihood(model.likelihood, model)
     17 fit_gpytorch_model(mll);

~/opt/anaconda3/envs/bayesopt/lib/python3.8/site-packages/botorch/models/multitask.py in __init__(self, train_X, train_Y, task_feature, output_tasks, rank)
     76             >>> model = MultiTaskGP(train_X, train_Y, task_feature=-1)
     77         """
---> 78         self._validate_tensor_args(X=train_X, Y=train_Y)
     79         validate_input_scaling(train_X=train_X, train_Y=train_Y)
     80         if train_X.ndim != 2:

~/opt/anaconda3/envs/bayesopt/lib/python3.8/site-packages/botorch/models/gpytorch.py in _validate_tensor_args(X, Y, Yvar, strict)
     82                         f" {Y.dim()}."
     83                     )
---> 84                 raise BotorchTensorDimensionError(message)
     85         else:
     86             warnings.warn(

BotorchTensorDimensionError: An explicit output dimension is required for targets. Expected Y with dimension: 1 (got 2).
```

**Comment by Balandat** [comment]
> Can you tell me why we are doing .cat with X1 and i1 (as well as X2 and i2)?

We're basically putting the `n x d` features and the `n x 1` task indices into a `n x (d+1)` tensor since that is what the model expects

> Can you explain what the task_feature parameter is and why we set it to -1?

That tells the model which of the columns of the input contains the task feature. Since we're concatenating at the end the column is the last one (-1, indexing from the back). 

> if I only have one input vector but have two outputs (i.e, train_Y = torch.cat([f1(X), f2(X)])) how would I change the code?

Actually it wouldn't. You just consider the tasks as outputs. Then the model models the outputs jointly and estimates the correlation between them. As the tasks represent your outputs, to predict output `i` you;'d use task index `i` in the input passed to the `posterior` function.

**Comment by Balandat** [comment]
Regarding the error, the `An explicit output dimension is required for targets` message gives it away. Your training input always has to have an explicit output dimension, even if there is only a single one. We have made this a requirement a while ago.  You can get this by changing the construction to `full_train_y = torch.cat([train_y1, train_y2]).unsqueeze(-1)`

Note that later on in the code you'll run into a `Must specify an objective when using a multi-output model.` error - as the name suggests, if the model has multiple outputs (which by default the multitask model does, unless you specify the `output_tasks` argument) then you need to specify an objective. If you want to only work with a single output, it makes sense to specify it via `output_tasks`.

May I ask where you got this example file from? If this is hosted somewhere in the docs / on the website we need to update it.

**Comment by hmedal** [comment]
Thanks a lot Max. I am asking all of these questions because I am collaborating with some materials scientists on a paper in which we do a little bit of prediction using a multi-output GP. Feel free to close the issue.

Regarding the file, I found it in this issue:

https://github.com/pytorch/botorch/issues/325

**Comment by hmedal** [comment]
Another question regarding the example (https://github.com/pytorch/botorch/files/3894750/botorch_MTGP_objective.ipynb.txt) if you don't mind. If I wanted to get the posterior means for task 1 (i.e., the one corresponding to `y1`) for a `test_x`, would that just be `mean[:,0]`? I tried this, but the predictions do not correspond to the function `sin(2*pi*x)`. (When I do `mean.flatten()` and take the first half of the values, the predictions do line up.) Probably I am making a simple mistake.

**Comment by Balandat** [comment]
Actually, this is a bug in how we re-arrange the outputs - thanks for flagging. I'll put up a fix.

**Comment by mutianzh** [comment]
Hi,
It seems that there is still a bug in task_feature. I'm using @hmedal 's code here:
My input dimension is 1, so train_X has two columns and the last column is the index column.
I use FixedNoiseMultiTaskGP with zero noise and print out the posterior mean of the first 4 training data. If I set task_feature = 1, posterior means will be exactly the same as the true values in train_Y, but if I set task_feature = -1 (It is supposed to select the last column as well), posterior means are completely different.
```
import math

import torch
from botorch.fit import fit_gpytorch_model
from botorch.models.multitask import MultiTaskGP, FixedNoiseMultiTaskGP
from gpytorch.mlls.exact_marginal_log_likelihood import ExactMarginalLogLikelihood

# generate a toy model on random data
train_x = torch.linspace(0, 0.95, 10) + 0.05 * torch.rand(10)
train_y1 = torch.sin(train_x * (2 * math.pi)) + torch.randn_like(train_x) * 0.2
train_y2 = torch.cos(train_x * (2 * math.pi)) + torch.randn_like(train_x) * 0.2
train_i_task1 = torch.full_like(train_x, dtype=torch.long, fill_value=0)
train_i_task2 = torch.full_like(train_x, dtype=torch.long, fill_value=1)
full_train_x = torch.cat([train_x, train_x])
full_train_i = torch.cat([train_i_task1, train_i_task2])
full_train_y = torch.cat([train_y1, train_y2])

train_X = torch.stack([full_train_x, full_train_i.type_as(full_train_x)], dim=-1)
train_Y = full_train_y.unsqueeze(-1)
noise = torch.full_like(train_Y, dtype=torch.long, fill_value=0)
# print(train_X)
# print(train_Y)
# print(train_X.shape)
# print(train_Y.shape)
# not specify output_tasks will give an output for each task
model = FixedNoiseMultiTaskGP(train_X, train_Y, noise, task_feature=1)
mll = ExactMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_model(mll);

test_x = train_X[:4,:1]
print(test_x)
# # test_x = torch.rand(3, 1)
# # print(test_x)
p = model.posterior(test_x)
print(p.mean)
print(train_Y)
```

**Comment by Balandat** [comment]
Good catch, there was something wrong with the backward indexing. I guess that says something about our unit tests for the multitask model - will need to increase quality of those to better catch these issues. Fixed in the PR above.
