### ISSUE TITLE
[Feature Request] Simplex constraint on parameters

### ISSUE THREAD

**Issue by Balandat** [pytorch/botorch#484]
# 🚀 Feature Request

We'd like to support a simplex constraint on a subset of parameters (all parameters positive, sum to 1). 

## Motivation

See e.g. discussion in #480

**Comment by sdaulton** [comment]
This issue in #480 is more related to equality constraints with transformed parameters, right? Subsetting is already supported (as long as you know what the subset(s) are that you want to enforce a simplex constraint on) by using weights in  {0, 1} on the parameters in the equality constraint.

**Comment by Balandat** [comment]
I guess this is something we haven't really tested much in botorch. It definitely would be something that is currently not supported explicitly in Ax (other than using two one-sided inequality constraints, which has its own issues and won't work in Ax b/c of how we do point generation).

**Comment by esantorella** [comment]
This should be doable with the `bounds` and `equality_constraints` arguments to `optimize_acqf`.
