### ISSUE TITLE
[Bug] Error in constraint slack calculation in ConstrainedBraninCurrin class

### ISSUE THREAD

**Issue by jayl940712** [pytorch/botorch#489]
Hi. I believe there is a possible error in the constraint slack calculation in ConstrainedBraninCurrin class.

In botorch/test_functions/muti_objective.py on line 576:
X_tf = unnormalize(X, self.con_bounds)
Should be :
X_tf = unnormalize(X, self.con_bounds.t())

The current results I think produce incorrect mappings x1: (-5,0) and x2:(10,15) which is inconsistent with the paper.
Thanks!

**Comment by Balandat** [comment]
Thanks for reporting, looking into it.

**Comment by sdaulton** [comment]
Yep, good catch. Thanks! I'll put up a diff later today

**Comment by jayl940712** [comment]
Thank you. Would there be updated tutorials for Constrainted Multi-Objective problems in the future?

**Comment by sdaulton** [comment]
Yeah, adding a constrained tutorial is on my todo list. I’ll open an issue for that and prioritize getting that in ASAP

**Comment by jayl940712** [comment]
Thank you @sdaulton. I am a bit confused what MCMultiOutputObjective() to pass to qExpectedHypervolumeImprovement. It would be much clearer with a tutorial!

**Comment by sdaulton** [comment]
Constrained MOO tutorial added in https://github.com/pytorch/botorch/pull/493
