### ISSUE TITLE
[Bug] model.train_targets returns transformed training outcomes

### ISSUE THREAD

**Issue by saitcakmak** [pytorch/botorch#495]
# 🐛 Bug

When using a GP model with an `outcome_transform`, `model.train_targets` returns the transformed training outcomes and not the original values. I am not sure if this is an actual bug or the intended behavior, but I would expect to get the original training outcomes without having to manually un-transform `model.train_targets`. A typical use case (where the un-transformed values are needed) is plotting the posterior mean of the GP, along with the training samples.

## To reproduce

The assertion will fail. Alternatively, one can print `train_Y` and `model.train_targets`.

```python
import torch
from botorch.models import SingleTaskGP
from botorch.models.transforms import Standardize

n = 10
dim = 2
train_X = torch.rand(n, dim)
train_Y = torch.rand(n, 1)

model = SingleTaskGP(train_X, train_Y, outcome_transform=Standardize(m=1))
assert torch.all(model.train_targets == train_Y.reshape(-1))
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/snap/pycharm-professional/209/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/209/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/saitcakmak/PycharmProjects/ttsKG/plot_gp_test.py", line 17, in <module>
    assert torch.all(model.train_targets == train_Y.reshape(-1))
AssertionError
```

## Expected Behavior

I would expect `train_Y` and `model.train_outcomes` to share identical data.

## System information

**Please complete the following information:**
BoTorch 0.3.0
GPyTorch 1.1.1
PyTorch 1.5.1

**Comment by sdaulton** [comment]
Yeah this is known and not really a bug. The botorch models manipulate the training data under the hood. For example, if you are using a BatchedMultiOutputGPyTorchModel, the provided training targets `train_Y` with shape `n x m` would be result in `model.train_targets` with shape `m x n` under the hood (where m is a batch dimension). As you have observed, the original training data that `train_Y` refers to is unchanged.
