### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'botorch.test_functions.multi_objective'

### ISSUE THREAD

**Issue by yifeng-li** [pytorch/botorch#503]
# 🐛 Bug

I hit the following error when trying to reproduce https://botorch.org/tutorials/multi_objective_bo

## To reproduce

** Code snippet to reproduce **
```python
>>> import botorch
>>> print(botorch.__version__)
0.1.4
>>> from botorch.test_functions.multi_objective import BraninCurrin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'botorch.test_functions.multi_objective'

>>> from botorch.utils.multi_objective.scalarization import get_chebyshev_scalarization
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'botorch.utils.multi_objective'

```

** Stack trace/error message **
```
// Paste the bad output here!
```

## System information

**Please complete the following information:**
- 
- 
- 
-

**Comment by Balandat** [comment]
According to your debug printout you're on a very old version (0.1.4). If you update to the most recent one (0.3.0) things should work. May need to do `pip install --upgrade` to force the update.
