### ISSUE TITLE
Multi-fidelity Bayesian Optimization

### ISSUE THREAD

**Issue by rima2992** [pytorch/botorch#570]
Hello, 
i am trying to implement a multi-fidelity bayesian optimization to solve an inverse problem. I have two sources for my data: an analytical solution, which is fast and cheap and a simulation, which is very slow. I read the tutorial about mfKG but in this example the fidelity level is random from 0 to 1. Can I use this example for my case and bound the  fidelity-levels to be either 0 or 1? Or what would be a suggestion for an acquisition function to predict the next fidelity-level? 
Thank you !

**Comment by Balandat** [comment]
We added a new tutorial for this here: https://github.com/pytorch/botorch/blob/master/tutorials/discrete_multi_fidelity_bo.ipynb, hopefully this helps.
