### ISSUE TITLE
Implementing a cost function to reward or penalize the acquisition function

### ISSUE THREAD

**Issue by faranirshad** [pytorch/botorch#579]
## Issue description

Thanks for the nice botorch package. I had a question regarding the implementation of a custom cost function that I need to put in directly to either penalize or reward the acquisition function. I wanted to do this with the MES where I would like it to search around certain points. I wanted some advise on what would be the best way to go about this using botorch and if there is already something (I could not find it ) in the botorch that allows me to penalize/reward or in any way change the values of the acquisition functions in the input parameter space. Looking forward to your response. Thanks.

## System Info
Please provide information about your setup, including
- BoTorch Version (0.3.0)
- GPyTorch Version (1.2.0)
- PyTorch Version (1.6.0)
- Windows 10 (10.0.18363)

**Comment by Balandat** [comment]
This is pretty straightforward to do in botorch, the most obvious way is sth along the lines of

```
class MyPenalizedqEI(qExpectedImprovement):

    def forward(self, X):
        val = super().forward(X)
        return val - my_penalty_function(X)
```

We've actually played around with this ourselves, and have implemented of a generic wrapper that can wrap arbitrary acquisition functions and use apply custom penalty functions. We can put this up and add it to the library if that would be useful (your question makes clear that it would). 

@abbas-kazerouni, is this something you could put up a PR for soon?

**Comment by faranirshad** [comment]
Thanks @Balandat  for the reply. I will definitely try this, seems pretty straight forward. One more quick question. I am doing a Multi-fidelity optimization using the MF-MES. I have a discrete fidelity space (something like 2 or 3 fidelity level). As I see it now the MF-MES works on continuous fidelity spaces. I was thinking of maybe discretizing just by rounding the fidelity to integers but I am not sure if this is right approach. Do you have any ideas how do I go about this? Is there any native support for mixed-domain optimization in botorch where I can have the normal input space to be continuous and a fidelity space that is discrete?

**Comment by eytan** [comment]
I would recommend starting with using an ICM kernel for the different tasks.  I am not familiar w/ the MF-MES implementation, but for KG it's pretty easy to just evaluate the KG objective with some given "fixed feature" for all 2 or 3 discrete fidelity values and pick the max.  I would imagine the same is possible for MF-MES.

**Comment by Balandat** [comment]
@faranirshad Regarding the penalized acquisition functions, this functionality has been landed to master in #585 and is part of the recent 0.3.2 release.

**Comment by faranirshad** [comment]
@eytan  Thanks for this idea. If I understand correctly I can either evaluate the KG/MES objective for all the fidelity values and can then scale with cost and chose the max or just evaluate the multi fidelity versions of these two with a generic cost aware utility. Both approaches are essentially the same right? 
I will try this. 
@Balandat Thanks for this. Much appreiciated.

**Comment by liangshi7** [comment]
> I would recommend starting with using an ICM kernel for the different tasks. I am not familiar w/ the MF-MES implementation, but for KG it's pretty easy to just evaluate the KG objective with some given "fixed feature" for all 2 or 3 discrete fidelity values and pick the max. I would imagine the same is possible for MF-MES, but perhaps somebody else(cc @liangshi7, @bkarrer, @danielrjiang) can chime in here.

Given that 1) MES and KG basically share the same abstraction and 2) "fixed feature" seems to me more specific to the optimization stage (not specific to the acquisition function), "fixed feature" should also applicable to MES or MF-MES.

**Comment by faranirshad** [comment]
So I was trying to use MultiTaskGP for modelling 2 or 3 fidelities since it already is implemented with an ICM kernel. The problem that I run into is that the MF-MES accepts only single output models. I then used the output_task feature of the MutliTask to get a single output model (the idea was to get these single output models and then use the MF-MES to optimize the these single models and then select the max from them to be the next point). 

The problem that I face now is that the MF-MES has internal dimensions check on the candidate_set(used to generate max values) and the train_x it gets from the MultiTaskGP (which has an extra column with the task feature). How do I get across this problem? I do need the task feature for the column in the MultiTask. Any help would be appreciated. Thanks

**Comment by danielrjiang** [comment]
@faranirshad, interesting problem. We didn't test this specific use case, but since you now have a single-output model by setting output_task, I believe you can now use FixedFeatureAcquisition as @eytan suggested to fix the task feature during optimization. My guess for the dimensions check issue is that you may also need to generate a candidate set that has the task_feature (just keep it fixed to whichever value you're using).

**Comment by Balandat** [comment]
Assuming this has been resolved, feel free to re-open if needed.
