### ISSUE TITLE
[Bug] Issues with qKG.evaluate()

### ISSUE THREAD

**Issue by saitcakmak** [pytorch/botorch#587]
# 🐛 Bug

i) This line raises an `AttributeError` with models that do not have an `_input_batch_shape` attribute. (#578 as an example)
https://github.com/pytorch/botorch/blob/7e2a4040e60c6351ff127d6ff65506955c2beccb/botorch/optim/initializers.py#L328

ii) Since it is a subclass of `qKnowledgeGradient`, `qMultiFidelityKnowledgeGradient` has `evaluate` method implemented. However, the current implementation ignores the `project` operator in the inner optimization, and may produce buggy output. 

## Expected Behavior

i) The batch shape could be inferred from `model.train_inputs` batch shape. My observation is `_input_batch_shape = model.train_inputs[0].shape[:-2]`, but I am not sure if this is always true. If this is true, a simple try/except should do it.

ii) It should either raise a `NotImplementedError`, or be modified to accommodate the `project` operator.

**Comment by saitcakmak** [comment]
To add to this, `gen_one_shot_kg_initial_conditions` ignores the `project` operator as well.

**Comment by saitcakmak** [comment]
I see that you put up #588 for the batch shape. For the `project` issue, I was thinking a wrapper like this may work:

```
class ProjectedValueFunction(AcquisitionFunction):
    def __init__(
            self,
            base_value_function: AcquisitionFunction,
            project: Callable[[Tensor], Tensor]
    ):
        self.base_value_function = base_value_function
        self.project = project

    def forward(self, X: Tensor) -> Tensor:
        return self.base_value_function(self.project(X))


def _get_value_function(
    model: Model,
    objective: Optional[Union[MCAcquisitionObjective, ScalarizedObjective]] = None,
    sampler: Optional[MCSampler] = None,
    project: Optional[Callable[[Tensor], Tensor]] = None,
) -> AcquisitionFunction:
    r"""Construct value function (i.e. inner acquisition function)."""
    if isinstance(objective, MCAcquisitionObjective):
        base_value_function = qSimpleRegret(
            model=model, sampler=sampler, objective=objective)
    else:
        base_value_function = PosteriorMean(model=model, objective=objective)
    if project is None:
        return base_value_function
    else:
        return ProjectedValueFunction(base_value_function, project)
```

**Comment by Balandat** [comment]
Yeah this seems quite reasonable to me. @danielrjiang any thoughts?

**Comment by danielrjiang** [comment]
Thanks @saitcakmak, seems pretty useful to me too.

**Comment by saitcakmak** [comment]
Cool, I’ll put up a PR soon.
