### ISSUE TITLE
[Bug] Wrong sign in UpperConfidenceBound

### ISSUE THREAD

**Issue by AdrianSosic** [pytorch/botorch#608]
Hi folks, I think I might have found a bug in `UpperConfidenceBound` in the sense that the behavior is not consistent with other acquisition function such as `ExpectedImprovement` or `ProbabilityOfImprovement`.

## Issue description

The behavior seems correct for `maximize=True`, however, I think the sign of the function output should be inverted when setting `maximize=False` in order to be consistent with other acquisition functions. For those, the returned function values are always such that the optimal point is the one that **maximizes** the output, irrespective of how the `maximize` flag is set. By contrast, in case of `UpperConfidenceBound`, the optimal point is currently the one that **minimizes** the output when `maximize=False`. Any thoughts?

## Code example

The current lines of code that return the function values are
```
        if self.maximize:
            return mean + delta
        else:
            return mean - delta
```
and I think they should be changed to the following, in order to provide a consistent behavior:
```
        if self.maximize:
            return mean + delta
        else:
            return -mean + delta
```

## System Info

- BoTorch Version 0.2.1
- GPyTorch Version 1.2.1
- PyTorch Version 1.6.0

**Comment by AdrianSosic** [comment]
I just noticed that this has already been fixed.

**Comment by fengyiqi** [comment]
Hi, should the return be "- mean - delta" for a minimizing problem?
