### ISSUE TITLE
Optimize on varying amount of dimensions

### ISSUE THREAD

**Issue by Jimbo994** [pytorch/botorch#630]
## Issue description

I have this simulator code in place which computes an objective given input parameters X. Sometimes I want to perform BO on a subset of the parameters (and keep the other parameters fixed), while other times I might want to optimize on all of them. 

I am wandering if there already is a way to do this in BoTorch. At the moment, I choose my bounds in a way similar to this:

bounds = torch.tensor([[0, 0, 0, 0, 1,    0, 0, 0, 0, 1],
                               [1, 1, 1, 1, 1,    1, 1, 1, 1, 1]], **tkwargs)

So that here the 5th and 10th dimension are fixed. However, I wonder if this would be the best approach, as this means I have an overly complex GP. I also tried playing around with the active_dims argument (https://docs.gpytorch.ai/en/stable/kernels.html), which should allow for the computation of the covariance of only a few input dimensions. However, this seemed to change my BO results in more of a random search. 

What would you recommend doing? Should I make my own code more flexible and only use the parameters that I want to optimize on as input?

Thanks in advance.

## System Info
Please provide information about your setup, including
- BoTorch Version 0.3.2
- GPyTorch Version 1.2.1
- PyTorch Version 1.7.0
- MacOS Mojave 10.14.6

**Comment by Balandat** [comment]
Say wlog that you consider fixing the first dimension of the input `X`. The main thing to understand here is whether your model is going to be fit on observations for different values in that dimension of not.

If not, then the easiest (and easiest for the model) is to just drop that dimension entirely. If you do have observations that are different than your target value in that dimension, which in general I would think is the case, you will want to fit the full GP on that data and then just fix that feature when optimizing the acquisition function. We have the handy `FixedFeatureAcquisitionFunction` wrapper for this: https://github.com/pytorch/botorch/blob/master/botorch/acquisition/fixed_feature.py#L22-L32

**Comment by Jimbo994** [comment]
Thanks for the swift response! So, in general, we are going to keep those dimensions fixed. But we do indeed have observations that are different than the target value. 

So this is very useful information, thanks a lot! I will look into the wrapper and implement it.

Thanks again.

**Comment by Balandat** [comment]
great, let us know if you run into any issues.
