### ISSUE TITLE
[Question] Correlations between outputs (Higher order GP model)

### ISSUE THREAD

**Issue by jrojsel** [pytorch/botorch#635]
Is it possible to calculate the Pearson correlation(s) between outputs in the newly added [higher_order_gp](https://github.com/pytorch/botorch/blob/master/botorch/models/higher_order_gp.py) model at a given test input? 

Another question: can the model be extended to use a linear mean function? @wjmaddox 

I was trying to implement the [GPAR](http://proceedings.mlr.press/v89/requeima19a.html) model to achieve this, but training seems to be unstable, and so I decided to use GPyTorch's Multitask GP -- but maybe  the Higher order GP is a viable option?

Br,
Jimmy

**Comment by wjmaddox** [comment]
Good questions!

I don't know off the top of my head how to extend the HOGP model to use a linear mean function due to the batching across output dimensions. Do you mean some type of linear mean that also takes into account the location of the matrix/array indices -- if so, I think that there's a way and I can take a look at setting that up?

Here's a quick example of how to get out the predictive correlation matrix between the indices for a test point; as a warning, if you have more than about 1000 total outputs (e.g. test points * output shape), computing this matrix will slow down dramatically:

```python
import torch
import matplotlib.pyplot as plt

from botorch.models import HigherOrderGP
from botorch import fit_gpytorch_model
from gpytorch.mlls import ExactMarginalLogLikelihood

# setup a toy problem
train_x = torch.randn(10,1, 1) # trailing batch dimension only for constructing the data
periods = torch.meshgrid(torch.linspace(0., 1., 3), torch.linspace(1., 2., 4))
train_y = torch.sin(6.28 * periods[0] + periods[1] * train_x) + 0.001 * torch.randn_like(train_x)
train_x = train_x[...,0]

# build and fit model
model = HigherOrderGP(train_x, train_y)
mll = ExactMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_model(mll);

# compute posterior distribution over test points
model.eval()

test_x = torch.randn(3, 1)
pred_dist = model(test_x)
# the covariance matrix here will be tiled with n_{test} blocks of the number of output dimensions

predictive_covariance = pred_dist.covariance_matrix
predictive_correlation = predictive_covariance / predictive_covariance.diag()

# show the entire correlation matrix
f = plt.imshow(predictive_correlation.detach())
plt.colorbar(f)

# and subset only on the first test point
f = plt.imshow(predictive_correlation.detach()[:12, :12])
plt.colorbar(f)
```

**Comment by jrojsel** [comment]
> Do you mean some type of linear mean that also takes into account the location of the matrix/array indices -- if so, I think that there's a way and I can take a look at setting that up?

For my particular use case, it does not need to take the location of the array indices into account, but I sure can think of a few future ones where this would be neat!

> Here's a quick example of how to get out the predictive correlation matrix between the indices for a test point; as a warning, if you have more than about 1000 total outputs (e.g. test points * output shape), computing this matrix will slow down dramatically

Thank you very much! This is exactly what I was looking for! :)

**Comment by Balandat** [comment]
> `predictive_correlation = predictive_covariance / predictive_covariance.diag()`

Shouldn't this be 
```
std = predictive_covariance.diag().sqrt().view(-1, 1)
predictive_correlation = predictive_covariance  / std / std.transpose(-1, -2)
```
?

**Comment by wjmaddox** [comment]
Ahh yes, it is. Serves me right for not double checking the math properly..

```python
predictive_covariance = pred_dist.covariance_matrix

inv_stddev_matrix = predictive_covariance.diag().pow(-0.5).diag()
predictive_correlation = inv_stddev_matrix.matmul(predictive_covariance).matmul(inv_stddev_matrix)
```

**Comment by jrojsel** [comment]
> Ahh yes, it is. Serves me right for not double checking the math properly..
> 
> ```python
> predictive_covariance = pred_dist.covariance_matrix
> 
> inv_stddev_matrix = predictive_covariance.diag().pow(-0.5).diag()
> predictive_correlation = inv_stddev_matrix.matmul(predictive_covariance).matmul(inv_stddev_matrix)
> ```

Ok so I had a look at my old code for doing this with GPyTorch's Hadamard GP and this agrees with what I came up with then. I will close this issue as the main question has been answered, but I surely will be interested in any progress in formulating a linear mean -- feel free to reopen.

Br,
Jimmy
