### ISSUE TITLE
BO with external objective evaluation

### ISSUE THREAD

**Issue by lcollia** [pytorch/botorch#660]
# 🚀 Feature Request

Do you have an example of the application of BOTorch when the objective is evaluated externally?

## Motivation

A lot of time, the object we want to optimize is not a mathematical function but something not calculable (e.g. measured property of a molecule). Thus we want to create a surrogate model with the existing data, and select with BO the best point to test in the next experiment. 
Do you an example of BO (with BOTorch) based on external files containing observations?

Thanks,
Lionel

**Comment by Balandat** [comment]
Sure, that's the primary application of BayesOpt - the synthetic examples we have in the tutorials are just toy examples. 

If you're not interested in working on BO itself but just want to use it in that sense, I recommend you start with Ax (https:/ax.dev), which is a higher level API that will make this a lot easier. Specifically, you can use the service API as in this tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html. The only thing you'll need to do is to pass in the `trial_index` and the `raw_data` from your evaluation in cell [5] of that tutorial. 

On the BoTorch end, if you look at https://botorch.org/tutorials/closed_loop_botorch_only, then you just need to swap out the evaluation code
```
def optimize_acqf_and_get_observation(acq_func):
    """Optimizes the acquisition function, and returns a new candidate and an observation."""
    # optimize
    candidates, _ = optimize_acqf(
        acq_function=acq_func,
        bounds=bounds,
        q=BATCH_SIZE,
        num_restarts=10,
        raw_samples=512,  # used for intialization heuristic
        options={"batch_limit": 5, "maxiter": 200},
    )
    new_x = candidates.detach()
    # now you can use some API to evaluate the function, or just write the candidate to some local file
    # do something with it, write the results to some other file and read it in from there
    # the world is your oyster. 
    [...]
    return new_x, new_obj
```

**Comment by lcollia** [comment]
Thanks for your answer
