### ISSUE TITLE
Changes in partitioning for MO optimization

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#676]
Dear botorch developers,

I was just updating my workflow to the newest botorch version to incorporate the new features (especially the X values in the objective) and came across another change. Namely that the class `NondominatedPartitioning` has not only been moved but also changed its `__init__` signature. To make sure that I use it in the correct way, I checked the `constrained_multi_objective_bo.ipynb` file for the corresponding tutorial, but this is not yet updated. 

It would be nice if you could update it to using the new implementation of `NondominatedPartitioning`. 

In the old version, one had to provide a `num_outcomes` argument and `Y`. In the new one, it is now the `ref_point` and `Y`. Is `Y` in this case still `Y=train_obj[better_than_ref & is_feas]`?

Thanks for all your efforts!

Best,

Johannes

**Comment by Balandat** [comment]
Sorry about the tutorial inconsistencies. We've had some trouble with testing the tutorials on CI, but I'm working on getting us to a better place there. 

@sdaulton could update this particular one, please?

> Is Y in this case still Y=train_obj[better_than_ref & is_feas]?

I believe so, @sdaulton can confirm (and maybe update the docstring to make this more clear).

**Comment by sdaulton** [comment]
Thanks for flagging.

Yes, `Y=train_obj[better_than_ref & is_feas]` is correct. I'll put up a PR for fix the arguments in the tutorials
