### ISSUE TITLE
[Bug]`param_or_closure` must operate on a module instance

### ISSUE THREAD

**Issue by pietromercati** [pytorch/botorch#682]
# 🐛 Bug

**Running the tutorial:**

https://botorch.org/tutorials/bo_with_warped_gp

**Ran into error:**

```
As of version 1.4, `param_or_closure` must operate on a module instance. For example:

                    likelihood.noise_covar.register_prior(
                        "noise_std_prior",
                        gpytorch.priors.NormalPrior(0, 1),
                        lambda module: module.noise.sqrt()
raised by gpytorch\module.py
```

**Libraries and versions:**
torch = 1.7.1+cpu
gpytorch = 1.3.1
botorch = 0.3.3

I fixed by changing the following in botorch\models\transforms\input.py
"lambda self" instead of "lambda":

```
 if concentration0_prior is not None:
            self.register_prior(
                "concentration0_prior",
                concentration0_prior,
                lambda self: self.concentration0,
                lambda self, v: self._set_concentration(i=0, value=v),
            )
        if concentration1_prior is not None:
            self.register_prior(
                "concentration1_prior",
                concentration1_prior,
                lambda self: self.concentration1,
                lambda self, v: self._set_concentration(i=1, value=v),
            )
```

**Comment by saitcakmak** [comment]
Check out #668. It looks like the same issue to me. You should either upgrade BoTorch to master via `pip install --upgrade git+https://github.com/pytorch/botorch.git` or downgrade GPyTorch to 1.3.0 via `pip install gpytorch==1.3.0`. Hope this helps!

**Comment by Balandat** [comment]
I had to make some breaking changes in gpytorch that were necessary to fix a bug, which are not taken into account in the last botorch release, hence the error. We plan to release new versions of both gpytorch and botorch soon, which will resolve this issue.

In the meantime, @saitcakmak's suggestion (thanks!) should unblock you.

**Comment by Balandat** [comment]
Closing this out as this is fixed on master and will be part of the upcoming 0.4.0
