### ISSUE TITLE
Handling NaN inputs in acquisition functions

### ISSUE THREAD

**Issue by saitcakmak** [pytorch/botorch#685]
## Issue description

Sometimes, when optimizing an acquisition function with `optimize_acqf`, the solution becomes a tensor of `NaN`s, at which the acquisition function gets evaluated (haven't diagnosed what leads to `NaN` yet). This does not raise any errors until the posterior `rsample(...)` call (using qEI). An example stack trace is as follows:

```
/Users/saitcakmak/.conda/envs/other-BO/lib/python3.8/site-packages/gpytorch/lazy/lazy_tensor.py:1354: NumericalWarning: Runtime Error when computing Cholesky decomposition: Matrix not positive definite after repeatedly adding jitter up to 1.0e-04. Original error on first attempt: cholesky_cpu: For batch 8: U(7,7) is zero, singular U.. Using RootDecomposition.
  warnings.warn(
/Users/saitcakmak/.conda/envs/other-BO/lib/python3.8/site-packages/gpytorch/lazy/lazy_tensor.py:1354: NumericalWarning: Runtime Error when computing Cholesky decomposition: cholesky_cpu: 1000 of 1000 elements of the torch.Size([10, 10, 10]) tensor are NaN.. Using RootDecomposition.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/saitcakmak/.conda/envs/other-BO/lib/python3.8/site-packages/botorch/posteriors/gpytorch.py", line 87, in rsample
    samples = self.mvn.rsample(
  File "/Users/saitcakmak/.conda/envs/other-BO/lib/python3.8/site-packages/gpytorch/distributions/multitask_multivariate_normal.py", line 230, in rsample
    samples = super().rsample(sample_shape=sample_shape, base_samples=base_samples)
  File "/Users/saitcakmak/.conda/envs/other-BO/lib/python3.8/site-packages/gpytorch/distributions/multivariate_normal.py", line 173, in rsample
    covar_root = covar.root_decomposition().root
  File "/Users/saitcakmak/.conda/envs/other-BO/lib/python3.8/site-packages/gpytorch/utils/memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "/Users/saitcakmak/.conda/envs/other-BO/lib/python3.8/site-packages/gpytorch/lazy/lazy_tensor.py", line 1364, in root_decomposition
    evals, evecs = self.symeig(eigenvectors=True)
  File "/Users/saitcakmak/.conda/envs/other-BO/lib/python3.8/site-packages/gpytorch/utils/memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "/Users/saitcakmak/.conda/envs/other-BO/lib/python3.8/site-packages/gpytorch/lazy/lazy_tensor.py", line 1596, in symeig
    return self._symeig(eigenvectors=eigenvectors)
  File "/Users/saitcakmak/.conda/envs/other-BO/lib/python3.8/site-packages/gpytorch/lazy/lazy_tensor.py", line 1879, in _symeig
    evals, evecs = torch.symeig(self.evaluate().to(dtype=torch.double), eigenvectors=eigenvectors)
RuntimeError: symeig_cpu: For batch 0: the algorithm failed to converge; 9 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.
```  

I personally read the stack trace bottom up, so I completely miss the warning about `NaN`s until much later. I trace it step by step, originally speculating that it is an issue with the model etc, until I realize that the `forward` call was done with a tensor of `NaN`s. 

This is partially my fault for not looking through the stack trace more carefully, but I think this whole process can be made more efficient by catching `NaN` inputs to `forward` before it leads to errors down the line. I think a great place to do this would be in `t_batch_mode_transform`. I don't think any acquisition function supports `NaN` inputs, so it should be ok to simply raise the error before the `forward` call is evaluated. If this sounds like a good idea, I could add this to #577 or make a separate PR for it.

**Comment by Balandat** [comment]
Good catch! Yeah stuff like this is hard to miss. Presumably something goes wrong in L-BFGS-B, will need to dig into the scipy docs to understand what's going on there. 

I agree that `t_batch_mode_transform` would be a good place to check for this. A few acquisition functions don't use that decorator though, so another place to check this would be here: https://github.com/pytorch/botorch/blob/dd17a4c19890e87460dbb50e14456c2f525aeeeb/botorch/generation/gen.py#L101

(turns out that `nan` checks for smaller arrays are faster in numpy than in torch, so this would reduce some of the overhead).

**Comment by saitcakmak** [comment]
I identified the root cause. The `gradf` in `gen_candidates_scipy` becomes `NaN`, due to the same issue as #567. LBFGS happily takes in the `NaN` grad and returns the `NaN` solution. Switching to double resolves it.

> so another place to check this would be here:
 https://github.com/pytorch/botorch/blob/dd17a4c19890e87460dbb50e14456c2f525aeeeb/botorch/generation/gen.py#L101

Yeah, this is probably a better place to check for it. Since both in this case and in #567, the root cause is `grad` becoming `NaN`, it may also be a good idea to check for `NaN` in `gradf` directly. This would catch it before LBFGS processes the `NaN` grad.

**Comment by Balandat** [comment]
Good find. We should probably do the following within `f(x)` definition in https://github.com/pytorch/botorch/blob/dd17a4c19890e87460dbb50e14456c2f525aeeeb/botorch/generation/gen.py#L101:

1. Add a check for the input `x` to not contain any NaN values (in numpy)
2. Check `grad_f` for NaN values

In both cases, raise an `RuntimeError` with an informative error message. 

Are you planning to put up a PR? I'm also happy to.

**Comment by saitcakmak** [comment]
That sounds like a good plan. I can put this up later today
