### ISSUE TITLE
SingleTaskGP with an outcome transform is not subsetted properly

### ISSUE THREAD

**Issue by RaulAstudillo06** [pytorch/botorch#708]
## Issue description

 When a SingleTaskGP is subsetted, the outcome transform remains the same. This causes an error when making predictions with the subsetted model.

## Code example

        import torch
        from botorch.models import SingleTaskGP
        from botorch.models.transforms.outcome import Standardize

        train_X = torch.tensor(
                    [[0.0, 0.1], [0.2, 0.5], [0.8, 1.0]]
                )
        train_Y = torch.tensor([[1.0, 1.0], [2.0, 3.0], [3.0, 5.0]])
        
        outcome_transform = Standardize(m=train_Y.shape[-1], batch_shape=train_Y.shape[:-2])
        
        model = SingleTaskGP(
                    train_X=train_X,
                    train_Y=train_Y,
                    outcome_transform=outcome_transform,
                )
        
        model.outcome_transform.eval()
        
        subsetted_model = model.subset_output(idcs=[0])
        X = torch.tensor([[0.5, 0.5]])
        
        posterior_X = subsetted_model.posterior(X=X)
        
        posterior.mean

Error message: Incompatible output dimensions encountered for transform 2 and posterior 1.

**Comment by Balandat** [comment]
Fixed by #711
