### ISSUE TITLE
Using Constrained BO to Solve Minimization Problem

### ISSUE THREAD

**Issue by zzhou612** [pytorch/botorch#719]
## Issue description

I am trying to use botorch to solve a constrained minimization problem. I have read the tutorial of "Closed-loop batch, constrained BO in BoTorch with qEI and qNEI". 

Since botorch assumes a maximization problem, I need to maximize -f(x) in order to minimize f(x). ( f(x) > 0 for all x ) But in that case, -f(x) would be less than zero, I am not sure whether `ConstrainedMCObjective` will still work. 

I checked the documentation and it led me to `botorch.utils.objective.apply_constraints`. So I am wondering how to use `botorch.utils.objective.apply_constraints` function to solve this problem? Is there any example? Or should I simply use `infeasible_cost` arg to make the objective function f(x) non-negative? 

Thanks!

**Comment by Balandat** [comment]
So in this case you'd use `infeasible_cost` to shift the function to be positive as you suggested.

Do you know the maximum value of f across the search space (maybe there is some natural maximum you know from domain knowledge or the definition of the function?). If you do know that then you'll want to use an upper bound on that, the tighter the bound the better. 

So say you know from your application that `max_{x \in X}  f(x) = M` then you would set `infeasible_cost=M`. 

If you have no idea, we can also estimate this from the model, there is a utility for this: 
https://github.com/pytorch/botorch/blob/2fe7d00a29edf80129572a16cf670e2d323c1f2a/botorch/acquisition/utils.py#L158-L191

**Comment by zzhou612** [comment]
Thank you!
