### ISSUE TITLE
[Feature Request] Docs listing available models and their properties

### ISSUE THREAD

**Issue by saitcakmak** [pytorch/botorch#732]
# 🚀 Feature Request

I find myself searching through the docstrings or the API reference whenever I am not sure what model to use. These typically have enough information to make a decision but reading through them is not the most user friendly thing. So, I was thinking having a page in docs that lists all model types packaged into BoTorch, along with a short discussion on underlying assumptions and use cases would be a handy reference. I'm sure I'd use it, and I think it'd also be a good reference for anyone that's new to BoTorch.

**Comment by Balandat** [comment]
So we do have a high-level description of some model types here: https://botorch.org/docs/models

But this is not particularly detailed and also incomplete. We could either update that page, or add a new one that goes into some more detail and lists all the models.

**Comment by saitcakmak** [comment]
> So we do have a high-level description of some model types here: https://botorch.org/docs/models

Not sure how I missed that page. I knew something like that existed somewhere but couldn't find it at a quick look. I must have been looking under tutorials.

> But this is not particularly detailed and also incomplete. We could either update that page, or add a new one that goes into some more detail and lists all the models.

Yes, I was thinking something more detailed and complete. Adding a new page with a short paragraph (or a few bullet points) for each model sounds like a good option

**Comment by saitcakmak** [comment]
We've made a good bit of progress here thanks to @esantorella's efforts. Closing the issue.
