### ISSUE TITLE
[Feature Request] Implement a variational GP model using the BoTorch API. 

### ISSUE THREAD

**Issue by Balandat** [pytorch/botorch#758]
This would be a good thing to have and was requested in #753

**Comment by wjmaddox** [comment]
I have at least one implementation sitting around, see [here](https://github.com/wjmaddox/online_gp/blob/main/online_gp/models/variational_gp_model.py) for a more advanced version. I could polish, add unit tests and setup a PR.

**Comment by Balandat** [comment]
That would be great!
