### ISSUE TITLE
Question: Discrete optimization

### ISSUE THREAD

**Issue by preritt** [pytorch/botorch#781]
Hi

Suppose my input takes only discrete value (for e.g. 1,2,3,4). I also have a single output. What is the optimization function suitable for this case.  Should I use `optimize_acqf_mixed` or is there some other function suitable for this?

In standard BO, we maintain the mean and variance of the output for each choice of input. Based on the accumulated statistics, we decide the next candidate solution to use using some acquisition function (like UCB) . Is there something equivalent in BoTorch?

**Comment by Balandat** [comment]
I recently added [optimize_acqf_discrete](https://github.com/pytorch/botorch/blob/master/botorch/optim/optimize.py#L472-L536) for the fully discrete case (you'll need to be on master to use this, it's not part of any release yet). This is essentially just a convenience wrapper to compute the model for a set of possible choices and pick the best acquisition function value. This interface requires that you enumerate all possible combinations, but that shouldn't be an issue for spaces of low cardinality.

**Comment by preritt** [comment]
Great, thanks for sharing this. I will try it out.

**Comment by Balandat** [comment]
Great, feel free to open another issue if you run into trouble. Or a "Discussion" if you have more general questions.
