### ISSUE TITLE
Support proper tutorial linking in docs on both repo and website

### ISSUE THREAD

**Issue by Balandat** [pytorch/botorch#831]
This is an issue that came up in #754:

Currently, tutorial  so the links in the `.md` doc files are such that the website points to the rendered tutorials (e.g. linking to `https://botorch.org/docs/botorch_and_ax`). With the `.ipynb` suffix the link on the website won't work anymore. Conversely, when following the link from a rendered `.md` on the repo, one will get a 404. There probably is a better solution that allows to do both (e.g. do some regexp parsing & editing of the `.md` files during the website building that removes `ipynb` suffixes).

**Comment by esantorella** [comment]
[This page](https://github.com/pytorch/botorch/blob/main/docs/botorch_and_ax.md) is where you'll currently find non-working links, when reading in GitHub.

**Comment by esantorella** [comment]
I don't think this is worth fixing. The effort and hit to maintainability from creating fancy links that work from both the website and from markdown files isn't worth it, unless it's more common than I realize to get deep into the documentation on GitHub rather than through the website or an IDE.

**Comment by Balandat** [comment]
Makes sense. Especially if we are thinking about updating the website setup at some point which may fix this issue atutomatically.
