### ISSUE TITLE
[Question] Question about direction of optimization in "botorch.optim.optimize.optimize_acqf"

### ISSUE THREAD

**Issue by mohammad-saber** [pytorch/botorch#834]
Hi, 

I have a question about direction of optimization of "acquisition function" and "objective variable" in the following example:

```
import torch
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_model
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood

train_X = torch.rand(10, 2)
Y = 1 - torch.norm(train_X - 0.5, dim=-1, keepdim=True)
Y = Y + 0.1 * torch.randn_like(Y)  # add some noise
train_Y = standardize(Y)

gp = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
fit_gpytorch_model(mll)


# Construct an acquisition function
from botorch.acquisition import UpperConfidenceBound
UCB = UpperConfidenceBound(gp, beta=0.1)


# Optimize the acquisition function
from botorch.optim import optimize_acqf

bounds = torch.stack([torch.zeros(2), torch.ones(2)])
candidate, acq_value = optimize_acqf(
    UCB, bounds=bounds, q=1, num_restarts=5, raw_samples=20,
)
```

There are two points I would like to clarify.

1) When we use "optimize_acqf", does it maximize the acquisition function or minimize it?

2) In this example, objective variable is "Y". Are we going to maximize "Y" or minimize it?
 For example, when we get next candidate point by optimizing the acquisition function, is it the point that maximizes "Y" or minimize it?

Thank you for your help.

**Comment by Balandat** [comment]
1. Our convention is that we maximize all acquisition functions, so `optimize_acqf` always maximizes.
2. This is generally encoded in the acquisition function and should not concern `optimize_acqf`. As the acquisition functions: These generally also assume that the modeled function (from which the observations `Y` are obtained) is supposed to be maximized. Some acquisition functions have a `maximize` argument in case you'd like to do minimization of the modeled function instead.
