### ISSUE TITLE
[Feature Request] Add `maximize` flag to `PosteriorMean` acquisition function

### ISSUE THREAD

**Issue by lukasfro** [pytorch/botorch#875]
Unlike other acquisition functions, the `PosteriorMean` does not have a `maximize` flag, hence it is not currently not possible to find the minimum of the posterior mean function via `optimize_acqf`. This should not be too much effort to implement. Happy to create a PR when the feature is desired.

**Comment by saitcakmak** [comment]
Hi @lukasfro. With the existing API, you can use
```
pm = PosteriorMean(model=model, objective=ScalarizedObjective(weights=torch.tensor([-1.0]))
optimize_acqf(...)
```
to minimize the posterior mean. This will internally negate the posterior, so any value you get out of this will also be negated. 

You may have noticed that everything is maximized by default in BoTorch. If you need to minimize a function, it is typically easiest to just negate your function evaluations and maximize that. In the past, I worked with BoTorch in a minimization setting without negating the function evaluations and things get messy pretty quickly.

**Comment by lukasfro** [comment]
Hi @saitcakmak, thanks for the clarification. It looks like `ScalarizedObjective` is the way to go then. I thought it might be nice to have a consistent interface to the other analytical acquisition functions that do make use of the `maximize` flag.

**Comment by Balandat** [comment]
I think it would be fine to add a `maximize` arg to `PosteriorMean` for consistency with the other analytic acquisition functions. Should be trivial to do by adding a constructor and flipping a sign conditionally on that in forward. Happy to review a PR for this :)

**Comment by lukasfro** [comment]
Sounds good to me. Will create the PR next week! 
I just noticed that `ScalarizedPosteriorMean` could be extended in a similar manner. Should this be included in the PR as well?

**Comment by Balandat** [comment]
I don't think `ScalarizedPosteriorMean` needs a `maximize` option, since this can easily be done just by flipping the sign of the weights.

**Comment by Balandat** [comment]
For `PosteriorMean`, this was added by #881.
