### ISSUE TITLE
[Bug] Constrained Optimization with Fixed Features and batch size q > 1 - constraints are violated midway through the optimization loop.

### ISSUE THREAD

**Issue by alantan-SQ40** [pytorch/botorch#898]
# 🐛 Bug

I'm performing constrained optimization with fixed features. Here, q > 1 (e.g. 8). Somehow, the constraints are failing after the first candidate of the batch is found. After some digging, I found that some of the inequality constraints have been modified causing some of the fixed features to violate the constraints. I'm not sure where the source of the bug is.

Secondly, in a related problem, when there are multiple constraints, the fixed features constraints check:  "new_rhs > 0" is quite strict (botorch\optim\parameter_constraints.py). I find that occasionally, due to numerical issues, it violates the constraints by some small number (e.g. 5e-8). I should note that the fixed features I'm using come from parts of a candidate found by the same optimizer (with the same set of inequality constraints). Do you know how I should best try to resolve this? Note, there is no rounding happening as far as I could tell. 

# all indices were fixed, so the constraint is gone.
if len(new_indices) == 0:
    if (eq and new_rhs != 0) or (not eq and new_rhs > 0):
        prefix = "Eq" if eq else "Ineq"
        raise CandidateGenerationError(
            f"{prefix}ality constraint {constraint_id} not met "
            "with fixed_features."
        )

Also there may be a typo in the error msg ("Ineqality")

** Stack trace/error message **
File "C:\Anaconda3\envs\ai-engine-updated\lib\site-packages\botorch\optim\optimize.py", line 113, in optimize_acqf
    candidate, acq_value = optimize_acqf(
  File "C:\Anaconda3\envs\ai-engine-updated\lib\site-packages\botorch\optim\optimize.py", line 184, in optimize_acqf
    batch_candidates_curr, batch_acq_values_curr = gen_candidates_scipy(
  File "C:\Anaconda3\envs\ai-engine-updated\lib\site-packages\botorch\generation\gen.py", line 97, in gen_candidates_scipy
    _no_fixed_features = _remove_fixed_features_from_optimization(
  File "C:\Anaconda3\envs\ai-engine-updated\lib\site-packages\botorch\generation\utils.py", line 131, in _remove_fixed_features_from_optimization
    inequality_constraints = _generate_unfixed_lin_constraints(
  File "C:\Anaconda3\envs\ai-engine-updated\lib\site-packages\botorch\optim\parameter_constraints.py", line 312, in _generate_unfixed_lin_constraints
    raise CandidateGenerationError(
botorch.exceptions.errors.CandidateGenerationError: Ineqality constraint 6 not met with fixed_features.

## Expected Behavior

Be able to run constrained optimization with fixed features (that are potentially close to the boundaries of the constraints).

## System information

**Please complete the following information:**
-  0.5.1.dev23+g1d35f168
-  1.5.0
-  '1.9.0+cu111'
-  Windows 10

**Comment by vishwakftw** [comment]
Hi @alantan-SQ40, thank you for the bug report.

> I found that some of the inequality constraints have been modified causing some of the fixed features to violate the constraints.
In `gen_candidates_scipy`, we remove the `fixed_features` from the optimization under some conditions. However, we do not change the inequality constraints in-place. Are you seeing the inequality constraints being changed in-place? This check that is being referred to, is only done when all the features are fixed (as you had pointed out), so are you ensuring that the fixed features are feasible?

> Secondly, in a related problem, when there are multiple constraints, the fixed features constraints check: "new_rhs > 0" is quite strict (botorch\optim\parameter_constraints.py). I find that occasionally, due to numerical issues, it violates the constraints by some small number (e.g. 5e-8).
@Balandat, is it worth adding a small amount of slack to the check?

> I should note that the fixed features I'm using come from parts of a candidate found by the same optimizer (with the same set of inequality constraints). Do you know how I should best try to resolve this?
This is concerning, because the fixed features that are being generated are infeasible in the first place.

Would it be possible for you to give a minimum example for when this happens?

**Comment by Balandat** [comment]
> is it worth adding a small amount of slack to the check?

Yes. My guess is that when generating the fixed features via optimization some constraint is binding, and the optimizer just returns a solution on up to some numerical inaccuracy. We should be able to tolerate that as this is a common setting.

**Comment by vishwakftw** [comment]
How do you suggest we add this? Something like `torch.finfo(coefficients.dtype).eps * len(inequality_constraints)`?

**Comment by alantan-SQ40** [comment]
I was able to narrow down the line which modifies the inequality constraints. That's this line here: https://github.com/pytorch/botorch/blob/eb51a5de68185f797957c0811d206745a73c7da4/botorch/optim/parameter_constraints.py#L306

If I created the variable RHS with a deepcopy, the problem seems to go away.

**Comment by Balandat** [comment]
> If I create the variable "new_rhs" with a deepcopy, the problem seems to go away.

 What exactly do you mean by that? Could you please share your code change?

**Comment by Balandat** [comment]
Ah I see. It think the issue is the in-place operation https://github.com/pytorch/botorch/blob/eb51a5de68185f797957c0811d206745a73c7da4/botorch/optim/parameter_constraints.py#L306

If you replace this with `new_rhs = new_rhs - coefficient.item() * ffval_or_None`, do things also work?

**Comment by alantan-SQ40** [comment]
> Ah I see. It think the issue is the in-place operation
> 
> https://github.com/pytorch/botorch/blob/eb51a5de68185f797957c0811d206745a73c7da4/botorch/optim/parameter_constraints.py#L306
> 
> If you replace this with `new_rhs = new_rhs - coefficient.item() * ffval_or_None`, do things also work?

Yes! It works!

**Comment by Balandat** [comment]
Great. Another example why inplace ops are bad (as if we needed more). Let me put up a PR with the fix.

**Comment by vishwakftw** [comment]
Sorry about introducing this bug. Thank you @alantan-SQ40 for debugging this!

**Comment by vishwakftw** [comment]
I did some more digging, and I'm not able to reproduce the change the constraints after passing them through `_generate_unfixed_lin_constraints` or `_remove_fixed_features_from_optimization`.

```python
In [17]: inequality_constraints
Out[17]: 
[(tensor([0, 1, 2]), tensor([ 1.3248, -2.3086,  0.9494]), 0.0),
 (tensor([0, 2]), tensor([ 0.2646, -0.5955]), -0.5)]

In [18]: _generate_unfixed_lin_constraints(inequality_constraints, fixed_features={1:0.5, 2:0.5}, dimension=3, eq=False)
Out[18]: 
[(tensor([0]), tensor([1.3248]), 0.6796339154243469),
 (tensor([0]), tensor([0.2646]), -0.20227116346359253)]

In [19]: inequality_constraints
Out[19]: 
[(tensor([0, 1, 2]), tensor([ 1.3248, -2.3086,  0.9494]), 0.0),
 (tensor([0, 2]), tensor([ 0.2646, -0.5955]), -0.5)]

In [20]: for c, i, r in inequality_constraints:
    ...:     nr = r
    ...:     nr -= 10
    ...: 

In [21]: inequality_constraints
Out[21]: 
[(tensor([0, 1, 2]), tensor([ 1.3248, -2.3086,  0.9494]), 0.0),
 (tensor([0, 2]), tensor([ 0.2646, -0.5955]), -0.5)]

In [22]: nff = _remove_fixed_features_from_optimization({1: 0.5, 2: 0.5}, acquisition_function=lambda x: x, initial_conditions=torch.rand(10, 1, 3), lower_bounds=None, upper_bounds=None, inequality_constr
    ...: aints=inequality_constraints, equality_constraints=None)

In [23]: inequality_constraints
Out[23]: 
[(tensor([0, 1, 2]), tensor([ 1.3248, -2.3086,  0.9494]), 0.0),
 (tensor([0, 2]), tensor([ 0.2646, -0.5955]), -0.5)]

In [24]: nff.inequality_constraints
Out[24]: 
[(tensor([0]), tensor([1.3248]), 0.6796339154243469),
 (tensor([0]), tensor([0.2646]), -0.20227116346359253)]
```

But it's better to get the patch in for reasons @Balandat specified about in-place ops.

**Comment by vishwakftw** [comment]
@alantan-SQ40 Is the third element of the tuple per inequality constraint a `Tensor` or a `float`? Both of them have different semantics with regard to inplace operations and that could explain the change as you are seeing.

For instance:
```python
In [47]: inequality_constraints = [(torch.arange(3), torch.randn(3), torch.tensor(0.0)) , (torch.tensor([0, 2]), torch.randn(2), torch.tensor(-0.5))]

In [48]: inequality_constraints
Out[48]: 
[(tensor([0, 1, 2]), tensor([-0.8823, -1.0317,  0.8022]), tensor(0.)),
 (tensor([0, 2]), tensor([-0.4684,  1.5794]), tensor(-0.5000))]

In [49]: _generate_unfixed_lin_constraints(inequality_constraints, fixed_features={1:0.5, 2:0.5}, dimension=3, eq=False)
Out[49]: 
[(tensor([0]), tensor([-0.8823]), tensor(0.1148)),
 (tensor([0]), tensor([-0.4684]), tensor(-1.2897))]

In [50]: inequality_constraints
Out[50]: 
[(tensor([0, 1, 2]), tensor([-0.8823, -1.0317,  0.8022]), tensor(0.1148)),
 (tensor([0, 2]), tensor([-0.4684,  1.5794]), tensor(-1.2897))]
```

**Comment by alantan-SQ40** [comment]
Thanks! Happy to help!
Thanks for the great work and the great library!
