### ISSUE TITLE
[Question]  How to increase "Jitter" when fitting model?

### ISSUE THREAD

**Issue by mohammad-saber** [pytorch/botorch#926]
Hi, thank you for sharing your great work.

When I fit a model by following code:

```
gp = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
fit_gpytorch_model(mll)
```

Sometimes, I get the following error:

`NotPSDError: Matrix not positive definite after repeatedly adding jitter up to 1.0e-06. Original error on first attempt: cholesky_cpu: U(41,41) is zero, singular U.
`

In GPyTorch, it is possible to set Jitter as [documented](https://docs.gpytorch.ai/en/stable/settings.html#gpytorch.settings.cholesky_jitter) here. 

I would like to know how I can increase Jitter in BoTorch? And is it effective to avoid the above error?

**Comment by saitcakmak** [comment]
Hi @mohammad-saber. I haven't used it myself, but you should be able to use the same GPyTorch option to set jitter in BoTorch as well. So, you would modify your code as follows:
```
gp = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
with gpytorch.settings.cholesky_jitter(**my_jitter_options):
    fit_gpytorch_model(mll)
```

It is worth noting that if you're running into this issue, it is likely that some of your training points are very tightly clustered in the input space, which is leading to numerical issues. I'd first recommend using `dtype=torch.double`. In many cases, I've seen double precision help eliminate many numerical issues and it should be a healthier solution than using excessive jitter. Note that using double will lead to higher memory usage and longer runtimes.

**Comment by Balandat** [comment]
Definitely agree with using `torch.double`, especially when you're running this on a CPU (will only be minimally slower than `float` there).

**Comment by mohammad-saber** [comment]
Thank you for your help. 

Should I set the data-type of train data into `torch.double` , or data-type of kernel lengthscale?

I notice that when I initialize kernel like below:

```
kernel = RBFKernel()
kernel.lengthscale.dtype
```

Data-type of lengthscale is `torch.float32`.

**Comment by saitcakmak** [comment]
If you set the `train_X` and `train_Y` to double (before creating the model), the rest of the model should automatically be set to double (internally, the model calls `self.to(train_X)`). An important thing to keep in mind is that you want to have the same dtype for all tensors you create from scratch, e.g., as `train_X = torch.rand(5, 2, dtype=torch.double)`. If you don't do this, pytorch will complain that you're mixing `float` and `double`.

**Comment by mohammad-saber** [comment]
Thank you for your help.
