### ISSUE TITLE
[Question] RuntimeError: Unknown method '<gpytorch.lazy.non_lazy_tensor.NonLazyTensor object at 0x7ff5503b8a20>'

### ISSUE THREAD

**Issue by mohammad-saber** [pytorch/botorch#932]
Hi, thank you for sharing your great work.

I am trying to use combination of kernels by setting parameter `active_dims` as below:

```
import math
import torch
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_model
from gpytorch.kernels import MaternKernel, LinearKernel
from gpytorch.mlls import ExactMarginalLogLikelihood


'''
Data
'''

num_features = 3

train_x = torch.rand(100, num_features)

train_y = torch.sin(train_x[:,0] * (2 * math.pi)) + torch.randn(train_x[:,0].size()) * math.sqrt(0.04)
train_y = train_y.reshape(-1, 1)


"""
Train
"""

kernel = MaternKernel(nu=1.5, active_dims=[0, 1]) + LinearKernel(active_dims=[2])   

gp = SingleTaskGP(train_x, train_y, covar_module=kernel)   
likelihood = gp.likelihood
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)   
fit_gpytorch_model(mll)   
```

However, I get the following error: 

`RuntimeError: Unknown method '<gpytorch.lazy.non_lazy_tensor.NonLazyTensor object at 0x7ff567f34470>'
`

When I use `active_dims` with only one kernel (like below), there is no problem.

`kernel = MaternKernel(nu=1.5, active_dims=[0, 1])    
`

## System Info
- Python version : 3.6
- BoTorch Version : 0.2.1
- GPyTorch Version : 1.4.1
- PyTorch Version : 1.8.1
- Computer OS : macOS Big Sur (11.5.2)

**Comment by mohammad-saber** [comment]
I tested with Python 3.7 and it works without error. 

It seems that Python 3.6 is not compatible with the newest version of BoTorch.

**Comment by Balandat** [comment]
Correct, BoTorch requires python 3.7 starting with v0.2.2 which was released about a year and a half ago. This is also why you get BoTorch 0.2.1 when you pip install from a 3.6 environment (there are no newer versions on PyPi for py<3.7.
