### ISSUE TITLE
Is optimize_acqf_discrete compatible with qEI?

### ISSUE THREAD

**Issue by fipeop** [pytorch/botorch#957]
I have a function that has a purely discrete input space. 

I would like to use constrained optimization with qEI as in the tutorial, with the only difference that my parameter space is discrete. Is it recommended? 

The cardinality is something like 3 discrete variables with 3 values each and 1 discrete variable with 10 values.

Thank you!

**Comment by Balandat** [comment]
I hope this helped - closing this for now, feel free to reopen if you run into any issues.

**Comment by fipeop** [comment]
@Balandat  thank you for the response! One follow-up question, is optimize_acqf_discrete compatible with multi-objective problems? (without constaint)

**Comment by Balandat** [comment]
Yes. Ultimately even multi-objective acquisition functions will return a scalar value so whether or not the acquisition function is multi-objective or not should not matter for the optimizer.
