### ISSUE TITLE
[question] How to scalarize a multi output GP?

### ISSUE THREAD

**Issue by LLipschitz** [pytorch/botorch#959]
I have a function ` f(x): R^d --> R^m `. Let's say I fit a multi output GP as `gp = FixedNoiseGP(X, Y)` where `Y \in R^nxm, X in R^nxd`. Then I have weights `w \in R^m`, and I want to construct the GP for `w^T x f`.

The scalarized GP posterior will have means `mu = w_1 mu_1 + ... + w_m mu_m` and covariance `E = w1^T E1 w + ... + wm^T Em wm`

Thanks.

**Comment by r-ashwin** [comment]
I am looking at something similar. Is there an example of using the `posterior_transform` for a multioutput GP?

**Comment by saitcakmak** [comment]
> Is there an example of using the posterior_transform for a multioutput GP?

This tutorial has a small part in the end that shows how to use `ScalarizedPosteriorTransform`: https://botorch.org/tutorials/custom_acquisition#Appendix:-Using-ScalarizedPosteriorTransform It is supported for all single-objective acquisition functions. You just construct the usual multi-output GP, and pass the `PosteriorTransform` while constructing the acquisition function (or making predictions, as `model.posterior(X, posterior_transform=<posterior transform object>)`).

**Comment by r-ashwin** [comment]
Amazing! Thanks.

**Comment by saitcakmak** [comment]
Closing this since the `PosteirorTransform`s are fully supported in recent releases.
