### ISSUE TITLE
[Bug] Potential bug with Gumbel distribution for GIBBON

### ISSUE THREAD

**Issue by npielawski** [pytorch/botorch#961]
# 🐛 Bug

I am relatively new to using GIBBON, so there might be something I overlooked. The gumbel distribution is fitted to the distribution of the gaussian process by computing the quantiles. In order to compute the quantiles, a domain is chosen and I believe the current way is suboptimal and could lead to some issues.

The current domain is 3 standard deviations below and above the mean. This guess is suboptimal since the gumbel distribution matches the maximum of each point's normal distribution, so it will match somewhere high. As you can see figure 1, the gumbel distribution appears really close to the 3rd standard deviation. I think using the domain between -1 and 5 standard deviations is more accurate. If the 75th quantile is outside the range, brentq optimization will fail.

Link to the Gumbel fitting and sampling: https://github.com/pytorch/botorch/blob/e23ad502629846bdc0a75a2e2af7f50982a330eb/botorch/acquisition/max_value_entropy_search.py#L781

Maybe another domain than -1, 5 is better as well?

![image](https://user-images.githubusercontent.com/11574848/139527219-61813d46-a898-4d90-a448-4b5f059b3ca1.png)

![image](https://user-images.githubusercontent.com/11574848/139527222-dc97bdeb-d57e-43b1-92d7-71f97fcca47c.png)

## To reproduce

** Code snippet to reproduce **

I made my own toy example, but I can share if needed.

** Stack trace/error message **

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/bq/nq30hq3x3ybb_vv_5cbjdy3r0000gn/T/ipykernel_90159/2224487089.py in <module>
      4
      5 
----> 6 q75 = brentq(lambda y: np.exp(np.sum(st.norm(mu_d, std).logcdf(y))) - .75, lo3.min(), hi3.max())
      7 q50 = brentq(lambda y: np.exp(np.sum(st.norm(mu_d, std).logcdf(y))) - .50, lo3.min(), hi3.max())
      8 q25 = brentq(lambda y: np.exp(np.sum(st.norm(mu_d, std).logcdf(y))) - .25, lo3.min(), hi3.max())

~/opt/miniconda3/envs/jupyter-test/lib/python3.9/site-packages/scipy/optimize/zeros.py in brentq(f, a, b, args, xtol, rtol, maxiter, full_output, disp)
    774     if rtol < _rtol:
    775         raise ValueError("rtol too small (%g < %g)" % (rtol, _rtol))
--> 776     r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
    777     return results_c(full_output, r)
    778 

ValueError: f(a) and f(b) must have different signs
```

## Expected Behavior

brentq should converge regardless of the distribution of the GP, but that might be difficult to control for?

**Comment by Balandat** [comment]
> The current domain is 3 standard deviations below and above the mean

Just to clarify, you're talking about this domain here?https://github.com/pytorch/botorch/blob/e23ad502629846bdc0a75a2e2af7f50982a330eb/botorch/acquisition/max_value_entropy_search.py#L810-L811

So this would be 3 below and 5 above?

**Comment by npielawski** [comment]
Yes, those exact two lines.

I suggested a -1, +5, but maybe -3, +5 is safer? I guess brentq converges quickly anyways even on a bigger range.
