### ISSUE TITLE
[Feature Request]can you create a toturial for batch gradient decent model in computer vision task ?

### ISSUE THREAD

**Issue by lzu-zhanghr** [pytorch/botorch#967]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

**Comment by Balandat** [comment]
I am not sure what specifically a “batch gradient decent model in computer vision task” tutorial would do. Closing this for now, happy to reopen if you can detail the request and how it is relevant to BoTorch.
